### ISSUE TITLE
Regolith still passes --builtin to gnome-session-binary which is not supported anymore.

### ISSUE THREAD

**Issue by denny-futurice** [regolith-linux/regolith-desktop#1001]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

Regolith will fail to startup using recent builds of the GNOME session package.

It seems the upstream package has obsoleted the `--builtin` argument and will just hard crash if it is passed (not great migration-proof behavior perhaps...).

This is discussed in the upstream mailing list here in relation to a different desktop environment: https://bugs.launchpad.net/ubuntu/+source/gnome-session/+bug/2060266 

**To Reproduce**

Issue can be observed on Debian/Sid and Regolith-bookworm and Regolith-testing after a full-upgrade on 10th of April 2024.

**Expected behavior**

**Screenshots**

following snippet snipped to remove env vars being dumped.

```
File: .xsession-errors.old

Xsession: X session started for denny at Wed Apr 10 03:08:52 PM EEST 2024
dbus-update-activation-environment: setting USER=denny

** (gnome-session-binary:35043): WARNING **: 15:08:52.454: Unknown option --builtin
X connection to :0 broken (explicit kill or server shutdown).
```

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [e.g. 3.1]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [Debian/Sid]

**Additional context**
N/A

**Comment by SoumyaRanjanPatnaik** [comment]
Thanks for reporting. Will investigate.

**Comment by SoumyaRanjanPatnaik** [comment]
@kgilmer we might have to migrate the session files to `systemd`.

**Comment by cjohnston1158** [comment]
Seeing this on 24.04 as well. I was able to work around it by removing `--builtin` from `/usr/share/wayland-sessions/regolith-sway.desktop`

**Comment by SoumyaRanjanPatnaik** [comment]
Does the session boot with sway. This change loads gnome for me.

**Comment by cjohnston1158** [comment]
It does.

**Comment by kgilmer** [comment]
Looks like we are both working on the problem..

https://github.com/regolith-linux/regolith-session/pulls

**Comment by SoumyaRanjanPatnaik** [comment]
Ohh, I didn't know you were working on this either, haha.
