### ISSUE TITLE
Gtk Box Window (Open File...) fails.

### ISSUE THREAD

**Issue by roxchgt** [regolith-linux/regolith-desktop#1003]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic

**Describe the bug**
Anywhere I need to access the file manager from the browser or another app (e.g. to pick and upload a file), the window doesn't appear. The following lines are from `journalctl`

```
Apr 17 18:39:28 rxch-tp14s xdg-desktop-por[12287]: Portal.vala:11: open_file
Apr 17 18:39:28 rxch-tp14s regolith-contro[31582]: gtk_box_remove: assertion 'GTK_IS_BOX (box)' failed

```
**To Reproduce**
It's probably difficult to reproduce, since it's most likely some local issues on my installation (Regolith 3.1 on fresh Ubuntu 23.10), but:
Open (Regolith-)Settings and go for instance to Appearance and click on Add Picture..._

**Expected behavior**
A box file selector window should appear and let me select a file.

**Screenshots**
[Screen Recording 1st Example](https://github.com/regolith-linux/regolith-desktop/assets/18581157/bd433077-5ac7-4acd-ae3d-c6420029d5dc)
[Screen Recording 2nd Example](https://github.com/regolith-linux/regolith-desktop/assets/18581157/d626093b-a184-4e97-a227-c6879971704b)

**Configuration file(s)**
I've done some "look & feel" related customizations including using a fork of picom (with animations, the issue still exists with no picom or standard picom. The whole setup was working flawlessly on Ubuntu 22.04. I migrated most of the config file. 
**Installation Details**
 - Regolith Install Type: [ISO/PPA]
 - Regolith Version: 3.1
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 23.10

**Additional context**

**Comment by SoumyaRanjanPatnaik** [comment]
This is fixed on unstable. Should be more generally available once Regolith 3.2 is generally available.

**Comment by roxchgt** [comment]
When will the 3.2 be released? This issue deserves a patch / hotfix. The OS is not usable with this and 3.1 is an official release (the [Install](https://regolith-desktop.com/docs/using-regolith/install/) link redirects to it). Is there any workaround? or should try to go back to 3.0 in the meantime ?

**Comment by SoumyaRanjanPatnaik** [comment]
Pretty soon. You can try out the changes from the `unstable` branch.

**Comment by SoumyaRanjanPatnaik** [comment]
The workaround for this would be uninstalling `xdg-desktop-portal-regolith` and `xdg-desktop-portal-sway`.
