### ISSUE TITLE
Sway: Keyboard Layout Handling differs to I3 For Shortcut Help

### ISSUE THREAD

**Issue by aykborstelmann** [regolith-linux/regolith-desktop#1004]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
On the German keyboard layout the questionmark is on the US underscore keybinding.
Since in the `sway/config.d/20_ilia` `bindsym --to-code` is used for the help keyboard shortcut, this shortcut would need to be executed via `Super+Shift+minus` (from German perspective). 
Strangly pressing the original US shortcut (`Super+Shift+minus` from German perspective) does nothing at all.
In turn the decrease gaps shortcut lies on the German `Super+?` which is quite confusing. 
When using regolith with i3 this is not the case. 
`bindsym --to-code` are also not in place in the corresponding `i3/config.d` folder. 

![image](https://github.com/regolith-linux/regolith-desktop/assets/31162687/fe931fb3-770b-488b-9327-1e7d6e95a66f)

**To Reproduce**
Select German keyboard layout and try to invoke the help.

**Expected behavior**
The help window opens, which it does not.

**Installation Details**
 - Regolith Install Type: [ISO/PPA]
 - Regolith Version:3.1
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 23.10

**Additional context**

**Comment by SoumyaRanjanPatnaik** [comment]
Try setting `XKB_DEFAULT_LAYOUT=de` in `.config/environment.d/kb_layout.conf` where `de` is the layout code for your keyboard.

**Comment by aykborstelmann** [comment]
Ah, thank you ! That's what indeed solves the problem. 
I had already rewritten the config files myself. 

But why does this not occur on I3 ? And did I overlooked something in the regolith documentation ?
