### ISSUE TITLE
st and rofi not launching, i3 bar showing an error?

### ISSUE THREAD

**Issue by MoreThanLuck** [regolith-linux/regolith-desktop#101]
Hey Ken! Not sure what changed here, but something got very broken on my box. When I launched into Regolith from a reboot a day or so ago, I noticed my wallpaper had been auto-changed to the default. The i3 Bar is displaying an error in the bottom right, saying, `Error: Could not parse JSON (lexical error: invalid char in json text.)` 

I'd try and update, but `super + enter` isn't launching st. And I can't take a screenshot, since Rofi won't launch for me either. Did something change? I haven't been digging around in the internals or anything.

**Comment by kgilmer** [comment]
Hi Ian. Sorry for the mangled upgrade.  Please see this link to resolve the issue: https://regolith-linux.org/troubleshooting.html#outdated-xresources

We had a bit of a rough upgrade when moving to Xresource based configuration. We hope to avoid this kind of breakage in the future!

**Comment by MoreThanLuck** [comment]
No problem, Ken! I can't even imagine the difficulty of swapping over. Let me try this fix tonight and I'll reopen if I continue to have issues. Thanks for you hard work, and sorry I've been out of the loop to miss this fix in the first place!

**Comment by vlnn** [comment]
Link is already broken, and that's no good as I have same issue here.

**Comment by kgilmer** [comment]
Hi @vlnn , the page has moved to the wiki here: https://github.com/regolith-linux/regolith-desktop/wiki/Troubleshooting#outdated-xresources

Kindly open a new issue or join us in Slack if you're still having troubles after applying the fix suggested.
