### ISSUE TITLE
Can't bind Print

### ISSUE THREAD

**Issue by TomFaulkner** [regolith-linux/regolith-desktop#102]
`xev` shows my Print key as `Print`, but when I bind it with `bindsym --release Ctrl+Print exec maim ~/Pictures/$(date +%s).png
` and try to use nothing happens. If I press the key by itself a screenshot is saved, but I think this is due to Gnome capturing it.

I am using Regolith ppa on Pop 19.04. I have also tried `Mod1+Print' with the same lack of results.

The screenshot application that Pop ships with takes a screenshot of the proper sized but only captures wallpaper. maim capures as expected if called from a shell.

**Comment by kgilmer** [comment]
Hi @TomFaulkner , yes I'm thinking you're right in that Gnome is hijacking the key event before it's getting to i3.  I believe you can disable or remap this functionality via the control panel:
![image](https://user-images.githubusercontent.com/49683/63909752-c367f600-c9d8-11e9-8750-92f0ab744922.png)

**Comment by TomFaulkner** [comment]
I'll take a look there. thanks!

**Comment by kgilmer** [comment]
Closing from lack of activity.  Please reopen if still an issue.
