### ISSUE TITLE
Customization of 30_navigation and 40_workspace-config not possible because of dependency in 50_resize-mode 

### ISSUE THREAD

**Issue by develNor** [regolith-linux/regolith-desktop#1023]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic

**Describe the bug**
When using custom partials for `common/30_navigation` or  `common/40_workspace-config` a sway error in `50_resize-mode` appears because it needs variables from these two partials.

**To Reproduce**
1. Copy Partials to  `common/30_navigation` and/or  `common/40_workspace-config` to `~/.config/regolith3`:
2. Remove corresponding Packages:
```
sudo apt purge -y regolith-wm-workspace-config 
sudo apt purge -y regolith-wm-navigation
```
2. Reload Sway (Super+Shift+R)
=> Sway Error in `50_resize-mode` because of missing variables `wm.binding.left`, …, `wm.binding.move_down`
 
**Installation Details**
 - Regolith Version: 3.2 (Beta 1)
 - Host OS (for PPA): Ubuntu 24.04
 - Install Commands:
```
wget -qO - https://regolith-desktop.org/regolith.key | gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null
echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/testing-ubuntu-noble-amd64 noble main" | sudo tee /etc/apt/sources.list.d/regolith.list
sudo apt update
sudo apt install -y regolith-desktop regolith-session-sway regolith-look-default
```

**Proposal**
To resolve the dependency between the partials, I suggest moving the declaration of the variables `wm.binding.left`, ..., `wm.binding.move_down` to the general config `/etc/regolith/sway/config`.

**Comment by develNor** [comment]
Found another reported issue with the same problem: https://github.com/regolith-linux/regolith-wm-config/issues/23

**Comment by jc00ke** [comment]
Manually patching `etc/regolith/sway/config` from https://github.com/regolith-linux/regolith-wm-config/pull/39 worked for me. :pray:
