### ISSUE TITLE
Picom crashing on Ubuntu 24.04 and X11

### ISSUE THREAD

**Issue by Etienne-gh** [regolith-linux/regolith-desktop#1029]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

Thank you to develop and maintain Regolith, It is awesome!

**Describe the bug**
I've just reinstalled my laptop with Ubuntu 24.04 and regolith 3.2 beta 2. Picom is regularly crashing on workspace/window switching with the following error:

```shell
$ /usr/bin/picom --config /usr/share/regolith-look/nord/picom.conf 


picom: ../src/win.c:349: win_bind_mask: Assertion `!w->mask_image' failed.
[1]    788705 IOT instruction (core dumped)  /usr/bin/picom --config /usr/share/regolith-look/nord/picom.conf
```

It seems to be linked to this [Picom's issue](https://github.com/yshui/picom/pull/1035) which is fixed on the last Picom release (v11.2) and Regolith is using Picom v10 for now. 

**To Reproduce**
 - Default regolith 3.2 beta 2 installation with ubuntu 24.04, X11 and Picom as compositor.

**Expected behavior**

**Screenshots**

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version:  3.2 beta 2
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 24.04

**Additional context**

**Comment by kgilmer** [comment]
Thanks @Etienne-gh , I've packaged Picom v11.2 to ship in Regolith 3.2 beta3+
