### ISSUE TITLE
Notifications stop appearing after a while

### ISSUE THREAD

**Issue by cesarolea** [regolith-linux/regolith-desktop#104]
Hi,

First of all thank you! I'm forced to use Ubuntu at my work laptop and Regolith makes the experience very nice!

I noticed that when notifications start popping up, they are stored in a menu that is accessible through a system tray icon so you can see what you missed. However if I let them accumulate for a while, notifications will stop popping up altogether until I click the tray icon and clear all notifications.

Is there a way to force all notifications to always show as a popup on the desktop? Ideally there should be a gconf setting that I can toggle via a script, so that I can turn on/off notifications on demand (think a privacy/Do Not Disturb mode)?

On another note, do you know if it's possible to disable whatever notification daemon Gnome-Shell is using, so that I can replace it with dunst?

Thanks!

_Edit_: Forgot to mention that I have replaced the i3 bar and i3rocks with Polybar, and accessing the system tray that way.

**Comment by skalyan91** [comment]
I would also like to be able to use dunst, or at least customise the positioning of the notification popups.

**Comment by cesarolea** [comment]
For the "DND mode" the following can be used:

    gsettings set org.gnome.gnome-flashback notifications false

Changing it to `true` re-enables notifications again. This takes care of Gnome notifications, but not other sources such as notifications coming from the browser.

Haven't tried to install dunst and use that with the Gnome flashback notifications daemon disabled.

**Comment by cesarolea** [comment]
Turns out it was easier than I expected.

First you need to turn off notifications from Gnome:

    gsettings set org.gnome.gnome-flashback notifications false

Then install dunst and copy the sample config to your home directory for modification:

    sudo apt install dunst
    cp /etc/xdg/dunst/dunstrc ~/.config/dunst/

And that's it. Modify `dunstrc` to suit your needs. In my case it fixed the issue with notifications not showing up after a while, plus you can control the position, size and look and feel of the popup. It obviously is not integrated with the Regolith desktop, so it won't read your `Xresources`.

**Comment by kgilmer** [comment]
That's amazing @cesarolea !  I had tried to do something like this when I first started learning how to configure i3, but failed to integrate `dunst`.  I may take your work in a future version of Regolith.  Thank you!  If you'd like a laptop sticker email me a postal address and I'll send you one or two.  kgilmer at gmail.com.

**Comment by skalyan91** [comment]
@cesarolea Thanks! Disabling Gnome-flashback notifications using dconf-editor was enough to get dunst working. (I didn’t even have to manually start dunst!)

**Comment by kgilmer** [comment]
Like Rofi, the dunst developers are not interested in adding features like Xresources support because they see it complicating their Wayland future: https://github.com/dunst-project/dunst/issues/357

**Comment by leosunmo** [comment]
With something like https://github.com/leosunmo/regolith-base16 we could potentially generate the Rofi/Dunst native config format using template engines that read from Xresources.

**Comment by kgilmer** [comment]
True.  I'm still hoping for an Xresources-native solution and spent a few hours yesterday trying to remove all the deprecated GLib calls from `notification-daemon`.  We'll see how it goes, but it seems like the most approachable codebase among the options that are listed on the Arch wiki page for notification front-ends.

**Comment by kgilmer** [comment]
I have added the dunst installation steps provided by @cesarolea in a new wiki HowTo: https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Use-Dunst-to-view-notifications

**Comment by kgilmer** [comment]
This should be fixed in 1.3 w/ Rofication.  Please reopen if still experiencing loss of notifications.
