### ISSUE TITLE
Inconsistent border color

### ISSUE THREAD

**Issue by cjstock** [regolith-linux/regolith-desktop#106]
One edge of the window's border is always set to #EBCB8B on the focused window, only when it's the only window on the workspace.

Screen shot 1: leftmost window is in focus (bottom border is affected)
Screen shot 2: rightmost window is in focus (right border is affected)
Screen shot 3: middle window is in focus (no border is affected)

![Screenshot from 2019-08-31 12-03-59](https://user-images.githubusercontent.com/7853471/64068056-7b6aee00-cbe7-11e9-99b5-8960c0d3ab05.png)
![Screenshot from 2019-08-31 12-04-02](https://user-images.githubusercontent.com/7853471/64068058-7d34b180-cbe7-11e9-8807-f6920a84008f.png)
![Screenshot from 2019-08-31 12-06-54](https://user-images.githubusercontent.com/7853471/64068073-d6044a00-cbe7-11e9-9afe-d8bf61d8135a.png)

**Comment by leosunmo** [comment]
Does `mod+backspace` change the side the "lit" border is on? It's probably the "next pane" indicator from i3. I don't what it's called off the top of my head.

**Comment by cjstock** [comment]
`mod+backspace` does change the side as you thought. It looks like it's the 'i3wm.client.focused.color.indicator' value in my .Xresources.d/i3wm file. However, modifying that value doesn't change the indicator color.

**Comment by leosunmo** [comment]
Make sure to reload the Xresources database. `xrdb ~/. Xresources-regolith` should do it unless you've got a custom file.

**Comment by leosunmo** [comment]
Did you manage to change the colour to something less intrusive @cjstock?

**Comment by kgilmer** [comment]
Closing, assuming it's fixed.
