### ISSUE TITLE
File picker does not open at all

### ISSUE THREAD

**Issue by niraj-khatiwada** [regolith-linux/regolith-desktop#1066]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-desktop.com) and didn't find any relevant topic

**Describe the bug**
The file picker does not open at all for any apps. Some of the apps like Telegram is even stuck the moment when the file picker is requested. I have to force close it to make it work again.

**To Reproduce**
Not sure how to reproduce exactly. Please let me know if you need any more info to reproduce.

**Expected behavior**
When I click on any button that requests system to pick the file from my machine, it should open the file picker portal.

**Screenshots**
Here are logs from `journalctl`
![image](https://github.com/user-attachments/assets/4fe60728-044f-428e-9f97-dad667f622d6)

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Stage: release-3_2
 - Regolith Version: 3.2
 - Host OS: Debian 12 bookworm
**Additional context**

**Comment by kgilmer** [comment]
Hi @niraj-khatiwada , this might be of interest: https://github.com/orgs/regolith-linux/discussions/984

**Comment by niraj-khatiwada** [comment]
> Hi @niraj-khatiwada , this might be of interest: https://github.com/orgs/regolith-linux/discussions/984

Wow, [this](https://github.com/orgs/regolith-linux/discussions/984#discussioncomment-10596389) one solved it instantly after logout. 
Thank you so much for creating Regolith. Love every bit of using it as a lover of both i3 and gnome.
