### ISSUE TITLE
Screen lock shortcut not working as expected

### ISSUE THREAD

**Issue by skalyan91** [regolith-linux/regolith-desktop#107]
On my setup (regolith-desktop on top of Ubuntu 19.04), pressing `$mod4+Esc` (which is supposed to lock the screen) doesn’t do anything. This seems to be because `gnome-screensaver-command --lock` doesn’t do anything. However, `gnome-screensaver-command --activate` seems to work. Perhaps this should be made the default?

**Comment by kgilmer** [comment]
Hi @skalyan91 , interesting!  What version do you have?  Mine is:
```
$ gnome-screensaver-command --version
gnome-screensaver-command 3.6.1
```

For me `--lock` works as expected.

**Comment by skalyan91** [comment]
I had the `/org/gnome/desktop/lockdown/disable-lock-screen` setting turned on in dconf. That’s fixed now. Not an issue with Regolith at all.
