### ISSUE TITLE
i3xrocks fails to load configuration and crashes with segmentation fault on Ubuntu 24.04

### ISSUE THREAD

**Issue by leonardogonfiantini** [regolith-linux/regolith-desktop#1086]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-desktop.com) and didn't find any relevant topic

**Describe the Bug**
i3xrocks fails to load configuration files and crashes with the error:

     i3xrocks -u ~/.config/regolith3/ 
     <3>malformed property, should be a key=value pair
     <2>Failed to load configuration

The system also logs a segmentation fault:

    segfault at 0 ip 0000585b184b7928 sp 00007ffde98b5340 error 4 in i3xrocks[585b184b6000+6000].

**To Reproduce**
I don't know exactly how to reproduce it, but I have had this problem since I upgraded my ubuntu 22.04 to ubuntu 24.04 today, before doing this I uninstalled regolith and then reinstalled it afterwards

**Expected behavior**
The i3xrocks application should correctly load configuration files and render the status bar without crashing.

**Screenshots**
I hope you can read it, at the bottom right I have an error:

     Error: status_command process exited unexpectedly (exit 139)

![Screenshot from 2024-11-29 18-05-06](https://github.com/user-attachments/assets/b894852d-dc4b-4cc0-ab2d-9bbf0fd616ea)

**Installation Details**
 - Regolith Version: 3.2
 - Host OS: 24.04

**Comment by kgilmer** [comment]
Hi @leonardogonfiantini , it would seem there is an error in your configuration file given the message that's being emitted.  (Admittedly it would be nicer if the program told you were the problem was)

**Comment by leonardogonfiantini** [comment]
Hi @kgilmer , I tried editing the i3xrocks configuration file of the default style of regolith, as the error message says, I replaced the ‘:’ with ‘=’,  now if I run the command :

``` i3xrocks -c /usr/share/regolith-look/default/i3xrocks    ```

It doesn't show me any output, I think this is correct how this works.

The fact is even with those changes if I run ‘regolith-look refresh’ I still get the same error in the UI that you also see in the screenshot before.

**Comment by kgilmer** [comment]
You edited `/usr/share/regolith-look/default/i3xrocks`?  Can you paste your version of the file into this issue?

**Comment by leonardogonfiantini** [comment]
---

#define typeface_bar_glyph_app_launcher 
#define typeface_bar_glyph_battery_0 
#define typeface_bar_glyph_battery_100 
#define typeface_bar_glyph_battery_20 
#define typeface_bar_glyph_battery_50 
#define typeface_bar_glyph_battery_80 
#define typeface_bar_glyph_battery_ac 
#define typeface_bar_glyph_battery_charging 
#define typeface_bar_glyph_battery_unknown 
#define typeface_bar_glyph_capslock 
#define typeface_bar_glyph_cpu 
#define typeface_bar_glyph_disk 
#define typeface_bar_glyph_dn 
#define typeface_bar_glyph_error 
#define typeface_bar_glyph_help 
#define typeface_bar_glyph_media_paused 
#define typeface_bar_glyph_media_playing 
#define typeface_bar_glyph_memory 
#define typeface_bar_glyph_mute 
#define typeface_bar_glyph_next_workspace 
#define typeface_bar_glyph_notify_error 
#define typeface_bar_glyph_notify_none 
#define typeface_bar_glyph_notify_some 
#define typeface_bar_glyph_numlock 
#define typeface_bar_glyph_off 
#define typeface_bar_glyph_on 
#define typeface_bar_glyph_sound 
#define typeface_bar_glyph_thermometer 
#define typeface_bar_glyph_time 
#define typeface_bar_glyph_up 
#define typeface_bar_glyph_wifi 
#define typeface_bar_glyph_wired 
#define typeface_bar_glyph_workspace 

i3xrocks.label.color:     color_light_2
i3xrocks.value.color:     color_dark_1
i3xrocks.value.font:      gtk_monospace_font_name
i3xrocks.critical.color:  color_red
i3xrocks.error.color:     color_orange
i3xrocks.warning:         color_yellow
i3xrocks.nominal:         color_light_2

i3xrocks.label.thermometer=typeface_bar_glyph_thermometer

i3xrocks.label.wifi=typeface_bar_glyph_wifi
i3xrocks.label.wired=typeface_bar_glyph_wired
i3xrocks.label.up=typeface_bar_glyph_up
i3xrocks.label.dn=typeface_bar_glyph_dn

i3xrocks.label.cpu=typeface_bar_glyph_cpu

i3xrocks.label.disk=typeface_bar_glyph_disk

i3xrocks.label.battery100=typeface_bar_glyph_battery_100
i3xrocks.label.battery80=typeface_bar_glyph_battery_80
i3xrocks.label.battery50=typeface_bar_glyph_battery_50
i3xrocks.label.battery20=typeface_bar_glyph_battery_20
i3xrocks.label.battery0=typeface_bar_glyph_battery_0
i3xrocks.label.batterycharging=typeface_bar_glyph_battery_charging
i3xrocks.label.batteryac=typeface_bar_glyph_battery_ac
i3xrocks.label.batteryunknown=typeface_bar_glyph_battery_unknown

i3xrocks.label.time=typeface_bar_glyph_time

i3xrocks.label.mediaplaying=typeface_bar_glyph_media_playing
i3xrocks.label.mediapaused=typeface_bar_glyph_media_paused
i3xrocks.value.mediaplayerwidth=25

i3xrocks.label.notify.none=typeface_bar_glyph_notify_none
i3xrocks.label.notify.some=typeface_bar_glyph_notify_some
i3xrocks.label.notify.error=typeface_bar_glyph_notify_error

i3xrocks.label.help=typeface_bar_glyph_help

i3xrocks.label.sound=typeface_bar_glyph_sound
i3xrocks.label.mute=typeface_bar_glyph_mute
i3xrocks.label.memory=typeface_bar_glyph_memory

i3xrocks.label.on=typeface_bar_glyph_on
i3xrocks.label.off=typeface_bar_glyph_off

i3xrocks.label.capslock=typeface_bar_glyph_capslock
i3xrocks.label.numlock=typeface_bar_glyph_numlock

i3xrocks.weather.error_message=typeface_bar_glyph_error

i3xrocks.label.next-workspace-widget=typeface_bar_glyph_next_workspace

i3xrocks.label.app_launcher=typeface_bar_glyph_app_launcher⏎  

---



This is the version I modified, before instead of the character ‘=’ to form the key-value pair there was the character ‘:’, I simply tried to change this character.

**Comment by kgilmer** [comment]
You can restore the [stock version](https://github.com/regolith-linux/regolith-look-default/blob/main/usr/share/regolith-look/default/i3xrocks) of that file to resole any parse errors.   Do you have some i3xrocks/i3blocks customization in `~/.config/regolith3/`?

**Comment by leonardogonfiantini** [comment]
I restored the original file, i don't have any i3xrocks/i3blocks inside the .config/regolith3 folder:

```
⋊> ~/.c/regolith3 ls -lah                                                             20:01:07
total 16K
drwxrwxr-x  3 skalla skalla 4,0K nov 30 19:17 ./
drwx------ 65 skalla skalla 4,0K nov 29 17:43 ../
drwxrwxr-x  2 skalla skalla 4,0K nov 29 17:43 flags/
-rw-rw-r--  1 skalla skalla   53 nov 30 19:17 Xresources
```
