### ISSUE TITLE
Keyboard irresponsive 

### ISSUE THREAD

**Issue by rainer2208** [regolith-linux/regolith-desktop#109]
Installed Regolith on my Dell Laptop today, aside Ubuntu Gnome and Budgie. 

It is a cool distro. Unfortunately, the keyboard quickly became completely irresponsive. Virtually no shortcut works, just one, that Ctrl + Alt + Del, invoking the logout/ restart/ shutdown menu. 

All the specific key bindings listed [here](https://regolith-linux.org/keybindings.html) don't work. I am even unable to open a terminal. The mouse is working, though.

Restarting the computer did not solve the issue.

**Comment by kgilmer** [comment]
Hi @rainer2208 , hmm sorry to hear that.  I haven't seen this issue before...  Do you have any kind of special setup?  I have not tested w/ Bugie before..

**Comment by rainer2208** [comment]
hi @kgilmer, thanks for your reply and congrats for this interesting distro. 

No, I don't have any special setup. I'm using a fresh Ubuntu Budgie installation with the regular software, LibreOffice, VSCode and such. 

I have java and vala installed, don't know if this has any influence. And the Budgie development package from here:
https://discourse.ubuntubudgie.org/t/how-to-hack-the-budgie-desktop-on-ubuntu/574 

Tried it again yesterday. The keyboard woke up for a couple of keystrokes, but became irresponsive again. Only Ctrl +Alt+Del  works, as far as I could see.

**Comment by kgilmer** [comment]
In the next couple of days, I will release an updated ISO image that can be booted directly from USB.  If you can test with that, it will at least tell us if you issue is software or hardware.

**Comment by rainer2208** [comment]
Ken, it was apparently a hardware issue with my keyboard. The issue can be closed ....
