### ISSUE TITLE
Unable to change the configuration of my new Regolith Linux installation

### ISSUE THREAD

**Issue by pvnieo** [regolith-linux/regolith-desktop#110]
I am a new user of Regolith Linux. I'm just using the Desktop version with a Ubuntu Budgie 18.04. I followed the instructions on the website to customize my desktop by creating a new configuration file from the original:
```
$ mkdir -p ~/.config/regolith/i3
$ cp /etc/regolith/i3/config ~/.config/regolith/i3/config
```
After modifying the configuration file (to test, I just changed the name of a workspace), and reloading i3 (Win + Shift + r), the changes don't seem to be applied.

Can someone help me please!

**Comment by kgilmer** [comment]
Hi @pvnieo , you'll need to log out and back in (just once) after creating your user directory i3 config file before i3 will pick it up.  You can verify which i3 config file you're using with `i3 --moreversion`.

**Comment by pvnieo** [comment]
Hi @kgilmer Thanks for your response. I've already done this, and now the commands I added are working. However, is there a way to change the names of the work spaces (by naming them using icons for example)? I have tried `set_from_resource $ws1  i3-wm.workspace.01.name "new name"` but it's not working.
Thanks in advance.

**Comment by pvnieo** [comment]
I've actually solve this by modifying the file `/etc/regolith/styles/i3-wm`. 
Thanks for this great distro.

**Comment by kgilmer** [comment]
Ah, yep, you found the right place.  Glad you're enjoying it @pvnieo !
