### ISSUE TITLE
Meta package doesn't install all dependencies on non-Gnome installations

### ISSUE THREAD

**Issue by JimmyRecard** [regolith-linux/regolith-desktop#111]
I installed regolith-desktop meta package on top of Xubuntu 19.04. I note that in issue #43 you mention that you do not test on Xubuntu, so I presume this is outside of support scope, but I'll note it here for anyone else who might face the same issue.

I used following commands to install:
```
sudo add-apt-repository -y ppa:kgilmer/regolith-stable
sudo apt install --install-suggests regolith-desktop
```
After logging into the Regolith session, I noticed that settings was missing and indeed, gnome-control-center was not installed. Instead of opting to try to identify each individual dependency, I installed `ubuntu-desktop-minimal` which solved my issues. Given that there's plethora on non-Gnome Ubuntu spins, please consider expanding the list of dependencies of the meta package to cover packages normally supplied by the default Ubuntu session.

Thanks for all your work on this DE.

**Comment by kgilmer** [comment]
Excellent suggestion, thank you @JimmyRecard !
