### ISSUE TITLE
Create Regolith boot-up branding

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#113]
Customize https://wiki.ubuntu.com/Plymouth for the Ubuntu LiveCD release.

**Comment by ohyran** [comment]
Ok did the worlds worst quick mockup gif of an idea... which also kind of includes a polished up version of the logo (more mellowed red, less obsessive balancing to make it more dynamic and interesting)... Ignore the fact that it bounces around :D like I said a really quick animation idea
![rego2](https://user-images.githubusercontent.com/7491840/66306266-71808d00-e901-11e9-8c62-22d16acaa5b2.gif)

**Comment by ohyran** [comment]
Its basically just 9 svg images that are interchanged to create a ninestep animation (colors etc can be easily swapped)

**Comment by kgilmer** [comment]
That's really cool @ohyran !  Sorry I had seen this when you sent it but couldn't find it again until now.  The color I'd like to keep as is, otherwise I have to have another session with the designer which I'd prefer to avoid for now.  Is there something we can do to the background that will keep the original color looking nice?  Do you have any details regarding how this would be integrated into Plymouth?

**Comment by kgilmer** [comment]
Closing from lack of response.  Kindly reopen if wish to continue on this project @ohyran .
