### ISSUE TITLE
Launcher broken after upgrade:  failed to open theme regolith-theme.rasi

### ISSUE THREAD

**Issue by vanboom** [regolith-linux/regolith-desktop#115]
Ubuntu 18.04, apt upgrade, I noticed regolith was updated.  

The window manager works fine with hotkeys, but the launcher displays a box with an error message:  

```
The following errors were detected when starting rofi:

Failed to open theme:  /home/xxx/regolith-theme.rasi
Error: no such file or directory
```

Every Regolith update is a breaking config change.  Some upgrade notes would be nice to help us amateurs with these sort of issues.

**Comment by vanboom** [comment]
Thanks, I am now subscribed to the list.

**Comment by leosunmo** [comment]
If you're like me and frequently declare email bankruptcy you can join our Slack at https://regolith-linux.herokuapp.com/. The announcements will be shared there as well.

**Comment by topherbuckley** [comment]
After upgrading according to [this](https://regolith-linux.org/download/):

I have no ~/.Xresources-regolith file, log out and in, and still this error persists. I also see "Error: Could not parse JSON (lexical error: invalid char in json text.) for a status bar.

**Comment by kgilmer** [comment]
Hmm, yeah it seems so @topherbuckley but I am unsure of what it could be.  If you get back into that state, it would be good to know what `i3 --moreversion` prints.

**Comment by topherbuckley** [comment]
I just updated on a different machine and ran into the same issue. Here is the output of `i3 --moreversion`:

>Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 29801)bort…)
Loaded i3 config: /etc/regolith/i3/config (Last modified: Tue 28 Jan 2020 01:54:44 PM JST, 1654606 seconds ago)

>The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**Comment by kgilmer** [comment]
Thanks @topherbuckley , if your system is still in that state can you kindly run `i3xrocks -c /etc/regolith/i3xrocks/config` and give me the output?

**Comment by kgilmer** [comment]
Closing due to lack of response.

**Comment by topherbuckley** [comment]
@kgilmer, sorry I thought I had responded to this shortly after you had asked. Must have closed my  browser prematurely or something. I had previously responded with something of the order "I unfortunately am not still in that state, but as I have no messed with too many configuration files yet, I'm happy to return to that state for testing. Any ideas as to how I would revert to such a state? I'd suppose it difficult since I did a full reinstall, but if you have any ideas, I'm happy to try them out."

**Comment by kgilmer** [comment]
If things are working for you, let's leave it there @topherbuckley :smile: .  R1.3.1 was just released, and some changes were made to the Xresources and rofi configurations.  So, it may be that whatever problem you had was fixed.  In any case, if you experience more issues down the road don't hesitate to open another issue.  :smile:

**Comment by LevinFaber** [comment]
@kgilmer Hi, Im at the same point topherbuckly was. This is the output:

❯ i3xrocks -c /etc/regolith/i3xrocks/config   
<0> FATAL ini.c:ini_property:61: invalid Xresource key: "xresource:i3xrocks.value.color"
<0> FATAL bar.c:bar_load:392: Failed to load bar configuration file: /etc/regolith/i3xrocks/config

**Comment by topherbuckley** [comment]
@LevinFaber , I'm not on my Regolith machine atm, and I'm not sure about the first error you have there without being able to tinker on my Regolith machine, but the 2nd error looks like you may have something wrong with the /etc/regolith/i3xrocks/config file. Can you post the contents of that in a pastebin and upload here? [Here](https://pastebin.com/nhPhAghk) is what is in mine. Did you edit this file manually? If so, you may want to reinstall as I did and instead modify user files as laid out [here](https://regolith-linux.org/docs/reference/configurations/). Your first error may be stemming from the 2nd if this i3xrocks.value.color variable is supposed to be defined in /etc/regolith/i3xrocks/config and can't be loaded. Just a guess, but can try to help more Monday when I'm back on my main machine.

**Comment by kgilmer** [comment]
Hi @LevinFaber , sorry I didn't see a notification that you updated this closed issue.  I have added section to the site for steps to fix packaging problems: https://regolith-linux.org/docs/getting-started/install/#upgrades
