### ISSUE TITLE
Migrate from fontawesome to Material Design Icons font for i3bar.

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#119]
Material Design Icons are arguably cleaner and offer more variety than fontawesome: https://material.io/resources/icons/?icon=label&style=baseline

This change requires:
1. A new style that brings in the material design icon font instead of font awesome as a typeface in styles.
2. Update to bar style to include new glyph for workspace.
3. Update to blockets or i3xrocks config for new icons.

![image](https://user-images.githubusercontent.com/49683/64925354-3678b700-d7a4-11e9-9f4a-d48db8d85e03.png)

**Comment by kgilmer** [comment]
`gucharmap` is a program that can list and allow selection of any glyph in any installed font.  This is necessary to copy the glyph into a config file.

**Comment by leosunmo** [comment]
I think this could be a good option. I think we'd have to host a package ourselves (using https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.ttf)

I did notice that some icons are lacking, for example the battery one:
https://material.io/resources/icons/?search=battery&style=baseline

**Comment by leosunmo** [comment]
They are missing a few "stage" icons, like Wifi and battery it seems, https://github.com/google/material-design-icons/issues/434#issuecomment-397872923

**Comment by kgilmer** [comment]
The debian package I installed to get what is in the screenshot above is `fonts-materialdesignicons-webfont`.  I see what you mean about the missing icons, that's unfortunate.  I wonder if we can mix between fontawesome and these as needed..?

**Comment by leosunmo** [comment]
Potentially but the style might not match. Were there any specific icons that you wanted to replace? I'll have a look at replacing the bar icons at some point and compare

**Comment by kgilmer** [comment]
I see sufficient battery icons so I think we are GTG for the bar, no?

![image](https://user-images.githubusercontent.com/49683/65211086-6220c900-da52-11e9-81c5-7146f14b3375.png)

**Comment by kgilmer** [comment]
Also there is a nice "Windows" icon, which if added to the workspaces in the bar, would be a literal description of the key presses needed to navigate to the workspace.

![image](https://user-images.githubusercontent.com/49683/65211144-8aa8c300-da52-11e9-8e3d-07b2b2c0ef91.png)

**Comment by leosunmo** [comment]
Huh, I could have sworn the battery icons weren't available in the font. Well, in that case we can probably use it just fine!

**Comment by kgilmer** [comment]
Experiment ~

![image](https://user-images.githubusercontent.com/49683/65341222-b4620700-db84-11e9-9065-4acb030872bb.png)

**Comment by kgilmer** [comment]
Updates are in place for users to add this themselves relatively easily, will consider making default for next release.

https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Switch-bar-to-use-Material-Design-icons
