### ISSUE TITLE
apt dist-upgrade sometimes causes regolith-desktop to be uninstalled

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#120]

**Comment by kgilmer** [comment]
I'm unsure of why this is, and am unable to find any documentation of `apt` that provides any clues.  It has happened on both PPA and LiveCD installs.

**Comment by thebeardbe** [comment]
it is not only on dist-upgrade also on normal upgrade. Well not exactly. 

I got a heldback for my normal upgrade and after doing apt full-upgrade I lost regolith and all it's config files.

I'm on ubuntu 19.04

**Comment by falsechicken** [comment]
I am having theme related issues as well. I have two machines, a laptop and a desktop, after a recent apt update both seem to have lost the theme. Everything is a bright white theme now and I cannot for the life of me figure out what happened. A common issue I did have on both was the app launcher no longer launched. Both showing an error related to 'regolith-theme.rasi' and after a reboot everything is white.

**Comment by MikeShiner** [comment]
I got the same issue! Did a `apt upgrade` yesterday, logged in today to find i3 wizard pop up, offering a default config..
Checked my system to find regolith-linux was uninstalled and i3 was installed.

After running apt install regolith-desktop, it removed i3 and installed i3-gaps and my previous config has been restored.

Looks like I'm back to normal, why was regolith-desktop uninstalled from `apt upgrade` ?..

**Comment by kgilmer** [comment]
@thebeardbe the stock configuration files for Regolith are now in `/etc/regolith`.  Any config files in your user directory should not be removed or changed as a result of an `apt upgrade` or any variation.

**Comment by kgilmer** [comment]
@falsechicken let me know if `sudo apt install regolith-desktop` does not resolve your issue.

**Comment by kgilmer** [comment]
@MikeShiner I am not clear as to the root-cause of the issue.  My guess is that some apt policy is causing the maunally-installed `regolith-desktop` to be removed but I cannot find documentation as to the policy logic within `apt` to verify this theory.

**Comment by kgilmer** [comment]
I have added a section to the Troubleshooting page of the site regarding this issue: https://regolith-linux.org/troubleshooting.html#uninstalled

**Comment by MikeShiner** [comment]
@Ken Gilmer No problem. If it happens again I'l gather some more debugging info to help out. Still singing Regolith's praises, I really love the work you're doing here.

**Comment by kgilmer** [comment]
Thanks @MikeShiner!  If you'd like me to send you a Regolith laptop sticker email me a postal address to kgilmer at gmail.com.

**Comment by falsechicken** [comment]
> @falsechicken let me know if `sudo apt install regolith-desktop` does not resolve your issue.

That did solve the issue. Sorry for the delay!

**Comment by ploum** [comment]
What is probably happening is that the official Ubuntu repository has a more recent version for a package installed through regolith PPA. It then wants to upgrade that package, which will pull all its dependencies (i3) and remove lot of package from Regolith.

One way to solve that would be to do some apt pinning on the PPA (making the PPA prioritary even if versions are lower). That's a bit ugly. The correct way of fixing that is not offering packages which are also in the Ubuntu repository so "forking" and offering them a new name.

**Comment by kgilmer** [comment]
Sounds plausible.  After looking at the list of packages in the stable PPA I'm not sure which would be colliding with an Ubuntu repo.  In any case, a fix doesn't seem to be obvious.  I've added some documentation here that may help other users that encounter the error:

https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Upgrade-to-Ubuntu-19.10-(Eoan-Ermine)
