### ISSUE TITLE
i3 bar can't show 24 hour clock format

### ISSUE THREAD

**Issue by Davalm14** [regolith-linux/regolith-desktop#121]
It just goes from 00:00-12:00 then starts over.

**Comment by owen62601** [comment]
The datetime format is currently set in  `/etc/regolith/styles/i3xrocks`.
`%I` only displays 12 hour time so if you change it to `%H` it should work. (I use 24 hour time too)

Not part of the team but loving regolith <3. Hope this helps.
[https://github.com/vivien/i3blocks-contrib/tree/master/time](https://github.com/vivien/i3blocks-contrib/tree/master/time)

**Comment by Davalm14** [comment]
That worked thanks! Still fairly new to the linux world to be honest and changing things not in your home directory when running a dist with point releases instead of rolling ones has usually just ended up in things exploding in for me. But let's hope it doesn't..

**Comment by kgilmer** [comment]
@Davalm14 , yep @owen62601 gave you the right spot in which the date format is set.  You're also right that it's best to keep modifications in your home directory.  This page describes how to copy the default configs, in your case Xresources, into your home directory so that changes survive upgrades.

https://regolith-linux.org/configuring.html

**Comment by leosunmo** [comment]
I don't have this set in my Xresources so it defaults to `"+ %m-%d %H:%M "` which looks like this:
```
09-17 18:21
```
I didn't realise this had changed. I wonder if we want a clearer way of customising this? My first thought was to use a variable in the `i3xrocks.conf` file, as I don't know if this belongs in Xresources. 

Maybe a more global "24hr/12hr" clock variable in Xresources that can be used in many places?
Or should we just leave a commented-out `#FORMAT=24hr` in the `i3xrocks.conf` file?

**Comment by leosunmo** [comment]
I will close this for now as it is resolved, but please feel free to leave a comment with your opinions or join our Slack channel to leave feedback at https://regolith-linux.herokuapp.com/
