### ISSUE TITLE
i3 bar can't show utf-8 characters

### ISSUE THREAD

**Issue by Davalm14** [regolith-linux/regolith-desktop#122]
Connecting to a wifi with the character "ä" resulted in "\xC3\xA4" being displayed instead.

**Comment by kgilmer** [comment]
To narrow the problem down, can you run the `wifi2` blocklet and see if the issue is present?  Ex:
```
$ /usr/share/i3xrocks/wifi2
<span color="#7B8394"> </span><span font_desc="Ubuntu Mono 14" color="#D8DEE9">Tsukiji</span>
<span font_desc="Ubuntu Mono 14" color="#D8DEE9">Tsukiji</span>
```

**Comment by Davalm14** [comment]
`dalmgren@ ~/dev/dist (next/da-dist-3735) $ /usr/share/i3xrocks/wifi2
<span color="#7B8394"> </span><span font_desc="Source Code Pro Medium 13" color="#D8DEE9">vm\xC3\xA4</span>
<span font_desc="Source Code Pro Medium 13" color="#D8DEE9">vm\xC3\xA4</span>
dalmgren@ ~/dev/dist (next/da-dist-3735) $ here is the same text -> vmä
`

**Comment by Davalm14** [comment]
Not entirely sure what ^ means though..

**Comment by leosunmo** [comment]
This is definitely not i3blocks or Pango. It's coming out like that from the `iwconfig` utility.
```
iwconfig wlp3s0
wlp3s0    IEEE 802.11  ESSID:"W\xC3\xA4f\xC3\xA4"
<snip>
```
My wifi is called "wäfä".
I will see what I can do here.

**Comment by leosunmo** [comment]
Okay, `nmcli` is a lot nicer to work with and is friendlier with UTF-8. Am I correct in assuming `nmcli` will be available on all supported Regolith platforms, @kgilmer ?

PR https://github.com/regolith-linux/regolith-i3xrocks-config/pull/6

![image](https://user-images.githubusercontent.com/13341934/65015496-d6396f00-d975-11e9-99ca-684ef6b139e1.png)

**Comment by leosunmo** [comment]
Could you give that blocklet a try @Davalm14 ? Your blocklets should live in `/usr/share/i3xrocks`, just add a `wifi3` file and update your config and use `$mod+Shift+r` to reload i3.

**Comment by kgilmer** [comment]
`nmcli` ships with `network-manager`, no concerns with depending on it!

```
$ dpkg -S nmcli
...
network-manager: /usr/bin/nmcli
```

**Comment by kgilmer** [comment]
FYI I added the dependency on network-manager in a subsequent commit.

**Comment by kgilmer** [comment]
`regolith-i3xrocks-config_1.13-1ubuntu1~ppa4` is building in `regolith-unstable` for testing.
