### ISSUE TITLE
i3xrocks not using gnome-scaling on login

### ISSUE THREAD

**Issue by owen62601** [regolith-linux/regolith-desktop#123]
When using gnome-scaling of 200%, upon login i3xrocks is scaled at 100% instead of 200%.
After restarting i3 (Mod+Shift+R), the bar is properly scaled at 200%.

Minor annoyance but any tips/workarounds would be appreciated.

Running:
Ubuntu 18.04.3 LTS
regolith-desktop 2.30-1ubuntu1~ppa1

**Comment by kgilmer** [comment]
Hi @owen62601 :smile: .  Do you mean that the entire bar 100% or just the stuff on the right?

**Comment by owen62601** [comment]
Hi! I think it has something to do with the font scaling affecting the bar size but I'm not too sure. I've attached screenshots below to get a better picture.

## Before (right after login)
![Screenshot from 2019-09-17 12-02-33](https://user-images.githubusercontent.com/13184383/65005501-67dbb900-d943-11e9-9cb8-2b0db1ace513.png)
## After (with i3 restart)
![Screenshot from 2019-09-17 12-02-39](https://user-images.githubusercontent.com/13184383/65005537-82ae2d80-d943-11e9-97c3-d119478e299c.png)

**Comment by kgilmer** [comment]
Hmm, do you have DPI set in Xresources by chance?  [This page](https://computingforgeeks.com/how-to-set-correct-screen-dpi-in-linux-xresources/) covers the details.  You can verify with `xrescat Xft.dpi`.

**Comment by owen62601** [comment]
Thanks! Turns out it was set to 196.

I edited my `~/.Xresources-regolith` config to include `Xft.dpi: 196` and that fixed the problem and scaled properly during login.

I played around with the settings but can't seem to find what is setting the dpi setting or why it wasn't loading during the initial login. I used `xrdb -query -all > '/tmp/test.txt'` to output the xrdb list before i3 is executed in the `/usr/bin/i3-gnome-flashback` file but something had already set it.

Not sure if you want to pursue this further or not, but manually adding `Xft.dpi` to my personal config worked.

**Comment by kgilmer** [comment]
> can't seem to find what is setting the dpi setting

Are you saying that upon first load that `Xft.dpi` is unset, or it has a different value?

Do you also have a `~/.Xresources` file in addition to `~/.Xresources-regolith` @owen62601 ?

**Comment by owen62601** [comment]
No I don't have a Xresource file.

I just did a fresh minimal install of Ubuntu 18 and then added regolith straight after updating/upgrading the default packages.

First time booting into regolith was fine, but subsequent boots encountered the same issue.

I'm not too sure

**Comment by owen62601** [comment]
Sorry wrong button.

I couldn't find any files that set the Xft.dpi settings in the regolith configs or any other configurations I had.

I did some testing by logging the xrdb query again, this time on fresh install. It looks like Xft.dpi is set to 96 when i3 loads initially from i3-gnome-flashback. Logging from console reveals Xft.dpi to be 192 after the login finished.

**Comment by kgilmer** [comment]
While not rock-solid, this seems to provide a plausible root-cause for the issue: https://unix.stackexchange.com/questions/389355/who-is-setting-the-xresource-xft-dpi

**Comment by kgilmer** [comment]
@owen62601 if you'd like a free Regolith laptop sticker email me a postal address and I'll send you one.  kgilmer at gmail.com
