### ISSUE TITLE
Translate front page to German

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#124]
Front page: https://raw.githubusercontent.com/regolith-linux/regolith-linux.github.io/master/index.md

**Comment by DeastinY** [comment]
I'll be looking into it next week :)

**Comment by o0pwnd0o** [comment]
I have just written a quick translation. Can someone please go through it again?
[index_de.txt](https://github.com/regolith-linux/regolith-desktop/files/3658648/index_de.txt)

**Comment by kgilmer** [comment]
Thank you @o0pwnd0o ! :fireworks:  We're currently looking into how to best support multiple languages on the site.

**Comment by kgilmer** [comment]
This is complete, thanks again @o0pwnd0o !
