### ISSUE TITLE
Translate front page to French

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#125]
Front page: https://raw.githubusercontent.com/regolith-linux/regolith-linux.github.io/master/index.md

**Comment by ploum** [comment]
https://github.com/regolith-linux/regolith-linux.github.io/pull/15

**Comment by ahoneybun** [comment]
https://github.com/regolith-linux/regolith-linux.github.io/commit/348cc3d931d8eed53e2990a69c03b5c55b39b9a4 

This commit corrected it.

**Comment by kgilmer** [comment]
Thanks for your awesome contribution @ploum !  :fireworks:   If you'd like a Regolith laptop sticker send me a postal address to kgilmer at gmail.com.
