### ISSUE TITLE
Translate front page to Italian

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#129]
Front page: https://raw.githubusercontent.com/regolith-linux/regolith-linux.github.io/master/index.md

**Comment by andreagubellini** [comment]
Hi @kgilmer,

As a native speaking italian I would be glad to help.

Could you please tell me where to put the translated files and assign this to me?

thx.

**Comment by kgilmer** [comment]
Hey @andreagubellini :smile: thanks!  You can create a PR and modify this file: https://github.com/regolith-linux/regolith-linux.github.io/blob/master/index.md

We are not yet sure exactly how to configure ghpages in order to best properly render the appropriate language given the client useragent, but are working on it.

**Comment by kgilmer** [comment]
This is complete, thanks again @andreagubellini !
