### ISSUE TITLE
Pull i3xrocks blocket icon definitions out of scripts, into Xresources

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#131]
In some (all?) blocklets the "icon" characters are hardcoded in the scripts.  These should be pulled into Xresources for easier editing.

**Comment by kgilmer** [comment]
This may not be possible due to restrictions w/ cpp.  Need to do some tests.

**Comment by leosunmo** [comment]
Relevant to https://github.com/regolith-linux/regolith-i3xrocks-config/issues/3 I'd say.

**Comment by kgilmer** [comment]
A number of contributors have worked on this and I believe all supported blocklets have been updated and published to `regolith-unstable`.

**Comment by kgilmer** [comment]
This was completed in 1.3.
