### ISSUE TITLE
Lock screen delayed after waking from sleep

### ISSUE THREAD

**Issue by gigglearrows** [regolith-linux/regolith-desktop#132]
I have noticed that whenever I wake my laptop from sleep, it shows my desktop and everything thats on it for a few seconds before switching to the locked screen where I have to insert credentials. Is this a known issue, or have anyone else seen the same thing? I am on a Dell XPS 15 Ubuntu 19.04

**Comment by leosunmo** [comment]
Hey @gigglearrows. I definitely have this occasionally as well. It's a wider issue in Ubuntu and (at least in my experience) in for example Fedora running KDE Plasma. I will have to do some more digging on this as soon as I have time.

**Comment by krejac** [comment]
Yeah, I see this too (never on my gnome/ubuntu combo though). I't actually the only thing keeping me from using Regolith in 'production'. I would love to see this prioritized. :+1: 

Also, thanks a bunch for building Regolith. :muscle:

**Comment by leosunmo** [comment]
Hey @krejac ! For how long are we talking here? Seconds? A quick flash before the lock screen appears?

For me it's just a quick frame of my desktop ( only sometimes, not the majority of times). It'd be hard if not impossible to see what's on the screen as it only flashes for a split second

**Comment by krejac** [comment]
Hi @leosunmo, 
It's about a second or two. Enough to easily identify a known website or a person in an image, but not enough for me to see if I'm able to interact with the desktop before it locks...

**Comment by kgilmer** [comment]
I also experience this issue and believe this is the upstream tracking bug: https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1532508.  Please provide feedback there if you think it would be helpful.  It seems the bug is across both Unity and Gnome-shell so I'm guessing gnome-flashback may also be impacted.

**Comment by kgilmer** [comment]
@krejac , I haven't noticed the issue in Ubuntu 19.10.  If you're able to upgrade, can you let us know if there is any change or the problem persists?

**Comment by krejac** [comment]
Hi @kgilmer, I'm upgrading as I'm writing this. Was running 19.04 upgrading to 19.10. Will report back after having run it for some time. 

But I'll add that today I was actually able to interrupt the machine while showing the content of my session and having just the password box floating on top. From there I could read what I was working on before shutting the lid on my laptop. I could not interact with anything else than the password box though.

**Comment by krejac** [comment]
Just a check-in on this. I did a `do-release-upgrade` but it botched my test machine - so I'll have to do a restore and try again, but unfortunately that won't happen anytime soon... 💩

**Comment by krejac** [comment]
Allright, I've installed Regolith on two machines (both started out as Ubuntu). The glitch is rarer now (I think) but it still happens from time to time. One of my machines is a fairly fast new computer and there the glitch is less prominent (i.e. faster).

**Comment by kgilmer** [comment]
I've learned a bit more about the internals and believe this is an issue in `gnome-flashback`.  If still experiencing the issue kindly [file a bug](https://gitlab.gnome.org/GNOME/gnome-flashback/issues) against it.  We can re-open this if it's somehow determined to be a Regolith issue.
