### ISSUE TITLE
Booting from live USB

### ISSUE THREAD

**Issue by christophecricket** [regolith-linux/regolith-desktop#134]
Hi There.

I'm trying to boot into the v1 version of Regolith. I downloaded an ISO off sourceforge. When the initial GUI prompts me to install ubuntu, it gives me an error saying "the file /casper/vmiluz is missing", and that I need to load the kernel first. What's up with that? The regolith install page says it should be straightforward.

**Comment by kgilmer** [comment]
Hi @christophecricket , the v1 installer has issues with some computers BIOS settings.  More details are here: https://github.com/regolith-linux/regolith-desktop/issues/23.  You may get it to boot by changing your UEFI/Legacy boot settings but there is no guarantee.  Is there a reason you do not want to install from the R1.2 ISO?  If you need Ubuntu 18.04 and toggling BIOS values is not a good fix, then I suggest installing Ubuntu and then the Regolith DE via the PPA as described in the installation instructions.

**Comment by christophecricket** [comment]
Turns out my live USB creator doesn't give a prompt when your drive is smaller than the ISO file of the distro. I'll be sticking to Rufus from now one. Thanks for the quick reply though. Much appreciated :)
