### ISSUE TITLE
Running xrandr command causes desktop background to be lost.

### ISSUE THREAD

**Issue by metadan** [regolith-linux/regolith-desktop#135]
I'm running regolith on a 4k laptop with a 2k second screen, I run an xrandr command after login to configure the displays to be the correct resolution/position/scale.

Once I run the command my desktop background disappears (replaced with black) and resetting it in the settings doens't fix it.

Desktop background appears fine upon initial login.

Please let me know if this should be raised elsewhere.

**Comment by kgilmer** [comment]
Hi @metadan, can you give me the specific xrandr command you run to repro with?

**Comment by metadan** [comment]
xrandr --output "eDP-1-1" --auto --pos 0x0 --scale 1x1  --output "DP-1-1" --auto --scale 2x2 --pos 3840x0

**Comment by kgilmer** [comment]
@metadan , sorry I should have asked this first ~ can you use `gnome-control-center` to manage your screen layout instead of `xrandr`?  I'm not sure what the problem is but if you use gnome it should just work: `<super>`-`d`

**Comment by metadan** [comment]
@kgilmer No worries - I can use gnome but it doesn't let me have the layout/setup I need. I'll just survive without a background

**Comment by kgilmer** [comment]
Ubuntu 19.10 I've read provides more features for scaling, but I'm not sure if that makes its way into gnome-flashback or not.  Another approach to using gnome is described here: https://wiki.archlinux.org/index.php/HiDPI#Fractional_Scaling
