### ISSUE TITLE
kworker high CPU usage

### ISSUE THREAD

**Issue by vanboom** [regolith-linux/regolith-desktop#138]
When I run in the Regolith desktop, I get two kworker processes using 50% CPU, OS:  Ubuntu 18.04

If I log out and log back in using the stock Ubuntu desktop without rebooting, the kworker processes are gone. 

This process also appears near the top of the `top` stack very often at 3% CPU: 
```
compton -f  --config /etc/regolith/compton/config
```

I am still researching how to diagnose the kworker issue.  Is anyone else experiencing this? 

<pre> <font color="#CC0000">  26.03%</font>     0.00%  kworker/u24:0    [kernel.kallsyms]               [k] ret_from_fork                            ▒
+ <font color="#CC0000">  26.03%</font>     0.00%  kworker/u24:0    [kernel.kallsyms]               [k] kthread                                  ▒
+ <font color="#CC0000">  26.03%</font>     0.00%  kworker/u24:0    [kernel.kallsyms]               [k] worker_thread                            ▒
+ <font color="#CC0000">  26.02%</font>     0.00%  kworker/u24:0    [kernel.kallsyms]               [k] process_one_work                         ▒
<span style="background-color:#FCE94F"><font color="#000000">+   26.02%     0.00%  kworker/u24:0    [kernel.kallsyms]               [k] nv50_disp_atomic_commit_tail             </font></span>▒
+ <font color="#CC0000">  26.02%</font>     0.00%  kworker/u24:0    [kernel.kallsyms]               [k] nv50_disp_atomic_commit_work             ▒
+ <font color="#CC0000">  25.90%</font>     0.11%  kworker/u24:0    [kernel.kallsyms]               [k] nv50_base_ntfy_wait_begun                ▒
+ <font color="#CC0000">  23.56%</font>     0.00%  kworker/u24:1    [kernel.kallsyms]               [k] ret_from_fork                            ▒
+ <font color="#CC0000">  23.56%</font>     0.00%  kworker/u24:1    [kernel.kallsyms]               [k] kthread                                  ▒
+ <font color="#CC0000">  23.56%</font>     0.00%  kworker/u24:1    [kernel.kallsyms]               [k] worker_thread                            ▒
+ <font color="#CC0000">  23.56%</font>     0.00%  kworker/u24:1    [kernel.kallsyms]               [k] process_one_work                         ▒
+ <font color="#CC0000">  23.56%</font>     0.00%  kworker/u24:1    [kernel.kallsyms]               [k] nv50_disp_atomic_commit_work             ▒
+ <font color="#CC0000">  23.56%</font>     0.00%  kworker/u24:1    [kernel.kallsyms]               [k] nv50_disp_atomic_commit_tail             ▒
+ <font color="#CC0000">  23.41%</font>     0.13%  kworker/u24:1    [kernel.kallsyms]               [k] nv50_base_ntfy_wait_begun                ▒
+ <font color="#CC0000">  21.43%</font>  <font color="#CC0000">  13.89%</font>  swapper          [kernel.kallsyms]               [k] poll_idle                                ▒
+ <font color="#CC0000">  20.91%</font>  <font color="#CC0000">  20.82%</font>  kworker/u24:0    [kernel.kallsyms]               [k] ioread32                                 ▒
+ <font color="#CC0000">  18.84%</font>  <font color="#CC0000">  18.77%</font>  kworker/u24:1    [kernel.kallsyms]               [k] ioread32                                 ▒
+ <font color="#CC0000">  15.69%</font>     0.05%  kworker/u24:0    [kernel.kallsyms]               [k] nvif_device_time                         ▒
+ <font color="#CC0000">  15.57%</font>     0.12%  kworker/u24:0    [kernel.kallsyms]               [k] nvif_object_mthd                         ▒
+ <font color="#CC0000">  15.45%</font>     0.04%  kworker/u24:0    [kernel.kallsyms]               [k] nvif_object_ioctl                        ▒
+ <font color="#CC0000">  15.40%</font>     0.06%  kworker/u24:0    [kernel.kallsyms]               [k] nvkm_client_ioctl                        ▒
+ <font color="#CC0000">  15.37%</font>     0.20%  kworker/u24:0    [kernel.kallsyms]               [k] nvkm_ioctl                               ▒
+ <font color="#CC0000">  14.67%</font>     0.08%  kworker/u24:0    [kernel.kallsyms]               [k] nvkm_ioctl_mthd                          ▒
+ <font color="#CC0000">  14.58%</font>     0.00%  kworker/u24:0    [kernel.kallsyms]               [k] nvkm_object_mthd                         ▒
+ <font color="#CC0000">  14.54%</font>     0.05%  kworker/u24:0    [kernel.kallsyms]               [k] nvkm_udevice_mthd                        ▒
+ <font color="#CC0000">  14.45%</font>     0.06%  kworker/u24:0    [kernel.kallsyms]               [k] nv04_timer_read                          ▒
+ <font color="#CC0000">  14.43%</font>     0.02%  kworker/u24:0    [kernel.kallsyms]               [k] nvkm_timer_read                          ▒
+ <font color="#CC0000">  14.21%</font>     0.05%  kworker/u24:1    [kernel.kallsyms]               [k] nvif_device_time                         ▒
+ <font color="#CC0000">  14.08%</font>     0.13%  kworker/u24:1    [kernel.kallsyms]               [k] nvif_object_mthd                         ▒
+ <font color="#CC0000">  13.93%</font>     0.05%  kworker/u24:1    [kernel.kallsyms]               [k] nvif_object_ioctl                        ▒
+ <font color="#CC0000">  13.90%</font>     0.06%  kworker/u24:1    [kernel.kallsyms]               [k] nvkm_client_ioctl                        ▒
+ <font color="#CC0000">  13.85%</font>     0.22%  kworker/u24:1    [kernel.kallsyms]               [k] nvkm_ioctl                               ▒
+ <font color="#CC0000">  13.24%</font>     0.08%  kworker/u24:1    [kernel.kallsyms]               [k] nvkm_ioctl_mthd                          ▒
+ <font color="#CC0000">  13.16%</font>     0.01%  kworker/u24:1    [kernel.kallsyms]               [k] nvkm_object_mthd                         ▒
+ <font color="#CC0000">  13.11%</font>     0.04%  kworker/u24:1    [kernel.kallsyms]               [k] nvkm_udevice_mthd                        ▒
+ <font color="#CC0000">  13.05%</font>     0.05%  kworker/u24:1    [kernel.kallsyms]               [k] nv04_timer_read                          ▒
+ <font color="#CC0000">  13.05%</font>     0.02%  kworker/u24:1    [kernel.kallsyms]               [k] nvkm_timer_read                          ▒
</pre>

**Comment by vanboom** [comment]
SOLVED:  I was using the X.Org driver.  Switching to the NVIDIA proprietary driver has resolved the issue.  

The question still remains why this happens under regoith-desktop and not Unity.

**Comment by kgilmer** [comment]
Thanks for reporting the fix @vanboom :smile: .  Hard to say what might be causing the issue.  Other than i3 and the programs launched via `/etc/regolith/i3/config` I'm not aware of what other things would be causing load.  I guess I'd start with Compton.  It could be that the Compton configuration that ships with Regolith is not working well w/ the Xorg driver.  Since stock Unity wouldn't be using Compton, this could be the difference, although just a guess.  If you're interested in troubleshooting more, perhaps switch back to the Xorg driver, comment out compton from your i3 file and see if you still have high load.  If not, no worries.

**Comment by vanboom** [comment]
Yes, commenting out the Compton line solved it as well.  Thanks.  I am not yet sure which "effects" are missing by not using Compton, things look good so far.

**Comment by kgilmer** [comment]
Good to know.  I think I'll work on a section in Troubleshooting for Compton and discrete graphics cards.

**Comment by kgilmer** [comment]
Related: https://github.com/regolith-linux/regolith-desktop/issues/156
