### ISSUE TITLE
Illegible Chrome autofill dropdowns

### ISSUE THREAD

**Issue by harold** [regolith-linux/regolith-desktop#139]
Hi all, as ever - thanks for regolith, it's outstanding, a total blast, and my favorite setup at the moment!

I encountered one interesting thing and I wonder if others have seen it, or if someone here can give me a pointer to fixing it.

In Chrome, autofill/autocomplete dropdowns (often seen for login/password boxes, etc) have a funny background color that makes them illegible:
![image](https://user-images.githubusercontent.com/7443/66430415-53855c00-e9d7-11e9-9ace-9cda6c1eee45.png)

Potentially related: https://github.com/arc-design/arc-theme/issues/141#issuecomment-428638503

Also:
```
$ cat .Xresources.d/theme-regolith 
#define gtk_theme       SolArc-Dark
#define icon_theme      Arc
#define wallpaper_uri   "file:///usr/share/backgrounds/ESP_020528_1750_desktop.jpg"
```

Thanks in advance. Let me know what I can do to help.

**Comment by harold** [comment]
Relevant slack discussion: https://regolith-linux.slack.com/archives/CLM0Y3H5Y/p1570564265114900

**Comment by kgilmer** [comment]
Issue referenced from slack discussion: https://github.com/arc-design/arc-theme/issues/141#issuecomment-428638503

**Comment by leosunmo** [comment]
This doesn't seem to be an issue for me right now. Could be a change in Chrome itself. Anyone else still having this issue?

**Comment by harold** [comment]
Yup, definitely seeing this on both my machines that run regolith. What versions of related items are you running?

**Comment by kgilmer** [comment]
I am using the "Material Nord" color theme in Chrome and do not see this issue.

**Comment by priestoferis** [comment]
I also have this issue with color-nord

**Comment by nickgrim** [comment]
I was using the "GTK+" theme, and seeing this issue. Can confirm it is resolved if I switch to the "Material Nord" theme.

**Comment by kgilmer** [comment]
Thanks @nickgrim !
