### ISSUE TITLE
How to change keyboard layout?

### ISSUE THREAD

**Issue by mochja** [regolith-linux/regolith-desktop#14]
I somehow changed my keyboard layout and cannot find shortcut to switch back. How can I do it?

**Comment by kgilmer** [comment]
Hi @mochja , do you mean the i3 keybindings?  If so, you can reset back to the default configuration by removing the file `~/.config/i3-regolith/config` and logging back into the Regolith session.  A fresh copy will be written there when you log back in.

**Comment by mochja** [comment]
No, I mean [keyboard layout](http://kbd-intl.narod.ru/english/layouts). How can I switch between German and US layout?

Interestingly I somehow switched to the other layout, but I don't know what I pressed. I was able to switch back via `setxkbmap us`.

**Comment by kgilmer** [comment]
Ah ok, well this is handled by the Settings app just like stock Ubuntu.  I found this page which describes changing and adding keyboard layouts: https://websiteforstudents.com/configure-ubuntu-18-04-lts-beta-keyboard-layout-for-native-languages/

Is that what you're looking for?

**Comment by mochja** [comment]
Yes,

by default there is Super + Space keyboard shortcut in Ubuntu, which is remapped in regolith.

I was able to change shortcut in keyboard settings

![image](https://user-images.githubusercontent.com/1218946/56803013-d0ee5300-6821-11e9-8e47-cbc23402e592.png)

I still wonder how I was able to switch the layout.

It would be nice if this could be mapped by default to something else than super + space, do you think it's possible?

**Comment by kgilmer** [comment]
I believe it's possible.  I think this [link explains how it would be done](https://askubuntu.com/a/1075949/834410).  Can you give a recommendation for a natural key combination for switching keyboard layouts?

**Comment by kgilmer** [comment]
I've opted for alt-super-backspace as an alternative for keyboard layout switching.  A new version of `regolith-gnome-flashback` has been published to `regolith-unstable` that will remap the keys with this: 

```
gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Alt><Super>BackSpace']"
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward "['<Shift><Alt><Super>BackSpace']"
```
I'll test it and close this if it works as expected.

**Comment by kgilmer** [comment]
Tested change in Bionic and Disco without issues.  Moved change to `regolith-stable` and closing issue.  Kindly re-open if the issue persists.

**Comment by joaocmd** [comment]
Seems like if I rebind to "alt + shift" it simply does not work. Is it possible to be some conflict with other keybindings?

**Comment by kgilmer** [comment]
It's possible.  You can check to see what gnome keybindings are set in `gnome-settings`.

**Comment by joaocmd** [comment]
I had it set like this:
![image](https://user-images.githubusercontent.com/5345834/109507598-cf81b780-7a96-11eb-8587-87229648e5fc.png)

From running `gsettings set org.gnome.desktop.wm.keybindings switch-input-source "['<Shift>Alt_L']"`.
All other keybinds are disabled. It was working on normal gnome from a fresh Ubuntu install. Different keybindings work, such as Ctrl+Space.
