### ISSUE TITLE
regolith desktop env doesn't work on linuxmint 19.2

### ISSUE THREAD

**Issue by oussama-he** [regolith-linux/regolith-desktop#140]
I installed regolith desktop on my linuxmint 19.2 like this:
```
sudo add-apt-repository -y ppa:kgilmer/regolith-stable
sudo apt install regolith-desktop
```
And after I reboot my pc I choose regolith in my login screen then press enter, it shows a black screen for few seconds then return to the login screen again.

Does any help please?

**Comment by leosunmo** [comment]
Hey @oussama-he ! Regolith doesn't officially support Mint, but it is built on top of Ubuntu, so it could probably be made to function properly.

I think we'd need to a bit of troubleshooting and log scouring to figure out what is causing this issue in LinuxMint. If you want to continue to make Regolith compatible with LinuxMint I am more than happy to help in the [Slack Channel](https://regolith-linux.herokuapp.com).

@kgilmer might have something in mind here, but I don't think we will focus too much on getting compatibility with LinuxMint right now.

**Comment by leosunmo** [comment]
https://github.com/regolith-linux/regolith-desktop/issues/141#issuecomment-544213867

@oussama-he as soon as we merge this in to the unstable repository you _should_ be able to run it on mint.

**Comment by leosunmo** [comment]
@oussama-he could you try the unstable repository and see if it work on mint? If you don't want to run the unstable repo you can wait until it's in stable.

**Comment by oussama-he** [comment]
@leosunmo Thanks, I would like to use the stable, so I will wait until be stable.

**Comment by leosunmo** [comment]
Excellent! I will leave this issue open until it's available in stable.

**Comment by kgilmer** [comment]
It's in `regolith-stable`.  At this point unstable and stable are in sync.

**Comment by tvvoorst** [comment]
Same issue @ kali 2019.3, even in stable

**Comment by kgilmer** [comment]
If anyone is interested and able to test this now with Regolith 1.3 kindly re-open the ticket and report back.

**Comment by ZanSara** [comment]
I just tried to install Regolith on a fresh install on Linux Mint 19.3 (with Cinnamon, if it matters) and I can confirm the issue is still present. Both LightDM and Ly show me a black screen, occasionally with a blinking cursor, and then go back to the login screen.

I installed Regolith according to the instruction on the main page:
```
$ sudo add-apt-repository ppa:regolith-linux/release
$ sudo apt install regolith-desktop
```
Please let me know if and how I can help you debug the issue further.

**Comment by dustinromey** [comment]
Same here.

Thanks

**Comment by kgilmer** [comment]
I have root-caused the issue.  I have created a new issue to track the work: https://github.com/practicalli/regolith-solarized-light/issues/1

In the mean time, if you're able and willing, simply update `/usr/bin/i3-gnome-flashback-session` to look like this:
```
#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
fi

exec gnome-session --session=i3-gnome-flashback --disable-acceleration-check "$@"
```

This script is supplied by Regolith (`regolith-gnome-flashback`) and there is no danger that changes to this script will effect other desktop sessions.  I have verified that this fix works on Linux Mint 19.3.

**Comment by ZanSara** [comment]
Thank you! It worked perfectly :)

**Comment by aitoehigie** [comment]
This issue is back for me. I upgraded to Linux mint ulyana and when try to login screen then press enter, it shows a black screen for few seconds then return to the login screen again.
