### ISSUE TITLE
Issue after upgrading to Ubuntu 19.10

### ISSUE THREAD

**Issue by carderne** [regolith-linux/regolith-desktop#141]
Had the same issue as #105, which was fixed in regolith-unstable.

Similar issue has now resurfaced: trying to log in to a Regolith session, I get a mouse icon, a brief purple or gray screen, and then back to the login screen. I'm on Ubuntu 19.10 with everything updated, using regolith-unstable channe, tried reinstalling Regolith and using default config.

Here's the result of `cat /var/log/syslog | grep i3`:
https://gist.github.com/carderne/1e87bf3299cc1e5683020db6cd2c9038#file-syslog-i3

**Comment by realignedTech** [comment]
I'm having the exact same issue. Initially it worked fine (I installed on a fresh Ubuntu 19.10 from the unstable ppa). Now this happens:

Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: method return time=1570726563.137893 sender=:1.36 -> destination=:1.81 serial=212 reply_serial=2
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]:    object path "/org/gnome/SessionManager/Client21"
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: md5sum: /home/stefan/.Xresources-regolith: No such file or directory
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: Usage:
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]:   gsettings [--schemadir SCHEMADIR] get SCHEMA[:PATH] KEY
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: Get the value of KEY
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: Arguments:
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]:   SCHEMADIR A directory to search for additional schemas
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]:   SCHEMA    The name of the schema
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]:   PATH      The path, for relocatable schemas
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]:   KEY       The key within the schema
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: Regolith is launching i3-gaps with /home/stefan/.config/regolith/i3/config
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: 10.10.2019 18:56:03 - ERROR: You did not specify required configuration option "font"
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: 10.10.2019 18:56:03 - ERROR: Another window manager seems to be running (X error 10)
Oct 10 18:56:03 Pahoa i3-gnome-flashback.desktop[4969]: method return time=1570726563.283505 sender=:1.36 -> destination=:1.94 serial=259 reply_serial=2

**Comment by leosunmo** [comment]
Definitely looks like `ERROR: Another window manager seems to be running (X error 10)` is the culprit for both of you. Weird. This is probably the same issue causing LinuxMint to not work (#140).

This will require some more digging (and probably a fresh system to install onto and play around).

**Comment by realignedTech** [comment]
I noticed the default Gnome bar is now visible on login (right before i get redirected to the login screen), it wasn't the case when I installed regolith a few days ago.

**Comment by kgilmer** [comment]
What has changed since it was working?  Did you perform an `apt update`?   Did Ubuntu 19.10 get updated or Regolith?

**Comment by realignedTech** [comment]
apt history reveals the following updates:

Start-Date: 2019-10-09  18:17:02
Commandline: /usr/bin/unattended-upgrade
Upgrade: xserver-common:amd64 (2:1.20.5+git20190820-0ubuntu3, 2:1.20.5+git20191008-0ubuntu1), xserver-xorg-legacy:amd64 (2:1.20.5+git20190820-0ubuntu3, 2:1.20.5+git20191008-0ubuntu1)
End-Date: 2019-10-09  18:17:04

Start-Date: 2019-10-09  18:17:07
Commandline: /usr/bin/unattended-upgrade
Upgrade: gnome-desktop3-data:amd64 (3.34.0-2ubuntu1, 3.34.1-1ubuntu1), libgnome-desktop-3-18:amd64 (3.34.0-2ubuntu1, 3.34.1-1ubuntu1)
End-Date: 2019-10-09  18:17:07

Start-Date: 2019-10-09  18:17:55
Commandline: /usr/bin/unattended-upgrade
Upgrade: gnome-session-common:amd64 (3.33.92-1ubuntu1, 3.34.1-1ubuntu1), ubuntu-session:amd64 (3.33.92-1ubuntu1, 3.34.1-1ubuntu1), gnome-session-bin:amd64 (3.33.92-1ubuntu1, 3.34.1-1ubuntu1)
End-Date: 2019-10-09  18:17:58

Start-Date: 2019-10-09  18:18:00
Commandline: /usr/bin/unattended-upgrade
Upgrade: gdm3:amd64 (3.34.0-1ubuntu1, 3.34.1-1ubuntu1), gir1.2-gdm-1.0:amd64 (3.34.0-1ubuntu1, 3.34.1-1ubuntu1), libgdm1:amd64 (3.34.0-1ubuntu1, 3.34.1-1ubuntu1)
End-Date: 2019-10-09  18:18:05

Start-Date: 2019-10-09  18:17:45
Commandline: /usr/bin/unattended-upgrade
Upgrade: xserver-xorg-core:amd64 (2:1.20.5+git20190820-0ubuntu3, 2:1.20.5+git20191008-0ubuntu1)
End-Date: 2019-10-09  18:17:47


Start-Date: 2019-10-09  18:18:38
Commandline: /usr/bin/unattended-upgrade
Upgrade: gnome-control-center-faces:amd64 (1:3.34.0.1-1ubuntu2, 1:3.34.1-1ubuntu1)
End-Date: 2019-10-09  18:18:38

Start-Date: 2019-10-09  18:19:22
Commandline: /usr/bin/unattended-upgrade
Upgrade: gnome-control-center-data:amd64 (1:3.34.0.1-1ubuntu2, 1:3.34.1-1ubuntu1), gnome-control-center:amd64 (1:3.34.0.1-1ubuntu2, 1:3.34.1-1ubuntu1)
End-Date: 2019-10-09  18:19:25


I have a few more but those might be related.

I tried apt reinstall regolith-desktop but no success unfortunately

**Comment by kgilmer** [comment]
Thank you @realignedTech !  I have repro'd the issue and am looking into it.

**Comment by ploum** [comment]
One more here. Weirdly, after re-install, the regolith session now opens a regular gnome-shell session !

**Comment by kgilmer** [comment]
Verified that the correct package version is staged in `regolith-unstable` for ` regolith-gnome-flashback` (2.0-1ubuntu1~ppa1).  I'm guessing that something in Eoan changed with Gnome sessions.  Will take a closer look.

**Comment by kgilmer** [comment]
i3 is starting but exits early here: https://github.com/Airblader/i3/blob/release-4.16.1/src/main.c#L606

I'm going to try stock i3 and see what happens on 19.10 as a way of reducing the possibilities.

**Comment by kgilmer** [comment]
I verified that a i3-gaps session works where a regolith session fails.  I then removed everything in `/usr/bin/i3-gnome-flashback` that is regolith specific but it still fails.  Will now look more closely at differences between i3-gaps and regolith sessions.

**Comment by kgilmer** [comment]
Perhaps i3 is failing with BAD_ACCESS?

http://www.rahul.net/kenton/xproto/xevents_errors.html

**Comment by ploum** [comment]
the problem may be i3-gnome-flashback itself if it is not started with the i3-wm-gaps session.

**Comment by kgilmer** [comment]
yep, agreed @ploum .  From the logs it appears that i3-gnome-flashback is failing because i3 is failing because i3 is returning X error code 10 upon start, thinking a window manager is already loaded.  It's unclear to me at this point why i3 is failing.  In comparing logs between i3 (working) and regolith (broken) I don't see something starting/not-starting that would seem to be the root cause of this issue.

**Comment by ploum** [comment]
intuitively, it looks like a change in gnome-session has re-enabled mutter which makes i3 fails. I feel that way because it happened once that the regolith session didn't crash and, instead, presented me with a completely vanilla gnome-shell desktop (including mutter). So probably kind of a race condition.

**Comment by SidBiffi** [comment]
Having the same issue here, do we have any updates on how we might solve it? 
Thank you in advance.

**Comment by kgilmer** [comment]
Update: @duill [provides the fix upstream](https://github.com/deuill/i3-gnome-flashback/commit/c7356953499c3dd6ab212b6ec026d1ecd521424a).  I will integrate the fix this weekend into Regolith.  Stay tuned!  :smile: 

![Screenshot from 2019-10-19 19-14-00](https://user-images.githubusercontent.com/49683/67153815-0f326f80-f2a5-11e9-82ba-98889e5dc54f.png)

**Comment by kgilmer** [comment]
`regolith-gnome-flashback - 2.1-1ubuntu1~ppa1` is available for testing in `regolith-unstable`.  If I (or anyone else testing) don't find any problems, tomorrow I'll promote to `regolith-stable`.

**Comment by darxkies** [comment]
The changes work for me.

**Comment by kgilmer** [comment]
Thanks for testing @darxkies !  If you'd like a Regolith laptop sticker send me a postal address to kgilmer at gmail.com and I'll mail you one.

**Comment by carderne** [comment]
Working here too, thanks @kgilmer and upstream!

**Comment by kgilmer** [comment]
Thanks @carderne !  Same goes if you'd like a Regolith sticker send me an address.

**Comment by kgilmer** [comment]
The Ubuntu process to update to 19.10 removes the Regolith PPA, and then requires the user to reboot.  This means the user will not get the working version of `regolith-gnome-flashback`.  If Regolith is the only desktop session installed, this means the user can no longer login except via TTY.  

Given this issue, I'll need to write some docs for the upgrade process before promoting the 19.10 support to stable.

In the mean time, anyone wanting to use Regolith on 19.10 will need to use the `regolith-unstable` PPA.  Simply run `sudo add-apt-repository ppa:kgilmer/regolith-unstable` and `sudo apt install regolith-gnome-flashback`.

**Comment by TomFaulkner** [comment]
Changing to the unstable worked for me on Pop 19.10.

Thanks!

**Comment by meatballs** [comment]
I've installed on a fresh 19.10 machine from the unstable ppa and all worked perfectly.

**Comment by leosunmo** [comment]
Great to hear this is working for everyone! This should unlock it for Linux Mint among others as well. 

I'll leave this open until we move to Stable and we've heard from some people that it works.

**Comment by realignedTech** [comment]
confirmed working here as well. Big thanks to the regolith team!

**Comment by kgilmer** [comment]
Great news!  Anyone wanting a Regolith laptop sticker on this issue, send me a postal address and I'll send you one!  kgilmer at gmail.com.
