### ISSUE TITLE
Gtk-theme sometimes display clear text on whitebackground

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#142]
It looks like the GTK theme is putting cleartext on whitebackground in at least 2 applications (astroid, geary).

![Screenshot from 2019-10-11 14-08-43](https://user-images.githubusercontent.com/1233155/66650599-495e9a00-ec31-11e9-91de-40dc8ecd55ee.png)

**Comment by kgilmer** [comment]
Are you using the default GTK theme, `nordic` @ploum ?

**Comment by ploum** [comment]
Yes, I don't even know how to change it.

Le mar. 15 oct. 2019 à 17:13, Ken Gilmer <notifications@github.com> a
écrit :

**Comment by ploum** [comment]
I confirm that this bug is only related to the theme Nordic and is still happening on 19.10 with Geary. It doesn't look like a Geary bug as Geary works well with Solarized Dark.

**Comment by kgilmer** [comment]
Thanks @ploum .  You can change your theme w/ the gnome-tweaks tool or via gsettings on the command line.  Here is how Regolith does it upon first login: https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L86-L87

Regarding the issue w/ the theme, I suggest you file an issue upstream, here: https://github.com/EliverLara/Nordic/issues

**Comment by ploum** [comment]
thanks, posted as https://github.com/EliverLara/Nordic/issues/42
