### ISSUE TITLE
Change st-terminal Font

### ISSUE THREAD

**Issue by Radonirinaunimi** [regolith-linux/regolith-desktop#143]
How can I easily change the font-size of the st-terminal in the last version?

**Comment by kgilmer** [comment]
Have a look at the customization guide and howtos: 
https://regolith-linux.org/configure.html
https://regolith-linux.org/howto.html

If you just want to change the font directly, you can specify a font when launching `st`.  Details are in the [arch wiki for st](https://wiki.archlinux.org/index.php/St).

**Comment by kgilmer** [comment]
Ah, and just to change the font size interactively: `<ctrl>-<shift>-<page up>` / `<ctrl>-<shift>-<page down>`

**Comment by Radonirinaunimi** [comment]
Thanks for the prompt response!

I have already gone through these documents before.
> Have a look at the customization guide and howtos:
> https://regolith-linux.org/configure.html
> https://regolith-linux.org/howto.html

What I really want is a permanent change that is automatically loaded once I open ```st``` without having to change at the launching time:
> If you just want to change the font directly, you can specify a font when launching `st`. Details are in the [arch wiki for st](https://wiki.archlinux.org/index.php/St).

And I think, with the following:
> Ah, and just to change the font size interactively: `<ctrl>-<shift>-<page up>` / `<ctrl>-<shift>-<page down>`

one cannot go below the default size.

On the other hand, I have become more comfortable with ```st``` (thanks to regolith) and do not want to go back to ```gnome-terminal```. Would there be any possibility to do that?

**Comment by kgilmer** [comment]
Hi @Radonirinaunimi , yes you can do that.  First, follow the "Xresources Example" on the Configure page to have your own copy of the Xresources root and typeface file.  Then modify the [typeface file](https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/typeface-sourcecodepro#L5) w/ the font size you prefer.  Then log out and back in to see the change.

**Comment by Radonirinaunimi** [comment]
Hi @kgilmer ! Thank you very much, it is working now.

**Comment by kgilmer** [comment]
Glad to help @Radonirinaunimi , closing issue.
