### ISSUE TITLE
There is a strange issue when runining regolith with other terminals like gnome-terminal or tilix

### ISSUE THREAD

**Issue by anaganisk** [regolith-linux/regolith-desktop#145]
The cursor is misplaced or has some delay untill multiple keystrokes are sent. Even openening on vim/nvim it gets stuck untill Eneter key is pressed.

**Comment by leosunmo** [comment]
Hey @anaganisk! This is a weird one, do you have any details around the version of the terminals and Ubuntu? 
I run Alacritty and don't have these problems, so might be something specific to these terminals or a general Compton issue.

**Comment by kgilmer** [comment]
Yeah I'd disable Compton first and see what that does.

https://regolith-linux.org/howto.html#disable-compton

**Comment by anaganisk** [comment]
Yeah its compton, disabled it and its fine.

**Comment by sotte** [comment]
Here is an updated link https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Disable-Compton because the previous link https://regolith-linux.org/howto.html#disable-compton is dead.

**Comment by akhi3030** [comment]
Hi, is it possible to get up-to-date instructions on how to do this please?  Note that first you have to create a copy of the config file in order to be able to edit it.  Then the current config file does not mention Compton at all.

**Comment by kgilmer** [comment]
@akhi3030 , this page explains how to find and swap between compositors: https://regolith-linux.org/docs/customize/compositors/

**Comment by akhi3030** [comment]
Thanks @kgilmer .  My google search helped me find that page finally and it did help address the problem.
