### ISSUE TITLE
Remove gnome-shell and evolution-data-server from the default install?

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#147]
Afaik, gnome-shell and evolution-data-server are not providing any feature to Regolith (I may be wrong). But those two packages are needed by GDM3.

As those two packages bring quite a few dependencies and are taking some ressources, it may be useful to investigate how to remove them from the default install either by providing a GDM package without the dependencies or by switching to another DM.

Of course, this ticket is irrelevant if both package are providing useful feature for the Regolith desktop.

**Comment by kgilmer** [comment]
`evolution-data-server` must be a transitive dependency but gdm3 and gnome-shell seem pretty integrated, giving my read of gdm3's debian control file.  

However, lightdm works, and allows the removal of evolution-data-* and gnome-shell.  Ubuntu-session requires gdm3.  I like the idea of moving to lightdm and removing gnome-shell and the evolution stuff as suggested.  I wonder if others have thoughts?

**Comment by ploum** [comment]
I've read that lightdm does not support Wayland. Which might be a problem for some users who also have a wayland session. But as i3w doesn't not work with Wayland, it might not be a priority.

If the goal is to switch one day to wayland/sway, then switching today to lightdm might be useless work.

**Comment by leosunmo** [comment]
While I'm not about to rush in to Sway-olith just yet, I do want to experiment with that at some point. Moving things away from Wayland supported solutions might make that trickier. But we should also not over-optimise towards something that _might_ happen in the future. If lightdm is a nice improvement, let's do it.

**Comment by kgilmer** [comment]
I didn't notice this originally but at least in my testing lightdm depends on Unity in the same way that gdm3 depends on gnome-shell.  IMHO lightdm is only a better option if we can easily get it without that or any other DE dependency.

**Comment by kgilmer** [comment]
I have opted not to do this for standard Regolith.  the gdm3<->gnome-shell dependency is not trivial to remove from experiments.
