### ISSUE TITLE
Workspaces Switch Monitors After Screens Come Back On

### ISSUE THREAD

**Issue by mtwb47** [regolith-linux/regolith-desktop#148]
This happens after my monitors have gone to sleep (as they should). When I wake them back up, all of my workspaces are on different monitors than they were when the monitors turned off.

For example, when I walked away now, ws1 and ws3 were on monitor 1 and ws2 and ws4 were on monitor 2. Now ws1-4 are all on monitor 1 and ws5 is open and on monitor 2. 
I'm going to try the i3 option of forcing workspaces to be on specific monitors and see if that works to fix this. 
(using the latest version of everything. Just installed this morning)

**Comment by mtwb47** [comment]
Dictating which monitor to open a workspace on, did not work. In fact, it made the entire monitor glitch out as seen in this vid: https://imgur.com/E7Nrirn

It's making my computer unusable, so I won't be able to help troubleshoot.

**Comment by kgilmer** [comment]
Hi @mtwb47 :smile: , interesting, I have not seen that glitch behavior before.  There seem to be a few things going on, let's break them down.

1. Window arrangement changes after wake: this I believe to be a hardware issue.  Or, at least it is for me.  I have 3 monitors connected to a laptop at work.  When my computer wakes, the windows are in random screens, and also sometimes empty workspaces are created that contain no windows.  The reason I believe this to be HW is that the same thing occurs when I boot into windows.  There are a number of programs available for i3 that allow you to save and restore a window layout, including one that I've written: [i3-snapshot](https://github.com/regolith-linux/i3-snapshot).  I have seen several other implementations of this feature, so another program may server you better.  I use this to save/restore window layout but it's a work around, not a fix.
2. Glitch: If you can get the glitch to occur consistently, please try and [disable Compton](https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Disable-Compton) and see if that has any effect.

**Comment by kgilmer** [comment]
Oh, also, cool wallpaper!

**Comment by leosunmo** [comment]
I agree with @kgilmer that the workspace shuffle is a HW issue.

I run a T480 laptop with a docking station and external screens. If I unplug my laptop from the docking station, the workspaces obviously move to the remaining screen (the laptop screen). When I plug it back in I have to manually move the workplaces back to my secondary screen.

The same behaviour is observed when my laptop goes to sleep and the external screen shuts down. From my laptop's perspective (i3? Something in Gnome? not sure) the screen is gone, so moves the workplaces back to the only remaining screen.

The "fix" for this is to use and polish something like [i3-snapshot](https://github.com/regolith-linux/i3-snapshot) or https://github.com/klaxalk/i3-layout-manager.

I will close this for now as it's not necessarily a Regolith issue, but one that we are definitely interested in solving for people (myself and Ken included).

The screen glitch is _very_ interesting though. If disabling Compton doesn't solve it, @mtwb47 could you please create a new issue? I'd very much like to solve that for you if it persists!
