### ISSUE TITLE
Translate front page into Hungarian

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#149]
Front page: https://raw.githubusercontent.com/regolith-linux/regolith-linux.github.io/master/index.md

**Comment by GyHUN95** [comment]
---
elrendezés: alapértelmezett
cím: 
nyelv: hu
---
A Regolith egy egyedülálló asztali környezet, amely áthidalja a Windows és Mac hibáit, hogy egy eredményes és szép helyet biztosítson a munkavégzéshez. Ubuntu-ra és GNOME-ra építkezve a Regolith stabil, jól támogatott, és következetes alapokon áll.

<a href="/assets/screenshot-intro.png"><img class="screenshot" alt="Intro Screenshot" src="/assets/screenshot-intro.png"/></a>

[Regolith vizuális túra](/visual-tour.html)

### Mi külömbözteti meg a Regolithot?

- A GNOME rendszerkezelőjének funkcióit biztosítja az [i3](https://i3wm.org/) produktív mukafolyamatának segítségével.
- Lehetővé teszi az új felhasználók számára, hogy egy gyors és szórakoztató módon próbáljanak ki egy [csempéző(tiling) ablakkezelőt](https://opensource.com/article/18/8/i3-tiling-window-manager).
- Támogatja [a könnyű testreszabhatóságot](https://github.com/regolith-linux/regolith-desktop/wiki/Customize) és [növekedést](https://www.reddit.com/r/unixporn/) egy konzisztens [Xresource konfigurációval](https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/root).
- Az [Ubuntu Szoftverközpontra](https://snapcraft.io/store) és csomagtárolókra támaszkodik egy hatalmas, jó minőségű szoftverválasztékért.
- Olyan asztalt szállít, amely kisebb felületet tartalmaz, amely testreszabható és búvíthető szükség szerint.
- Az alapvető billentyűkombinációkra vonatkozó áttekintéssel érkezik, hogy hogyan navigáljon abalakokat, indítson programokat, és kezelje a rendszert.
- Biztosít egy [telepítő szkriptet](https://github.com/regolith-linux/regolith-desktop/blob/master/build.sh) és [csomag-metaadatot](https://github.com/regolith-linux/regolith-desktop/blob/master/package-model.json) a felhasználók számára, hogy könnyedén felhasználhassák az asztali környezetet és a disztribúciót.

### Szerezze be a Regolith-et

Telepítse, vagy tesztelje a Regolithot az alapoktól a [LiveCD Telepítővel](https://sourceforge.net/projects/regolith-linux/), vagy amennyiben már rendelkezik egy Ubuntu telepítéssel*, egyszerűen adja hozzá, egy másik asztali folyamatként, azáltal, hogy telepíti a `regolith-desktop` csomagot a [Regolith PPA]-ból (https://launchpad.net/~kgilmer/+archive/ubuntu/regolith-stable). Nézze meg a [telepítési oldal]-t (https://github.com/regolith-linux/regolith-desktop/wiki/Install-Regolith) további információkért.

<sub>*Ubuntu 18.04 és Ubuntu 19.04 alapok elérhetőek</sub>

### Következő lépések

Vessen egy pillantást a [Hogyan kezdje](https://github.com/regolith-linux/regolith-desktop/wiki/Getting-Started), hogy többet tudhasson meg a  Regolith Linux használatáról, nézze meg a [legutóbbi frissítéseket](/news.html), vagy ellenőrizze a [konfigurációs](https://github.com/regolith-linux/regolith-desktop/wiki/Customize) oldalt [list of HowTos](https://github.com/search?utf8=✓&q=org%3Aregolith-linux+HowTo+in%3Atitle&type=Wikis), hogy hogyan szabhatja saját szájízére. Továbbá nézze meg a [Billentyűkombinációkat](https://github.com/regolith-linux/regolith-desktop/wiki/Keybindings), hogy elsajátíhassa az új asztali környezete használatának leggyorsabb módját. Miután kellően megismerkedett a Regolith-tal nézze meg az [aktív Komment kéréseket](https://github.com/regolith-linux/regolith-desktop/issues?utf8=✓&q=is%3Aissue+is%3Aopen+"Request+for+Comment").

### Kapcsolat

|---------|----------|
| Hibajelentések | [Github problémák](https://github.com/regolith-linux/regolith-desktop/issues) |
| Funkció kérések | [Github problémák](https://github.com/regolith-linux/regolith-desktop/issues) |
| Chat | [Slack csatorna](https://regolith-linux.herokuapp.com) |
| Változások bejelentése | [Levelező lista](https://www.freelists.org/list/regolith-linux) |

### Elismerések

A Regolith inkább kuráció, mint kreáció. Íme néhány a jelentős emberek és szervezetek közül, akik ehhez kapcsolódó/hasonló munkát készítettek **függetlenül** Regolith-tól.

|---------|----------|
| [Michael Stapelberg](https://i3wm.org) és [Ingo Bürk](https://github.com/Airblader/i3) | Asztali felület
| [Dave Davenport](https://github.com/davatorium/rofi) | Asztali felület
| [yshui](https://github.com/yshui/compton) | Asztali felület
| [Alberts Muktupāvels](https://wiki.gnome.org/Projects/GnomeFlashback) | Asztali felület
| [Jesús Castro](https://github.com/jcstr) és [Alex Palaistras](https://github.com/deuill) | Asztali felület
| [Vivien Didelot](https://github.com/vivien/i3blocks) | Asztali felület
| [Arctic Ice Studio](https://github.com/arcticicestudio) és [Ethan Schoonover](https://ethanschoonover.com/solarized/) | Színek
| [Eliver Lara](https://github.com/EliverLara/Nordic) | Téma
| [Sam Hewitt](https://snwh.org/paper) | Ikonok
| [suckless.org](https://st.suckless.org) | Terminál
| [Lucas Bellator](https://unsplash.com/photos/C0OD8OM-oM0) és [Luca Bravo](https://unsplash.com/photos/xnqVGsbXgV4) | Háttérkép
| [PJ Singh](https://launchpad.net/cubic) | Infrastruktúra
| [Canonical](https://canonical.com) and [GitHub](https://github.com) | Infrastruktúra

**Comment by kgilmer** [comment]
Thank you @GyHUN95 :smile: .  I will work on integrating this into the site this weekend!  If you would like a Regolith laptop sticker, I will mail you one.  Send me a postal address at kgilmer at gmail.com.

**Comment by kgilmer** [comment]
Added @GyHUN95 's content in commit: https://github.com/regolith-linux/regolith-linux.github.io/compare/2d6d23debea3...37d7fde23348
