### ISSUE TITLE
Support Ubuntu 18.10 in PPA

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#15]
Provide packages for Disco in PPA

**Comment by kgilmer** [comment]
18.10 versions of Regolith packages are available for testing in the `regolith-unstable` PPA.

**Comment by kgilmer** [comment]
I will not promote the Cosmic packages to `regolith-stable` until someone that wants Regolith on that version of Ubuntu tests it in unstable and verifies it's working.

**Comment by tek-warp** [comment]
I have installed the `regolith-unstable` version on 18.10.

 Everything seems to be working fine, except the fact that the colored squares of the workspace indicators only show the outline - they are not filled with the colors.

**Comment by kgilmer** [comment]
This issue may be related to https://github.com/regolith-linux/regolith-i3blocks/issues/1 .

**Comment by kgilmer** [comment]
I tested recently and have found some issues with how i3bar orders workspaces.  I have no idea why this behavior would vary on Disco.  Due to this I don't want to push packages to `regolith-stable` at this time.

**Comment by kgilmer** [comment]
Actually the workspace ordering bug was unrelated to 18.10, but rather this: https://github.com/regolith-linux/regolith-desktop/issues/59

**Comment by kgilmer** [comment]
Verified fixed against fresh install of 18.10 with `regolith-unstable`.  Moving Cosmic packages to `regolith-stable`.

**Comment by kgilmer** [comment]
Cosmic packages pushed to `regolith-stable`.  Closing.
