### ISSUE TITLE
jetbrains IDEs (like IntelliJ) are blank

### ISSUE THREAD

**Issue by soraphis** [regolith-linux/regolith-desktop#151]
they are just a white screen. even when in floating mode. i can click the menus and toolbar buttons.

![image](https://user-images.githubusercontent.com/3066582/67432366-71151100-f5e6-11e9-995e-f36e845fb5e5.png)

![image](https://user-images.githubusercontent.com/3066582/67432414-85590e00-f5e6-11e9-8cc6-e7469070fcc9.png)

```
OS: Ubuntu 19.10 x86_64
Host: W840SU Series
Kernel: 5.3.0-18-generic
Uptime: 2 days, 8 hours, 3 mins
Packages: 2870 (dpkg), 9 (flatpak), 16 (snap)
Shell: zsh 5.7.1
Resolution: 1920x1080
DE: GNOME 3.34.1
WM: i3
Theme: Nordic [GTK2/3]
Icons: Paper [GTK2/3]
Terminal: st
Terminal Font: Liberation Mono
CPU: Intel i5-4200U (4) @ 2.600GHz
GPU: Intel Haswell-ULT
Memory: 4700MiB / 7850Mi
```

**Comment by kgilmer** [comment]
Hi @soraphis , I'm suspecting that there is an issue with Compton on your machine.  Can you disable it and let us know if it makes a difference?

https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Disable-Compton

**Comment by soraphis** [comment]
disabled compton. error still remains.

when i enable compton, it throws this error: 

```
$ compton
[ FATAL ERROR ] Another composite manager is already running
```

mutter seems to be running instead, but:

```
(mutter:13314): Gdk-ERROR **: The program 'mutter' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 264 error_code 10 request_code 2 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by kgilmer** [comment]
Hmm, how did you install Regolith..PPA or LiveCD?  It is odd that mutter would be running at all in a Regolith session.  FWIW I also use JetBrains tools (Intellij, CLion) and have not seen this issue.

**Comment by realignedTech** [comment]
IntelliJ 2019.2 also works fine for me, could not reproduce this

OS: Ubuntu 19.10 x86_64
Kernel: 5.3.0-19-generic
Uptime: 3 hours, 41 mins
Packages: 2288 (dpkg)
Shell: zsh 5.7.1
Resolution: 2560x1440, 2560x1440
DE: GNOME 3.34.1
WM: i3
Theme: Nordic [GTK2/3]
Icons: Paper [GTK2/3]
Terminal: st
Terminal Font: Liberation Mono
CPU: AMD Ryzen Threadripper 1920X 12- (24) @ 3.500GHz
GPU: NVIDIA GeForce GTX 1060 6GB
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
Memory: 8576MiB / 64244MiB

What method did you use to install it?

**Comment by megatux** [comment]
Works fine here, too. OS: Elementary OS 5.0

**Comment by soraphis** [comment]
> Hmm, how did you install Regolith..PPA or LiveCD? It is odd that mutter would be running at all in a Regolith session. FWIW I also use JetBrains tools (Intellij, CLion) and have not seen this issue.

    sudo add-apt-repository ppa:kgilmer/regolith-stable
    sudo apt install regolith-desktop

just tested Rider 2019.2 -> works fine
intelliJ 2019.2 -> still the same problem
 
opened another project in intelliJ -> works fine
opening the first project again, results in this error

thats strange. invalidating caches did not help

**Comment by rcoh** [comment]
If anyone else hits this, I just closed intellij and opened it again. All good the second time.
