### ISSUE TITLE
Add branding to lightdm

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#152]
If we move to lightdm for the R1.3 LiveCD release, the stars background and maybe other stuff should be changed so it's apparent to the user that they'll be logging into Regolith.

This issue was created by https://github.com/regolith-linux/regolith-desktop/issues/147.

**Comment by kgilmer** [comment]
I'm not familiar with any others. Are there advantages or reasons to consider them over lightdm or gdm3 @ahoneybun ?

**Comment by ahoneybun** [comment]
Maybe being more lightweight but not really that I know of.

**Comment by kgilmer** [comment]
Moving to lightdm is not a priority at this point.  Closing.
