### ISSUE TITLE
Icon Tray Issues

### ISSUE THREAD

**Issue by J370** [regolith-linux/regolith-desktop#154]
With reference to [https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Enable-an-Icon-Tray-in-the-Bar](url); and various other issues on this repo; I tried to enable the icon tray through the steps suggested. However, if I do try to run nm-applet or any other applets, it does not seem to show on my Icon Tray.

**Comment by kgilmer** [comment]
Hi @J370 , what do you see after `i3 --moreversion` ?   And what output do you get when you run `nm-applet` from a terminal?

**Comment by J370** [comment]
Hi @kgilmer, Thanks for your reply. I believe that a restart fixed the issue and it now shows up in my icon tray.
