### ISSUE TITLE
open specific applications in fixed size

### ISSUE THREAD

**Issue by roxchgt** [regolith-linux/regolith-desktop#155]
Some desktop applications / clients are designed to be used "normally" in a specific aspect ratio, although they can be resized. For example Telegram Desktop or recently many progressive apps of famous web services like Google Keep or Twitter. It would be nice if it would be somewhere configurable to give a fixed width (percentage) for specific apps such that they don't have to be resized each time after opening in order to look ok… btw, it's just a "nice-to-have" feature request, nothing critical…

PS: floating mode is not the favorable solution

**Comment by kgilmer** [comment]
As a user, would you prefer that apps would remember their last width and keep that, or you'd prefer to explicitly define the subset of apps who's windows should take a specific ratio?

**Comment by roxchgt** [comment]
As a user and in my use case (mainly Telegram), I'd prefer to have a predefined aspect ratio for then given app. So it would be less resizing necessary, in case I close an app in another size than usually preferred.

![Screenshot from 2019-10-27 10-27-36](https://user-images.githubusercontent.com/18581157/67632513-6daead80-f8a4-11e9-84b2-38587267e9b8.png)

**Comment by kgilmer** [comment]
Got it, thanks for the screenshot, that makes it clear.  This is a feature request for i3-gaps (or i3).  I would suggest you post to the [reddit i3wm group](https://www.reddit.com/r/i3wm/).  Often others have found ways of doing what the window manager itself does not provide.

**Comment by leosunmo** [comment]
This is a really nice feature request that I hope i3 (or i3-gaps) can accommodate soon! 

I will close this for now, but we could always consider creating a separate tool that interacts with i3 through the i3 ipc, https://i3wm.org/docs/ipc.html. 

There's really good bindings/libraries for at least C++, Golang and Python (I haven't played with the Python stuff myself, but I presume it hooks in to the C stuff).

**Comment by roxchgt** [comment]
had to comment the first line of @leosunmo final post: I have not posted this feature request anywhere in i3 community, cuz in the first sight there are a lot of things going on there and couldn't find that level of motivation to find out what goes where! If anybody else really interested, then dig in!

**Comment by roxchgt** [comment]
After like 5 months I wanted again badly to make this possible! So i searched again and found out that I could write a simple script to open and resize Telegram Desktop using `i3-msg`, put that in the ~/bin/tel
```bash
#!/bin/bash

i3-msg 'split h; exec /home/roxch/Downloads/Telegram/Telegram'
sleep 0.05
i3-msg 'resize shrink width 400px'
```
then I pointed the app's desktop entry to execute this instead of original executable and voila!
Note that it's not a generic solution and the amount of resizing is relative to my screen (I wish i knew how i'd do this as percentage of screen resolution!)

I wish that in the future releases we have such features like saving different layouts and/or letting apps keep such settings…

**Comment by Irungaray** [comment]
Hey @roxchgt, im having the same issue but couldnt figure out where I should put those lines. Could you provide more information?

**Comment by roxchgt** [comment]
> Hey @roxchgt, im having the same issue but couldnt figure out where I should put those lines. Could you provide more information?

I'd call this solution deprecated! Telegram updater overwrites it and there are other problems with it. Now I figured it out directly from i3 config. Just add this line to your i3 config file:
`for_window [class="Telegram*"]; resize shrink width 10000px; resize grow width 480px;`

**Comment by Irungaray** [comment]
Man thank you so much! WIth your helps I was able not only to launch Telegram on specific size, but also launch some commands at startup, which was giving me some headaches since I installed Regolith (Im pretty noob on Linux) 

Thank you for answering, appreciate that!
