### ISSUE TITLE
Integrate i3-snapshot or alternative to Regolith

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#159]
For users that would like better management of window layout, add i3-snapshot or a better alternative, assign keybindings as needed, and update documentation.

**Comment by abacao** [comment]
I've been using 
https://flameshot.js.org/

**Comment by kgilmer** [comment]
Hi @abacao , actually i3-snapshot is not related to screen capture.  Rather, it's a way of saving and restoring your existing window state.  It mainly becomes useful when you are frequently switching monitor configurations (from desk, to meeting, to presentation, etc.) so that you can "save" your setup and then move all your windows back after various monitor hot-plug events causes them to be reorganized.  As such it's only really useful for laptops.

**Comment by abacao** [comment]
Thank you for the explanation.

**Comment by kgilmer** [comment]
This is complete as of 1.3.
