### ISSUE TITLE
Add panel to gnome-settings to configure Regolith

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#16]
For those wishing to make tweaks to Regolith, such as changing the meta key binding or defining the default size of window gaps, these changes must currently be done by editing a variety of configuration files.  While this is not difficult, it does require understanding several config file formats and it can be easy to get something slightly wrong and have a broken system.

This ticket is to track a feature that would add some kind of "Regolith" tab to the `gnome-settings` application that would allow users to:

1. Change i3 keybindings
2. Configure different wallpaper
3. Configure i3blocks (date/time format, etc.)
4. Configure st terminal font size

etc

Anything expressed in Regolith configuration that is not already available as a setting in `gnome-settings` would be a candidate for this panel but there is probably a small subset of items that would address most people's needs.

**Comment by muniter** [comment]
Well, It would definetly be a great thing. But at the same time quite complex in my opinion, for me I think using i3 is a learning process, and everyone likes their config different, learning i3 and It's configuration can empower you to do great thing on i3, using multiple scratchpads for floating terminals, marking containers, using workspace back and forth, etc. 

I think it would be better to create documentation on how to do things, and reference manuals, and config with comments, etc. And also provide some tooling. Something like the default i3 nagbar, when exiting; but for restoring the default config and restarting i3. This way users are not afraid of braking the config if with just some key combination they can restore all they did.

**Comment by kgilmer** [comment]
>  But at the same time quite complex in my opinion

Yeah, it's certainly a big project.  The worst part I think is not the development work of adding the panel, but the long-term maintenance of tracking a fork of the gnome project, as it seems that [extension is not allowed](https://mail.gnome.org/archives/desktop-devel-list/2011-May/msg00089.html) in gnome-control-center (because they got tired of bug reports from extensions..?).

> I think it would be better to create documentation on how to do things, and reference manuals, and config with comments, etc. And also provide some tooling.

Yes, I agree with this.  Editing the i3 config and/or having a control panel UI are not exclusive.  I would like Regolith to be easy enough to be inclusive to those that cannot or care not to edit files directly.  From the feedback and discussion I've received so far on Regolith, I think most users are already familiar with i3 to some degree and have no problem with editing files.  I want to increase the audience for which such a system appeals to, and I think that some kind of UI is needed for that.  

> Something like the default i3 nagbar, when exiting; but for restoring the default config and restarting i3. This way users are not afraid of braking the config if with just some key combination they can restore all they did.

Great idea!  I think even something like a Desktop shortcut that simply references a script to reset the i3 config file (it can be launched via Rofi) might be a quick and consistent way of implementing your idea.

> Maybe creating a series on getting started wit i3wm by a Regolith user would be great! I would also like if the config files where in the default paths, so when users read other documentation can apply it to Regolith.

Interesting idea as well.  I personally do not watch youtube videos for this sort of thing but can see how it would be useful for people that need more context.  I would certainly support this effort if someone wanted to make the video.

**Comment by drewofdoom** [comment]
+1 for standard config paths.

I also like the idea of a configuration "panel," even if it will not fit in the context of Gnome Settings. Perhaps a custom Rofi menu, that will give you an actionable list of customizations and direct access to the various config files? Could even use this to set the wallpaper, for example.

**Comment by PickingUpPieces** [comment]
Maybe a small shell program which makes it easy to set certain things?

As a start, we should collect the things which should be configured by such a config or panel? If it's not so much a small and easy to understand config file or shell would be enough? What I thought about (or what I changed) and maybe is something, what is a candidate for the settings:
- Color scheme (Maybe nord and gruvbox as options) #31 
- Selection of blocks for i3blocks (Even if they are pretty easy to add, there are problems when you want to have them in a certain color)
- Maybe another terminal option?

**Comment by kgilmer** [comment]
I have a hunch that the terminal option would have some scary edge cases but the other two seem to be a great idea.  What about integrating them into Rofi instead of a shell script?  Have a look at https://github.com/regolith-linux/regolith-desktop/issues/45

**Comment by PickingUpPieces** [comment]
Mhh you're right - shell script isn't a good solution. But Rofi is a little bit limited, isn't it? Haven't done a lot with rofi yet. I have the feeling, that it totally depends what you want to have in the settings. For changing color scheme a rofi menu would be perfect I guess, but not sure about more complex stuff. Maybe a small GTK Menu would be a solution, but that's more work then a rofi menu for sure^^

**Comment by kgilmer** [comment]
I think Rofi would be ok to select from a menu of existing themes.  It's not good for complex UI.  But it may be overkill.  Those wishing to change themes may be happy with editing the Xresources, hard to say.  I will know more when I look more closely into #45 .  GTK-based approach would be much nicer, but I don't like the idea of many (more than one) settings apps, and the problem is that gnome-control-panel can not be extended without forking, from my understanding.

**Comment by leosunmo** [comment]
I think Rofi menus are the way to go if we want to edit config. I'll look at how this would work at some point.

**Comment by kgilmer** [comment]
Agreed that it's not feasible to fork gnome-settings.  Closing.
