### ISSUE TITLE
Regolith won't start from loginscreen in Ubuntu 19.10

### ISSUE THREAD

**Issue by oyvindskaaden** [regolith-linux/regolith-desktop#161]
When I try to log in to Regolith in a fresh install of Ubuntu 19.10, the login screen flashes and goes back to start.
I have read the [HowTo: Upgrade to Ubuntu 19.10 (Eoan Ermine)](https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Upgrade-to-Ubuntu-19.10-(Eoan-Ermine)) in the docs, but this is not that issue. Regolith just don't start. 
I'm not sure where to start debugging, but I thought Regolith was a "plug-and-play" intro to i3.

**Comment by kgilmer** [comment]
Hi @oyvindskaaden :smile: .  You're assumption is correct.  I haven't seen this issue before.  Yes, you shouldn't need anything from the upgrade wiki pages since you're performing a base install.  Perhaps you added or removed packages after the Ubuntu install?  Anything else other than install Ubuntu and install Regolith?  I did this last night to test something else and didn't encounter any issue.  I would start by looking in `/var/log/syslog` after a failed login session for any errors generated by gdm3, gnome-session, or regolith.

**Comment by oyvindskaaden** [comment]
Thanks for fast reply! I have read through the part when i tried loging into Regolith, this was the errors i could find. I think i have read in the docs that gnome-flashback is a nessesary part (?). But i'n not sure. It is installed anyways.
The error blocks are seperated but only with up to 10 lines between.
```
Oct 30 14:28:29 linuXPS gnome-session[2690]: gnome-session-binary[2690]: WARNING: Unable to find required component 'gnome-flashback-init'
Oct 30 14:28:29 linuXPS gnome-session[2690]: gnome-session-binary[2690]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Oct 30 14:28:29 linuXPS gnome-session-binary[2690]: WARNING: Unable to find required component 'gnome-flashback-init'
Oct 30 14:28:29 linuXPS gnome-session-binary[2690]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Oct 30 14:28:29 linuXPS at-spi-bus-launcher[2698]: dbus-daemon[2703]: Successfully activated service 'org.a11y.atspi.Registry'
Oct 30 14:28:29 linuXPS systemd[1629]: gnome-session-manager@i3-gnome-flashback.service: Main process exited, code=exited, status=1/FAILURE
```
```
Oct 30 14:28:29 linuXPS systemd[1629]: gnome-session-manager@i3-gnome-flashback.service: Failed with result 'exit-code'.
Oct 30 14:28:29 linuXPS systemd[1629]: Stopped GNOME Session Manager (session: i3-gnome-flashback).
Oct 30 14:28:29 linuXPS systemd[1629]: gnome-session-manager@i3-gnome-flashback.service: Triggering OnFailure= dependencies.
```
```
Oct 30 14:28:29 linuXPS gnome-screensav[2696]: gnome-screensaver: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

**Comment by heigren** [comment]
I experienced this yesterday and was able to fix it as described here https://github.com/regolith-linux/regolith-desktop/issues/141#issuecomment-544325563. I don't recall adding or removing any packages, I just upgraded when I was prompted about the new version and rebooted afterwards. When trying to login after the reboot, it goes black for a second and then back to the login.

**Comment by kgilmer** [comment]
Hi @heigren :smile: .  To clarify, you had to install the `regolith-unstable` PPA or your fix was with `regolith-stable`?

**Comment by gbaims** [comment]
Hi everyone, regolith-stable worked for me after upgrading to 19.10!

Em qui, 31 de out de 2019 às 11:47, Ken Gilmer <notifications@github.com>
escreveu:

**Comment by leosunmo** [comment]
Hey @oyvindskaaden , did you find a solution for this in the end?

**Comment by oyvindskaaden** [comment]
@leosunmo , yes i did🥳 the fix was as @kgilmer said. I had to start all over again with installing regolith.

**Comment by heigren** [comment]
> Hi @heigren 😄 . To clarify, you had to install the `regolith-unstable` PPA or your fix was with `regolith-stable`?

Sorry for the late reply. I used the `regolith-unstable` just as the comment I linked to said.

**Comment by kgilmer** [comment]
Ok thanks @heigren .  At this point all changes are in `regolith-stable` so you should be able to move back to that if you want.
