### ISSUE TITLE
Grey color in terminal missing

### ISSUE THREAD

**Issue by mwip** [regolith-linux/regolith-desktop#163]
I am using zsh with auto suggestions. They are usually displayed in a grey color. Also e.g. `htop` uses grey colors. However the default theme does not include a grey text color for `st`. 
How can I fix this?

![Screenshot from 2019-10-31 07-58-44](https://user-images.githubusercontent.com/29728338/67926469-6514ea80-fbb6-11e9-9dc9-f03af7d504ae.png)

**Comment by kgilmer** [comment]
Hi @mwip :smile: I think this issue has a solution that may work for you: https://github.com/regolith-linux/regolith-st/issues/5

**Comment by leosunmo** [comment]
@mwip Let us know if the proposed solution doesn't work for you. I'll close this issue for now but feel free to comment and/or reopen!

**Comment by mwip** [comment]
Indeed that solves the problem for zsh-autosuggestions. 
However, for htop, this does not solve the issue. In this case I had to switch to the "broken grey" color scheme

**Comment by hendrikmaus** [comment]
@mwip how did you switch to the "broken grey" color scheme?

**Comment by jadia** [comment]
I fixed the autosuggestion by adding this to my `~/.zshrc` file fixed the issue

```bash
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'
```

[Source](https://stackoverflow.com/a/53070834)
