### ISSUE TITLE
.Xresources-regolith required format seems to differ from /etc/regolith/styles/root

### ISSUE THREAD

**Issue by Interesting-name** [regolith-linux/regolith-desktop#164]
First, thanks for this great piece of software, I love being able to use i3 without being tied down configuring the setup for a week!

So, I'm sure my problem is that I don't understand where all the configuration should happen.
I was trying to change the date/time format displayed in the i3-bar to `%Y-%m-%d %H:%M`.

After some unsuccessful attempts, I found the closed issue #95 mentioning the possibility to change settings via the `.Xresources` and `.Xresources-regolith` files. Thus, I created the file `~/.Xresources-regolith` and entered the following line, modeled after the syntax in `/etc/regolith/styles/i3rocks`: `i3xrocks.date.format: + %Y-%m-%d  %H:%M`
This unfortunately leads to a parsing error after rebooting.

Adding the same line into `~/.Xresources` and running `xrdb -merge ~/.Xresources` accomplishes what I want (after restarting i3 with `mod+Shift+R`)

(Also, a lot of the links that are currently found when troubleshooting link to non-existent pages on regolith-linux.org. Example: [https://regolith-linux.org/internals.html](https://regolith-linux.org/internals.html))

**Comment by kgilmer** [comment]
Hi @Interesting-name :smile: 

The page you're looking for is https://github.com/regolith-linux/regolith-desktop/wiki/Customize.  If you take a look at the "Xresources Example" you'll see the general idea of how to copy the defaults for customization.

Regarding .Xresources vs .Xresources-regolith, I'm not sure why you would not get parse errors on the former and not the latter if the content is the same.  Do you recall any specifics to the error?  For reference, here is where the Xresources are loaded upon session start: https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L24-L36

Thank you for letting me know about the broken links.  We recently have been moving most of the web content to the wiki to make it easier for others to contribute, but we missed some things!

Let me know if it's not clear how to update the datetime format after reading the Customization page and I can provide further details.

**Comment by kgilmer** [comment]
@Interesting-name I looked on the Troubleshooting wiki page and didn't find any broken links or even a link to Internals.  Can you tell me where you are seeing broken links?

**Comment by Interesting-name** [comment]
> The page you're looking for is https://github.com/regolith-linux/regolith-desktop/wiki/Customize.

Ah perfect! Thanks a lot! Not sure why I didn't see the part about Xresources this in the first place.

> Regarding .Xresources vs .Xresources-regolith, I'm not sure why you would not get parse errors on the former and not the latter if the content is the same. Do you recall any specifics to the error? For reference, here is where the Xresources are loaded upon session start: https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L24-L36

This is crazy! I actually tried both `~/.Xresources` and `~/.Xresources-regolith` at some point (both containing only the line `i3xrocks.date.format: + %Y-%m-%d %H:%M`). The error only occurred when `~/.Xresources-regolith` was present.

But the date/time format does not change on startup for `~/.Xresources` either. It does work (for any file containing the line) when manually running `xrdb -merge /path/to/file`. But this is not persistent obviously.

 I'll go ahead and try to reproduce the error. For now, I looked at my recent searches and one contained something that might have been the full error, or at least very close to it:
"Error: Could not parse JSON (lexical error: invalid char in json text.)"
I'll get back to you about this. (Should I open a new issue or maybe rename this one?)

> Let me know if it's not clear how to update the datetime format after reading the Customization page and I can provide further details.

Will do!

> Can you tell me where you are seeing broken links?

I didn't word that well, sorry. I think the problem is that when googling e.g. "regolith xresources config" the first result is a broken link. Then the next results are links to issues on github but not to the wiki. Maybe the old pages could link the new versions in the wiki? That might be less frustrating for newbies like me when trying to find solutions.

Thanks again, this was really helpful!

**Comment by Interesting-name** [comment]
@kgilmer The error message was indeed "Error: Could not parse JSON (lexical error: invalid char in json text.)".
It only occurs when the file `~/.Xresources-regolith` is present and contains the line above (although I did not test other contents).

**Comment by Interesting-name** [comment]
@kgilmer The error message was indeed "Error: Could not parse JSON (lexical error: invalid char in json text.)".
It only occurs when the file `~/.Xresources-regolith` is present.

I followed the instructions in the customization wiki, but unfortunately still the same error message pops up. Here's what I did:

1. Copy the defualt Xresources config file to `~/.Xresources-regolith`
2. Copy the file `/etc/regolith/styles/i3xrocks` into the dircetory `~/.Xresources.d`
3. Change the line `#include "/etc/regolith/styles/i3xrocks"` to `#include "~/.Xresources.d/i3xrocks"`
4. Log out and in again.

In code (I changed the line in vim and logged out and in again afterwards):
```
$ cp /etc/regolith/styles/root ~/.Xresources-regolith
$ mkdir ~/.Xresources.d
$ cp /etc/regolith/styles/i3xrocks ~/.Xresources.d
vim .Xresources.d/i3xrocks
```

**Comment by Interesting-name** [comment]
Hey @kgilmer, I think I found out why Xresources and Xresources-regolith don't behave the same.

Trying to understand what happens in the [code you linked](https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L24-L36), I noticed that .Xresources is loaded before the check for the old file's md5sum.
Then, we have `if [ -f "$USER_XRESOURCE_FILE" -a "$HASH" != "$BAD_XRES_HASH" ];`. Now this is always false if .Xresources-regolith does not exist. Then the default file is always loaded, overriding the stuff set in the regular .Xresources file.

So i tried with both .Xresources and .Xresources-regolith. I copied the default config into .Xresources and left .Xresources-regolith empty. WIth this, I get the same error as above.

Could this be `xrdb -merge` behaving differently than expected?

Well, I hope this helps!

**Comment by kgilmer** [comment]
Thank you @Interesting-name for the detailed steps you took and the outcomes, it's really helpful as without it I wouldn't really understand what is wrong.  You've uncovered an undocumented assumption in Regolith: that `~/.Xresources-regolith` will always be a modified copy of `/etc/regolith/styles/root`.

> Thus, I created the file ~/.Xresources-regolith and entered the following line, modeled after the syntax in /etc/regolith/styles/i3rocks: i3xrocks.date.format: + %Y-%m-%d %H:%M

In this case you just set a specific value and so all the definitions in `/etc/regolith/styles/root` are not defined, leading to your JSON parse error.  

Once I figure out where, I'll update the documentation to make this apparent to users.  But in general the rule is, `~/.Xresources` for your own Xresource values, and `~/.Xresources-root` for your customized Regolith defines.

Let me know if you're still having problems or you've gotten yourself fixed up, and thanks again!

**Comment by Interesting-name** [comment]
@kgilmer 

> You've uncovered an undocumented assumption in Regolith: that `~/.Xresources-regolith` will always be a modified copy of `/etc/regolith/styles/root`.

Ah, that makes sense. Though it seems kind of counter-intuitive for starters.

Wouldn't it be more convenient to _always_ load the standard configuration in `/etc/regolith/styles/root` before loading `~/.Xresources-regolith`?

> Once I figure out where, I'll update the documentation to make this apparent to users. 

Perfect!

> But in general the rule is, `~/.Xresources` for your own Xresource values, and `~/.Xresources-root` for your customized Regolith defines.

Yeah, this also makes sense _if you know it_. The weird part here is that if _only_ `~/.Xresources` exists and you do _not_ have `~/.Xresources-regolith`, settings from `~/.Xresources` might be overridden by loading `/etc/regolith/styles/root`. This should not happen in my opinion, since as a user you expect your dotfiles to just apply whatever you put in them.
 
> Let me know if you're still having problems or you've gotten yourself fixed up, and thanks again! Also, if you would like a Regolith laptop sticker, I'll mail you one if you send me a mailing address to kgilmer at gmail.com.

It all works now, thanks for the help and patience! I'd love a sticker, but I'm not sure if it's worth the effort of shipping to Europe. I'll shoot you a mail anyway and you can decide depending on the cost; please don't spend some ridiculous amount on postage! ;-)
