### ISSUE TITLE
i3bar Error: status command not found or is missing a library dependency 

### ISSUE THREAD

**Issue by gi4c0** [regolith-linux/regolith-desktop#167]
After updating regolith packages and rebooting I started seeing the red error in i3bar with message: `Error: status command not found or is missing a library dependency (exit 127)`.
After some googling found a solution with installing i3status but that didn't solve the problem. The bar works and shows workspaces and launched apps but doesn't show time/battery/etc

Update: I installed i3blocks and now the error disappeared and I have a lot of text data in i3bar like volume, memory, spap, ip, etc

**Comment by kgilmer** [comment]
Hi @gi4c0 , have you customized your i3 or Xresource settings?  Do you have files `~/.config/regolith/i3/config` or `~/.Xresources-regolith` present?

**Comment by gi4c0** [comment]
@kgilmer I don't have `~/.config/regolith/i3/config` my customized i3 config file in `.config/i3-regolith/config-4.16-1ubuntu18ppa10`. `~/.Xresources-regolith` is present and new `.Xresources-regolith-1.2.15` appeared, didn't touch both.

**Comment by kgilmer** [comment]
Have a look at this table: https://github.com/regolith-linux/regolith-desktop/wiki/Customize#config-files.  It defines where config files go based on which version of Regolith you are running.  Given what files you listed above, it looks like you customized R1.1 of Regolith.  You can either merge your changes into the new files or use the stock R1.2 configuration.  To merge, have a look at `/etc/regolith/i3/config` and `/etc/regolith/styles/root`.  You'll need to modify copies of those files in your user directory.  Or, to just start fresh, rename or delete `~/.Xresources-regolith` and log back in.

**Comment by gi4c0** [comment]
Thanks a lot. The issue was in the outdated config i3 config file which was referring to i3blocks instead of i3xrocks. For the future: where can I see braking changes before/after new release?

**Comment by kgilmer** [comment]
@gi4c0 nice, glad you got it figured out.  Regarding breaking changes, they will be announced on the mailing list, along with package updates: https://www.freelists.org/list/regolith-linux
