### ISSUE TITLE
Delete key not working in terminal

### ISSUE THREAD

**Issue by skurty** [regolith-linux/regolith-desktop#168]
I installed Regolith on an Ubuntu 18.04 and the delete key is not working in the terminal. It's well working in other applications but not in this one.

**Comment by TTBeNnI** [comment]
Does the backspace key work in bash or another shell?
For me it only did not work in st (simple terminal) the default.

If you want to switch it, you could follow https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Change-the-default-terminal-from-st-to-gnome-terminal

**Comment by kgilmer** [comment]
In addition to @TTBeNnI 's good question, any suggestions on how this issue can be reproduced?  What type of keyboard are you using?  Any specific region or locale settings?

**Comment by bnsv** [comment]
I am experiencing the same problem. my delete button won’t work in terminal, so currently I use backspace to erase. My machine is kubuntu 18.04 LTS, and installing regolith via ppa.

**Comment by Filip-K** [comment]
Same here with Ubuntu 19.10 on ThinkPad T480s, Regolith installed via PPA. The problem seems to occur in st only. Any way we can help?

**Comment by kgilmer** [comment]
Need to find a way to root-cause the issue.  If anyone is able/willing to compile[ st from source](https://st.suckless.org/), that would be a good way to see if it's related to any patches in the Regolith variant...

**Comment by kgilmer** [comment]
I have not seen the issue, and I use US keyboard and US locale settings in Ubuntu.  If those experiencing the issue have another keyboard layout or locale setting that may also be an issue...

**Comment by Filip-K** [comment]
I just noticed that the [st FAQ](https://git.suckless.org/st/file/FAQ.html) has a question called "Why doesn't the Del key work in some programs?". Both solutions cited there work for me, but I still find it strange that for some people it works out of the box. I use a mix of `en_US.UTF-8` and `en_GB.UTF-8` locale settings, and a US keyboard with a US layout.

**Comment by kgilmer** [comment]
Nice find @Filip-K !  @bnsv, @skurty , does this also resolve the issue for you?  

https://git.suckless.org/st/file/FAQ.html#l25

**Comment by kgilmer** [comment]
FWIW I tried various changes to "Region and Language" in the gnome-control-center trying to reproduce the issue but was unable to find a combination that would reproduce it.

**Comment by ScreamingHawk** [comment]
I have this issue as well. `gnome-terminal` didn't have the issue so switching to that was the quickest solution.

**Comment by Filip-K** [comment]
Just to wrap it up a bit. I think this is not an issue with Regolith, but a *feature* of st, as described in [their FAQ](https://git.suckless.org/st/file/FAQ.html#l25). If you want to stick with st, the cleanest persistent solution might be to `cp /etc/inputrc ~/.inputrc` and uncomment `set enable-keypad on` there.

**Comment by ScreamingHawk** [comment]
@Filip-K This did indeed fix the issue for me. Thank you!! :heart:

**Comment by bnsv** [comment]
Yes right, it turns our not a Regolith issue. I switched to Konsole (KDE’s terminal) and the delete key is just work. Thank you for point it out.

**Comment by kgilmer** [comment]
I have added @Filip-K 's fix to the [wiki's Troubleshooting page](https://github.com/regolith-linux/regolith-desktop/wiki/Troubleshooting#st-delete).  Thanks again @Filip-K !  Closing issue.

**Comment by omarsamad-plutoflume** [comment]
+1

this is still an issue, delete key does not work in bash for ragolith-termianl, entering vim within ragolith-terminal delete works as expected, its only on the bash prompt.

FYI, delete key works for gnome-terminal as expected.
