### ISSUE TITLE
Add 中文 translation to site

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#17]
I've created stub pages for Chinese versions of the Regolith site.  The pages are in the /cn directory.  Because of some complexity around github pages and jekyll plugins I oped to keep it simple and simply use links and page language as ways of determining current language and navigation.

To add Chinese translations, just check out https://github.com/regolith-linux/regolith-linux.github.io, see the markdown files in the /cn directory and add the text.  When creating links, they must be prefixed with the language code, like this case in which the prefix is `cn`:
```
[入门]({% link cn/getting_started.md %})
```

**Comment by kgilmer** [comment]
Once translations are available I'll add a header or footer w/ a link to the root index of that translation, ex: `[中文]({% link cn/index.md %}`

**Comment by MinjunYu** [comment]
Should this issue under regolith-linux/regolith-linux.github.io instead of regolith-linux/regolith-desktop
? The change is made to the former repo, that's why I am wondering.

**Comment by kgilmer** [comment]
I've been using this repo as a general place for all Regolith issues but yeah that would be cleaner. Either way is fine w me.
