### ISSUE TITLE
The following errors were detected when starting rofi

### ISSUE THREAD

**Issue by Matoo125** [regolith-linux/regolith-desktop#170]
Failed to open theme /home/matej/regolith-theme.rasi
Error: No such file or directory

I cannot open app launcher (win+space) after update. I know there are similar issues here, but I couldn't fix it by following the advice. 

I don't even have a file ~/.Xresources.d/rofi

after removing .Xresources.d my terminal became unstyled, but it didn't help with the problem.

**Comment by kgilmer** [comment]
Hi @Matoo125 , you can get back to defaults by moving or removing:
~/.Xresources-regolith
~/.config/regolith/i3/config

After moving/removing these files, log back in and the default system should be working.

Regarding customizations, if you have something specific in mind it may be better to ask in the Slack channel.

**Comment by kgilmer** [comment]
Any update on the issue @Matoo125 ?

**Comment by Matoo125** [comment]
I tried it and it didn't work.
and I had config in ` ~/.config/i3-regolith/config`

**Comment by kgilmer** [comment]
@Matoo125 are your packages up to date?  `sudo apt update && sudo apt upgrade`.  The current version of Regolith no longer reads from the `~/.config/i3-regolith/config` file unless you change the init script to do so...

**Comment by kgilmer** [comment]
Closing due to lack of response.

**Comment by daviddahl** [comment]
> Hi @Matoo125 , you can get back to defaults by moving or removing:
> ~/.Xresources-regolith
> ~/.config/regolith/i3/config
> 
> After moving/removing these files, log back in and the default system should be working.

FWIW, These instructions worked for me when updating regolith to the latest release.
