### ISSUE TITLE
Start from Command Line?

### ISSUE THREAD

**Issue by Alterae** [regolith-linux/regolith-desktop#171]
Is there a way to manually start regolith from the command line?

**Comment by kgilmer** [comment]
Hi @Alterae, I have not tried that but it must be possible. Regolith is i3 and gnome-flashback.  Starting i3 from the command line should be straight forward. Gnome may be more work. Have a look at this: https://askubuntu.com/questions/30483/how-do-i-start-ubuntu-classic-desktop-no-effects-from-the-command-line

FYI here is where the session initialize logic lives: https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L93

I would be interested to know if you get it working!

**Comment by kgilmer** [comment]
Closing due to lack of response.
