### ISSUE TITLE
how to get dropbox working?

### ISSUE THREAD

**Issue by cmorgan** [regolith-linux/regolith-desktop#174]
this:
exec --no-startup-id /usr/bin/dropbox start -i  
doesn't seem to be working
am i missing something?

**Comment by ploum** [comment]
For me, Dropbox is working great (but I simply followed the instructions to install it under Ubuntu, nothing extravagant).

Firstly, check that you have the tray icon enabled ( https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Enable-an-Icon-Tray-in-the-Bar ). It is well possible that Dropbox requires the tray icon.

Anyway, I think that this is not a regolith issue so the ticket can be closed. Feel free to ask for support in the Slack channel.

(I took the liberty to close tickets which are note related to development but are mostly help and support. If the policy is to keep them open and use tickets for support, feel free to correct me)

**Comment by cmorgan** [comment]
just for completeness it was working great but the icon was not present. Thanks for closing
