### ISSUE TITLE
Consider disabling avahi by default

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#176]
Avoids an annoying and persistent notification, detailed here: https://askubuntu.com/questions/339702/network-service-discovery-disabled-what-does-this-mean-for-me

Unsure if this will cause regressions for users.

**Comment by nickgrim** [comment]
I'm a user that uses Avahi, and I'd rather it wasn't disabled by default. Reading that ticket, it looks like the OP's problem is that they're using a `.local` domain for their machine, which clashes the domain that Avahi uses for autodiscovery.

I think a better solution is to either _not_ configure your machine to use that domain, or get Avahi to use a different domain (which will probably require you to reconfigure all of your _other_ devices that use it, thus kinda missing the point of "autodiscovery")

I don't know what it is in your machine's configuration that's causing Avahi to show you that error, but here's a guess at a brief checklist:
 * Ensure that `/etc/hostname` / `hostname -f` don't return something ending in `.local`
 * Ensure that any `127.0.0.1` record in `/etc/hosts` doesn't return something ending in `.local`
 * …check your DHCP config isn't generating you a name ending in `.local` ?

**Comment by kgilmer** [comment]
Thanks for the feedback @nickgrim! Based on user feedback will not be making this change.
