### ISSUE TITLE
Where to change the i3-frame font?

### ISSUE THREAD

**Issue by DerpGusta** [regolith-linux/regolith-desktop#177]
How do I change the font for i3-frame? 
![image](https://user-images.githubusercontent.com/40120124/70504188-31c96200-1b4b-11ea-8316-a53ca62b9a15.png)

Should I add a line to the i3 config or is there a line in the Xresources file?

**Comment by kgilmer** [comment]
Great question @DerpGusta , it never occurred to me to set it as I never use these i3 layout modes.  As it stands there is no specific Xresources definition for an i3 font.  I was able to set this easily enough by adding the following line to my i3 config file:

```
font pango:Source Code Pro Medium 13
```

![image](https://user-images.githubusercontent.com/49683/70542255-4989f180-1b1d-11ea-9725-3f85d30b1659.png)

**Comment by DerpGusta** [comment]
Thank you for the quick fix!
