### ISSUE TITLE
Unable to reinstall regolith-desktop on Ubuntu 18.04

### ISSUE THREAD

**Issue by TickingFeather** [regolith-linux/regolith-desktop#178]
After a few weeks of testing i3wm, a friend told me about Regolith and I decided to give it a try, but (unfortunately) I forgot to remove my stock i3 first. On the first login everything worked fine, except for the i3 config which didn't seem to take effect. After a reboot, I wasn't able to login on regolith (sent back to login screen every time) and had to fall back to my previous DE (Budgie).
- I tried an `apt remove regolith-desktop` and `apt autoremove` for the dependencies, reinstalled, didn't work better. 
- Removed everything again with `apt purge`, manually deleted every file or dir named "regolith" or "i3" and reinstalled. Now when I log into regolith, only stock i3 is present, with the i3status bar showing an error message. 

Interesting point : all folders in `/etc/regolith` are empty (compton, conky, i3, i3xrocks, rofi and styles), and `~/.config/regolith` only contains `flags`, `i3` and `i3xrocks` . I understand that as missing config for some of regolith components, but I don't know how I can fix this (since fully reinstalling the packages doesn't help).
My last option is a complete distro reinstall, but I won't be trying that anytime soon considering the time it takes to backup and restore everything.

Apart from this specific issue though, this DE really got me hyped, keep up the good work!

**Comment by arendina** [comment]
You could try to run apt-get with --reinstall option, so:

sudo apt-get install --reinstall regolith-desktop

in this way you should have /etc/regolith filled with packaged files

**Comment by kgilmer** [comment]
Hi @TickingFeather , yes @arendina is right in that should restore the Regolith config files staged in `/etc/regolith`.  I suggest the following to get a "vanilla" Regolith R1.3 install on an existing Ubuntu 18.04 system:

1. `sudo apt remove regolith-destkop regolith st`
2. `sudo apt autoremove`
3. `apt policy | grep regolith` and if you have anything other than `regolith-stable`, remove it with `sudo add-apt-repository --remove <PPA URI>`
4. `rm -Rf ~/.config/regolith && rm -Rf ~/.Xresources-regolith`
5. `sudo apt install --reinstall regolith-desktop`
6. Reboot (GDM3 is finicky without a restart)
7. Select Regolith session upon login

If you still have issues please let me know, and thanks for the kind words about the project!  :smile:

**Comment by TickingFeather** [comment]
Alright, the `--reinstall` alone wasn't enough, but the steps you suggested @kgilmer worked! (I also removed all regolith PPAs as an extra precaution, then added back regolith-stable only)
I'm currently logged in Regolith and everything seems fine, I'll try a few i3 config changes and report if new problems appear. 
Thanks for the support!
