### ISSUE TITLE
i3 child_border colours not set?

### ISSUE THREAD

**Issue by jsy1001** [regolith-linux/regolith-desktop#182]
Thank you for your work on Regolith.

I'm finding it hard to distinguish between the focused, focused_inactive and unfocused window states from the window borders, as they are all similar shades of grey.

I looked at the default i3 Xresources in /etc/regolith/styles/i3-wm and noticed that the i3-wm.client.*.child_border colours are not set. Also the lines in /etc/regolith/i3/config that import these colours don't have a fallback colour at the end of the line. This suggests to me that omitting the child_border colours might have been deliberate, but I can't think of a reason why. I also don't understand where the grey border colours that I'm seeing come from.

I have tried staging my own copy of the i3 configuration and setting fallback colours for child_border. The fallback colours are then used. Another thing I've tried is making a customised copy of the i3 Xresource file, but I haven't managed to get this working yet.

Could you help please?

**Comment by kgilmer** [comment]
Hi @jsy1001 , the existing documentation is pretty vague, sorry about that.  I've updated the [page which describes how to stage user versions of files](https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Stage-your-own-version-of-Regolith-configuration-files) and created [a new HOWTO](https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Add-more-focused-window-border-contrast) to specify a new border color as you intend.  Please let me know if this clears things up! :smile:

**Comment by jsy1001** [comment]
Hi @kgilmer , many thanks for the quick response. I will have another attempt at customising my configuration.

Is it deliberate that the child_border colours are not set in the default regolith configuration? This is just to satisfy my curiosity.

**Comment by kgilmer** [comment]
Yep, it was intentional.  It is a style choice of mine.

**Comment by jsy1001** [comment]
@kgilmer , I have now succeeded in customising the window border colours. It turns out that I had mistyped a filename where my top-level ~/.Xresources-regolith included my copy of /etc/regolith/styles/i3-wm.

I ended up changing several of the colours. In case you are interested the result is attached: [i3-wm.txt](https://github.com/regolith-linux/regolith-desktop/files/4011121/i3-wm.txt)

Please feel free to close this issue, and many thanks for your help.

**Comment by kgilmer** [comment]
Glad to hear it @jsy1001 . Do you have a screenshot? You can just paste it into here...

**Comment by jsy1001** [comment]
Sure @kgilmer , here you go:
![image](https://user-images.githubusercontent.com/4949517/71619680-79c52d00-2bbd-11ea-8782-de9de23c1f2d.png)

**Comment by kgilmer** [comment]
Thanks @jsy1001 !  Looks good!
