### ISSUE TITLE
Mod+L locks screen instead of 'move right' after update

### ISSUE THREAD

**Issue by kbknapp** [regolith-linux/regolith-desktop#184]
I did a fresh install of the R1.2 ISO and did only this:

* installed updates
* install ubtuntu-session
* restart into ubuntu session and do update-manager (to 19.10)
* restart into Ubuntu session and re-add ppa regolith-stable
* update
* restart into regolith 

Now `$Mod+l` (lower case L) locks the screen.

**Comment by kbknapp** [comment]
Also I did this whole procedure twice just to ensure I wasnt going crazy.

`$Mod+l` works correctly all the way up until after the final restart into regolith

**Comment by kgilmer** [comment]
Perhaps a gnome keybinding setting is stealing it?  <Super>-c , Devices -> Keyboard will get you to all of the gnome keybindings.

**Comment by kbknapp** [comment]
That's definitely the issue. I found it under `dconf-editor` as the X11-screensaver keybinding. However after disabling that I'm left with `$Mod+l` simply inputting `l` anywhere text input is allowed.

I'm more curious how to keep this from happening or what caused it to happen in the first place.

**Comment by kgilmer** [comment]
I cannot say what package is responsible for changing the keybindings unfortunately.  I'm guessing something in GNOME but it's just a guess.  There is [some code](https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L74-L75) in Regolith that resets some keybindings on first session login.  This script will only run once, unless you delete the flags in `~/.config/regolith/flags`.

**Comment by kbknapp** [comment]
Ok cool, thanks. After removing the screen-saver keybinding and rebooting everything works as it should. So it's not a major issue, more of a papercut because whatever (non-Regolith) package is overriding the keybindings. You can close this issue if you'd like :smile:
