### ISSUE TITLE
Migrate landing page and wiki to new Hugo site hosted on github

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#185]
There are a few different wiki pages (customize, various HowTos) that overlap regarding how and what to modify when customizing Regolith.  After the R1.3 release, these pages should be cleaned up for consistency, accuracy, and conciseness.

**Comment by kgilmer** [comment]
@leosunmo suggested a static site generator that checks off all of the boxes:
* image control (drop shadows for bling)
* i18n support
* ability to segment content by a version

The github wiki is very simple, and does not support easy i18n support.  Additionally, metrics are limited.  Hugo appears to integrate well with github allowing users to easily create PRs to add/modify content.

**Comment by thomaslawton91** [comment]
Is this something that needs help or has work begun on this already? I may be able to contribute to helping with this in some of my weekend time.

**Comment by kgilmer** [comment]
Thanks for the offer @thomaslawton91 !  Well I'm still figuring out the details.  The main idea is to use Hugo instead of Jekyle and move some of the documentation back from the wiki so it can be more structured for new users to get at.  I'll update the ticket if something actionable emerges.  Also, feel free to join us on #regolith-dev on the slack channel if you like.

**Comment by kgilmer** [comment]
This was completed with the 1.3 release.
