### ISSUE TITLE
Resize tiles vertically

### ISSUE THREAD

**Issue by gustavoip** [regolith-linux/regolith-desktop#186]
Is there a way to resize tiles vertically?

**Comment by kgilmer** [comment]
Resize mode will let you adjust the size of a tile in relation to those around it in either horizontal or vertical dimensions.  If you wish to make a window smaller than the height of the screen, you can use floating mode which by default is <Super><Shift>F.

**Comment by gustavoip** [comment]
thanks! and split vertically like i3wm?

**Comment by gustavoip** [comment]
thanks
