### ISSUE TITLE
i3 title_fomat does not show formatted text

### ISSUE THREAD

**Issue by Sokushinbutsu** [regolith-linux/regolith-desktop#188]
I have enabled the title bar for only firefox using `for_window [class="(?i)firefox"] border normal`.
When trying to set the font using `title_fomat` the \<span/> tags show up instead of the correctly formatted text. I'm making this issue here because I tried the exact example from the i3 docs and it didn't work.
Here is the example I used: 
`for_window [class="(?i)firefox"] title_format "<span foreground='red'>%title</span>"`

You can find my complete i3 config file [here](https://github.com/Sokushinbutsu/dotfiles/blob/master/.config/regolith/i3/config).

**Comment by Sokushinbutsu** [comment]
If anyone is wondering how to do this:
<pre><code>for_window [class="(?i)firefox"] border normal   
font pango:Source Code Pro Medium 10</code></pre>

Still not sure why the spans tags show up, but this seems to work with the default regolith config because the bottom bar font is explicitly set using `set_from_resource`

**Comment by kgilmer** [comment]
Thanks for posting the fix @Sokushinbutsu , and sorry I didn't have any suggestions for you.
