### ISSUE TITLE
Visual studio code flicker when in full screen mode on HDPI display

### ISSUE THREAD

**Issue by mislavzlatar** [regolith-linux/regolith-desktop#190]
Hello, 

If I put VS Code in full screen mode with MOD+F it flickers when I hover over files. It works ok if not in full screen mode and it works ok in Ubuntu without Regolith.

I cant capture flicker in screen record but it looks like that gray flash at the begining of attached gif and it flashes on each hover over files in file explorer side window.

PC: Dell XPS 13 9360 i7 7500U
Display: 3200x1800
OS: Ubuntu 19.10 

Thanks,

Mislav

![Peek 2020-01-03 18-20](https://user-images.githubusercontent.com/5214324/71738135-0c7ff900-2e56-11ea-97c7-f4523dae8a8a.gif)

**Comment by kgilmer** [comment]
Hi @mislavzlatar , I have this issue too.  It is related to the compositor [compton (AKA picom)](https://github.com/yshui/picom).  If I kill compton, I do not see the issue.  If I use another compositor such as xcompmgr, I do not see the issue.  You may want to create an issue with picom, or try building latest to see if that resolves the issue. From reading the release notes, I don't see anything that's changed that would fix this issue but you never know for certain.

Regolith 1.3 will include a feature called pluggable compositors which will make it easy to swap out various compositor backends and configurations.  Until that's available (as a quick fix) I suggest you comment out the exec line in your i3 config file that loads compton, and log back in.

**Comment by mislavzlatar** [comment]
Hi @kgilmer ,

Thanks for sharing that tip. It works if I comment out compton, but on desktop and control center mouse cursor is scaled down and on VSCode, Firefox scale cursor is ok. And bottom regolith bar is also scaled down.

Is there any workaround?

Thanks,

Mislav

**Comment by kgilmer** [comment]
Hi @mislavzlatar , setting your DPI via Xresources has resolved this for others in in the past.  Have a look at https://computingforgeeks.com/how-to-set-correct-screen-dpi-in-linux-xresources/.

**Comment by mislavzlatar** [comment]
Thank you very much @kgilmer !
It's ok now,

Mislav

**Comment by mislavzlatar** [comment]
Hey @kgilmer,
 
I have installed Regolith 1.3, could you provide some tips or example how to switch to something that works on HDPI like you said xcompmgr?

Thanks,

Mislav

**Comment by mislavzlatar** [comment]
Hey @kgilmer ,
Nvm last question, setting unredir-if-possible to false inside /etc/regolith/compton/config fixed my issue with VSCode flicker.

Thanks,

Mislav

**Comment by kgilmer** [comment]
Indeed it does fix the issue!  I will update the config, thanks for letting me know @mislavzlatar :smile:

**Comment by mislavzlatar** [comment]
Glad I could help :)
