### ISSUE TITLE
Spaceship Zsh Broken 

### ISSUE THREAD

**Issue by abeljim** [regolith-linux/regolith-desktop#192]
Spaceship theme for zsh is broken by regolith. Working properly until regolith is installed. Tested on Ubuntu 19.10. Constant Error: "awk: line 1: syntax error at or near ,". Installed via oh my zsh. Any ideas why?

**Comment by kgilmer** [comment]
Hmm, I have not heard of this before @abeljim . When you say "constant error" can you be more specific? Did you remove `/bin/bash`? Any idea which script is generating that error?

**Comment by abeljim** [comment]
Anytime something is ran in the shell it first outputs the error. Seems to affect both gnome terminal and st. I did not remove /bin/bash.  I think i might be related to prompt. I tried this on a fresh system as well same problem. I installed Ubuntu 19.10. Uninstall regolith returns to normal behavior. Does regolith modify the prompt in any way?

**Comment by kgilmer** [comment]
No, in fact Regolith does not modify any files in your user directory outside of ~/.config/regolith, and those files are simply state flags.

**Comment by kgilmer** [comment]
>I tried this on a fresh system as well same problem. 

Perhaps you have a system environment variable with a textual value that isn't being properly escaped in your shell init script?  Unicode hostname or something?  If you run the init script in the shell, do you also get the error? (ex: `$ source ~/.profile` or whatever your init script is called)  If you add `set -x` at the top you'll be able to debug what line is producing the error.

**Comment by regnerisch** [comment]
I force the exact same problem (popOS! 19.10, zsh + spaceship theme)! After installing regolith `awk: line 1: syntax error at or near ,` appears on each new terminal and after each command.

**Comment by abeljim** [comment]
Good find. Temp fix is to comment out battery in the prompt order in .oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh

**Comment by regnerisch** [comment]
Spaceship-Contributors fixed the bug, so this can be closed i think.

**Comment by kgilmer** [comment]
Thank you for updating the issue @regnerisch :smile: , closing.
