### ISSUE TITLE
gnome-screenshot not working

### ISSUE THREAD

**Issue by justinmoon** [regolith-linux/regolith-desktop#195]
`shift-printscreen` produces a different screenshot than what I select with the selector tool.

For example, here I was trying to capture a screenshot of a youtube video. I selected the frame of the player with the selection tool. Below is the screenshot produced by gnome-desktop -- not the frame of the YouTube video:

![image](https://user-images.githubusercontent.com/4335621/72210375-01455280-3480-11ea-9fd6-20055eefd7c9.png)

**Comment by kgilmer** [comment]
Hi @justinmoon .  The screenshot functionality is provided by `gnome-flashback` and it looks like an issue related to this may have been recently addressed.  Can you have a look at the [upstream ticket](https://gitlab.gnome.org/GNOME/gnome-flashback/issues/26) and compare your version of flashback with the fix version?

**Comment by kgilmer** [comment]
Closing due to lack of response from issue creator.  Feel free to reopen if more info becomes available.
