### ISSUE TITLE
i3xrocks time format

### ISSUE THREAD

**Issue by WuerfelDev** [regolith-linux/regolith-desktop#196]
So it seems like the time format is hardcoded and doesn't adapt to the settings made on install or in `gnome-control-center`

https://github.com/regolith-linux/regolith-i3xrocks-config/blob/master/scripts/time#L2
https://github.com/regolith-linux/regolith-styles/blob/master/Xresources/i3xrocks#L8

**Comment by kgilmer** [comment]
Hi @WuerfelDev .  In the upcoming release, some of the GNOME time preferences will be reflected in the bar.  You've got the right files.  If you update the value of `i3xrocks.date.format` and reload i3 you will find the date format is updated.  See here about Xresource customization, and you can sanity check what the time format is set to on the commandline with `xrescat i3xrocks.date.format`.

**Comment by kgilmer** [comment]
This should be fixed in 1.3.1.
