### ISSUE TITLE
Integrate gtk3-nocsd

### ISSUE THREAD

**Issue by drewofdoom** [regolith-linux/regolith-desktop#197]
gtk3-nocsd implements an LD_PRELOAD hack to remove the CSD in GTK3+ applications. This makes all GTK3+ applications look significantly better in I3 (and hence, in Regolith as well!). Creating an easy way to implement this hack in Regolith would be extremely beneficial to users who are interested in having their GTK3 applications blend seamlessly with i3.

There is a package for gtk3-nocsd in the Ubuntu archives, but it does not work very well, and seems to be well--bugged. It points to the wrong library location in the integrated X11 detection scripts (`/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0` is the correct location, but it points to `/usr/lib/gtk3-nocsd/gtk3-nocsd.so` instead), generating a plethora of error messages unless you create a symlink to the correct file.

It also does not actually work, as the detection mechanism looks to see if you are running GNOME, and disables the override if you are. Since we are technically running a GNOME session, I believe this is causing it to turn itself off. While you can flip some toggles in the X11 scripts, I found that this still did not cause the CSDs to be disabled.

All of those issues aside, the LD_PRELOAD injection does actually work if you set it manually in your terminal and run the GTK3+ application from there. Similarly, prepending `gtk3-nocsd` to Exec lines in local .desktop overrides causes applications to load with the hack when launching from Rofi, but opening applications via Nautilus results in the local override version to be ignored.

**Comment by drewofdoom** [comment]
Did some testing, and I was able to get it working correctly!

The only modification to the package that's required is to remove or modify the check in `/etc/X11/Xsession.d/51gtk3-nocsd-detect`.

It would be better to modify the check to ignore Gnome-Flashback, or adjust the check to see if Regolith is running on top of Flashback before disabling the hack.

FWIW, this is currently working for me to work around the check and _always_ disable CSD:

```# This file is sourced by Xsession(5), not executed.

# Check if /usr/bin/gtk3-nocsd is executable, to make sure that the
# case where gtk3-nocsd is removed but not yet purged is also
# handled properly.
# if [ -x /usr/bin/gtk3-nocsd ] && ( [ -z "$GTK3_NOCSD_IGNORE" ] || [ x"$GTK3_NOCSD_IGNORE"x = x"0"x ] ) ; then
#     case "$XDG_CURRENT_DESKTOP" in
#       *GNOME*|*Gnome*)
#           # This is GNOME, make sure GTK_CSD is not set to 0
#           if [ x"$GTK_CSD"x = x"0"x ] ; then
#               unset GTK_CSD
#           fi
#           ;;
#       *)
#           # not GNOME, and the user didn't specify GTK_CSD
#           # themselves, so set it to 0
#           if [ -z "$GTK_CSD" ] ; then
#               GTK_CSD=0
#           fi
#           export GTK_CSD
#           if [ x"$GTK_CSD"x = x"0"x ] ; then
#               export LD_PRELOAD="libgtk3-nocsd.so.0${LD_PRELOAD:+:$LD_PRELOAD}"
#           fi
#           ;;
#     esac
# fi

if [ -z "$GTK_CSD" ] ; then
    GTK_CSD=0
fi
export GTK_CSD
if [ x"$GTK_CSD"x = x"0"x ] ; then
    export LD_PRELOAD="libgtk3-nocsd.so.0${LD_PRELOAD:+:$LD_PRELOAD}"
fi```

**Comment by kgilmer** [comment]
Thanks @drewofdoom , I'll take a look!

**Comment by kgilmer** [comment]
@drewofdoom , I believe this can be achieved without the gtk3-nocsd package, by just changing some settings, as described here: https://github.com/regolith-linux/regolith-desktop/issues/305

Here is a screenshot of my control panel after making the last change in the above issue.  Can you let me know if this satisfies the issue or there is more to the story?

![image](https://user-images.githubusercontent.com/49683/78516968-57b8e900-7770-11ea-84f6-e1cd0ba6423f.png)

![image](https://user-images.githubusercontent.com/49683/78516999-715a3080-7770-11ea-91b3-2655c82ad30a.png)
