### ISSUE TITLE
Issue with keyboard shortcut to launch Simplenote

### ISSUE THREAD

**Issue by MechJM** [regolith-linux/regolith-desktop#198]
I'm trying to create a keyboard shortcut to launch Simplenote but I get an error whenever I try to use it. According to the simplenote.desktop file, the command to launch Simplenote is "/opt/Simplenote/simplenote" %U so in my i3 config file I created a line that looks like this: bindsym [keybinding] exec "/opt/Simplenote/simplenote" %U. After saving and reloading everything is fine but when I use the shortcut I get an error message that looks like this:
![Captura de ecrã de 2020-01-27 15-15-12](https://user-images.githubusercontent.com/56487084/73186588-e7f70400-4117-11ea-84c4-56d893b44fa3.png)
After clicking "show errors" I get this:
![Captura de ecrã de 2020-01-27 15-15-32](https://user-images.githubusercontent.com/56487084/73186676-0bba4a00-4118-11ea-9b10-2f2e4ceea6d2.png)
Despite all this, the app still launches normally. What can I do to solve this?

**Comment by kgilmer** [comment]
Hi @MechJM :smile: ... looks like i3 doesn't like the `%U` at the end of the line.  Can you try without it?  Generally, once you have some way to launch a program from the terminal you can use the same syntax in the i3 config file.  More here: https://i3wm.org/docs/userguide.html#exec

**Comment by MechJM** [comment]
That solved it! Thanks @kgilmer !
