### ISSUE TITLE
Compatibility with systems utilizing i3, general install hiccups

### ISSUE THREAD

**Issue by grahamPegNetwork** [regolith-linux/regolith-desktop#2]
I have used i3 for roughly one year and was excited to see this project. (Side note: I experimented with various gnome3 + i3 [and gave up]options for most of the features you are providing, so great work!)
When I attempted to install from the PPA (Ubuntu 18.04) I ran into issues relating to attempting to overwrite a file contained in another package (see similar issue: https://askubuntu.com/questions/176121/dpkg-error-trying-to-overwrite-file-which-is-also-in) and ultimately it failed.

I was able to finally resolve everything by:
1. Fully removing Regolith
2. Rebooting, logging into a non-i3 window manager
3. Fully removing i3 and all related packages
4. (Did I restart again?) Reinstalling Regolith without errors
5. Rebooting and logging back in

This process took 30-45 minutes rather than the anticipated 5-10 to install Regolith.

Related note: When I first attempted to log in I just got a blank/busy screen for a minute or two, then crashed back to the login screen. Logging in a second time was successful, however this was somewhat concerning.

Another usability issue I ran into was the lack of a first run wizard. As a Dvorak user, I am familiar with i3's setup wizard which not only generates the standard config file under .config/i3/config but also accounts for the user's keyboard layout. I was able to copy enough from my old config file to make Regolith functional, but I spent a good 30+ minutes tweaking things to get it working again.

Overall once I got through some of the issues outlined above it feels fairly good. I think the missing applet area ( #1 ) is the only major issue I have which makes Regolith feel less complete than i3. I was expecting a drop in replacement/supplement and was a bit disappointed, however it is definitely functional enough to be a daily use replacement for i3 after ~2 hours of tinkering. 

Keep up the good work and I'll provide more feedback if anything arises.

**Comment by kgilmer** [comment]
Thanks for the detailed information regarding your issues with Regolith @grahamPegNetwork , I appreciate the time you spent to put it together.

Yes the packages will not install if you already have any of the UI components such as i3, rofi, or gnome-flashback already installed.  I'll update the site for links on troubleshooting these issues.

Regarding the first time wizard, yes that doesn't come up because when the Regolith session is being initialized for the first time, a stock configuration is copied into the user's ~/.config directory and i3 will only launch the wizard if no configuration is available.  My thinking there was that the wizard is ... not the greatest UI and having that be the first thing a new user sees would be kind of a sad first impression.  I did not consider your use case though in which you need to specify a custom keyboard layout.  I will have to think about the best way of solving this issue, it's not clear to me at the moment.

**Comment by kgilmer** [comment]
Also @grahamPegNetwork , if you would be open to trying gnome-settings for BT and wifi management rather than the applets, I would really value your opinion.

**Comment by grahamPegNetwork** [comment]
Agreed on the i3 wizard not being the best UI. I'm not sure if there is a clean way of handling it, but watching for the keyboard layout and letting the user choose which meta key is used are probably the only major things the wizard provides to my recollection. (I think it prompts for Home or Alt)

Currently using gnome-settings for configuration. It's not my ideal setup (per comments in #1) but does the job. In the past when I was just starting with i3 and hadn't found the applets I did something similar, but had to manually create wifi networks to connect to after scanning them on my phone. It was far from ideal, and using gnome-settings is 10x better, so I can work with that. 

Most of the time I'm connected to the same networks, so I don't need to change often. Bluetooth may be more used when connecting to my headset/choosing audio sources, but I'll give it a shot and see how things go.

**Comment by kgilmer** [comment]
Thanks for the followup.  I hope gnome-settings grows on you, but would also like to hear if you continue to prefer panel apps.  Closing this issue in favor of #3 and #16.  Please re-open if I've missed something contained in this issue.

**Comment by grahamPegNetwork** [comment]
Hey a notification, well I might as well mention that I have been using Regolith daily and fairly easily adjusted to using gnome-settings. There are occasionally cases where I could see a panel being helpful, such as when doing some new bluetooth device management, but no trouble working with it. I do appreciate that ...I think it's Rofi...the launcher keeps settings at the top, that makes it rather convenient to hit Home+Space, Enter and have access to various settings. And yes, as I think you mentioned in the other issue, the flow has grown on me. Glad to see you are still working on things!

**Comment by kgilmer** [comment]
Very much appreciate the update Graham!  If you've updated the packages recently you'll also have keybindings that load specific gnome-settings panels directly.  For example Super-b will launch Bluetooth settings without even having to go to Rofi.

**Comment by muniter** [comment]
I like to have gnome-settings for changing wifi, audio, and bluetooth. But it's also a little impractical sometimes when you just want to change the network. I think having the applets, and the bindings would be the better choice. But I think the bindings for volume, power, Bluetooth are too wasted in the sense that they should be inside a mode. So when in the future adding more functionality we have simple easy to reach keybindings available.

**Comment by kgilmer** [comment]
Thanks for your feedback @muniter .  I will add a howto section on enabling the applet tray and adding wifi and bluetooth applets for users that prefer that style of configuration.  If enough people feel strongly about the tray configuration, I may look into it again.  Early proto-Regolith has the applets but I was unable to consistently theme them and the UIs across applets had enough variance and inconsistency that I chose to rely on gnome-control-center.
