### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by dustinromey** [regolith-linux/regolith-desktop#20]
Just wanted to write and give some kudos for the project, and an Issue seemed as good as any way.

Reading the Motivations discussion, I arrived to similar conclusions about the Macintosh direction, and it also carried me to linux. I went through some work setting up both Debian and Ubuntu with i3 and found myself slowly finding my way to my preferences, but with plenty of tweaking along the way, which wasn't really the goal.  I just wanted a system that would work well, easily, and be easily configurable, with some good defaults as a starting point.

That's exactly what you've created. And with some better defaults than I used, as after spending just an hour or two installing and configuring Regolilth on my desktop machine, I have all the software I need installed, and it functions pretty close to how I'd like (having been able to import my i3 config tweaks easily), and it uses about 1/6th of the memory at idle. 

Next up, my laptop.

If I find bugs, I'll report them. If I have suggestions, I'll put in a real issues. But I haven't seen much yet.

So Thanks.  Feel free to close the issue, or to leave open for others to heap on more praise. But do so knowing you made my day better and improved my computing experience.

**Comment by kgilmer** [comment]
It's incredibly wonderful to get your feedback @dustinromey !  I'll keep the issue open and keep the feedback coming :).  Also, if you have any specific tweaks you think would be useful to others please share those as well.

I am using Regolith at home and work.  I have 3 monitors connected to a laptop at work and have issues w/ my windows being re-arranged after sleep/resume cycles.  I'm working on a variation on i3-save-tree that I hope will allow me to quickly save and restore the window arrangements as a bandaid to this issue.

Other things I'm thinking of changing is adding a control center panel for common i3 settings (change the meta key, specify the bar should be hidden, etc.) as well as a custom bar that is only a few pixels deep but still lets the user know which workspace they are on.  I'm also considering writing a page on the site for people unfamiliar w/ tiling window managers, kind of like an introduction and tutorial wrapped into one. 

Anyway, thanks again for your kind words!

**Comment by dustinromey** [comment]
I have a desktop with 2 monitors, and I noticed on restarts that the left monitor sometimes is number 1 and sometimes number 2. Which I'm assuming is the same issue you identified. I've read a couple of posts on 13-save-tree, but haven't played with it. But sounds like the right thing to work out.

Your other ideas sound like good ones. My input would be that I expect what's useful for people who would be interested in regolith (or at least useful for me), would be help on how to make repeatable, maintainable tweaks to the system. 

For example, I made two tweaks to i3blocks to add a memory % and an power control to the bar. And I moved i3bar to the top. Then I made a couple of small changes to the bindings in ~/.config/i3/config, which I had previously worked out before using regolith.

You seem versed in not only making these changes, but doing them in the "right" place in the system to keep them clean, clear, and maintainable. So I would think it would be very useful to have things like:
  - An already setup way to track dotfiles upon install (though it seems you went with a ppa instead, which is fine)
  - Documentation on how to set up your own fork and/or ppa to maintain your tweaks
  - Documentation on where to do the tweaks (for example, I wasn't familiar with i3blocks as I had used polybar before, so I had to hunt for where to make changes to its config. In the end I went with ~/.config/i3blocks/config, as within home seems more logical than touching the /etc/i3blocks.conf in case you rollout changes there later)

You already have some of that documentation on the site. So I expect I'm just confirming your plans.

I'm working on installing on my laptop. If/when I run into anything else, I'll communicate it.

**Comment by kgilmer** [comment]
Very helpful feedback, thanks!  Yes it's a design goal of Regolith to make it for anyone to essentially do the same thing I've done here ~ package up configuration into an Ubuntu PPA.  There is some work that remains in terms of documentation to get that design goal realized.  Knowing what people find useful helps me prioritize work, so knowing this will push this doc work up on the list.

**Comment by muniter** [comment]
Indeed a great project! I've been using i3 for something like 3 years now, and I love it. But I'm also a little lazy when It comes to eye candy! I usually keep it simple, since I don't want to have to reconfigure when I re-image my system. Having Regolith is great, since I just can add the ppa, and get a pretty much configure system, my bindings are quite different and I prefer them, but having a nice looking system right away is very very nice!!!! Hope the project thrives, I'll try to help when possible!

**Comment by kgilmer** [comment]
Thank you @muniter for the kind words, and also for providing valuable feedback and help on the issues!  Your help is be much appreciated! :+1:

**Comment by MDutro** [comment]
@kgilmer - Thank you for Regolith! This is just the sort of thing I have been looking for, since I'm not a fan of Arch and the prospect of setting everything up from scratch myself is a bit daunting.

I have only one question - how do I change the colors/theme? I find the dark solarized theme to be rough on my eyes (I need a little more contrast between background and text).

Thanks again!

**Comment by kgilmer** [comment]
Glad that you're enjoying Regolith @MDutro .  You can install GNOME Tweaks from the Software app.  This will let you select alternate GTK themes.  The terminal colors are unfortunately hardcoded at the moment but work is being done to make them themeable as well.  In the mean time, you could use a different terminal such as GNOME terminal which is installed by default.  The news page will be updated when themeing and changing colors becomes easier.

**Comment by MDutro** [comment]
GNOME Tweaks! I feel a bit stupid... Whenever I use i3 I tend to forget that some of the more traditional desktop applications still exist/work for some reason.

Thanks - that is very helpful.

Will updates come through the usual "sudo apt upgrade"?

**Comment by im7FFY** [comment]
gj for the recent implementation of background managed by gnome and better applets integration (icons fits better)

**Comment by bketelsen** [comment]
Adding my thanks here too, really enjoying the thought and care you put into this pseudo-distro @kgilmer

**Comment by kgilmer** [comment]
Thanks for the kind words everyone!  It's a real boost to hear it!

**Comment by b-connect** [comment]
Love it !!!
Exactly fit my needs.

**Comment by aacebedo** [comment]
Wanted to thank you too. 
You're doing an amazing work. The integration of i3 with gnome is really great !

**Comment by kgilmer** [comment]
Very nice to hear all the kind words.  Closing now though to get the issue count down!
