### ISSUE TITLE
Manually starting regolith desktop

### ISSUE THREAD

**Issue by sirredbeard** [regolith-linux/regolith-desktop#200]
How do I start the Regolith desktop manually, like you would with gnome-session, startkde, startxfce4, or i3 for plain i3?

I am asking because when using the Ubuntu images with enhanced session in Hyper-V you login over Xrdp and bypass gdm3, kdm, lightdm, etc.

You have to then have to configure xrdp in /etc/xrdp/startwm.sh or manually override your Xsession to load the alternate DE by calling startkde, etc.

I tried i3 but got a plain i3 setup and then tried i3-gnome-flashback-session and got the same.

Any suggestions?

![Annotation 2020-01-30 175313](https://user-images.githubusercontent.com/33820650/73498476-6a3b2e80-438b-11ea-9c5c-1f04f7e7cd15.png)

**Comment by sirredbeard** [comment]
![Annotation 2020-01-30 180808](https://user-images.githubusercontent.com/33820650/73498513-88089380-438b-11ea-9c93-670119ae491c.png)

**Comment by kgilmer** [comment]
Hi @sirredbeard !  I was able to directly load i3 using `xinit` on an old macbook a few weeks back:

https://faq.i3wm.org/question/6126/how-do-i-start-i3/index.html

Does this work for you?

**Comment by kgilmer** [comment]
Kindly reopen if the issue persists.

**Comment by sirredbeard** [comment]
So the real question here is, how do you start regolith desktop over xrdp?

xrdp bypasses gdm3, lightdm, etc.

xrdp will load the default desktop environment, which GNOME in most cases.

It will run /etc/xrdp/startwm.sh which runs your Xsession file.

Even after you install regolith-desktop and xrdp into a box you will just go back to GNOME.

With other desktop environments I have overridden this behavior by editing /etc/xrdp/startwsm.sh to run startkde or mate-session instead of Xsession.

I have tried:

i3-gnome-flashback-session (nothing happens)
i3 (runs a default i3 session from scratch)

**Comment by sr9992** [comment]
I just placed
```
i3-gnome-flashback
```
into ~/.xsession, and it works for me.  I left all the other files in their default states.  I get Regolith when I RDP in from a Windows laptop.

**Comment by paranoidminotaur** [comment]
> I just placed
> 
> ```
> i3-gnome-flashback
> ```
> 
> into ~/.xsession, and it works for me. I left all the other files in their default states. I get Regolith when I RDP in from a Windows laptop.

I could hug you

**Comment by dowcet** [comment]
> 
> 
> > I just placed
> > ```
> > i3-gnome-flashback
> > ```
> > 
> > 
> > into ~/.xsession, and it works for me. I left all the other files in their default states. I get Regolith when I RDP in from a Windows laptop.
> 
> I could hug you

This has been working great for me over the last few months but suddenly stopped after an update. Now when I log in, the RDP client just closes immediately after authenticating. I notice that .xsession-error mentions "i3-gnome-flashback: command not found". Did it go away or change name?

**Comment by sr9992** [comment]
> > > I just placed
> > > ```
> > > i3-gnome-flashback
> > > ```
> > > 
> > > 
> > > into ~/.xsession, and it works for me. I left all the other files in their default states. I get Regolith when I RDP in from a Windows laptop.
> > 
> > 
> > I could hug you
> 
> This has been working great for me over the last few months but suddenly stopped after an update. Now when I log in, the RDP client just closes immediately after authenticating. I notice that .xsession-error mentions "i3-gnome-flashback: command not found". Did it go away or change name?

This changed in Regolith 1.5. I believe you should use `regolith-session` now.

**Comment by dowcet** [comment]
> This changed in Regolith 1.5. I believe you should use `regolith-session` now.

Thanks, tried this and while I know longer get the line about i3-gnome-flashback, I still can't connect. :( Here's what ~/.xsession-errors looks like now.

`Xsession: X session started for dowcet at Tue 17 Nov 2020 06:58:40 AM EST
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:10.0
localuser:dowcet being added to access control list
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting USER=dowcet
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting HOME=/home/dowcet
dbus-update-activation-environment: setting XRDP_PULSE_SINK_SOCKET=xrdp_chansrv_audio_out_socket_10
dbus-update-activation-environment: setting XRDP_PULSE_SOURCE_SOCKET=xrdp_chansrv_audio_in_socket_10
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting LOGNAME=dowcet
dbus-update-activation-environment: setting XDG_SESSION_CLASS=user
dbus-update-activation-environment: setting PATH=/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
dbus-update-activation-environment: setting XRDP_SOCKET_PATH=/run/xrdp/sockdir
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting DISPLAY=:10.0
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting UID=1000
dbus-update-activation-environment: setting SHELL=/bin/bash
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XRDP_SESSION=1
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting PWD=/home/dowcet
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
X connection to :10.0 broken (explicit kill or server shutdown).`

**Comment by kgilmer** [comment]
Hmm, in the short term you could use the Regolith 1.4 PPA to continue to use what you had working before: https://launchpad.net/~regolith-linux/+archive/ubuntu/regolith-1.4.1

Also, kindly open a new issue for your problem so it can be properly managed.

**Comment by joemiller** [comment]
I am trying to get regolith 2.0 on ubuntu 22.04 going over vnc (tightvncserver). I tried `regolith-session` and `regolith-session-init` in its `.vnc/xstartup` script as well as `~/.xsession` but nothing works. Any suggestions on what to try next?

**Comment by sr9992** [comment]
This may not fit your use case, but when I want to connect to an already-running instance of Regolith over VNC, I just run `x11vnc` and connect to that using whatever VNC client app I have available and it works fine.  Unfortunately, I don't have experience with starting X with tightvncserver.

**Comment by joemiller** [comment]
I am attempting to do this on a cloud vm so i don't think that's an option.
