### ISSUE TITLE
Unmet dependencies while installing a look

### ISSUE THREAD

**Issue by Philipp0205** [regolith-linux/regolith-desktop#201]
I freshly installed Rigoleth with the latest release on Ubuntu 19.10. 

Following happens when I try to install a new look 

    philipp@xps13:~$ sudo apt install regolith-look-ubuntu
    [sudo] password for philipp: XXXXXXX

    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    You might want to run 'apt --fix-broken install' to correct these.
    The following packages have unmet dependencies.
         regolith-desktop : Depends: regolith-st
         regolith-look-ubuntu : Depends: fonts-font-awesome but it is not going to be installed
    E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a 
    solution).

The recommend solution (adding --fix...) does not work. 

How do I fix this?
Thanks!

**Comment by kgilmer** [comment]
Hi @Philipp0205 , thanks for the detailed report.  Some dependencies didn't make it into the release PPA.  I will fix and let you know when it's working.

**Comment by kgilmer** [comment]
Hmm, actually `fonts-font-awesome` is supplied by Ubuntu archives.  Have you run `sudo apt update` since installation?  Can you run `sudo apt install fonts-font-awesome`?

**Comment by bchopson** [comment]
I'm getting a slightly different error but may be related, when installing a look:
```
sudo apt install regolith-look-ayu-mirage
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-look-ayu-mirage : Depends: ayu-mirage-theme but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I also noticed that `/etc/regolith/styles` only contains the `cahuella` folder. I'm on Pop OS 19.10 and on the stable PPA

**Comment by adworacz** [comment]
Same here, missing ayu dependencies:

```
 % sudo apt install regolith-look-ayu-dark regolith-look-ayu-mirage
Authenticated with cached credentials.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-look-ayu-dark : Depends: ayu-theme but it is not installable
 regolith-look-ayu-mirage : Depends: ayu-mirage-theme but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kgilmer** [comment]
Until the ayu-* packages are hosted in a Regolith PPA, you can manually install them from here: https://github.com/appelgriebsch/ayu-theme/releases

**Comment by Philipp0205** [comment]
Thank you. All fixed now!
