### ISSUE TITLE
Searching files

### ISSUE THREAD

**Issue by SRotendahl** [regolith-linux/regolith-desktop#204]
Hi,
Just installed Regolith, and it is super cool. I have not gotten into i3 due to the learning curve, but Regolith helps so much, so thank you very much.

I am wondering whether there is a search like standard Ubuntu where you search a file name, and press enter to open it in its default application? For example searching for a pdf and having it open in evince. 

I am new to this, so I apologize if the information is right in front of me, and I am just not seeing it.

**Comment by kgilmer** [comment]
No need to for apologies!  Yeah, a file search dialog has been suggested before, and we just haven't gotten around to it yet.  But let's make it happen!

**Comment by kgilmer** [comment]
Perhaps https://github.com/davatorium/rofi-scripts/tree/master/rofi-finder

**Comment by SRotendahl** [comment]
> Perhaps https://github.com/davatorium/rofi-scripts/tree/master/rofi-finder

I tried it briefly, but a friend suggested Albert, which is kinda like spotlight on Mac (The Mac version is called Alfred). It works great, and I would recommend it to anyone wanting this feature :)

https://albertlauncher.github.io/

**Comment by kgilmer** [comment]
I was not aware of Albert, looks very cool!  If you're interested in adding a howto for switching from Rofi to Albert, here is where it would go: https://github.com/regolith-linux/website/tree/master/content/en/docs/HowTo
