### ISSUE TITLE
Unable to display full workspace name in i3xrocks

### ISSUE THREAD

**Issue by djuelg** [regolith-linux/regolith-desktop#205]
Hi,
when using Regolith with i3xrocks (standard bar) I see the workspace number and a color on the left side of the bar. Can I switch this behaviour back to displaying the normal workspace name e.g. "1. Browser" instead of "1 [COLOR-SQUARE]"

I couldn't find any docs on this.

Thanks!
Dominik

**Comment by kgilmer** [comment]
Hi @djuelg , sure you can, but yeah it's not obvious how to do that.  I created a brief howto that explains the basics, but please let me know if it's unclear or you get stuck:

https://regolith-linux.org/docs/howto/remove-workspace-icons/

**Comment by djuelg** [comment]
Thanks for the quick help!

I switched it to the following, so that the names match the font on the right

`
#define WORKSPACE_NAME(NAME, FONT) <span font_desc=FONT> NAME </span>
i3-wm.workspace.01.name: WORKSPACE_NAME(1. Browser, glyph_font)
i3-wm.workspace.02 ...
`
