### ISSUE TITLE
Login screen issue

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-desktop#207]
I installed regolith 1.3 from the iso file then changed the user icon. Now in the login screen, there is this weird-looking artifact.

![IMG_0213](https://user-images.githubusercontent.com/13016644/73611194-f4aaaa80-45a4-11ea-8265-8a7e57e13403.JPG)
![IMG_0214](https://user-images.githubusercontent.com/13016644/73611195-f4aaaa80-45a4-11ea-9092-759014c6bad7.JPG)

.

**Comment by kgilmer** [comment]
Hmm, if you remove the `regolith-gdm3-theme` package and reboot, is the problem fixed?

**Comment by cheginit** [comment]
Yes, it seems that the tray icons issue is also gone. The tray icons had this background color. I guess that the transparent background of the icons couldn't be rendered correctly.

**Comment by kgilmer** [comment]
There were a lot more differences between the ubuntu css and regolith css for the theme than I remember.  I've cowardly opted to go back to the upstream version all except for the background.  Change is building (regolith-gdm3-theme_2.0.0-1ubuntu1~ppa1) into unstable now.

**Comment by cheginit** [comment]
I see. Was I the only one with this issue?

**Comment by kgilmer** [comment]
No one else reported it.

**Comment by cheginit** [comment]
That's strange.

**Comment by kgilmer** [comment]
Well it's still broken. :smile:  I'll reopen until change is promoted to `release`.

**Comment by kgilmer** [comment]
The fix is in unstable now for both eoan and bionic if you can verify it fixes you @cheginit ...

**Comment by cheginit** [comment]
Greate, it's fixed now!

**Comment by kgilmer** [comment]
Verified fix in Bionic and Eoan.  Promoting fix to all PPAs.

**Comment by kgilmer** [comment]
Fix promoted, closing.
