### ISSUE TITLE
Virtualbox full screen not working - Regolith 1.3

### ISSUE THREAD

**Issue by mislavzlatar** [regolith-linux/regolith-desktop#208]
Hello,

If I enter full screen mode in Virtualbox, I see only desktop image background.

In earlier version of Regolith 1.2, when i disable line that starts compton and then when I enter full screen, it shows only black screen.

I am on Dell XPS 13, 3200x1800 res, Ubuntu 19.10, Regolith 1.3.

Mislav

**Comment by mislavzlatar** [comment]
Update: 

It works with Regolith fullscreen(MOD+F) but not with VirtualBox fullscreen(Right Ctrl + F)

**Comment by danieltomasz** [comment]
It doesnt work, after trying to run virtualbox I am getting weird behavoiur (host desktop wallpaper view instead  of full screen guest).  Maybe this is related to dual screen setup.

Also empty space in the primary screen.
![Screenshot from 2020-02-11 15-10-48](https://user-images.githubusercontent.com/7980381/74244509-d4d06080-4ce1-11ea-96f0-bad76d6b957f.png)

The virtualbox is unusable :(

**Comment by kgilmer** [comment]
Please try using `regolith-compositor-none` and let me know if the behavior changes or remains the same.  https://regolith-linux.org/docs/customize/compositors/

**Comment by kgilmer** [comment]
Closing for lack of response, kindly re-open if issue persists in Regolith 1.4.
