### ISSUE TITLE
regolith-look not found

### ISSUE THREAD

**Issue by verajosemanuel** [regolith-linux/regolith-desktop#209]
installed regolith desktop on Ubuntu Eoan no issue so far. Everything is working ok out of the box (Great Work!!) but when I tried to change theme via:

Terminal:

```
regolith-look 

command not found regolith-look
```

**Comment by kgilmer** [comment]
Hmm, do you have /usr/bin/regolith-look ?  How did you install?

**Comment by verajosemanuel** [comment]
I;ve installed adding PPA and desktop on top of my ubuntu
 /usr/bin/regolith-look  not present

**Comment by broeker** [comment]
I'm seeing the same thing on Ubuntu 18.04 installed on top of existing desktop -- command not found, no `/usr/bin/regolith-look` is not present, and I get `Unable to locate package regolith-look-ubuntu
` if I try to install a look. Otherwise, good stuff!

**Comment by kgilmer** [comment]
Thanks @verajosemanuel and @broeker .  I have found the issue.  I'm building a fix now and will let you know when it's available.

**Comment by kgilmer** [comment]
Actually after looking more closely, I'm not sure what the problem is.  Can someone provide the output of `apt list --installed | grep regolith` please?

**Comment by broeker** [comment]
`regolith-assets/bionic,now 1.09-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-compton-config/bionic,now 1.7-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-conky-config/bionic,now 2.01-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-desktop/bionic,now 2.30-1ubuntu1~ppa2 amd64 [installed]
regolith-gnome-flashback/bionic,now 1.46-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3-gaps-config/bionic,now 1.18.19-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3xrocks-config/bionic,now 1.21-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-rofi-config/bionic,now 1.2-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-st/bionic,now 0.8.2-1ubuntu20ppa4 amd64 [installed,automatic]
regolith-styles/bionic,now 1.2.36-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-xeventbind/bionic,now 1.3-1ubuntu1~ppa1 amd64 [installed,automatic]
`

**Comment by broeker** [comment]
FWIW -- prior to installing Regolith, i was running vanilla i3 and did not bother to uninstall. Not sure if that would affect things.

**Comment by verajosemanuel** [comment]
fresh clean install in my case. No previous vanilla i3
```
regolith-assets/eoan,now 1.09-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-compton-config/eoan,now 1.7-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-conky-config/eoan,now 2.01-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-desktop/eoan,now 2.30-1ubuntu1~ppa3 amd64 [installed]
regolith-gnome-flashback/eoan,now 2.1-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3-gaps-config/eoan,now 1.18.20-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3xrocks-config/eoan,now 1.21-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-rofi-config/eoan,now 1.2-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-st/eoan,now 0.8.2-1ubuntu20ppa4 amd64 [installed,automatic]
regolith-styles/eoan,now 1.2.36-1ubuntu1~ppa1 amd64 [installed,automatic]

```

**Comment by kgilmer** [comment]
Ok, it looks like both of you both have package versions of `regolith-styles` (and `regolith-desktop` and probably others) from the previous Regolith release: 1.2.  You can [see here](https://launchpad.net/~regolith-linux/+archive/ubuntu/release) that the latest version of `regolith-styles` is 2.2.14.  Check the "Upgrade from previous version" block on https://regolith-linux.org/download/ and see if `dist-upgrade` fixes you package versions.

**Comment by broeker** [comment]
Awesome @kgilmer i did not realize there was a new release -- `regolith-look` is now working and I suspect a few other things I was finding that didn't seem to work from the docs will now work also. What is the best way to get notified about new releases?

**Comment by broeker** [comment]
I just found this, so for others interested:

https://regolith-linux.org/interact/

I'll follow on Twitter -- I am super impressed with v1.3. Nice work! I had been using vanilla i3 and running into various frustrations and things I just didn't want to deal with, installed v1.2 on a whim and have not looked back. This new version is even better, seems to have fixed my screen tearing on a 34" ultrawide and just nice little touches everywhere i look. Kudos!

**Comment by cheginit** [comment]
Today, I faced this issue after running the update command and not being able to update `regolith-desktop` since `regolith-look` doesn't exist. I installed Regolith from ISO of 18.04 v1.3. I didn't have this issue yesterday it happened today. I am using the Unstable PPA.

```bash
$ apt list  | grep regolith

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

regolith-compositor-compton-glx/bionic,now 1.0.4-1ubuntu1~ppa1 amd64 [installed]
regolith-compositor-none/bionic 1.0.2-1ubuntu1~ppa1 amd64
regolith-compositor-xcompmgr/bionic 1.0.2-1ubuntu1~ppa1 amd64
regolith-desktop/bionic 2.48-1ubuntu1~ppa1 amd64 [upgradable from: 2.47-1ubuntu1~ppa1]
regolith-ftue/bionic,now 1.0.2-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-gdm3-theme/bionic,now 2.0.0-1ubuntu1~ppa1 amd64 [installed]
regolith-gnome-flashback/bionic,now 1.53-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3-gaps-config/bionic,now 2.2.8-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3xrocks-config/bionic,now 2.2.10-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3xrocks-focused-window-name/bionic 2.2.10-1ubuntu1~ppa1 amd64
regolith-look-ayu/bionic 2.2.15-1ubuntu1~ppa1 amd64
regolith-look-ayu-dark/bionic 2.2.15-1ubuntu1~ppa1 amd64
regolith-look-ayu-mirage/bionic 2.2.15-1ubuntu1~ppa1 amd64
regolith-look-cahuella/bionic,now 2.2.15-1ubuntu1~ppa1 amd64 [installed]
regolith-look-nord/bionic 2.2.15-1ubuntu1~ppa1 amd64
regolith-look-solarized-dark/bionic 2.2.15-1ubuntu1~ppa1 amd64
regolith-look-ubuntu/bionic 2.2.15-1ubuntu1~ppa1 amd64
regolith-rofication/bionic,now 1.0.8-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-st/bionic,now 0.8.2-1ubuntu20ppa5 amd64 [installed,automatic]
regolith-styles/bionic,now 2.2.15-1ubuntu1~ppa1 amd64 [installed]
```

**Comment by kgilmer** [comment]
Very strange @cheginit !  `ls /usr/bin/regolith-look` returns no file?  I would suggest purging `regolith-styles` and reinstalling.  It would be great if I could find the documentation in apt that describes when a `purge` is necessary.

**Comment by cheginit** [comment]
@kgilmer, The file exists but I think the issue is that there is no `regolith-look` package in the [PPA](https://launchpad.net/~regolith-linux/+archive/ubuntu/unstable) and it's a dependency for the `regolith-desktop` so it fails. If it's installed by `regolith-styles` or is a part of it you might want to modify the `regolith-desktop` dependencies accordingly or add `regolith-look` as a package to the PPA.

**Comment by kgilmer** [comment]
Oh I see what you mean.  I misunderstood your reference to `regolith-look` being the shell script and not the package.  I reverted my mistaken change and will push to `unstable`.  Happily the broken change didn't make it to stable, and you caught it in testing!  Process win!

**Comment by cheginit** [comment]
Great! It's fixed.
