### ISSUE TITLE
Add howto entry for people just wanting stock i3wm on Ubuntu

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#21]
For those that are interested in using i3 on Ubuntu but do not want Regolith in particular, give some quick steps and links to install stock i3 from a PPA.

**Comment by kgilmer** [comment]
Fixed: http://regolith-linux.org/howto.html

**Comment by renxida** [comment]
I was looking for a way to start a regolith-less i3 session and ended up here. Is there a way to do that? While keeping my regolith?

**Comment by kgilmer** [comment]
Yes @renxida , you can install the package `i3-gaps-session` which will provide a new session option on your login screen for vanilla i3-gaps.
