### ISSUE TITLE
regolith 1.3 makes it difficult to identify focussed window

### ISSUE THREAD

**Issue by tomster** [regolith-linux/regolith-desktop#210]
previously windows would have a title bar and its color made it easy to identify which was active.

now, with 1.3 the title bar is gone (which in itself is a welcome change because it usually doesn't contain any useful information, anyway). however, now it's very difficult to distinguish the focussed window from the other ones.

my preferred soltution which i've attempted is to simply make the height of the tile bar a few pixels larger (in my own i3 config i made the text color the same as the background color for the titlebar and set the font size for it to 6px which left me with a 8 or 10px tall bar which served no other purpose than to indicate the active window)

now that the title bar is gone this approach no longer works and so i tried to identify which part of the new theme is responsible for deactivating the titlebar but couldn't find any corresponding XResource  directive in /etc/regolith/styles.

any pointers?

**Comment by kgilmer** [comment]
Yes, it is very subtle... Perhaps it crosses the line between form and function.  There are a few ways you could make the distinction more apparent.  The setting you are look for are here: https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config#L250

But you could also increase the window border width, and play with the color of that border.

**Comment by tomster** [comment]
Thank you - the relevant setting was right in front of me all along (doh!) even with a helpful comment.
this has cleared up the issue for me entirely.
however, when looking up the setting you mention i noticed that it has been deprecated so i took the liberty of creating a pull request for updating it https://github.com/regolith-linux/regolith-i3-gaps-config/pull/8
oh and while i have your attention: thank you so much for your work on regolith. it has made my (developer) life a whole lot more enjoyable ever since i've come across it and 1.3 is a wonderful improvement.

**Comment by kgilmer** [comment]
Great to hear and thanks for the kind words @tomster :smile:

**Comment by markstos** [comment]
I just to want to agree that's near impossible to tell which window is focused. I use Regolith on a 4k screen, so a single pixel with is just a sliver.

Would I would love is if an obvious border could be highlighted the moment a window is focused. I don't think i3 supports something like that, though.

**Comment by tomster** [comment]
@markstos FWIW here's how i dealt with it:

```# Disable titlebar
default_border normal 0px
default_floating_border normal 0px

set $hide_edge_borders smart
set $default_border normal 0
# setting font tiny in conjunction with using identical background and text colors
# for window title bars (see below) effective renders discreet, but noticeable bars
# that easily convey which window is active without annoying unreadable titles
font pango:DejaVu Sans Mono 2 
# Window Border color
# class                 border                             background                         text                               indicator                          child_border
client.focused          #4C7899                            #049AFF                            #049AFF                            #2E9EF4                            #285577
client.focused_inactive $focused_inactive.color.border     $focused_inactive.color.background $focused_inactive.color.background       $focused_inactive.color.indicator  $focused_inactive.color.child_border
client.unfocused        $unfocused.color.border            $unfocused.color.background        $unfocused.color.background              $unfocused.color.indicator         $unfocused.color.child_border
client.urgent           $urgent.color.border               $urgent.color.background           $urgent.color.background                 $urgent.color.indicator            $urgent.color.child_border
```

HTH

**Comment by markstos** [comment]
@tomster That's helpful, thanks!

**Comment by hltan** [comment]
So. I'm not getting this. How do make the active border bigger? Which file should I edit? I copied the config file from /etc/regolith/i3/config to ~/.config/regolith/config and changed the default_border to 10. And nothing. I think I need to change the .xresource file but don't know how. If you can point me to the documentation I would greatly appreciate it because this is confusing me. I keep typing in the wrong window.

**Comment by kgilmer** [comment]
In Regolith 1.3.1 (current version a the time of this message), you can override the default border width by adding a line to `~/.config/regolith/Xresources`.  Here's a one liner that achieves the screenshot below for me.

```bash
echo "i3-wm.window.border.size: 10" >> ~/.config/regolith/Xresources && regolith-look refresh
```

![image](https://user-images.githubusercontent.com/49683/77811852-8ccf8800-705a-11ea-9752-5c7def2f66b7.png)
