### ISSUE TITLE
Installing regolith-desktop fixes powerline fonts

### ISSUE THREAD

**Issue by MechJM** [regolith-linux/regolith-desktop#212]
This isn't directly related to Regolith but I thought it was worth asking here since I'm having trouble figuring out what's going on. Before installing regolith-desktop, powerline fonts don't work in my terminal (Alacritty), the shell prompt shows rectangles instead of the proper powerline prompt (like [this](https://github.com/powerline/powerline/issues/1697)). I think this is related to a font issue in Alacritty but, for some reason, installing regolith-desktop fixes the prompt problem. 

Does anyone have any idea what Regolith is doing under the hood that fixes this problem? I'm trying to figure out how to solve the issue in systems where I don't use Regolith.

**Comment by cheginit** [comment]
Regolith uses a patched font that includes the powerline symbols. You can find may of the patched fonts in the [nerd-font](https://github.com/ryanoasis/nerd-fonts) repo among other places. Just go [releases](https://github.com/ryanoasis/nerd-fonts/releases) then download and install (e.g., copy them to `~/.fonts` directory) the fonts that you like. I personally use Microsoft's [Cascadia Code PL](https://github.com/microsoft/cascadia-code) as my terminal font. If you're using Alacritty you need to set the font in the config file, more details are provided in their [wiki](https://github.com/alacritty/alacritty/wiki/Changing-the-default-font).

**Comment by MechJM** [comment]
That fixed it! Thanks!
