### ISSUE TITLE
Worksapce management in multi-monitor setting

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-desktop#213]
I was wondering if it's possible to make workspace management in multi-monitor settings smarter! Personally, I create workspaces with odd numbers on the first monitor and with even numbers on the second monitor. It's more intuitive for me at least.

Is it possible to automate such numbering? For example, the number of monitors can be detected by `DISPLAY=:0 xrandr -q | grep ' connected' | wc -l` then somehow provide this numbering approach and give the user option to activate it via the config file.

**Comment by kgilmer** [comment]
I agree that the association between workspace index and monitor could be more intuitive that it is presently @cheginit .  It seems that the even/odd heuristic only works for 2 monitors though.  I think there are two related features to this that would be nice to have:
1. "create and move to next free workspace", saves the step of having to scan your active workspaces to find an empty slot.
2. "android-like back stack for workspace transitions" ~ essentially keeping a list of workspaces sorted by most recently used, and a way to navigate to "the last workspace I used" (which is implemented in i3 but I find to be confusing as it overloads existing workspace navigation semantics) or "3rd last workspace used".

I wonder if there is another heuristic other than even/odd that scales to a variable number of displays?  Perhaps something in presentation (custom i3 bar) could also be considered...

**Comment by cheginit** [comment]
I agree with your point about the odd-even limitations. How about a shortcut (like mod+alt+number) for changing the ''monitor space" without explicitly specifying the workspace just jump to the next monitor and the last active workspace. Essentially, the workspaces are be grouped into monitor spaces that also show up in the mod+ctrl+space menu like so:
Monitor 1:
    1:
    ...
Monitor 2:
     3:
    ...

**Comment by priestoferis** [comment]
> 
> 1. "create and move to next free workspace", saves the step of having to scan your active workspaces to find an empty slot.

We have this now (or we've had this for a few months now), I'm not sure about the default binding (or if indeed it is in regolith by default, I'd need to check).

It is also possible to switch between the last two active workspaces, so if those are on two different monitors that should not be an issue, and it is possible to move the workspace to another monitor (I always move them right, on two monitors that switches, on three you can quickly cycle through).

@cheginit I'm not sure what you mean by your last comment or I am maybe too tired, but could you please elaborate a bit more on this? Maybe we can come up with something.

**Comment by cheginit** [comment]
@priestoferis I meant that in addition to workspaces (ws) we can have monitorspaces (ms). This monitor space essentially "groups" the workspaces based on the monitor number. Regarding the keybinding we will have mod+$ws and mod+alt+$ms.

**Comment by priestoferis** [comment]
So if WS 10 is assigned to monitor 2, opening WS 10 will automatically place it on monitor 2? 

What would the keybind for the monitor space do? Open a new WS on it? Or switch to the last used WS on the other monitor and if you have more than two, cycle through monitors?

**Comment by cheginit** [comment]
> So if WS 10 is assigned to monitor 2, opening WS 10 will automatically place it on monitor 2?

Yes.

>What would the keybind for the monitor space do? Open a new WS on it? Or switch to the last used WS on the other monitor and if you have more than two, cycle through monitors?

The ms key will jump to the last used ws in that ms. If by cycling through you mean like mod+tab for ws we have mod+alt+tab for ms, then yes.

**Comment by priestoferis** [comment]
I think creating a proper monitor space would be a) too complicated (all kinds of new settings, naming and whatnot) b) out-of-scope for regolith (i.e. it should be implemented in i3 itself). But thinking along the lines of what we already have, we could have functionality for
- switching monitors (e.g. $mod+$alt+l could take focus to the workspace on the monitor to the right of your current one)
- switching to the last used workspace on the given monitor

Although both of these will require to run some permanent service that can remember these things and the keybinds would need to poll that. Hmm.

**Comment by cheginit** [comment]
Yeah, it makes sense. I couldn't think of a simple way either.

@kgilmer Maybe, we can close this for now since it doesn't seem to be doable.

**Comment by jensens** [comment]
I have two outputs (monitors) and dispatch my workspaces by first defining the outputs:
https://gist.github.com/jensens/eabd5416e884b43591976fca34c4e2df#file-config-L60

Assign which of my logical workspaces got to which output (including single fallback)
https://gist.github.com/jensens/eabd5416e884b43591976fca34c4e2df#file-config-L602
and then assign the programs to workspaces.

I can connect/disconnect my main screen from my notebook and it switches immediately and dispatches the workspaces as configured.

**Comment by priestoferis** [comment]
Binding `workspace next_on_output` and `workspace prev_on_output` might solve a lot of the above, no?

**Comment by priestoferis** [comment]
@cheginit @kgilmer My suggestion is to close this and if someone finds/comes up with a nice script that does some more fancy stuff, than the built-in commands we just have bound the mentioned PR, then maybe we can reopen and think about whether we want to add such services to regolith or not.

**Comment by kgilmer** [comment]
+1, thanks @priestoferis :smile:
