### ISSUE TITLE
regolith ignores focus_follows_mouse setting

### ISSUE THREAD

**Issue by ingsme** [regolith-linux/regolith-desktop#214]
I have `focus_follow_mouse yes` in my config, but this is ignored. I have also tried setting it with 
`gsettings set org.gnome.desktop.wm.preferences focus-mode 'mouse'`. I am just unable to get the focus to obey my mouse movements.

**Comment by baldrailers** [comment]
@ingsme what version are you running?

**Comment by ingsme** [comment]
I am running the latest version from the stable ppa for Ubuntu 18.04.

**Comment by baldrailers** [comment]
Just a quick check, the new version looks at the config file in `$HOME/.config/regolith/i3/config` ... I just tested this setting `focus_foolow_mouse yes` and it is working. I wonder if you are still updating the old config.

**Comment by ingsme** [comment]
No I am using the new config. However if it is working with you as intended the problem is most certainly at my end and not an error with regolith. 

Thank you for confirming that it should work.

**Comment by ingsme** [comment]
I found the culprit. It turned out that buried deep (line 357) in the config file the line `focus_follows_mouse no` was hidden away. I thought I had searched for its presence, but that was obviously only in my imagination and me trying to turn it on at the top of the config naturally did not work. Nor any other trick I tried.
