### ISSUE TITLE
Super+Shift+Enter does not launch default browser

### ISSUE THREAD

**Issue by jessegranger** [regolith-linux/regolith-desktop#215]
Press Super+c to open Control Center.  Browse to Details -> Default Applications.

Observe that "Firefox Web Browser" is selected as the default "Web" application.

Super+Shift+Enter still opens Chrome.

**Comment by kgilmer** [comment]
The browser that is launched is defined by `sensible-browser`.  I'll look into GNOME integration.

**Comment by kgilmer** [comment]
There are two overlapping systems which define a default browser:
1. gnome-settings / xdg-settings
2. update-alternatives gnome-www-browser

#1 has the UI integration with gnome settings, however doesn't seem to have an easy way of determining the actual executable to launch:
```
$ xdg-settings get default-web-browser
firefox.desktop
```
I'm guessing this is used by gnome apps to then load the desktop file and act accordingly.  It's not obvious to me how this can be implemented in i3 config without predicates or additional shell scripts.

#2 has no GUI, but is consistent with the terminal settings.  The preferred browser can just be launched via `/usr/bin/gnome-www-browser`.  

Additionally, the only reference to 'browser' from the gnome settings schema is that it has been removed in the NEWS file: https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas

Despite the lack of GUI, `update-alternatives` seems like the best use.

**Comment by kgilmer** [comment]
After a brief search it does not seem possible to disable the browser selection in `Default Applications` in gnome-control-panel.

**Comment by kgilmer** [comment]
I [found this](https://askubuntu.com/questions/5172/running-a-desktop-file-in-the-terminal) and was able to launch the gnome-settings configured browser from the command line with:
```
gtk-launch $(xdg-settings get default-web-browser)
```

**Comment by kgilmer** [comment]
The inconsistencies bother me but I now think that using the gnome variant is better for users, as it has a GUI and if it is not used, users will be confused when their setting changes have no effect.  I will move this to the GUI.

**Comment by kgilmer** [comment]
This should be fixed in 1.3.1.

**Comment by tomchuk** [comment]
I recently installed the `regolith-desktop` package from the unstable ppa into an Ubuntu 20.04 server install. It seems that as a result of this change, the `regolith-desktop` metapackage is missing a dependency on `xdg-utils`.

**Comment by HossamElwahsh** [comment]
same problem ubuntu 22.04
[regolith-diag.txt](https://github.com/regolith-linux/regolith-desktop/files/10755310/regolith-diag.txt)

**Comment by HossamElwahsh** [comment]
fixed by hardcoding firefox in `/usr/share/regolith/i3/config.d/15_base_launchers`

> ## bindsym $mod+$i3-wm.binding.browser exec --no-startup-id gtk-launch $(xdg-settings get default-web-browser)
> bindsym $mod+$i3-wm.binding.browser exec --no-startup-id /snap/bin/firefox

**Comment by steshaw** [comment]
I am having the same problem as @HossamElwahsh. I am using your provided workaround for now. Thanks.
