### ISSUE TITLE
How to set default terminal.

### ISSUE THREAD

**Issue by jessegranger** [regolith-linux/regolith-desktop#216]
In the Super+c control center for Default Application, there is no option for what Terminal to prefer.

Using `update-alternatives --set x-terminal-emulator /usr/bin/alacritty` has no effect.

Using `gsettings set org.gnome.desktop.default-applications.terminal exec alacritty` has no effect.

Super+Enter only ever launches `/usr/bin/st`.

**Comment by MechJM** [comment]
You're supposed to follow [this tutorial](https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Change-the-default-terminal-from-st-to-gnome-terminal) from the wiki.

**Comment by kgilmer** [comment]
Thanks for supplying the documentation link @MechJM .  But, this should also be fixed so that i3 config uses the appropriate extension mechanism.  I'll have to do some research about gnome vs update-alternatives for both this and the other related bug @jessegranger has opened.

**Comment by jessegranger** [comment]
Thanks for looking into it.

**Comment by kgilmer** [comment]
This should be fixed in 1.3.1.
