### ISSUE TITLE
How to switch looks in R1.3

### ISSUE THREAD

**Issue by MechJM** [regolith-linux/regolith-desktop#217]
The website says it should be easier to switch looks in this release. Can someone explain how to do this? I'm really not a fan of the new Cahuella theme.

**Comment by kgilmer** [comment]
Hi @MechJM , did you see this page?  

https://regolith-linux.org/docs/customize/look/

You can also just use gnome-tweaks to change the gtk theme if that's all you are after.

**Comment by MechJM** [comment]
Oh, I didn't see that page. I'm so used to having the information in the wiki that I didn't dig through the website. Thanks a lot!
