### ISSUE TITLE
Regolith added buttons/bar to firefox

### ISSUE THREAD

**Issue by hedich** [regolith-linux/regolith-desktop#219]
Before installing Regolith there where no buttons/bar and now after install there are added buttons and a full "bar" on Firefox and i have no ide how to remove this as i cant find any added code to my css files.

![no](https://user-images.githubusercontent.com/18218984/74066933-6432f680-49f8-11ea-8e58-ea950451b76a.png)

![no2](https://user-images.githubusercontent.com/18218984/74066941-685f1400-49f8-11ea-8ba5-c4c9591ded88.png)

[https://imgur.com/a/qlfuxGn](url)

**Comment by kgilmer** [comment]
Hi @hedich :smile: .  That's odd.  How did you install Regolith? (PPA, ISO)  If you log into the stock ubuntu session, is your Firefox restored?

Regolith doesn't have any code that modifies Firefox.  I'm guessing that you maybe have multiple versions/instances of Firefox installed and the one that Regolith launches (via /usr/bin/sensible-browser) isn't the one you normally load...

**Comment by hedich** [comment]
Hi @kgilmer thanks for the reply, i installed Regolith with ppa on Ubuntu (18.04.3 LTS) 
tried logging in to stock Ubuntu and i get the same buttons/bar as in i3-Regolith
i start Firefox with drum normally and i tried with the one from i3 config as well (sensible-browser)
as well as directly from a terminal they all start my normal Firefox that i have custom css for but with the added buttons/bar

I upgraded to the latest Regolith today (the ppa i used to install Regolith did not install the latest before) and things changed a bit

![newbuttons](https://user-images.githubusercontent.com/18218984/74087576-02bd6700-4a8e-11ea-845c-c55a51c16c10.png)

new icons for the buttons and still the same bar i am so confused as to where this comes from, nothing in my chrome folder (css files Firefox) have changed, i am a bit new to all this so i am probably missing something obvious, my guess is that Regolith installed and is applying some kind of theme on top of my Firefox? buttons changed when i did a update so it must have something to do with that right? the buttons does not even do anything except the close button.

**Comment by kgilmer** [comment]
Ah, ok I think I understand your issue.  I believe Firefox's UI is being configured from your GTK+ theme.  Regolith **does** change this when you install, as part of the session init script.  I think that if you change your GTK to something else, say with `gnome-tweaks` then you'll see Firefox being updated as well.  If you simply wish to revert ever theme change to your previous configuration, Regolith makes a backup before changing it.  The backup is the file `~/.regolith-gnome-backup`.  This script is intended for those that wish to completely uninstall Regolith so it's not advised to run it and continue to use Regolith.  Rather, apply the lines in the file relating to your theme, which should be the last 3 lines.  Mine look like this:
```
gsettings set org.gnome.desktop.interface gtk-theme 'Ambiance'
gsettings set org.gnome.desktop.wm.preferences theme 'Adwaita'
gsettings set org.gnome.desktop.interface icon-theme 'ubuntu-mono-dark'
```

If you run whatever your copy of the `.regolith-gnome-backup` file has, Firefox should revert to it's previous look.

**Comment by hedich** [comment]
Talked to a friend that had the exact same issue and he wiped Firefox clean and reinstalled it and it worked for him, i did the same and it worked. Everything is back to normal now but thanks for the info i will take notes and save it if this ever happens again. Thanks for the help!
