### ISSUE TITLE
Moved: Dialogue box for apps larger than screen

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#22]
Issue created by @anthrolisp on a [deprecated repo](https://github.com/kgilmer/Regolith-Desktop-Environment/issues/13), moving here.  Anthrolisp's issue:
```
Dialogue box for apps are larger than screen. For example, the dialogue box for Gedit when you try to "save as" goes off the screen, and cannot see the bottom of the dialogue box.
```

**Comment by kgilmer** [comment]
Hmmm, I just tried launching gedit and did not see the issue, although I did notice the dialog is quite large.  **What resolution are you running at?  Did you install Regolith from PPA or LiveCD? Anything special about your setup?**  As a possible workaround: floating windows can be moved by pressing Super and then clicking anywhere in the window and dragging it.  And windows can be resized with Super-r, using arrow keys, and then hit escape or enter.

**Comment by geajack** [comment]
I have an issue where when I save or open a file in most apps (basically anything that opens a file browser window), the Save button is offscreen. For instance this is what I get pressing Ctrl+S on this page:

![](https://i.imgur.com/v643wkW.png)

**Comment by geajack** [comment]
@kgilmer Unfortunately, resizing only seems to work horizontally, the very direction in which it doesn't need to be resized. Moving the window works as a workaround, unfortunately the application doesn't seem to remember the position or size of the dialog.

**Comment by kgilmer** [comment]
@geajack are you able to verify if this is still an issue in Regolith 1.3?

**Comment by kgilmer** [comment]
Closing due to lack of response.

**Comment by dbriemann** [comment]
I am also encountering this issue currently. Fresh install of regolith here. Resolution is 2560x1440. I have two screens with this resolution.. not sure if dual screen is an issue here. Here is a screenshot of the `save as` dialog from gedit:

![before](https://user-images.githubusercontent.com/791374/86820800-d718ca00-c089-11ea-85bf-618c03eb70b6.jpg)

I can enter the resize mode and move up the bottom. It then looks like this:

![after](https://user-images.githubusercontent.com/791374/86820845-e5ff7c80-c089-11ea-9798-fa20891c51f2.jpg)

I can however not make the top visible and also this is not saved and when I use ctrl+s in gedit the next time it is out of screen again. I have seen this issue with multiple `save as` dialogs so far.

**Comment by kgilmer** [comment]
Hmm, your issue seems a bit different than the original poster @dbriemann .  Can you kindly open a new issue?  Can you also mention if your two screens are both in landscape, and if possible what happens if you only use one monitor (to determine if it's related to multiple displays)?

**Comment by nikarul** [comment]
I appear to be having a similar issue.  Like the original poster, I have a 1280x800 desktop.
![screenshot](https://user-images.githubusercontent.com/751249/93039453-2a207780-f60d-11ea-879a-e6a7e951c81c.png)

**Comment by kgilmer** [comment]
You can resize the window via the i3 resize mode <super>r.  I'm hoping that
after you resize it the next time it comes up it will remember the size
from before.

**Comment by nikarul** [comment]
That did the trick!  And it does indeed remember its position. Thank you so much!

**Comment by big-ole-barge** [comment]
I'm having the same issue. I can resize the window and move it into a better position with the keyboard shortcuts. If it's a standardly installed package, the size of the window is remembered the next time I open the window with that application, but not the position. It's good enough for me, though. The issue comes when I use an appimage. I use the Balena Etcher appimage a lot and the pop up dialog to choose an image to flash is opened larger than the screen every time. It's not a big issue for me since I can double click on the image just fine, but I figured I'd share since this seems like a common problem.

**Comment by jakesgordon** [comment]
I have the same issue. I believe it only happens if you've used TweakUI to adjust the font scaling factor. I have mine set to 1.25 and the file open dialogs are always too large for my display, but if I change the font scaling factor back to 1.0 it works fine.

**Comment by jakesgordon** [comment]
Just to clarify my previous comment. I have `gnome-tweak-tool` installed and use it to change the font scaling factor to 1.25 and that causes the issue.
