### ISSUE TITLE
Multiple battery statuses for laptops with multiple batteries

### ISSUE THREAD

**Issue by alexj136** [regolith-linux/regolith-desktop#220]
The regolith i3bar is configured to show the status of only one battery. The status bar should either show all battery statuses, or show an aggregated percentage over all batteries (although the latter would be more difficult to implement since differences in capacity would have to be accounted for).

**Comment by baldrailers** [comment]
I think what you can do is identify the `instance` e.g. `BAT1, BAT0` then set another config in the `~/.config/regolith/i3xrocks/config` for the following:

```conf
# Battery indicator
#
# Displays total percentage charge left of specified battery.
[battery3]
interval=30
instance=BAT0

[battery3]
interval=30
instance=BAT1
```

**Comment by kgilmer** [comment]
@alexj136 did @baldrailers 's suggestion work for you?

**Comment by alexj136** [comment]
Yes thanks @kgilmer @baldrailers, it worked well. Perhaps worth a (mention in a) wiki page?

**Comment by kgilmer** [comment]
Fixed, thanks @baldrailers !  https://regolith-linux.org/docs/howto/multiple-batteries/
