### ISSUE TITLE
On wake up from sleep, lock screen isn't immediately shown

### ISSUE THREAD

**Issue by CJMaughon** [regolith-linux/regolith-desktop#221]
After I put my computer to sleep, and then go to wake it up, it will flash the desktop really quickly, and then go blank. I'll hit enter again and I go to the lock screen. Any idea why this is happening?

**Comment by kgilmer** [comment]
Hi @CJMaughon, yes, from what I have read I believe there is a race between the X server, gnome-flashback and/or gnome-screensaver.  See https://github.com/regolith-linux/regolith-desktop/issues/132 for details.  I suggest opening a ticket upstream in gnome-flashback.

**Comment by CJMaughon** [comment]
That's what I figured it was. Will open a ticket. Thanks!
