### ISSUE TITLE
Unable to change workspace names

### ISSUE THREAD

**Issue by MechJM** [regolith-linux/regolith-desktop#223]
I tried to change the names of some workspaces by performing these changes:
![Captura de ecrã de 2020-02-10 23-35-58](https://user-images.githubusercontent.com/56487084/74200620-5c28c000-4c5f-11ea-97d3-ec20d7165c0f.png)

However, even after performing a reboot, it's not working:
![Captura de ecrã de 2020-02-10 23-36-18](https://user-images.githubusercontent.com/56487084/74200668-76629e00-4c5f-11ea-8fc9-29470b7b4f8d.png)

Can someone help me with this?

**Comment by kgilmer** [comment]
Hi @MechJM , you're almost there.  the `set_from_resource` command in i3 tries to read a value from Xresources, and if nothing is found falls back to the default.  So in this case you only changed the fallback value.  To quickly get what you want, make the lines look like this:
```
set $ws9 "Messaging"
```

A cleaner way would be to update the Xresrouce values in `/etc/regolith/styles/i3-wm` but it's a little complex in there so I suggest just experimenting in your i3 file for now.

**Comment by MechJM** [comment]
Don't I just have to edit the first parameter in WORKSPACE_NAME?
![Captura de ecrã de 2020-02-11 12-21-18](https://user-images.githubusercontent.com/56487084/74236736-c70ee100-4cc9-11ea-970d-1c7413ebabfd.png)

**Comment by kgilmer** [comment]
I believe that will work @MechJM if you wish to keep the 'color box' to the right of the title.

**Comment by MechJM** [comment]
OK thanks!
