### ISSUE TITLE
i3blocks nettraffic script should not display negative values for bandwidth

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#229]
User reported in slack that during dock hotplug events, intermittent negative bandwidth values are displayed.  Perhaps some network metrics evaporate faster than others in this scenario resulting in nonsensical values.

acceptance criteria: if the `nettraffic` script calculates a negative bandwidth value, it should not display anything.

**Comment by kgilmer** [comment]
The code lives here: https://github.com/regolith-linux/regolith-i3xrocks-config/blob/master/scripts/nettraffic

**Comment by cheginit** [comment]
Solved by [this](https://github.com/regolith-linux/regolith-i3xrocks-config/commit/33de43cd1b3e13b5153f6908d7640c3145c92ddc#diff-0eebc2b5e52d4b338a2003604de0f616) commit.
