### ISSUE TITLE
Login on wake happening twice after uninstalling regolith desktop

### ISSUE THREAD

**Issue by danieljhill** [regolith-linux/regolith-desktop#230]
So, I tried the Regolith desktop. I'm on Ubuntu Mate 19.10. 

I installed the DE following the instructions [here](https://github.com/regolith-linux/regolith-desktop/wiki/Install-Regolith) via Option 2.

After deciding it wasn't for me I followed the uninstallation instructions further down the same page.

All is well. However, now when opening my laptop from suspend I put my password in to login via the usual Mate greeter/screen. It will then go to desktop for about a second before sending up a second login prompt, this time via the greeter/screen that Regolith used. Has the uninstallation missed some config file somewhere? Is there an easy fix for this?

**Comment by kgilmer** [comment]
Hi @danieljhill , very odd.  Did you reboot after uninstalling Regolith?  What does `apt list --installed | grep -i regolith` say?  What about `apt list --installed | grep -i gnome`?

**Comment by danieljhill** [comment]
Bizarrely the first command comes back with nothing. The second command comes back with 

`gnome-control-center-data/eoan,eoan,now 1:3.34.1-1ubuntu2 all [installed,automatic]
gnome-control-center-faces/eoan,eoan,now 1:3.34.1-1ubuntu2 all [installed,automatic]
gnome-control-center/eoan,now 1:3.34.1-1ubuntu2 amd64 [installed,automatic]
gnome-desktop3-data/eoan-updates,eoan-updates,now 3.34.2-2ubuntu1~19.10.1 all [installed,automatic]
gnome-disk-utility/eoan,now 3.34.0-2ubuntu1 amd64 [installed,automatic]
gnome-icon-theme/eoan,eoan,now 3.12.0-3 all [installed,automatic]
gnome-keyring-pkcs11/eoan,now 3.34.0-1ubuntu1 amd64 [installed,automatic]
gnome-keyring/eoan,now 3.34.0-1ubuntu1 amd64 [installed,automatic]
gnome-menus/eoan,now 3.32.0-1ubuntu1 amd64 [installed,automatic]
gnome-mpv/eoan,now 0.16-1ubuntu1 amd64 [installed,automatic]
gnome-online-accounts/eoan,now 3.34.0-1ubuntu1 amd64 [installed,automatic]
gnome-power-manager/eoan,now 3.32.0-1 amd64 [installed,automatic]
gnome-screensaver/eoan,now 3.6.1-8ubuntu3.2 amd64 [installed,automatic]
gnome-session-bin/eoan,now 3.34.1-1ubuntu2 amd64 [installed,automatic]
gnome-session-canberra/eoan,now 0.30-7ubuntu1 amd64 [installed,automatic]
gnome-session-common/eoan,eoan,now 3.34.1-1ubuntu2 all [installed,automatic]
gnome-settings-daemon-common/eoan,eoan,now 3.34.1-1ubuntu1 all [installed,automatic]
gnome-settings-daemon/eoan,now 3.34.1-1ubuntu1 amd64 [installed,automatic]
gnome-software-common/eoan-updates,eoan-updates,now 3.30.6-2ubuntu10.19.10.0 all [installed,automatic]
gnome-software/eoan-updates,now 3.30.6-2ubuntu10.19.10.0 amd64 [installed]
gnome-startup-applications/eoan,now 3.34.1-1ubuntu2 amd64 [installed,automatic]
gnome-system-tools/eoan,now 3.0.0-8ubuntu1 amd64 [installed,automatic]
gnome-user-docs/eoan,eoan,now 3.34.0-2ubuntu1 all [installed,automatic]
language-pack-gnome-en-base/eoan,eoan,now 1:19.10+20191010 all [installed]
language-pack-gnome-en/eoan,eoan,now 1:19.10+20191010 all [installed]
language-selector-gnome/eoan,eoan,now 0.198 all [installed,automatic]
libgnome-autoar-0-0/eoan,now 0.2.3-2 amd64 [installed,automatic]
libgnome-autoar-gtk-0-0/eoan,now 0.2.3-2 amd64 [installed,automatic]
libgnome-bluetooth13/eoan,now 3.34.0-1 amd64 [installed,automatic]
libgnome-desktop-3-18/eoan-updates,now 3.34.2-2ubuntu1~19.10.1 amd64 [installed,automatic]
libgnome-menu-3-0/eoan,now 3.32.0-1ubuntu1 amd64 [installed,automatic]
libgnomekbd-common/eoan,eoan,now 3.26.1-1 all [installed,automatic]
libgnomekbd8/eoan,now 3.26.1-1 amd64 [installed,automatic]
libpam-gnome-keyring/eoan,now 3.34.0-1ubuntu1 amd64 [installed,automatic]
libreoffice-gnome/eoan-updates,now 1:6.3.4-0ubuntu0.19.10.1 amd64 [installed,automatic]
libsoup-gnome2.4-1/eoan,now 2.68.2-0ubuntu1 amd64 [installed,automatic]
network-manager-gnome/eoan,now 1.8.22-2ubuntu1 amd64 [installed,automatic]
network-manager-openvpn-gnome/eoan,now 1.8.10-1 amd64 [installed,automatic]
network-manager-pptp-gnome/eoan,now 1.2.8-2 amd64 [installed,automatic]
pinentry-gnome3/eoan,now 1.1.0-3 amd64 [installed,automatic]`

**Comment by kgilmer** [comment]
I'm not sure what could be going on @danieljhill but if Regolith session stuff is somehow still on your system, it uses gnome-screensaver to lock the screen.  You may try `sudo apt remove gnome-screensaver` and look at the packages it will remove if you uninstall the package.  If that package list looks ok to you, try uninstalling gnome-screensaver, `sudo apt autoremove` and reboot.

**Comment by danieljhill** [comment]
@kgilmer That seems to have solved it! Bizarre. I'm not sure why it didn't get picked up by the initial uninstall procedure.
