### ISSUE TITLE
config files missing

### ISSUE THREAD

**Issue by shashank-k** [regolith-linux/regolith-desktop#232]
After restarting system, the config files seems to be not found in `~/.config/regolith/`

There is only one `flags` dir in the above mentioned path.

**Comment by kgilmer** [comment]
Hi @shashank-k , can you be more specific about your problem?  Also, see here for specifics about config files in Regolith 1.3: https://regolith-linux.org/docs/reference/configurations/

**Comment by shashank-k** [comment]
My bad, my hangover from my earlier i3 configuration still exists :(
Closing this now.
