### ISSUE TITLE
[enhancement] different icon when battery is charging & adapter plugged 

### ISSUE THREAD

**Issue by danieltomasz** [regolith-linux/regolith-desktop#235]
Would be useful if the icon used for battery  indicator would be different, when the computer is charging when Ac adapter is plugged

**Comment by kgilmer** [comment]
I believe the existing icons represent this state.  Please let me know if I'm missing something.

Charging:
![image](https://user-images.githubusercontent.com/49683/75359577-72429d00-5869-11ea-9360-398213875e6d.png)

Discharging:
![image](https://user-images.githubusercontent.com/49683/75359709-9d2cf100-5869-11ea-933a-a4ff00bddd97.png)

**Comment by aadilayub** [comment]
@kgilmer I don't think this is a very discoverable implementation. Until now, I had no idea those arrows represented charging status until now. I'd guess that @danieltomasz was under this impression as well, which is why he filed this issue.
