### ISSUE TITLE
Volume block and mute

### ISSUE THREAD

**Issue by gnzlbg** [regolith-linux/regolith-desktop#244]
The volume block just shows "S" when the output is muted (as opposed to "S X%"). 

It would be nicer to use a speaker icon for the volume, and to change that to use the "Speaker with cancelation" (unicode) icon when the volume gets muted.

**Comment by moritzheiber** [comment]
@gnzlbg To me this looks fixed in the latest release. Can you confirm?

**Comment by moritzheiber** [comment]
I'm closing this for now. Please open a new issue for it and reference this one if it's still an issue :slightly_smiling_face:
