### ISSUE TITLE
Volume unmute and volume scroll not working for me

### ISSUE THREAD

**Issue by gnzlbg** [regolith-linux/regolith-desktop#245]
In the bar volume control, I can use the right click to mute the sound. However:

* right click to unmute alter the display of the sound level in the bar, but does not unmute the sound - I need to manually press the FN+VolUP key to unmute.

* when the sound is unmuted, I can scroll up and down, and this raises and lowers the sound level percentage, but the sound does not change.

**Comment by kgilmer** [comment]
I typically use the media keys on the keyboard and the OSD provided by `gnome-flashback` for sound. (FYI)

**Comment by kgilmer** [comment]
This issue is being worked on in this PR: https://github.com/regolith-linux/regolith-i3xrocks-config/pull/28

**Comment by kgilmer** [comment]
This should be fixed in Regolith 1.4.1.
