### ISSUE TITLE
Font Problem in windows search (super + ctrl + space)

### ISSUE THREAD

**Issue by benabhi** [regolith-linux/regolith-desktop#246]
For some reason the characters are not recognized in the names of the list displayed in the window search.

Here I leave a screenshot of the problem in a system that I have mounted in virtualbox.

![SharedScreenshot](https://user-images.githubusercontent.com/1945599/74619546-b4a30600-5114-11ea-9909-dc796e437e51.jpg)

I installed the operating system multiple times and the error persists.

**Comment by kgilmer** [comment]
Hi @benabhi , I also have a similar issue.  It's seems to be due to misconfigured font encoding within Rofi.

**Comment by cnasc** [comment]
![2020-02-22-120207_2560x1600_scrot](https://user-images.githubusercontent.com/9300702/75096250-bf71f680-556b-11ea-932d-1f80d0a12089.png)

I've encountered the same issue. Installed this morning from the 19.10-based image with all updates applied. About to dive into the docs to see if I can resolve

**Comment by kgilmer** [comment]
Related: https://github.com/davatorium/rofi/issues/69

**Comment by kgilmer** [comment]
Related: https://developer.gnome.org/pygtk/stable/class-pangofontdescription.html

**Comment by kgilmer** [comment]
Was unable to get Rofi to deal correctly with multiple fonts in the window dialog, so fell back to trying to specify a subset of info that would not include the Pango markup that we load into workspace title, however was unable to get that working either so filed a bug against Rofi: 

https://github.com/davatorium/rofi/issues/1062

**Comment by kgilmer** [comment]
This should be fixed in 1.3.1.
