### ISSUE TITLE
Merge i3xrocks changes upstream?

### ISSUE THREAD

**Issue by naclander** [regolith-linux/regolith-desktop#248]
Thanks for curating these different resources and getting i3 to integrate so well with various gnome features.

While I was exploring trying to package regolith for Arch, I noticed i3xrocks is forked from i3blocks so that 

> config file can resolve Xresource dependencies if prefixed with xresource:

Is it possible to try and merge this change upstream to i3blocks? I think it should make packaging for various other distros easier, as it can depend on packages already in the offical repos, instead of custom ones. For example for Arch Linux, I think I would have to now package i3xrocks to its own package, and then package the regolith configs into their own package.

EDIT: 

Same question for [regolith-rofication](https://github.com/regolith-linux/regolith-rofication)

**Comment by kgilmer** [comment]
Hi @naclander! Regolith on Arch sounds great!

> Is it possible to try and merge this change upstream to i3blocks? 
Yes, initially i3xrocks [started as a PR](https://github.com/vivien/i3blocks/pull/385#issuecomment-518369669) against i3blocks. They did not feel an additional dependency was worth the additional value.  Entirely understandable.
 
I agree that it adds additional packaging burden, and if there are ways to rectify that I'm happy to move in that direction.  The goal of the variation is to concentrate all UI configuration to Xresource settings.  If there is another way of doing that without regressing the user experience, I would be open to changing.

Regarding Rofication, it needs to extract some hard coded things like help, and keybindings to some configuration that I can set from Regolith.  I've made some other changes as well.

Out of curiosity, what about Arch packaging differs from Debian other than, say the meta package format?  Is there anything in particular w/ Regolith packages that is troublesome?

**Comment by naclander** [comment]
I am by no means an Arch Linux packaging expert, so my understanding my not be 100% complete.

It's definitely possible to create Arch packages for all Regolith package forks ( rofication, i3xrocks, etc. ). Then create a ( meta ) package that depends on all of those, which would pull those all in during install. 

My understanding is for Ubuntu/Debian you were able to put all those forks for Regolith to a PPA. For Arch Linux the equivalent would be to put them in the [Arch User Repository ](https://aur.archlinux.org/)  which is kind of like a global user PPA. 

Anyway, my reason for asking about the forks was that if Regolith was to be promoted to the official Arch Repos, all the fork packages would also first need to be promoted as well. And I figured it would be easier if there were less forks, and all the artifacts Regolith delivered were configs. I see now that the changes you made when forking are a little more complex.

So anyway, I think an Arch packager should start by first creating AUR packages for all dependant forked packages ( i3xrocks and friends ), and then a package that would contain the regolith desktop files and configs. 

> Yes, initially i3xrocks started as a PR against i3blocks. They did not feel an additional dependency was worth the additional value. Entirely understandable.

That answers my direct question, and is unfortunate. 

Thanks again for putting this together. It works really well on my Ubuntu machine, and I'm looking forward to Regolith on other distributions.

Since the direct question in this issue has been answered I'm going to go ahead and close it. Tracking Regolith on other distros can probably stay tracked in #169
