### ISSUE TITLE
The random flag for feh command not working

### ISSUE THREAD

**Issue by tek-warp** [regolith-linux/regolith-desktop#25]
The wallpapers weren't randomly being selected.

The `--random` flag for `feh` should be changed to `--randomize`. Then the command works correctly.

Thank you for making Regolith!

**Comment by kgilmer** [comment]
Hi @tek-warp , thanks for fix!  You're certainly correct about the name of the flag.  Oddly, although I'm using "random", it still works for me.  Out of curiosity, are you using the same version of feh?  And if you reload i3 on an empty workspace (Super-Shift-r) you don't see wallpaper changes?

```
$ feh --version
feh version 2.23.2
Compile-time switches: curl exif xinerama
```

**Comment by tek-warp** [comment]
> Out of curiosity, are you using the same version of feh? 

No, mine is different. Maybe that's why it's acting differently.

```
~ feh --version 
feh version 2.27
Compile-time switches: curl exif xinerama 
```

> And if you reload i3 on an empty workspace (Super-Shift-r) you don't see wallpaper changes?

Nah, It doesn't do anything.

**Comment by kgilmer** [comment]
Fix pushed to `regolith-unstable`: regolith-i3_4.16-1ubuntu16.  I will promote to `regolith-stable` after verification.

**Comment by kgilmer** [comment]
Verified and pushed to `regolith-stable` PPA.  Closing.
