### ISSUE TITLE
Rofication crash

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#250]
![image](https://user-images.githubusercontent.com/49683/74706881-f5f6ec80-51cc-11ea-8537-ddd4ec644136.png)

**Comment by kgilmer** [comment]
It now is clear to me what I did wrong here w/ this screenshot.

**Comment by mmoutenot** [comment]
I also ran into a similar crash on 19.10.

![Screenshot from 2020-04-19 20-26-59](https://user-images.githubusercontent.com/339996/79703833-32ea6880-827c-11ea-9f3c-dd0de2f9762d.png)

**Comment by kgilmer** [comment]
Thanks for the complete screenshot @mmoutenot :smile: .  @farsil has been working quite a bit on this program, I expect this issue should be Resolved in R1.4.

**Comment by farsil** [comment]
I assume it should not happen again, but let's keep this in the backyard of our minds until we can verify that rofication 1.2.0 fixes the issue.
