### ISSUE TITLE
Unable to complete installation of Regolith Linux 1.3 Ubuntu 19.10 variant

### ISSUE THREAD

**Issue by rboerner** [regolith-linux/regolith-desktop#253]
Expected behavior:
Complete install of Regolith Linux 1.3 Ubuntu 19.10 variant on Intel NUC DN2820 (https://ark.intel.com/content/www/us/en/ark/products/78953/intel-nuc-kit-dn2820fykh.html) 

Experienced behavior:
Installation cannot complete due to inability to type text into certain user account creation fields within the installed.  Video of behavior is captured here --> https://youtu.be/amvdZeTEOno

Notes:
I attempted the installation of Regolith Linux 1.3 Ubuntu 19.10 variant within Oracle's VirtualBox and experienced identical problem behavior. 

I attempted the installation of Regolith Linux 1.3 Ubuntu 18.04 variant within Oracle's VirtualBox and the installation completed successfully. The problem was not present. 

I repeated testing using the standard Ubuntu 19.10 installation image (non-Regolith) on the Intel NUC hardware and the installation completed successfully.  The problem was not present.

I am not sure if I did something wrong at any point in the process, or if the problem is related to the Ubuntu installer rather than Regolith's customization, however I wanted to report the experience  to raise visibility.

Thank you for your excellent work on Regolith Linux!

**Comment by kgilmer** [comment]
Hi @rboerner , that's very strange!  Thanks for all of the details regarding the various scenarios you've tried.  Regolith's installer is a minor customization on the [stock Ubuntu installer](https://wiki.ubuntu.com/Ubiquity).  Other than package selections and a few text labels, they are identical.  So, I'm puzzled as to what could differ to cause the behavior that you're seeing.  

To unblock you, I suggest simply installing stock Ubuntu 19.10 and then installing Regolith via PPA.  It will result in the same experience as by installing via the ISO.  If you'd like, kindly [file a bug](https://bugs.launchpad.net/cubic/+filebug) with the [Cubic team](https://launchpad.net/cubic) to see if perhaps there is something we can improve in the future to avoid this problem.

**Comment by kgilmer** [comment]
Closing since not actionable at this time.
