### ISSUE TITLE
Switching Audio Interface 

### ISSUE THREAD

**Issue by aeikenberry** [regolith-linux/regolith-desktop#254]
I'm having trouble selecting a USB output device while booted in the Regolith desktop, but booting into the default Ubuntu desktop works ok.

I see the other sound options in the sound outputs, and i'm able to switch to an HDMI monitor as my output device, but when i click on other options, nothing happens.

![Screenshot from 2020-02-20 19-44-11](https://user-images.githubusercontent.com/599112/74996532-68f4a300-5419-11ea-8be3-3e7d1d7dd789.png)

Choosing Headphones or HDMI work just fine, but the other options don't switch from what's already chosen. Any ideas?

**Comment by kgilmer** [comment]
Hi @aeikenberry , hmm, I'm not aware of anything in particular to Regolith that would cause this.  It may be an issue with gnome-flashback.  I suggest [opening a bug there](https://gitlab.gnome.org/GNOME/gnome-flashback/issues/) and seeing what comes of it.

**Comment by wpbrown** [comment]
@aeikenberry Try using pavucontrol .

**Comment by kgilmer** [comment]
`pavucontrol` is cool, thanks for the tip @wpbrown .  @aeikenberry did this work for you?

**Comment by aadilayub** [comment]
I'm also experiencing this issue, also with USB headphones.

**Comment by aadilayub** [comment]
I tried using `pavucontrol` as suggested by @wpbrown, and it looks like my headphones aren't being detected. Strange that this is happening, considering they work fine on elementary OS, which is also based on Ubuntu LTS. I wonder what could be causing the issue.

**Comment by Olical** [comment]
I'm 99% sure my headphones were working over USB -> USB-C hub a little while ago, now I only have output. It's not registering as an input :thinking:

**Comment by muktupavels** [comment]
@aeikenberry Can you test also GNOME Flashback session? Maybe in the end `gnome-flashback` is missing something...

**Comment by moritzheiber** [comment]
We haven't heard back from you on this issue for a while, if you're still experiencing this issue please either file it upstream with `gnome-flashback` (should you be able to verify that it's indeed also happening under a "pure" `gnome-flashback` session) or feel free to re-open this issue instead if you have more information.
