### ISSUE TITLE
Slow terminal performance[Ubuntu 18.04]

### ISSUE THREAD

**Issue by pd321** [regolith-linux/regolith-desktop#255]
Firstly, thanks for such an easy working out of the box implementation for i3. 
I installed regolith-desktop on an Ubuntu 18.04 installation. Everything works well however any terminal works very slow and it hangs consistently. I changed the terminal from st to gnome but the problem persists. Any pointers to changes to be done in config or else would be helpful.

**Comment by kgilmer** [comment]
Hi @pd321 , I suspect the issue is with the compositor.  Try this guide for changing it and see if the problematic behavior changes: https://regolith-linux.org/docs/customize/compositors/

**Comment by Retro64XYZ** [comment]
Open your terminal and do the following -

```
$ sudo vi /etc/ssh/sshd_config
[sudo] password for user:
```

Search for UseDNS and change it to no. If it does not exist, explicitly set it to No using the following.

`UseDNS no`

Then restart your SSH server.

`$ sudo systemctl restart sshd`

See if that helps.

**Comment by pd321** [comment]
Thanks @kgilmer. Changing the compositor to `regolith-compositor-xcompmgr` fixed it for me. The terminal is performing as expected.
@Retro64XYZ - I did not changed the UseDNS setting as possibly my issue was related to the compositor. However in case it comes again I will try this change. Thanks.
