### ISSUE TITLE
help window (shortcuts) opens half hidden outside of screen

### ISSUE THREAD

**Issue by RafalSkolasinski** [regolith-linux/regolith-desktop#256]
Hitting `<Super><Shift>?` opens help dialog half outside of the main screen.
How can I fix it?

**Comment by kgilmer** [comment]
Do you have multiple screens?  If it's easy to do so, can you check to see if the problem persists with only one screen?

**Comment by RafalSkolasinski** [comment]
Hi @kgilmer!

The problem is present also with only one screen. Reproduced on two machines (laptop and desktop). It basically looks like this

![Screenshot from 2020-02-22 20-11-25](https://user-images.githubusercontent.com/10928117/75098570-b9056e00-55af-11ea-801e-cbb90b3e5f22.png)

I have installed Regolith today on top of Kubuntu 19.10 using `ppa:regolith-linux/release` PPA.

If I can provide you any more info, please, do let me know.

**Comment by kgilmer** [comment]
Thank you @RafalSkolasinski , that is helpful.  I'll look into it.

**Comment by kgilmer** [comment]
This should be fixed in 1.3.1.

**Comment by edenworky** [comment]
This is happening to me on a fresh install, using two monitors. Sometimes it works well, then gets half-hidden like in OP's screencap. One time it was even entirely centered.

**Comment by kgilmer** [comment]
@edenworky hmm, I'd thought I'd fixed all of those bugs.  Can you confirm the version of Remontoire you're using?  You may have better luck by changing the position.  See here for details: https://github.com/regolith-linux/remontoire#window-position
