### ISSUE TITLE
Add i3xrocks to package list

### ISSUE THREAD

**Issue by naclander** [regolith-linux/regolith-desktop#258]
I was trying to gather all the different packages regolith is made up of and found the very convenient list here:
https://github.com/regolith-linux/website/blob/master/content/en/docs/Reference/packages.md

However I see `regolith-i3xrocks-config` is present, but not the `i3xrocks` package. 

It should be added right?

**Comment by kgilmer** [comment]
Thanks @naclander , will fix shortly!

**Comment by kgilmer** [comment]
This will be added to the R1.3.1 site, thanks for the suggestion @naclander .  You may also be interested in this file, which what the build script uses to generate all of the packages Regolith requires on top of what Ubuntu provides in Universe: https://github.com/regolith-linux/regolith-builder/blob/master/package-model-R1.3.1.json

**Comment by naclander** [comment]
@kgilmer  Thanks for that file. I'm trying to narrow down the work required to create the regolith packages in the [Arch User Repository](https://aur.archlinux.org/).

**Comment by naclander** [comment]
Actually I still think `package-model-R1.3.1.json` is still missing the link to the `i3xrocks` package. It only contains i3xrocks-config.

**Comment by kgilmer** [comment]
It's down in the 'copies' block.  This package, like i3-gaps, are part of the speed-ricer project, in which when possible, for packages that I need that I can keep vanilla, I package them in a way for anyone to consume (as opposed to being specific to Regolith).  So for these packages I just copy the packages from the speed-ricer PPA into the Regolith ones.  Info here: 

https://launchpad.net/~kgilmer/+archive/ubuntu/speed-ricer
https://github.com/regolith-linux/speed-ricer

**Comment by kgilmer** [comment]
A little more info: the build has two primary stages, generating the debian package metadata for upload to the PPA (this is the first JSON block in the model file) and the second stage is copying packages from other PPAs into the target.
