### ISSUE TITLE
Reload should work with ~/.Xresources-regolith

### ISSUE THREAD

**Issue by Rizhiy** [regolith-linux/regolith-desktop#261]
Since a lot of options are defined in `~/.Xresources-regolith` other files and then later used in i3 config, I think it would make sense to merge it before reloading in the default config.

It's quite unintuitive if you are new to i3 and stuff.

**Comment by kgilmer** [comment]
By `reload` are you referring to reloading i3 or something else @Rizhiy ?

**Comment by Rizhiy** [comment]
I mean `$mod+Shift+c`.

**Comment by kgilmer** [comment]
I agree with you @Rizhiy . I need to think about this and do some testing.
