### ISSUE TITLE
Help menu is broken after upgrading to 1.3.1

### ISSUE THREAD

**Issue by MechJM** [regolith-linux/regolith-desktop#263]
I'm not completely sure this is related to the 1.3.1 release but this is the first time I tried to use the help menu after upgrading. After hitting the key combination or clicking the icon in the bar I get this:
![](https://user-images.githubusercontent.com/56487084/75827529-ce457e00-5da1-11ea-82d4-733892d3cd87.png) on the right side of the screen.

**Comment by kgilmer** [comment]
Hi @MechJM , this means that Remontoire didn't find any shortcuts.  Before 1.3.1, they were hardcoded into the app, but now they come from your i3 config file.  If you've created your own copy, it's likely that you don't have the data it's looking for.  The quick fix would be to remove your custom i3 config and see if it works, and then if so manually merge your changes into the new i3 config file (staged at `/etc/regolith/i3/config`).

Here is an example of the comment format it's looking for: https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config#L37

I have yet to document this but plan to once support issues (like this) for 1.3.1 die down, but here is the format:

```
## <category> ## <action> ## <keybinding description> ##
```

**Comment by jr0cket** [comment]
I have a custom theme and am also experiencing this problem after upgrading to 1.3.1 yesterday.  

It seems this issue also affects the drun menu (`Ctrl-Space`).  The menu is use a black background with no text.  No text appears when I type, although if I type correctly the menu does work.

I have a custom theme, so will see if merging changes from `/etc/regolith/i3/config` resolves the issue.  Thank you.

**Comment by jr0cket** [comment]
If I remove my custom theme, defined in a series of `.Xresources-*` files, then Regolith 1.3.1 help and drun menus all work correctly.

Adding back my .Xresources- customization, a red bar is displayed at the top of the regolith desktop stating "You have an error in your i3 config file".  The following are the errors I get in the log  `/run/user/1001/i3/pidid.log`

```
ERROR: CONFIG: Expected one of these tokens: <end>, <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 273: set_from_resource i3wm_window_border_size i3-wm.window.border.size "1"
ERROR: CONFIG: Line 274: set_from_resource i3wm_floatingwindow_border_size i3-wm.floatingwindow.border.size "1"
ERROR: CONFIG: Line 275: default_border pixel i3wm_window_border_size
ERROR: CONFIG:                                ^^^^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 276: default_floating_border pixel i3wm_floatingwindow_border_size
ERROR: CONFIG: Line 277: 
ERROR: CONFIG: Expected one of these tokens: <end>, <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 274: set_from_resource i3wm_floatingwindow_border_size i3-wm.floatingwindow.border.size "1"
ERROR: CONFIG: Line 275: default_border pixel i3wm_window_border_size
ERROR: CONFIG: Line 276: default_floating_border pixel i3wm_floatingwindow_border_size
ERROR: CONFIG:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 277: 
ERROR: CONFIG: Line 278: # Specify the distance between windows in pixels. (i3-gaps)
ERROR: CONFIG: Expected one of these tokens: <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 279: set_from_resource i3wm_gaps_inner_size i3-wm.gaps.inner.size "5"
ERROR: CONFIG: Line 280: set_from_resource i3wm_gaps_outer_size i3-wm.gaps.outer.size "0"
ERROR: CONFIG: Line 281: gaps inner i3wm_gaps_inner_size
ERROR: CONFIG:                      ^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 282: gaps outer i3wm_gaps_outer_size
ERROR: CONFIG: Line 283: 
ERROR: CONFIG: Expected one of these tokens: <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 280: set_from_resource i3wm_gaps_outer_size i3-wm.gaps.outer.size "0"
ERROR: CONFIG: Line 281: gaps inner i3wm_gaps_inner_size
ERROR: CONFIG: Line 282: gaps outer i3wm_gaps_outer_size
ERROR: CONFIG:                      ^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 283: 
ERROR: CONFIG: Line 284: # Only enable gaps on a workspace when there is at least one container
ERROR: CONFIG: Expected one of these tokens: 'top', 'bottom'
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 359: # The bar configuration
ERROR: CONFIG: Line 360: bar {
ERROR: CONFIG: Line 361:   position i3wm_bar_position
ERROR: CONFIG:                      ^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 362:   font pango:FontAwesome 13
ERROR: CONFIG: Line 363:   separator_symbol " "
ERROR: FYI: You are using i3 version 4.17.1 (2019-08-30)
```

I am not using a custom `config` file, just the `/etc/regolith/i3/config` file.

OS: Ubuntu Linux 19.10 with Regolith PPA

**Comment by jr0cket** [comment]
I fixed the above errors by adding the extra properties in `/etc/regolith/styles/ubuntu/theme` into my custom theme file.

I also replaced my `rofi.rafi` file with `/etc/regolith/styles/ubuntu/rofi.rafi` as there is significant differences (and I dont believe I customized that file anyway).

Everything is working just fine now.  I will push the changes to the custom theme solarized-light theme on https://github.com/practicalli/regolith-solarized-light

Thank you.

**Comment by MechJM** [comment]
I managed to fix the issue by performing the aforementioned merge but there were several issues with the default configuration file that I had to fix. Some lines in the 270-290 range had numbers inside quotes and I had to remove the quotes because i3 was expecting numbers; I also had to remove the quotes from the variable that contains the bar position.

**Comment by kgilmer** [comment]
Thanks for reporting the issues @MechJM .  I've created another one to fix.  I did not hit (test) this code as I had the Xresource values defined and so the invalid defaults were ignored by i3.

**Comment by kgilmer** [comment]
I used your copy to verify all of my fixes @MechJM , thanks for providing the link.  Out of curiosity, why did you override the shutdown and reboot commands?  Personal preference or is there some functional difference that you prefer?

**Comment by MechJM** [comment]
I guess I just prefer to have those actions performed instantly. I used to have these shortcuts in GNOME before I switched to Regolith (just with different bindings).
