### ISSUE TITLE
i3-wm.font not used in i3 configuration

### ISSUE THREAD

**Issue by uselessthird** [regolith-linux/regolith-desktop#264]
Hello,

I noticed that a new X resource `i3-wm.font` was added to /etc/regolith/styles/i3-wm. However, this doesn't seem to be used in the i3 configuration. Rather the configuration includes the following line:

```
font $i3-wm.bar.font
```

which perhaps erroneously is *above*:

```
set_from_resource $i3-wm.bar.font i3-wm.bar.font "pango:Source Code Pro Medium 13, FontAwesome 13"
```

Presumably the new X resource was added to allow the font that i3 uses for window titles to be configured independently of the bar font.

**Comment by kgilmer** [comment]
Thanks @uselessthird !  You presume correctly.

**Comment by uselessthird** [comment]
Hi @kgilmer 

Thanks for the quick response. I think you forgot to add a line to load the X resource in your fix, like:

```
set_from_resource $i3-wm.font i3-wm.font "pango:Source Code Pro Medium 13, FontAwesome 13"
```

**Comment by kgilmer** [comment]
:man_facepalming: Thanks @uselessthird !
