### ISSUE TITLE
Invalid defaults for new Xresource values in i3 config file

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#265]
Reported in https://github.com/regolith-linux/regolith-desktop/issues/263

**Comment by topherbuckley** [comment]
After logging in today I found an error "you have an error in your i3 config file". Searching in the past issues I found the exact error from another user @jr0cket quoted below:

>
```
ERROR: CONFIG: Expected one of these tokens: <end>, <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 273: set_from_resource i3wm_window_border_size i3-wm.window.border.size "1"
ERROR: CONFIG: Line 274: set_from_resource i3wm_floatingwindow_border_size i3-wm.floatingwindow.border.size "1"
ERROR: CONFIG: Line 275: default_border pixel i3wm_window_border_size
ERROR: CONFIG:                                ^^^^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 276: default_floating_border pixel i3wm_floatingwindow_border_size
ERROR: CONFIG: Line 277: 
ERROR: CONFIG: Expected one of these tokens: <end>, <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 274: set_from_resource i3wm_floatingwindow_border_size i3-wm.floatingwindow.border.size "1"
ERROR: CONFIG: Line 275: default_border pixel i3wm_window_border_size
ERROR: CONFIG: Line 276: default_floating_border pixel i3wm_floatingwindow_border_size
ERROR: CONFIG:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 277: 
ERROR: CONFIG: Line 278: # Specify the distance between windows in pixels. (i3-gaps)
ERROR: CONFIG: Expected one of these tokens: <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 279: set_from_resource i3wm_gaps_inner_size i3-wm.gaps.inner.size "5"
ERROR: CONFIG: Line 280: set_from_resource i3wm_gaps_outer_size i3-wm.gaps.outer.size "0"
ERROR: CONFIG: Line 281: gaps inner i3wm_gaps_inner_size
ERROR: CONFIG:                      ^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 282: gaps outer i3wm_gaps_outer_size
ERROR: CONFIG: Line 283: 
ERROR: CONFIG: Expected one of these tokens: <number>
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 280: set_from_resource i3wm_gaps_outer_size i3-wm.gaps.outer.size "0"
ERROR: CONFIG: Line 281: gaps inner i3wm_gaps_inner_size
ERROR: CONFIG: Line 282: gaps outer i3wm_gaps_outer_size
ERROR: CONFIG:                      ^^^^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 283: 
ERROR: CONFIG: Line 284: # Only enable gaps on a workspace when there is at least one container
ERROR: CONFIG: Expected one of these tokens: 'top', 'bottom'
ERROR: CONFIG: (in file /etc/regolith/i3/config)
ERROR: CONFIG: Line 359: # The bar configuration
ERROR: CONFIG: Line 360: bar {
ERROR: CONFIG: Line 361:   position i3wm_bar_position
ERROR: CONFIG:                      ^^^^^^^^^^^^^^^^^
ERROR: CONFIG: Line 362:   font pango:FontAwesome 13
ERROR: CONFIG: Line 363:   separator_symbol " "
ERROR: FYI: You are using i3 version 4.17.1 (2019-08-30)
```
_Originally posted by @jr0cket in https://github.com/regolith-linux/regolith-desktop/issues/263#issuecomment-594514216_

Did a similar issue get pushed to the apt repo recently? 

Unfortunately the [solution](https://github.com/regolith-linux/regolith-desktop/issues/263#issuecomment-594537563) proposed by @jr0cket previously does not seem to work after restarting regolith via (SUPER+Shift+R) . Can you provide details as to where I should have definitions of these variables (i3wm_window_boarder_size, etc.) and if I need to do a full system restart or log-out/in in order for such changes to take effect?

**Comment by jr0cket** [comment]
On Saturday I restarted regolith, I had an json error and a message saying the rasi.rosi file wasnt found.  I restarted again and all was well (although there is a little glitch with my zsh powerline10k prompt, but not serious).  I assume there was a minor release since 1.3.1 that tripped up on something initially.

**Comment by topherbuckley** [comment]
@jr0cket thanks for chiming in. I noticed you mentioned this rasi.rosi file in issue I quoted as well. I'm not familiar with this file, where might I find it (or where it should be)? If I cannot find it, is there a default/template somewhere else I can copy from?

**Comment by kgilmer** [comment]
Hi @topherbuckley what PPA are you using? `apt policy | grep regolith`.  There have been no updates to the release or stable PPA in over a week.  If you're using `unstable`, yes there are a lot of dev updates there and it's likely you've hit a problem.

**Comment by topherbuckley** [comment]
I hadn't logged into this machine for several weeks, so I'm not sure when exactly the update took place, but more than a week for sure. 

Here is the output of the requested commands:
```
$ apt policy | grep regolith

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

 500 http://ppa.launchpad.net/regolith-linux/release/ubuntu bionic/main i386 Packages
     release v=18.04,o=LP-PPA-regolith-linux-release,a=bionic,n=bionic,l=Regolith Linux - Release,c=main,b=i386
 500 http://ppa.launchpad.net/regolith-linux/release/ubuntu bionic/main amd64 Packages
     release v=18.04,o=LP-PPA-regolith-linux-release,a=bionic,n=bionic,l=Regolith Linux - Release,c=main,b=amd64
```
```
$ apt list --installed | grep regolith

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

regolith-compositor-compton-glx/bionic,now 1.0.5-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-desktop/bionic,now 2.49-1ubuntu1~ppa1 amd64 [installed]
regolith-ftue/bionic,now 1.0.3-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-gnome-flashback/bionic,now 2.4.5-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3-gaps-config/bionic,now 2.3.6-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3xrocks-config/bionic,now 2.2.14-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-look-cahuella/bionic,now 2.3.5-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-rofication/bionic,now 1.0.9-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-st/bionic,now 0.8.2-1ubuntu20ppa5 amd64 [installed,automatic]
regolith-styles/bionic,now 2.3.5-1ubuntu1~ppa1 amd64 [installed,automatic]

```

**Comment by kgilmer** [comment]
Thanks @topherbuckley , your package and PPA settings look good.  I'm guessing you have a custom i3 config file from 1.3, and it needs to be updated to use the new settings in 1.3.1.  To do this just remove or move the following files, and log back in.  Once it's working without error, then you'll need to re-merge any of your changes into the updated files.

```
~/.Xresources-regolith
~/.config/regolith/i3/config
```

**Comment by topherbuckley** [comment]
Although possibly a completely different source of issue, I should also mention that the Application Launcher <SUPER> Space yields a blank grey rectangle that spans the full height of my monitor. It doesn't respond to any keystrokes other than ESC, at which point it closes properly. All other key combinations (Browser, Terminal, etc.) appear to work fine. Did the config file in question also have some launcher-related changes in recent (last month or two) updates?

**Comment by topherbuckley** [comment]
@kgilmer I removed those two files and rebooted. Issue still persists. I even reinstalled regolith as per [here](https://regolith-linux.org/docs/getting-started/install/#reinstallation) and issue still persists. After log out/in should the:

~/.Xresources-regolith
~/.config/regolith/i3/config

files be regenerated with some template files? I'm seeing no such files after removing them then log in/out.

**Comment by kgilmer** [comment]
I don't understand how you could be getting the same i3 errors as listed above after a fresh install.  Please send me your i3 config file, either DM me in slack or mail me at kgilmer at gmail.com.

The files I listed previously would be overrides you may have added in the past that could have been out of date, producing errors like you initially listed.  Unless you create them intentionally, Regolith will not add files to your user directory.

**Comment by kgilmer** [comment]
Nothing should survive from a previous install if you remove `~/.config/regolith` and follow the reinstallation steps.
