### ISSUE TITLE
Firefox notifications

### ISSUE THREAD

**Issue by uselessthird** [regolith-linux/regolith-desktop#269]
I noticed that notifications from Firefox (e.g. Google Calendar) don't use the new notification mechanism in Regolith 1.3. Instead they pop up a small window for a few seconds. Is there a way of fixing this?

I'm using the release PPA on Ubuntu 18.04.4 and Firefox 73.0.1.

Many thanks.

**Comment by kgilmer** [comment]
Hi @uselessthird :smile: , check this issue in which there is a fix: https://github.com/regolith-linux/regolith-desktop/issues/211

**Comment by uselessthird** [comment]
Hi @kgilmer ,
Thank you, I didn't spot that issue.

Feel free to close this one.
