### ISSUE TITLE
Issue with renaming workspace labels.

### ISSUE THREAD

**Issue by Fr0stykiller** [regolith-linux/regolith-desktop#270]
Hi,
I've followed the instructions to port config and syles files for i3 as described here:
https://regolith-linux.org/docs/howto/remove-workspace-icons/
After reload however label changes correctly yet I'm unable to switch workspaces using the shortcut: `$mod + 1` `$mod + 2` etc...
Changes to i3 styles looks something like this:
```
#define WORKSPACE_NAME(INDEX, FONT, COLOR, GLYPH)

i3-wm.workspace.01.name: Terminal
i3-wm.workspace.02.name: Web
i3-wm.workspace.03.name: Code
```
Haven't changed anything in i3 config so workspace switching looks like this:
```
## Navigate // Workspace // <Super> 0..9 ##
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
```

**Comment by kgilmer** [comment]
Hi @Fr0stykiller :smile: .  You need to prefix your workspace label with the index.  So:
```
i3-wm.workspace.01.name: 1 Terminal
i3-wm.workspace.02.name: 2 Web
i3-wm.workspace.03.name: 3 Code
```

The index will not appear in the bar by default but can be changed via Xresource key `i3-wm.bar.stripworkspacenumbers`.
