### ISSUE TITLE
Desktop bar date and time doesn't respect Gnome preferences

### ISSUE THREAD

**Issue by scmbradley** [regolith-linux/regolith-desktop#271]
I've set my date preferences to English (UK), which means DD/MM dates, and I've set the clock to 24 hours. Neither of these are respected by the desktop bar, which displays AM/PM time and US-style dates (MM/DD).

**Comment by kgilmer** [comment]
Hmm, can you tell me how you installed Regolith and which version of Ubuntu you are running?

**Comment by scmbradley** [comment]
19.10, via PPA. 

I had i3 installed (from the ubuntu repos) before I installed regolith, if that makes a difference?

**Comment by kgilmer** [comment]
Here is what I did, and worked as I would expect:

## Time
1. Go to control panel, in Details -> Date & Time toggle the 24 hour format switch.
Expected: see time format change
Actual: see format change

## Date
1. Go to control panel, in Region & Language -> Formats, set to United Kingdom
2. Reboot as requested
Expected: see US date format in bar
Actual: see US date format in bar

Is this how you set the time and date formats @scmbradley ?

**Comment by scmbradley** [comment]
That's what I did. Just checked my settings again (and even pressed "apply settings system wide" in the localisation menu), but the bar is still MM/DD, AM/PM format

If it's working as expected for you, I guess this is something weird about how I got to my set up (i.e. using vanilla i3 first before moving to regolith? The laptop was actually originally from germany, so the hardware keeps wanting to be in german.) I'm not sure how we'd move forward diagnosing this, and it doesn't seem like it's high priority. So I don't mind if you want to close it. (On the other hand,I'm happy to try to help find the problem).

**Comment by kgilmer** [comment]
Let's figure it out!

The script that generates the date/time is `/usr/share/i3xrocks/time2`.  This should be referenced in your copy of the i3xrocks config file, in `/etc/regolith/i3xrocks/config` unless you've created your own version in your user directory.  The file should have the following lines:
```
# Date Time
[time2]
interval=10
```

You can run the script from the command-line to see the output:
```bash
$ /usr/share/i3xrocks/time2
<span color="#D8DEE9"></span><span font_desc="Source Code Pro Medium 13" color="#E5E9F0"> 13/03 18:23 </span>
```

If you take a look in the shell script, you can see how it determines the date/time format:
```bash
$ locale | grep LC_TIME | head -n1 | cut -d "=" -f 2 | cut -d "_" -f 2 | cut -d "." -f 1
GB
```

```bash
$ gsettings get org.gnome.desktop.interface clock-format
'24h'
```

Does this provide any clues?

**Comment by scmbradley** [comment]
OK. So, `/usr/share/i3xrocks/` doesn't have a `time2`. It has `time`, but if you run that, you get something that outputs AM/PM MM/DD dates and times.

`/etc/regolith/i3xrocks/config` contains the following lines:

```
# Date Time
# 
[time]
interval=60
```

And `locale` tells me that  `LC_TIME=en_GB.UTF-8`

The `gsettings` thing returns `24h`.

**Comment by kgilmer** [comment]
Ok, well then the issue is because you're running an outdated version of regolith-i3xrocks-config.  Here's what I have:
```
$ apt list --installed | grep regolith-i3xrocks-config

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

regolith-i3xrocks-config/now 2.2.14-1ubuntu1~ppa1 amd64 [installed,upgradable to: 2.2.15-1ubuntu1~ppa1]
```

I suggest you upgrade to the latest as described here: https://regolith-linux.org/download/ "Upgrade from earlier version" section.

**Comment by scmbradley** [comment]
Aha. In that case, the "bug" is that [this page](https://github.com/regolith-linux/regolith-desktop/wiki/Install-Regolith) still lists the old PPA (I only installed regolith about a week ago).

**Comment by scmbradley** [comment]
Updating to the new repo fixed this issue (and made everything look a little nicer as well). 

I've edited the wiki page. so I'm closing this issue.

**Comment by kgilmer** [comment]
:man_facepalming: thanks @scmbradley .  I didn't realize the old installation page was still alive.  I just opted to wipe the whole thing and point to the site, but I appreciate your effort in updating it!
