### ISSUE TITLE
Add "Upgrade" section to Installation page on site

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#273]
Acceptance Criteria: all details needed for upgrading from a previous release are covered in new upgrade section of Installation page.

**Comment by korakinos** [comment]
Are the instructions in the wiki[1] still valid?

[1] https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Upgrade-to-Ubuntu-19.10-(Eoan-Ermine)

**Comment by kgilmer** [comment]
Hi @korakinos , the instructions were out of date.  I just updated them.  Please let me know if you experience issues.

**Comment by korakinos** [comment]
Worked perfectly, thank you! Worthy of note: Because I had automatic (passwordless) login enabled, I didn't get to to choose a session on reboot, but had to manually log out and in again in order to select the Regolith session.
