### ISSUE TITLE
WiFi and VPN don't work (nm-applet required)

### ISSUE THREAD

**Issue by TS-CUBED** [regolith-linux/regolith-desktop#277]
Hi, 
Using current Regolith PPA on Ubuntu 20.04 (developement).

Out of the box I cannot connect to WiFi or VPN (wired works). 

Solution here: add

exec --no-startup-id nm-applet

to .../i3/config

**Comment by kgilmer** [comment]
I am unable to repro this against the final version of 20.04.  Kindly re-open if issue persists with that.

**Comment by gdub** [comment]
I recently did an install with a final version of **Kubuntu** 20.04, installed Regolith via PPA, and configured wifi settings via `gnome-control-center`.  System did not connect to wifi automatically.  

After a fresh reboot and login to Regolith session, also no wifi connection established.

However, after running `nm-applet`, wifi connected successfully.  Should `nm-applet` (or some other process to handle wifi connection) already be running?

**Comment by kgilmer** [comment]
Hi @gdub , I cannot say how Kubuntu differs from stock Ubuntu, but it's possible that the gnome-settings-daemon is not running or not configured to perform this task.  I can say that nm-applet is not required when running from the ISO or installed via PPA into a "regular" Ubuntu install.  

In any case, you can add an Xres override to have i3 start nm-applet for you. Have a look at https://regolith-linux.org/docs/howto/override-xres/ for details.  The key you would set is something like:

```
i3-wm.program.1: /usr/bin/nm-applet
```

**Comment by ceejatec** [comment]
FYI, I'm using stock Ubuntu 20.04 (final) and confirm the same symptom as the original reporter. I installed network-manager-openconnect-gnome, and I can configure the VPN in the normal configuration panel, but actually clicking the slider to enable the VPN immediately fails (the slider just slides back to "off"). After some investigation I determined that running "nm-applet" in the background allows things to work. It appears that the VPN's login panel requires nm-applet to be running (unfortunately you can't set login credentials in the configuration window; it requires a login popup at the time you enable the VPN).

**Comment by TS-CUBED** [comment]
Adding the following two lines to .config/regolith/i3/config solves the issue. It seems to be a common i3 issue and not limited to regolith:

# Start nm-applet (otherwise VPN won't work)
exec --no-startup-id nm-applet

**Comment by ceejatec** [comment]
True. I actually am trying very hard to be a Good Boy and not customize my i3config, so instead I have ~/.config/regolith/Xresources containing `i3-vm.program.1: /home/ceej/.i3/startup.sh` and in there I execute all my startup programs. Adding `nm-applet` to that file does indeed fix the issue. I'm just not sure that this is the right out-of-the-box experience for Regolith, which is why I commented to confirm the reported issue.

**Comment by TS-CUBED** [comment]
> True. I actually am trying very hard to be a Good Boy and not customize my i3config, so instead I have ~/.config/regolith/Xresources containing `i3-vm.program.1: /home/ceej/.i3/startup.sh` and in there I execute all my startup programs. Adding `nm-applet` to that file does indeed fix the issue. I'm just not sure that this is the right out-of-the-box experience for Regolith, which is why I commented to confirm the reported issue.

Yep, I agree it should be in the default config. I'm more old school, I guess. My i3config has a lot of modifications already (automatically concatenated from the regolith one and a couple of local files to allow quick updates). Actually using i3/regolith brings me back to the times when I was running a heavily modified .fvwmrc ;-)

But I admit, the Xresources solution is quite elegant if you only need to start applications rather than adding modifying i3 behaviour.

**Comment by TS-CUBED** [comment]
> Hi @gdub , I cannot say how Kubuntu differs from stock Ubuntu, but it's possible that the gnome-settings-daemon is not running or not configured to perform this task. I can say that nm-applet is not required when running from the ISO or installed via PPA into a "regular" Ubuntu install.

I can confirm that the issue is still there in the final Ubuntu 20.04 LTS and that automatic connection to WiFi only works if no popup for credentials is required (e.g. when WIFi is configured at installation or credentials are in config files), but that is also not always the case if WiFi is changed a lot. VPN login requires nm-applet in any case. Everything works fine when nm-applet is started.

**Comment by ceejatec** [comment]
So far I've been able to avoid needing to modify i3 behaviour beyond the things that regolith allows tweaking in Xresources. Not sure that'll last forever, so I'll remember your "build custom .i3 config by catenating the stock one and my changes" approach for the future. And yes, i3's lack of an include directive mystifies me as well.

Ahh, fvwm. That brings back some memories of sitting in the computer labs at college tweaking X color values instead of getting my assignments done...

**Comment by chuahou** [comment]
I can add that on a fresh install of Regolith 1.4 previously (not 1.4.1), using gnome-control-center to add Wifi connections did not show an authentication window for adding password. Clicking on an access point added it to "saved connections" with no password saved, making it not possible to connect. Manually adding the password by clicking on the gear button worked.

If nm-applet was running, clicking an access point to add it would display the dialogue for authentication as expected.

I found the same behaviour in Regolith 1.4.1 installed on Pop!_OS.

**Comment by paolomainardi** [comment]
I confirm this bug, the password dialog don't show up, just a plain ubuntu 20.04 + the latest stable regolith.

**Comment by kgilmer** [comment]
The password can be set/edited by opening the settings for the wifi profile and selecting the security tab.  Yes, it's true that with `nm-applet` this can be done via a pop-up.  I opted to avoid running `nm-applet` for this feature, as IMHO the utility of the pop-up does not seem significant, once you know where to go to set the password.  Also, users can easily have nm-applet run at start with a single Xres override statement.

**Comment by ceejatec** [comment]
That's likely true for Wifi, but it isn't for VPN. There's nowhere to enter credentials for a new VPN connection, at least not using the Openconnect framework. Moreover, even after initial configuration, nm-applet is still required every time the VPN is started. So out of the box, regolith effectively doesn't allow use of VPNs, which is a pretty serious limitation especially for business use.

I agree that nm-applet can easily be added using Xresource overrides. What I think is probably the best compromise here is to document that fact clearly, and possibly even have a dedicated Xresource for enabling nm-applet specifically as opposed to using one of the generic i3-wm.program.X slots.

**Comment by TS-CUBED** [comment]
I agree with ceejatec. Regolith has the potential to get i3 out to a wider audience since it has sane defaults. 
Users who are likely to see no problem with solving this issue by starting nm-applet via an Xres or i3/config entry are more likely to opt for plain i3 over regolith.
It's your project, so your philosophy. But I'd be more likely to recommend it (some of my students are awed when I teach using my laptop), if the default was the other way. Straightforward for beginners, and advanced users can deactivate nm-applet.

And I would definitely recommend this, since I think regolith is awsome. Especially with the new Xres framework. Useable and with very sane defaults by beginners, but still very tweakable for those that want to do it.

BTW, I don't really need nm-applet to deal with my vpn issue, since my vpn is autostarted for connections that need it, but I still believe it should be easy by default.

**Comment by kgilmer** [comment]
Thanks for your well-reasoned perspectives @ceejatec and @TS-CUBED .  I will certainly add some better documentation for this on the site.  I'll also look into the runtime costs of `nm-applet` to better gauge the cost.  I'll update this ticket if any changes are made.
