### ISSUE TITLE
[question] disable regolith wallpaper completely

### ISSUE THREAD

**Issue by verajosemanuel** [regolith-linux/regolith-desktop#278]
I have nitrogen installed to set my wallpaper randomly, but when booting my PC, at the end of the process, regolith takes control and sets a wallpaper I don't want.

I have this command at the end of my i3 config:

`exec --no-startup-id nitrogen --restore &`

so the background is set, but regolith takes control and replaces the wallpaper.

is there any way of disabling this behaviour or disabling regolith background completely?

**Comment by kgilmer** [comment]
Hi @verajosemanuel , can you try running the following command.  I believe this will disable gnome-flashback from setting the wallpaper:
```
gsettings set org.gnome.gnome-flashback desktop-background false
```

**Comment by verajosemanuel** [comment]
worked flawlessly, thanks!!!

**Comment by verajosemanuel** [comment]
hi, after latest update. Wallpaper is set again and command raises an error:

 gsettings set org.gnome.gnome-flashback desktop-background false
No such key “desktop-background”

**Comment by gregor-tb** [comment]
I have same issue, after each suspend I get the default theme wallpaper, but I want to use nitrogen. Removing the "desktop_wallpaper" define just restores the OS default one instead. :(

**Comment by kgilmer** [comment]
@verajosemanuel This has changed in Ubuntu 20.04.  The new form is `gsettings set org.gnome.desktop.background picture-uri <file uri>` 

@gregor-tb  I need to know the specific steps you are taking and what you expect to happen to help you.  Also I don't know what you mean by `Removing the "desktop_wallpaper" define`.  To have Regolith ignore wallpaper changes, the define must be set to empty, not removed. If you continue to have a problem, please create a new issue and clearly describe your problem.
