### ISSUE TITLE
Setting a terminator as a default terminal Regolith on Ubuntu 19.10 

### ISSUE THREAD

**Issue by GiorgChr** [regolith-linux/regolith-desktop#280]
I installed today the Regolith window manager on ubuntu 19.10 and i cant set terminator as my default terminal. i use `sudo update-alternatives --config x-terminal-emulator` but after selecting terminator and closing the current terminal window nothing changes. I tried uninstalling the regolith-st but then nothing opened.

**Comment by hypergig** [comment]
So ironic, I just did this 5 mins ago... i used the following command:
```
sudo update-alternatives --set x-terminal-emulator /usr/bin/alacritty
```
Maybe you are missing `sudo`?

**Comment by GiorgChr** [comment]
Still no results...i use `sudo update-alternatives --set x-terminal-emulator /usr/bin/terminator` but after i close the terminal nothing changes.

**Comment by kgilmer** [comment]
When you launch a terminal i3 executes this: `/usr/bin/x-terminal-emulator`  (https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config#L38)

What happens when you run `/usr/bin/x-terminal-emulator` ?  What does `$ update-alternatives --display x-terminal-emulator` say?

**Comment by GiorgChr** [comment]
I found the solution. While installing regolith there was no .config file created. I had to create the path and refresh. Then i found the command that opens the terminal and replaced st with terminator.

**Comment by kgilmer** [comment]
Sounds like you are running an old version of Regolith @GiorgChr . How did you install?
