### ISSUE TITLE
Emacs cursor stutter and lag

### ISSUE THREAD

**Issue by wsturgiss** [regolith-linux/regolith-desktop#285]
I'm not noticing this in any other applications, but in emacs the cursor is stuttering and lagging at times.  I did a fresh install of regolith to see if I had messed it up somehow, or perhaps the issue had been patched.  This only happens in emacs.  I am on ubuntu 18.04.  

A video of it happening.  Apologies for using a cell phone camera.  As you can see, its not a problem with input devices, the stutter continues while input devices are unplugged.  
https://photos.app.goo.gl/tL5HYLPXYcYLj6H46

I saw a sort of similar issue filed already, and the solution was to disable compton, but I don't see that anywhere in the i3 config file.

**Comment by kgilmer** [comment]
Hi @wsturgiss  :smile: , yeah my first guess is that's related to compton.  To disable or change to another variant see here: https://regolith-linux.org/docs/customize/compositors/  Note you'll have to log out for the change to take effect.

The compositor configuration is per-implementation.  For the default, compton, the configuration lives in `/etc/regolith/compton/config` and is referenced from `/usr/share/regolith-compositor/init`.

**Comment by wsturgiss** [comment]
@kgilmer switching to xcompmg fixed the issue.  Thank you!
