### ISSUE TITLE
Notifications Stopped Working

### ISSUE THREAD

**Issue by skostojohn** [regolith-linux/regolith-desktop#288]
Yesterday notifications worked perfectly as described in the docs.  The counter on the system tray showed the notifications, and I could super+n to view them.

Today, this feature is not working.  The counter does not move from zero, and notifications appear as a gray pop-up box:

![image](https://user-images.githubusercontent.com/2495345/77448482-1c044380-6dae-11ea-89a9-c47e54396710.png)

I don't think I changed anything - any ideas on how to get notifications working again?

Thank you in advance for the help!  Sorry to be posting two issues in two days. Sheesh!

**Comment by kgilmer** [comment]
Hmm, if you have `dunst` installed you'll need to remove it.  `sudo apt remove dunst`.  Or it could be that some upgrade reverted some gnome settings changes.  To cause Regolith to reset gnome settings, remove the directory `~/.config/regolith/flags` and log back in.

No worries regarding issue frequency, I'm happy to help where I can!  :smile: :+1:

**Comment by skostojohn** [comment]
I didn't have `dunst` installed, but removing the flags directory seemed to work, Ken - my notifications are working properly again.  Thanks.

I'm going to leave this open for a couple of days just to make sure the problem doesn't resurface, then I will close this out.

Thank you for being so responsive and helpful - I really appreciate it.

**Comment by skostojohn** [comment]
I powered up my laptop this morning, and the same problem has returned.  Any ideas as to a more permanent fix, rather than deleting the `flags` directory and logging out/in?

**Comment by skostojohn** [comment]
I may have fixed this...
I commented out the line in the i3 config that starts `rofication-daemon.py`.
Then I updated this file:
`/usr/share/dbus-1/services/org.freedesktop.Notifications.service` 
to call `rofication-daemon.py` instead of `notify-osd`.
Logged out/in and notifications were working again.  I will let you know if anything changes.

**Comment by skostojohn** [comment]
This is working smoothly this morning.  Closing the issue out.

**Comment by kgilmer** [comment]
Interesting, thanks for the info @skostojohn .  I don't see that service file locally nor does any package I have in apt provide it.  Any idea where it comes from?

```
$ dpkg -S org.freedesktop.Notifications.service
dpkg-query: no path found matching pattern *org.freedesktop.Notifications.service*
```

**Comment by skostojohn** [comment]
I don't know where it came from - here is the output when I run the same query you ran above:
```
➜ dpkg -S org.freedesktop.Notifications.service
diversion by notify-osd from: /usr/share/dbus-1/services/org.freedesktop.Notifications.service
diversion by notify-osd to: /usr/share/dbus-1/services/org.freedesktop.Notifications.service.notify-osd
notify-osd: /usr/share/dbus-1/services/org.freedesktop.Notifications.service
diversion by notify-osd from: /usr/share/dbus-1/services/org.freedesktop.Notifications.service
diversion by notify-osd to: /usr/share/dbus-1/services/org.freedesktop.Notifications.service.notify-osd
```
Hope that is helpful!

**Comment by kgilmer** [comment]
Yep, that's it @skostojohn .  `notify-osd` is not shipped with Regolith.  Work is on-going to modularize the notification packages so that we can declare that rofication conflicts with notify-osd, dunst, etc..  This will force you as the user to explicitly choose which notification system you prefer and prevent these sort of bugs in the future.

**Comment by rguilmont** [comment]
For the record, i had a very similar issue ( Running ubuntu 20.04 with Regolith packages installed ).

For some reason i had xfce4-notify installed, which caused the exact same behaviour. Removed it, logged out/in and problem was fixed!
