### ISSUE TITLE
Add howto to add applet tray and a few common applets to the bar.

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#29]
Some users prefer applets for some configuration over `gnome-control-center`.  This task is to write a howto block on the site that describes how to do this with Regolith.  Related to https://github.com/regolith-linux/regolith-desktop/issues/2.

**Comment by kgilmer** [comment]
Fixed: https://regolith-linux.org/howto.html#i3-tray

**Comment by shijiantian** [comment]
Simply change the value of tray_output can't make applet work.
I finally find the solution in here:https://github.com/jcstr/i3-gnome/issues/25
```exec --no-startup-id dbus-launch nm-applet```  can  work.

**Comment by kgilmer** [comment]
I'll add some details to the documentation on that point, thanks @shijiantian

**Comment by kag0** [comment]
@kgilmer is this still supported? the doc link is dead and I can't find anything about applets in the new docs.

**Comment by kgilmer** [comment]
Hi @kag0 , enabling the tray in the i3bar is supported in Regolith.  This will do it:
```bash
echo "i3-wm.bar.trayoutput:	primary" >> ~/.config/regolith/Xresources
```

Reload your i3 session, and then to test from the commandline:

```bash
$ dbus-launch nm-applet
```
