### ISSUE TITLE
Always restart i3 when...

### ISSUE THREAD

**Issue by hypergig** [regolith-linux/regolith-desktop#290]
There are a few situations when i3 always needs to be restarted. Since regolith has broader control over the workstation in general, it would be convenient if it did it for us. These situations include:
* when a new display is plugged in
* when the computer comes out of suspend (this isn't always needed but does seem necessary when you fiddle with displays while computer is asleep)
* when the computer comes out of hibernate (similar to ^)
* when you open or close the laptop lid (sorta related to first bullet)
* when you change the scale on any display

**Comment by kgilmer** [comment]
Hi @hypergig , I do not need to restart i3 under these conditions.  What happens if you do not restart i3 after opening the laptop lid?  And when a display is plugged in?  These use cases are particularly why I chose to integrate i3 with GNOME, but it seems like maybe somethings not working for you?

**Comment by hypergig** [comment]
@kgilmer are you using mixed scales? My laptop screen is scale 2, my external monitor is scale 1. So what happens for me is, mixed scale UI components. The top bar may be scale 1 on my laptop screen, (super small) or the bars for tabulated i3 containers get out of sync with the current scale. It is automattic now when I clamshell my laptop and plug it in to my external or "undock" it, meta-R.

**Comment by hypergig** [comment]
...honestly.. it is sorta moot due to 
https://github.com/regolith-linux/regolith-desktop/issues/289
I almost always have to reboot anyway due to ^
