### ISSUE TITLE
Move cheat sheet window into rofi

### ISSUE THREAD

**Issue by hypergig** [regolith-linux/regolith-desktop#291]
The cheat sheet is boss. But wouldn't it be even more boss if it was in rofi as a custom menu?
* built in fuzzy search
* option to execute the shortcut directly from the menu
* icons if you like
* you can remap meta-? to new menu to keep it real

Here are a few examples of custom rofi menus for reference https://github.com/davatorium/rofi/wiki/User-scripts, there are already a few i3 ones in there already.

**Comment by hypergig** [comment]
https://forum.manjaro.org/t/rofi-based-application-launcher-menu-with-categories/43113

Some hacky ways to implement sub-menus

**Comment by hypergig** [comment]
Just playing around to see how doable it is
`cat ~/repos/workstation/config/i3.config | grep '##' | cut -d'/' -f3-6 | sed 's/\/\//->/' | sed -E 's/(^ |##)//g' | rofi -dmenu`
looks like:
![rofi](https://user-images.githubusercontent.com/8643560/77464749-0575e080-6dde-11ea-86b4-f2b2fbfd81d6.png)
Which is pretty decent for a one liner!

Would prob need to flatten it out and remove the shortcut categories, but I think this is ok being that rofi is the interface. If we put a descriptor comment/line before every shortcut in the config file (rather than groupings) than it would trivial to parse to command, and then later run it through `i3-msg`.

**Comment by kgilmer** [comment]
Nice!  You're parsing the comments meant for Remontoire in Rofi, very cool!  Are you interested in adding this as a feature of Regolith?  You'd probably want to add your script in https://github.com/regolith-linux/regolith-rofi-config...

**Comment by hypergig** [comment]
I love those annotating comments in the config, they are great way to self document with external applications.

Yeah, I would be happy to. I have a few enhancements on my mine... just need to find the time.

**Comment by matclab** [comment]
I've just published a smal rofi modi script that fit my needs : https://gitlab.com/matclab/rofi-i3-shortcut-help
Hope it may be of some use.

**Comment by dowcet** [comment]
The current cheat sheet sends me into a rage because it requires the mouse to use, doesn't fit on the screen when expanded, etc. This looks like a nice solution.

**Comment by kgilmer** [comment]
That is really nice @matclab  , I'll take it for a spin!

**Comment by kgilmer** [comment]
@matclab 's work was inspiration for the keybinding page in `ilia`.  I'm closing this issue as we will not be adding new features to rofi going forward in Regolith 2.x (although we still support users using rofi rather than ilia)

![image](https://user-images.githubusercontent.com/49683/181863008-ea914f27-3233-47e8-9cb0-61932da2cfa3.png)
