### ISSUE TITLE
Looking for some support to install Regolith on Kali Linux.

### ISSUE THREAD

**Issue by shamb0** [regolith-linux/regolith-desktop#292]
Hi,

Looking for some support to install Regolith on Kali Linux.

Followed below two guides, but doesn't help ...

> - [Installation | Regolith](https://regolith-linux.org/docs/getting-started/install/)

> - [Installing Regolith for Kali - Remco Verhoef - Medium](https://medium.com/@remco_verhoef/installing-regolith-for-kali-e4152c446cdf)

**Comment by kgilmer** [comment]
Hi @shamb0 , I don't use Kali myself so cannot help you.  But, you may have better luck finding help if you give details as to what is not working for you.

**Comment by phuncmain** [comment]
Hi @shamb0, where exactly are you getting stuck in the process? Both the article you referenced (from Medium) and the [official Debian wiki](https://wiki.debian.org/CreatePackageFromPPA) should cover most of your bases. Furthermore, Kali also has solid documentation on packaging in their [docs](https://www.kali.org/docs/development/intro-to-packaging-example/) also.

**Comment by shamb0** [comment]
Plz kindly ignore the request, Thanks
