### ISSUE TITLE
Unthemed notifications on 1.3

### ISSUE THREAD

**Issue by SteadBytes** [regolith-linux/regolith-desktop#297]
Notification popups do not follow the theme set by `regolith-look` (or any theme/styling AFAICT). Here's an example using `notify-send` to force a notification, but all system notifications look the same:

![Screenshot from 2020-03-28 10-39-28](https://user-images.githubusercontent.com/14834132/77821236-753ae280-70e0-11ea-8cbf-3c1801a5a66c.png)

Currently on latest `regolith-desktop` package from `release` PPA:
```
$ apt show regolith-desktop
Package: regolith-desktop
Version: 2.49-1ubuntu1~ppa1
Priority: optional
Section: x11
Maintainer: Ken Gilmer <kgilmer@gmail.com>
Installed-Size: 10.2 kB
Depends: gnome-control-center, gnome-flashback, gnome-screensaver, gnome-settings-daemon, i3-gaps-wm, i3-snapshot, i3xrocks, nautilus, regolith-compositor-compton-glx | regolith-compositor, regolith-gnome-flashback, regolith-i3-gaps-config, regolith-i3xrocks-config, regolith-look-cahuella, regolith-st, regolith-styles, rofi, software-properties-gtk, unclutter-xfixes, update-manager, xrescat
Download-Size: 3,580 B
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/regolith-linux/release/ubuntu eoan/main amd64 Packages
Description: Regolith Desktop
 This package provides dependencies on top of Ubuntu to install the Regolith
 Desktop Environment.
```

**Comment by kgilmer** [comment]
Hi @SteadBytes , at this time Regolith only themes/supports the Rofication notification system. It looks like you've got dunst or another notification system running.  Work is currently on-going to enable "modularization" of notification backends but at this time it's not technically possible to change between them via the package manager and must be done manually.

If you're interested in contributing the look theme info for dunst or another notification system, that would be great!

**Comment by SteadBytes** [comment]
Thanks for the info! This install has regolith-desktop installed on top of Pop!_OS so it's likely that.

if I get a chance I'll have a look into it! :+1:
