### ISSUE TITLE
Keybinding Helper is Blank after clean 19.10 is updated

### ISSUE THREAD

**Issue by mkellyxp** [regolith-linux/regolith-desktop#298]
Installed regolith-19.10.0-R1.3-desktop-amd64.iso from scratch.  On first boot, the Keybinding helper worked great.  However, after I ran the default Ubuntu updates and reboot, they now show as blank.

I'm just learning i3, so I miss those greatly!

![IMG_8356](https://user-images.githubusercontent.com/6528226/77830631-0f058e00-70e7-11ea-84c9-2c455364d982.jpeg)

**Comment by kgilmer** [comment]
Hi @mkellyxp , what does `i3 --moreversion` say?

**Comment by mkellyxp** [comment]
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 1725)abort…)
Loaded i3 config: /home/mkelly/.config/regolith/i3/config (Last modified: Sat 28 Mar 2020 10:46:10 AM PDT, 7236 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**Comment by kgilmer** [comment]
Ok, so the reason the keybinding are blank is because now they come from the i3 config file instead of being hardcoded, but because you have your own copy of the i3 file, there is no shortcuts in the new format.  The quickest way of fixing the issue is to move `~/.config/regolith/i3/config` to `~/.config/regolith/i3/config-backup` and then log back in.  After verifying that the shortcuts now work, you'll need to re-integrate your customizations into your i3 config file.

**Comment by mkellyxp** [comment]
AHhh that makes sense, thank you.  All I did was put the bar up top.  (guilty MacOS user here).  I noticed that the new config had a position in there with a variable.  Should I be making my bar position edit somewhere else?

**Comment by kgilmer** [comment]
If you are running the latest version (R1.3.1) you can use Xresource overrides.  You just specify the Xresource values you wish to change and put them in the file `~/.config/regolith/Xresources`.  The keys defined by Regolith are documented here: https://regolith-linux.org/docs/reference/xresources/

Specifically for the bar, you would add this line to `~/.config/regolith/Xresources`:
```
i3-wm.bar.position: top
```

**Comment by kgilmer** [comment]
Docs for Xresource overrides: https://regolith-linux.org/docs/howto/override-xres/

**Comment by mkellyxp** [comment]
Brilliant. Thank you. That seems like a much cleaner way to do it. I'll do that from now on. 

This issue is considered closed.

**Comment by kgilmer** [comment]
You're very welcome @mkellyxp .  I always love feedback, both for the good things and the bad.

**Comment by mkellyxp** [comment]
I've been wanting to try i3 for a while but always felt like too much friction to get started. This got me in, and I love it. 

My only issue is that I'm on a laptop with 4gigs of ram and gnome proper isn't exactly light on resources. I was going to try and install as a session with mint to see if that lightens the load a bit. Hoping because it's all GTK, it'll be an easy move over.

**Comment by kgilmer** [comment]
The biggest improvement I have found regarding resource usage is to switch from gdm3 to lightdm as the display manager.  In fact, Regolith 1.4 ISO install will utilize this approach.  gdm3 depends on gnome-shell, and all of it's dependencies, however Regolith doesn't use it.  As is, gdm3 loads gnome-shell, evolution-data*, and others into RAM but this is unnecessary.  In my tests I save 200-300Mb of RAM on cold start simply by changing to lightdm.  I will be providing a howto for those that installed via PPA once 1.4 is released.

**Comment by mkellyxp** [comment]
That sounds incredible.. I had a feeling there was too gnome shell flying around in the processes.  Looking forward to it.  I'm really enjoying this spin of i3 for sure.  Really maximizes my smaller screen and speeds up workflow.  I even installed tiling on my mac now..

Let me know if you ever want me to test something out.  And if you ever need anything in the web development angle, let me know.  That's my day job.
