### ISSUE TITLE
Change language after pressing Super+Space

### ISSUE THREAD

**Issue by GiorgChr** [regolith-linux/regolith-desktop#299]
I use two languages on my laptop, Greek and English(US) and i change between them by pressing `Shift+Alt`. However when i enable the Application Search I cannot change language. this is a problem for me because i usually type in greek.

**Comment by nvoronkin** [comment]
+1
I have same problem, languages English and Russian,  key for switch - Caps

**Comment by kgilmer** [comment]
I believe this is the same issue: https://github.com/regolith-linux/regolith-rofi-config/issues/1

**Comment by kgilmer** [comment]
This may also be related: https://github.com/davatorium/rofi/issues/263

I suggest opening an issue against the [Rofi project](https://github.com/davatorium/rofi), as (from my understanding of the issue), Rofi needs to be able to switch languages while the dialog has focus.  Please let me know if I've mistaken the issue.  In searching I did not find any option or other mention of this issue.

**Comment by kgilmer** [comment]
A solution to this issue was found by Mohamed Gritli reported in slack:

```
I found the solution finally, after a long time of re-search
bindsym $mod+Shift+Return exec --no-startup-id "setxkbmap -layout us -option grp:alt_shift_toggle; rofi -show drun; setxkbmap -layout us,ara -option grp:alt_shift_toggle"
```

Kindly re-open if this fix does not resolve the issue.
