### ISSUE TITLE
Status bar icons not working on 19.10 iso version

### ISSUE THREAD

**Issue by pwklein** [regolith-linux/regolith-desktop#300]
Hi,

I freshly installed the Ubuntu 19.10 iso version and there seems to be a problem with the statur bar icons which are not working. Maybe you have some insights?

Best
pwk
![Screenshot from 2020-03-31 01-19-34](https://user-images.githubusercontent.com/59847153/77970998-e8657400-72ed-11ea-8676-50e48c60b3b1.png)

**Comment by kgilmer** [comment]
Hi @pwklein , odd.  I notice that the bar's on the top so you've done some customization.  You can troubleshoot the font issue by running one of the blocks on the command-line and observing the output, for example:
```bash
$ /usr/share/i3xrocks/memory
<span color="#D8DEE9"></span><span font_desc="Source Code Pro Medium 13" color="#E5E9F0"> 26.5G</span>
```

Also, what do you get for `$ apt list --installed | grep material` and `$ apt list --installed | grep awesome`?

**Comment by pwklein** [comment]
Hi @kgilmer, 
thanks for your message. Yes you are right, I did some customization. I actually did this before on the ubuntu 18.04 ppa version. Sorry - I should probably have mentioned that before. The customization was working before, now after transporting the config files to the 19.10 iso version, the status bar icons are not working anymore. I just deactivated my customizations and the 19.10 iso version seems to work fine out of the box. That means that my 18.04 ppa config files are somewhat not compatible to 19.10 iso. Do you have any idea where the break could occur?

best 
pwk

**Comment by kgilmer** [comment]
The configuration files change quite a bit from version to version.  I'm guessing that you may have had 1.3 on Ubuntu 18.04 and now we're on 1.3.1.  If you're able to just diff the files, I bet it will be easy to spot the differences.  Note that changes are spread across several files but all confined to `/etc/regolith`. 

With every release I try to get closer to the place where updates don't break custom configs, but it's a journey...

**Comment by pwklein** [comment]
So I was able to find a workaround without having to give up or change my previous config files. 
I also made customizations the color scheme (nord) before as well. To this end I followed the example given here: https://github.com/regolith-linux/regolith-desktop/wiki/Customize (cf 'Xresources example'), and therefore pointed the root file  `~/.Xresources-regolith` to the theme in `~/.Xresouces.d` where I made my changes to it. Now, when I moved to Ubuntu 19.10 and used my config files, the nord theme was not istalled by default. So now there is somewhere, some file other than .Xresources-regolith (the root file) that points to the theme in `/etc/regolith/styles/nord` - which is however not installed. 
That means for me: installing nord via `sudo apt install regolith-look-nord` solved the problem.

Edit: rofi was also not working before installing nord to `/etc/...`. The reasons for that seems to me that the color file in the nord directory calls the rofi-theme from `/etc/regolith/styles/nord/rofi.rasi` (again, which did not exist by default on my new install)

**Comment by kgilmer** [comment]
I see.  Nord was the default theme that was installed in Regolith 1.2.  In 1.3 this moved to Cahuella.  So, your new 1.3-based Regolith does not have the Nord styles installed by default.  Your 1.2 based config files were referencing files that were not locally installed.  But, it seems that you've got that figured out now.

Thanks for all the details in reporting your solution!
