### ISSUE TITLE
Rofication blocket

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-desktop#302]
The Rofication blocket is very close to the tray Icon. I think there should be more distance between them like the other blockets.

![image](https://user-images.githubusercontent.com/13016644/78282186-79e90780-74e1-11ea-8ab7-ac0d4bc44344.png)

**Comment by kgilmer** [comment]
I think for this you can add a spacer blocklet at the end.

**Comment by cheginit** [comment]
Thanks, fixed it.
