### ISSUE TITLE
Remontoire crashed on 20.04/unstable

### ISSUE THREAD

**Issue by cjohnston1158** [regolith-linux/regolith-desktop#304]
After logging in remontoire crashed. Uploading crash file.
[_usr_bin_remontoire.1000.crash.zip](https://github.com/regolith-linux/regolith-desktop/files/4430468/_usr_bin_remontoire.1000.crash.zip)

**Comment by kgilmer** [comment]
hi @cjohnston1158 I've updated the version of Remontoire for 20.04.  Can you update to version 1.3.1 and kindly try again?

**Comment by cjohnston1158** [comment]
Seems to be running fine on 1.3.1
