### ISSUE TITLE
Hide/Disable title bar buttons on CSD apps (like control center; solution below)

### ISSUE THREAD

**Issue by SkyyySi** [regolith-linux/regolith-desktop#305]
I think that the window controls (close, minimize and maximize) should be disabled by default, as they don't really serve a purpose on i3 anyways (except maybe for the close button, but it still make the user experience unnecessarily inconsistent). On non-gnome/non-dconf desktops (like KDE plasma), you can do this via the `~/.config/gtk-3.0/settings.ini` file (by adding the line `gtk-decoration-layout=:`), but since regolith uses gnome and thus dconf, you can do this by running `gsettings set org.gnome.desktop.wm.preferences button-layout :` from the command line. It is also possible to show the appmenu (in gnome 3 it is, or at least was, in the top panel) and the menu (shows the window's icon; usually on the very left of a window's title bar, like on KDE plasma or Window) by instead running `gsettings set org.gnome.desktop.wm.preferences button-layout menu:appmenu`. Everything before the : will be on the left, everything behind on the right. Oh, and this ofc. also applys to the settings.ini :)

**Comment by kgilmer** [comment]
Perfect, thank you for the detailed description @SkyyySi !  I will use this in R1.4.
