### ISSUE TITLE
Spotify Window turn white

### ISSUE THREAD

**Issue by malmalia** [regolith-linux/regolith-desktop#307]
Hi! Spotify Window on my Laptop turn white when I move to other workspace, when I start the spotify, the window display normal. After turn white, there's no way to turn the window normal except restart the spotify.

![WbvMnEnC](https://user-images.githubusercontent.com/44871724/78620998-a9b25980-78ab-11ea-9245-ab3e090e6c08.jpg)

**Comment by kgilmer** [comment]
Hi @malmalia , thanks for creating this issue.  My first guess would be to see if this is related to the Compton compositor.  Can you try installing another one (either none, or xcompmgr) and see if it causes a difference?

https://regolith-linux.org/docs/customize/compositors/

**Comment by malmalia** [comment]
Ok It's fixed after Installing xcompmgr and regolith-compositor-xcompmgr. Thanks for your responses!
