### ISSUE TITLE
system tray icons not showing

### ISSUE THREAD

**Issue by Afsalmc** [regolith-linux/regolith-desktop#308]
Tray icons are not showing in the bottom bar . Changing tray_output to primary in i3 config files didnt help .strangly Tray icons appears sometimes after logout is clicked .

**Comment by Afsalmc** [comment]
I can confirm that the telegram tray icon starts appearing after clicking logout .

**Comment by kgilmer** [comment]
Other users have reported issues when Regolith is installed on variants of Ubuntu such as MATE or Zorin.  Please see this issue for details and possible solution: https://github.com/regolith-linux/regolith-desktop/issues/181

**Comment by Afsalmc** [comment]
okey , So killing all related process to indicater-application give me system tray icons back .
**uninstalling package indicator-application is the permanent fix .**
`sudo apt remove indicator-application`
Solved the issue .

**Comment by p3k** [comment]
could this either be added to the documentation or be made a requirement in the installation process, i.e `indicator-application` would be automatically removed? @kgilmer
