### ISSUE TITLE
An issue with i3-gnome-flashback and GNOME 3.36 (tip for future releases, not current ones!)

### ISSUE THREAD

**Issue by SkyyySi** [regolith-linux/regolith-desktop#309]
This is not a current problem for regolith (but for people like me who run bleeding edge distros like Arch Linux), but with the release of Ubuntu 20.04, this might become one, so I figured I might as well point it out here. Will probably be fixed, but just in case it does not: The GNOME devs have made a change to how the desktop is rendered on gnome-flashback, it is no longer done by Nautilus (as far as I understand, I am not a developer ;) ). This means that you have to use the following workaround to get gnome to render the wallpaper and not to show desktop icons (in a window, not the background which would be fine): https://github.com/deuill/i3-gnome-flashback/issues/8
Though you guys probably knew this already :)

**Comment by SkyyySi** [comment]
My bad, this has already been fixed, gonna close this :D

**Comment by kgilmer** [comment]
Not at all, thanks for bringing it up!  I did in fact (last night? they all seem to blend together these days) just make this change for ubuntu 20.04 support, but was unaware of the screensaver change.  Thanks for bringing it up, very helpful @SkyyySi !
