### ISSUE TITLE
Try out the nord color theme, see how it compares to Solarized

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#31]
https://www.nordtheme.com/

**Comment by kgilmer** [comment]
Example: https://www.reddit.com/r/unixporn/comments/c15h91/i3_my_first_nordish_rice/

**Comment by MDutro** [comment]
Rookie question - how do I change the theme to try it out?

**Comment by leosunmo** [comment]
First of all, thank you so much for your work here @kgilmer , I'm a massive fan!

This is how I applied the Nord theme to my Regolith installation on top of Ubuntu 19.04 (not LiveCD installation).

#### Desktop theme: https://www.gnome-look.org/p/1267246/
Just download the files, put them in `/usr/share/themes` (probably requires that you use `sudo`) and run the two commands recommended on the page.

#### Terminal theme: https://github.com/arcticicestudio/nord-alacritty
I replaced the default terminal `st` with  Alacritty by installing it and replacing the `Mod + Enter` command in the i3 config (` ~/.config/i3-regolith/config`). Then I just copy-pasted the `nord-alacritty` theme in to the config at `~/.config/alacritty/alacritty.yml`.

---

I haven't modified anything else as it's pretty close to the Nord theme as it is, so for example the Workspace icon colours and the bottom bar (can't remember what that's called) is the default colour still, and it looks great.

Here's some quick screenshots. Nothing as fancy as on /r/unixporn, but very functional.

![Screenshot from 2019-06-19 09-12-19](https://user-images.githubusercontent.com/13341934/59720325-a98c9300-9272-11e9-80ae-428856ab071f.png)


![Screenshot from 2019-06-19 09-15-14](https://user-images.githubusercontent.com/13341934/59720359-c3c67100-9272-11e9-8cff-2983e71b4a3c.png)

**Comment by leosunmo** [comment]
Oh, and Slack as well, if you use that.
https://github.com/arcticicestudio/nord-slack

**Comment by MDutro** [comment]
Thank you for the instructions. I appreciate it!

**Comment by kgilmer** [comment]
:astonished: Very cool @leosunmo !  Thanks for the screenshots.  It does feel very different than Solarized.  It's certainly something I'd like to make easier for users to configure.  Work is underway to consolidate all of the colors, but at this point there are several places where they need to be changed.  This issue is tracking that effort:

https://github.com/regolith-linux/regolith-desktop/issues/24

If you'd like to change the bar colors, have a look at the file `~./config/i3-regolith/config`.  You'll see Solarized colors in here.  The [i3 User Guide](https://i3wm.org/docs/userguide.html#_changing_colors) gives details of how all the colors can be configured.  Or, you can wait until it's all in Xresources and then it should be much simpler.  If you're interested in committing the configuration for Nord when #24 is done, let me know.  :smile:

**Comment by leosunmo** [comment]
Thanks for the links, I'll take some time and properly colour my i3bar and i3blocks (a lot of default colours there). I'll try to come up with a proper overarching Nord theme and help with #24 .

**Comment by leosunmo** [comment]
Initial Nord theme for bar:
```
# Configure the bar
bar {
  font pango:Source Code Pro Medium 13
  separator_symbol " "
  status_command i3blocks
  tray_output none

  # Nord theme
  colors {
    background $nord0
    statusline $nord11

    separator  $nord9
#                      BORDER  BACKGROUND TEXT
    focused_workspace  $nord3  $nord3     $nord6
    active_workspace   $nord3  $nord2     $nord6
    inactive_workspace $nord1  $nord1     $nord4
    urgent_workspace   $nord1  $nord12    $nord6
  }
}
```

Nord color variables according to their docs:
```
# Nord theme
set $nord0   #2E3440
set $nord1   #3B4252
set $nord2   #434C5E
set $nord3   #4C566A
set $nord4   #D8DEE9
set $nord5   #E5E9F0
set $nord6   #ECEFF4
set $nord7   #8FBCBB
set $nord8   #88C0D0
set $nord9   #81A1C1
set $nord10  #5E81AC
set $nord11  #BF616A
set $nord12  #D08770
set $nord13  #EBCB8B
set $nord14  #A3BE8C
set $nord15  #B48EAD
```

**Comment by kgilmer** [comment]
Another theme: https://github.com/morhetz/gruvbox

**Comment by kgilmer** [comment]
Nord and Gruvbox color themes are now shipped with Regolith.  A Nord (Nordic) GTK theme is available in the regolith PPA.  To install it: `sudo apt install nordic`.
