### ISSUE TITLE
vertical/horizontal split in new ppa

### ISSUE THREAD

**Issue by funkythings** [regolith-linux/regolith-desktop#311]
Hi, I can't figure out how the switch to vertical/horizontal opening mode since I reinstall regolith with new new ppa, and I can't seem to find it in the config file. I remember there was a keybinding, after which every window I opened opened "under" the current (horizontal) and vise versa. Could you help me out here? Thanks!

**Comment by umamiMike** [comment]
Since this is the first thing that came up for my issue but you opened then closed the issue with no comment.  Why did you close it?  What was your solution?

**Comment by juliangaal** [comment]
It's <modifier key> + <backspace>
