### ISSUE TITLE
terminal colors are not good for htop in default mirage ayu theme

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#312]
![](https://files.slack.com/files-pri/TLS2Y1W3B-F011QHZKQBE/image.png)

**Comment by kgilmer** [comment]
![image](https://user-images.githubusercontent.com/49683/79013776-47ad5a80-7b1e-11ea-819e-c6a7d509a554.png)

**Comment by agoose77** [comment]
Here's my implementation using alacritty:
https://gist.github.com/agoose77/14f94d07847c189a13b7d1d3c1b53cfe

![image](https://user-images.githubusercontent.com/1248413/79552387-dc6e0600-8092-11ea-82a7-142fbf7178e4.png)

**Comment by kgilmer** [comment]
Nice...maybe we need to package alacritty and other commonly used terminals...  Here is what mirage ayu regolith (renamed to lascaille) looks like in gnome-terminal:

![image](https://user-images.githubusercontent.com/49683/79643497-09382100-8158-11ea-8736-a54ffcb29cd2.png)
