### ISSUE TITLE
Reinstall Issues on Focal Fossa

### ISSUE THREAD

**Issue by jfrcom** [regolith-linux/regolith-desktop#314]
I'm on Ubuntu 20.04 and had `regolith-desktop` (unstable) installed. However I had changed some stuff in the `/etc/regolith` directory so I wanted to do a fresh install. I've followed the [reinstallation](https://regolith-linux.org/docs/getting-started/install/#reinstallation) instructions and also removed all config files. After reinstalling `regolith-desktop` and then logging in it just logs me out immediately. I've checked `/etc/regolith` and it has all the folders but they are empty. 
I've also tried to reinstall `gnome-flashback` and then `regolith-desktop`.
I'm not sure what to do anymore.

I'd appreciate your help as I love regolith but don't want to reinstall my OS.

**Comment by kgilmer** [comment]
Hi @jfrcom , we can get you fixed up.  When you removed the packages did you use `uninstall` or `purge`?  If the former than re-install and try the latter.  Then, just for good measure `$ sudo rm -rf /etc/regolith /usr/share/regolith`.  Run `apt list --installed | grep regolith` and insure no regolith packages are still installed, then follow the directions to install Regolith via PPA.

**Comment by jfrcom** [comment]
Hi @kgilmer, it finally worked. I just had to remove `/usr/share/i3xrocks`. 
Thank you so much for your quick response and the great DE, keep up the good work!
