### ISSUE TITLE
Installing regolith on Ubuntu 20.04 only shows notifications in status bar

### ISSUE THREAD

**Issue by stefanhgm** [regolith-linux/regolith-desktop#316]
I installed regolith from the PPA on Ubuntu 19.10 which worked nicely and gave me a rich status bar at the bottom of the screen.

Recently, I upgraded to Ubuntu 20.04 with a fresh install and reinstalled regolith from `ppa:regolith-linux/unstable`. Everything went fine except that the status bar at the bottom only contains notifications. I looked into the configuration of i3xrocks in `/etc/regolith/i3xrocks` and it seems it changed to a directory based configuration now. I tried to reuse my old configuration, but there are no i3block scrips in `/usr/share/i3xrocks` anymore, which could be utilized by my configuration file.

Is this the intended behavior? I think the default configuration for the status bar was very nice. And is there a simple way to restore the status bar I had on Ubuntu 19.10? I already looked into https://github.com/regolith-linux/i3xrocks, but this approach seems pretty complicated compared to the nice default configuration I had before.

Thank you!

**Comment by kgilmer** [comment]
Hi @stefanhgm , you're running on unstable (1.4) which isn't really documented yet.  Have a look at [this page for details](https://github.com/regolith-linux/website/blob/R1.4/content/en/docs/Getting%20started/configuration.md#status-bar-indicators), but in essence you just install the blocks you want, for example `$ sudo apt install i3xrocks-memory i3xrocks-time` and `$ apt list | grep i3xrocks-` to list the available blocks.  After installing a block, `<super><shift>r` to refresh your session.

**Comment by stefanhgm** [comment]
Hey @kgilmer, thanks for your fast reply, works like a charm. Great work btw!
