### ISSUE TITLE
Screen Lock / Sleep require i3 restart for secondary monitors (20.04)

### ISSUE THREAD

**Issue by kbknapp** [regolith-linux/regolith-desktop#317]
On Regolith 1.4 on 20.04 I'm noticing a bug where if my computer goes to sleep and log back in, my primary monitor is back up perfectly. However I have two extra monitors (both vertical) which don't appear to "login." What I mean by that is, those two monitors only show the Focal Fossa wallpaper (like the login screen) and no i3status bar at the bottom. I also can't move any windows or cursor over them.

If I restart i3 (mod+shift+r), the i3status bar comes back up and I can then again move windows and workspaces over those monitors.

**Comment by kgilmer** [comment]
Laptop or desktop? Did this work in an earlier version of Regolith?

**Comment by kbknapp** [comment]
Desktop. I haven't had this issue on either Regolith 1.2 or 1.3, same machine.

It's an AMD Vega64 GPU in case that's relevant. I'm only using the Mesa driver though.

**Comment by kgilmer** [comment]
Thanks @kbknapp .  Can you try uninstalling the compositor?  This is the source of most UI problems.  `$ sudo apt install regolith-compositor-none`, log back in and see if the problem persists?

https://regolith-linux.org/docs/customize/compositors/

**Comment by kbknapp** [comment]
Sorry for the late reply. I've installed that package, next time the computer goes to sleep I'll let you know if it that was the culprit or not.

**Comment by kbknapp** [comment]
Same thing still happens.

**Comment by kgilmer** [comment]
Hmm, ok thanks for trying @kbknapp .  I have not seen this issue yet but haven't tested multi-monitor setups in 20.04 yet.  I'll let you know if I find anything that may be of help.

**Comment by kgilmer** [comment]
With 20.04 officially released now, can you update your system @kbknapp  and check if the problem has been resolved?  There was a fix specific to displays.

**Comment by ZawadaZSE** [comment]
I've got the same problem, I've noticed that in journal I get those entries:
gnome-flashback[2084]: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

**Comment by FischerMoseley** [comment]
I have the same issue as well, although I'm using a USB-C adapter to connect to my external display if that's of any importance.

**Comment by kgilmer** [comment]
@ZawadaZSE  and @FischerMoseley can you describe your graphics hardware and driver?

**Comment by ZawadaZSE** [comment]
I'm running on Lenovo ThinkPad T480 with integrated Intel GPU:
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)
	Subsystem: Lenovo UHD Graphics 620
	Kernel driver in use: i915
	Kernel modules: i915
My second screen is connected over HDMI.

I've noticed that this is somehow connected with power-saving. If my screen goes into standby then when I want to unlock it my screen start to blink like they are rearranging. Sometimes I end up with some part of my work screen being visible cause lock screen does not cover it.

**Comment by muktupavels** [comment]
Please test 3.36.3 release of `gnome-flashback`, it has few fixes for screensaver.

**Comment by muktupavels** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-flashback/+bug/1876731

**Comment by markstos** [comment]
I downloaded and installed these packages and it appears to fix it. I'm not sure when they will appear in Ubuntu, but perhaps they can be added to the Regolith PPA.

http://ftp.us.debian.org/debian/pool/main/g/gnome-flashback/gnome-flashback_3.36.3-1_amd64.deb
http://ftp.us.debian.org/debian/pool/main/g/gnome-flashback/gnome-flashback-common_3.36.3-1_all.deb

To test, after installed I logged out, logged back in opened an app on an external monitor, put the laptop to sleep, woke it back up and tested that I could still see and use the app.

**Comment by moritzheiber** [comment]
They won't be added to the PPA because they will become a regular update in the near future which you can obtain through the `focal-updates` channel.

**Comment by moritzheiber** [comment]
@markstos Since your issue is resolved with the `gnome-flashback` update, can we close this bug?

**Comment by markstos** [comment]
Yes.

**Comment by moritzheiber** [comment]
I'm glad we could sort this out, enjoy Regolith!
