### ISSUE TITLE
Fixing a corrupt Regolith install ubuntu 18.04

### ISSUE THREAD

**Issue by williamgrimes** [regolith-linux/regolith-desktop#318]
When trying to launch an application with `<super> Space` I started getting this error message:

```
Failed to open theme ... regolith-theme.rasi
Error: No such file or directory
```
See: https://github.com/regolith-linux/regolith-desktop/issues/170

I've tried removing the configs at `~/.config/regolith` and `~/.Xresources`, that did not solve, then I upgraded packages with `sudo apt update && sudo apt upgrade`.

Then when I logged back in this other issue started to emerge `Error: Could not parse JSON (lexical error: invalid char in json text.)` started to appear in the bar? So I looked here:

https://github.com/regolith-linux/regolith-desktop/issues/99
and 
https://github.com/regolith-linux/regolith-desktop/wiki/Troubleshooting#after-update-see-could-not-parse-json-in-bar

I tried to fix this but could not so gave up and decided to log into `ubuntu` default session and attempt to purge and reinstall regolith, following this advice 

https://github.com/regolith-linux/regolith-desktop/issues/178#issuecomment-568316987

This did not fix the previous two errors. I'm quite lost as to how to get back to a working version of regolith. 

Also I tried following the advice here to get back to a working version of regolith:
https://regolith-linux.org/docs/getting-started/install/#reinstallation
and here,
https://regolith-linux.org/docs/getting-started/install/#uninstallation-of-regolith-desktop

Help much appreciated, and I love the project by the way.

Thanks

**Comment by williamgrimes** [comment]
Fixed this by removing all regolith ppa and reinstalling the *stable* version

```
sudo add-apt-repository --remove ppa:regolith-linux/release
sudo apt purge regolith-*
sudo apt autoremove
rm -Rf ~/.config/regolith/flags
```

Then: 
```
rm -r ~/.Xresources-regolith
rm -r /etc/apt/regolith
rm -r ~/.config/regolith
```
And reinstall:
```
sudo add-apt-repository ppa:regolith-linux/stable
sudo apt-get install regolith-desktop
```

Not sure exactly what the issue I was having earlier was

**Comment by kgilmer** [comment]
Hi @williamgrimes , sorry I didn't get time to look into your issue but happy to see you got it figured out.  Seems like maybe you had upgraded but were using an older copy of a i3 config or Xresource file.  This is pretty common and we're working to make this sort of error less frequent in newer versions of Regolith.
