### ISSUE TITLE
VLC or OpenGL Video Output Fullscreen Issue

### ISSUE THREAD

**Issue by topherbuckley** [regolith-linux/regolith-desktop#319]
I noticed this a week or so ago for the first time. When playing a video in VLC and going fullscreen, the video, and screen remain black. Audio continues, but video does not appear. If I repeat the same steps in the default Ubuntu desktop, these issues do not exist. After fiddling with the video settings (Preferences->Video->Display->Output) I found only the following to work after a full reset of vlc (close, reopen):
 - XVideo Output (no issue)
 - X11 Video output (no issue)

It looks like the automatic choice would be OpenGL Video Output. 

Checking the /var/log/syslog doesn't show anything around the time of trying to enter fullscreen. 

I also tried with a few different video players:
- VLC (issue using anything but above stated video outputs)
- Firefox Youtube (no issue)
- mpv Media Player (issue, running from terminal states it is also using the openGL output)
- mplayer (no issue. Running from terminal states it is using "[xv]" which I assume to mean XVideo)
- Kylin Video (no issue. Can't figure out which video output it is using from terminal outputs.)

I don't see any other OpenGL related issues on here, and checked whether I had OpenGL installed and running according to [this](https://askubuntu.com/questions/993915/how-can-i-be-sure-opengl-is-working) and don't see any issues. Is anyone else seeing this behavior?

**Comment by kgilmer** [comment]
I have not seen this issue yet @topherbuckley .  I wonder if it's related to your graphics hw/driver?

**Comment by topherbuckley** [comment]
Alright. If I'm the only one experiencing this, I won't pursue it further and just use the workaround previously mentioned. I'm subscribed to the issue, so happy to help debug if others run into the same issue.

**Comment by josiah-roberts** [comment]
@topherbuckley I also have this issue. Can you tell me anything about your hardware config? I'm running Regolith on top of Pop!_OS 20.10, with a GTX 1080 outputting to DisplayPort.

**Comment by topherbuckley** [comment]
@josiah-roberts I'm running it on top of Ubuntu 18.04. No dedicated graphics card on this laptop:

>VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

Curious why you are using regolith on top of Pop!_OS, as it already [appears to have tiling](https://youtu.be/-fltwBKsMY0).

There are some interesting features in that video. I'll have to give it a try. @kgilmer maybe take some ideas from that video for tile orientation/rearrangement (maybe you already have implemented these and I just don't know how to use them in regolith :sweat_smile:

**Comment by josiah-roberts** [comment]
> Curious why you are using regolith on top of Pop!_OS, as it already [appears to have tiling](https://youtu.be/-fltwBKsMY0).

I was not aware of this!
