### ISSUE TITLE
Regolith stopped to work after upgrading to 20.04

### ISSUE THREAD

**Issue by sbacelar** [regolith-linux/regolith-desktop#320]
I upgraded from Ubuntu 18.04 to 20.04. Now `Regolith`stopped to work. Is it possible to install it in 20.04?
I tried but received the message `the repository 'http://ppa.launchpad.net/regolith-linux/release/ubuntu focal Release' does not have a Release file`.

**Comment by kgilmer** [comment]
Hi @sbacelar .  Ubuntu 20.04 hasn't been released yet and there is no official Regolith support.  However if you're interested in helping to test the next release that will include that support, you can switch to `ppa:regolith-linux/unstable` and install regolith-desktop.  There isn't any documentation public yet so it may not be worth your white until there is an official release.

**Comment by pvnieo** [comment]
Dear @kgilmer ! Thanks for your response. Is there a likely release date?

**Comment by PhillipRichdale** [comment]
Wanna help too.
What are the big obstacles you guys expect for an official stable 20.4 release?

**Comment by kgilmer** [comment]
Hi guys, thanks for the offers to help.  Regolith R1.4 on Ubuntu 20.04 has passed general testing, and now there is just the process of finishing up the documentation and doing the release.  You can monitor the #release-plan on slack for granular updates or wait for the mailing list announcement (or twitter) for when it's all done.

**Comment by gilvegliach** [comment]
I'm experiencing a problem with the flashback desktop icons and custom background. Basically if I set the key to false I can't set a custom background anymore (and I have a dull gray one instead). I wrote more on this issue: https://github.com/regolith-linux/regolith-desktop/issues/276

**Comment by kgilmer** [comment]
Closing this, as original issue is 20.04 availability has been addressed.
