### ISSUE TITLE
Screensaver (lock screen) adjustment mode ignored

### ISSUE THREAD

**Issue by agoose77** [regolith-linux/regolith-desktop#321]
Ubuntu 19.10:
```
ii  regolith-compositor-compton-glx            1.0.5-1ubuntu1~ppa1
ii  regolith-desktop                           2.49-1ubuntu1~ppa1
ii  regolith-ftue                              1.0.3-1ubuntu1~ppa1
ii  regolith-gnome-flashback                   2.4.5-1ubuntu1~ppa1
ii  regolith-i3-gaps-config                    2.3.6-1ubuntu1~ppa1
ii  regolith-i3xrocks-config                   2.2.14-1ubuntu1~ppa1
ii  regolith-look-ayu-dark                     2.3.5-1ubuntu1~ppa1
ii  regolith-look-ayu-mirage                   2.3.5-1ubuntu1~ppa1
ii  regolith-look-cahuella                     2.3.5-1ubuntu1~ppa1
ii  regolith-look-nord                         2.3.5-1ubuntu1~ppa1
ii  regolith-look-solarized-dark               2.3.5-1ubuntu1~ppa1
ii  regolith-look-ubuntu                       2.3.5-1ubuntu1~ppa1
ii  regolith-rofication                        1.0.9-1ubuntu1~ppa1
ii  regolith-st                                0.8.2-1ubuntu20ppa5
ii  regolith-styles                            2.3.5-1ubuntu1~ppa1
```

The adjustment mode for the background image appears to be respected, but my screensaver (lockscreen) just repeats the background image on both displays.
I took a little look around the source but I don't see anything specific to regolith, so is this an i3 thing, or something up with gnome?

Thanks!

**Comment by kgilmer** [comment]
Hi @agoose77 , it's actually a gnome-flashback issue.  Regolith does not use "modern gnome" which is gnome-shell but rather a more minimal gnome setup.  In this setup, gnome-screensaver is used as the lockscreen program but it is very old and does not load the wallpaper specified in the control panel.  In Ubuntu 20.04 some work has been done here upstream in gnome-flashback but I have not yet had a chance to see if this particular regression is resolved.

**Comment by agoose77** [comment]
Great, thanks for letting me know!
