### ISSUE TITLE
i3xrocks packages not showing

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#323]
After upgrading to 20.04 and regolith 1.4, I realized how empty my bar was (which is by design). I then installed a few i3xrocks packages (battery, cpu-usage, nm-vpn, time, volume, wifi) but without any success.

Even rebooting the computer is not enough.

**Comment by ploum** [comment]
Here is my /etc/regolith/i3xrocks/conf.d  (which I didn't touch, as far as I can remember)
![Screenshot from 2020-04-16 18-25-15](https://user-images.githubusercontent.com/1233155/79481372-b0f60780-800f-11ea-85e1-c326aaa95708.png)

**Comment by ploum** [comment]
Tried to uninstall every i3xrocks package, including regolith-desktop, to remove all the config files then reinstall i3xrocks and regolith-desktop, writing fresh config files.
Then logged out and logged in.
Now, I don't even have the "?" at the right and the notification counter. The bar is completely empty.
(on a side note, I realise how zen it is to have an empty bar and no notification counter)

**Comment by kgilmer** [comment]
If you're using the default i3, then this is what is being executed to populate the bar:
```
i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d
```

What happens when you run this directly from the command line?

**Comment by ploum** [comment]
the command seems to work well (except that I don't have the local folder)

![Screenshot from 2020-04-20 00-58-33](https://user-images.githubusercontent.com/1233155/79702074-4c9ea680-82a2-11ea-8e77-f264149e8eb3.png)

**Comment by kgilmer** [comment]
Hmm, what does `i3 --moreversion` say?

**Comment by ploum** [comment]
Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.17.1 (2019-08-30) (pid 1825)
Loaded i3 config: /home/ploum/.config/regolith/i3/config (Last modified: ven 10 avr 2020 23:41:36, 822317 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**Comment by ploum** [comment]
Ok, I found the bug. The ~/.config/regolith/config file, created during the upgrade on April 10th, was referencing /etc/regolith/i3xrocks/config which doesn't exist (it's now conf.d).
I simply remove ~/.config/regolith/config and restarted i3. Now, it seems to work.

Not sure something can be done, it's mainly an upgrade issue that may have been caused by upgrading to an alpha version.

**Comment by skostojohn** [comment]
I'm also having trouble with disappearing status indicators.
I tried @ploum 's suggestion of eliminating ~/.config/regolith/config and reloading i3, but it had no effect.

I also ran `i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d` and the output looked good. 

Any ideas for what I can try?  Happy to provide more info if it helps, and thanks in advance!

**Comment by kgilmer** [comment]
Can you send your i3 config file, the response from `i3 --moreversion`, and
`apt list --installed | grep i3xrocks-`?

**Comment by skostojohn** [comment]
Hi Ken,
I think the problem was that I had somehow partially upgraded to the new version.  I am not sure how that happened.  I believe I have completed the upgrade now, and my status indicators are there, except for notifications - not sure why that one is missing.  I am also getting some rofication errors.  

You might recall, I had some problems with this before and had to update `/usr/share/dbus-1/services/org.freedesktop.Notifications.service ` to point to the rofication-daemon.py file, and comment out the line in config that executes rofication-daemon.py.

I've just started troubleshooting but if you have any ideas, let me know.  The errors may be coming from the fact that `rofication-daemon.py` does not seem to be in `/usr/share/rofication` anymore.  I am thinking that if I can find it and point `/usr/share/dbus-1/services/org.freedesktop.Notifications.service` at it, my issues might be resolved.  I also no longer see the line in config that executes `rofication-daemon.py`.

**Comment by skostojohn** [comment]
Spoke too soon.  Logged out/in, and now I have no status indicators, and no keybindings.

![image](https://user-images.githubusercontent.com/2495345/80334558-6db54900-8806-11ea-915f-215b0e2057bd.png)

![image](https://user-images.githubusercontent.com/2495345/80334594-86bdfa00-8806-11ea-8f8a-900afb6cd2a1.png)


[config.txt](https://github.com/regolith-linux/regolith-desktop/files/4537520/config.txt)

Any advice would be appreciated, Ken - I'm pretty lost right now :)

**Comment by skostojohn** [comment]
OK - I'm all set again.

1) I had a bad config file - likely something that didn't get updated by my upgrade.
2) I had to recreate the `/usr/share/dbus-1/services/org.freedesktop.Notifications.service` file, pointing to the new location of rofication-daemon in `/usr/bin`

All seems working now!

**Comment by mstr3336** [comment]
Hi, I've noticed something similar with my own config, mainly that only the workspace number (Given in my regolith config, I think)

```
# i3xrocks config file. Override this for custom status indicators on the bar.
set_from_resource $i3-wm.bar.status_command i3-wm.bar.status_command i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d


# The bar configuration
bar {
  position $i3-wm.bar.position
  font $i3-wm.bar.font
  separator_symbol $i3-wm.bar.separator
  status_command $i3-wm.bar.status_command
  tray_output $i3-wm.bar.trayoutput
  strip_workspace_numbers $i3-wm.bar.stripworkspacenumbers

  colors {
      background $i3-wm.bar.background.color
      statusline $i3-wm.bar.statusline.color
      separator  $i3-wm.bar.separator.color

#                        BORDER  BACKGROUND TEXT
      focused_workspace  $i3-wm.bar.workspace.focused.border.color      $i3-wm.bar.workspace.focused.background.color   $i3-wm.bar.workspace.focused.text.color
      active_workspace   $i3-wm.bar.workspace.active.border.color       $i3-wm.bar.workspace.active.background.color    $i3-wm.bar.workspace.active.text.color
      inactive_workspace $i3-wm.bar.workspace.inactive.border.color     $i3-wm.bar.workspace.inactive.background.color  $i3-wm.bar.workspace.inactive.text.color
      urgent_workspace   $i3-wm.bar.workspace.urgent.border.color       $i3-wm.bar.workspace.urgent.background.color    $i3-wm.bar.workspace.urgent.text.color
  }
}

```

and rotifications seemed to be working.

Following through to `/etc/regolith/i3xrocks/conf.d`:

```bash
cd /etc/regolith/i3xrocks/conf.d
ls
```
```
01_setup  80_rofication
```

```bash
cat 01_setup
```
```
# i3xrocks config file
# # The man page for i3blocks is hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# ... More properties, truncated for documenting in GH issue
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/share/i3xrocks/$BLOCK_NAME
separator_block_width=35
markup=pango
color=xresource:i3xrocks.value.color
label_color=xresource:i3xrocks.label.color
```

Checking the location specified by the global `command` , I see no `/usr/share/i3xrocks`, which, I think, is the source of my problem.

**Comment by mstr3336** [comment]
https://regolith-linux.org/docs/howto/add-remove-blocklets/

Okay, as I understand it, blocklets migrated to separate packages during some upgrade, and weren't re-added by default. 

Installing the blocklets I wanted worked :)

**Comment by kgilmer** [comment]
Yep, that's correct @mstr3336 and happy that you got it fixed up.
