### ISSUE TITLE
[Suggestion] show-desktop-icons on Regolith

### ISSUE THREAD

**Issue by nachovizzo** [regolith-linux/regolith-desktop#325]
First of all, thanks for this amazing project. I started using a few weeks ago and I have nothing to complain about.

Just in case someone else searches for `show-desktop-icons`, I managed to show(yes I know, iI shouldn't) temporally the Desktop icons in the i3wm!

Yes, this will make the icons a window for i3, and that's annoying, but I hooked a keybind to temporally show the desktop icons in i3 (emulating Windows/Ubuntu <Super> + d)

1) Script, in my case is in `"$HOME/scripts/config/show_desktop.sh`
```sh
#!/bin/bash
# @file      show_desktop.sh
# @author    Ignacio Vizzo     [ivizzo@uni-bonn.de]
#
# Copyright (c) 2019 Ignacio Vizzo, all rights reserved

desktop_is_shown=$(gsettings get org.gnome.desktop.background show-desktop-icons)

if $desktop_is_shown; then
  gsettings set org.gnome.desktop.background show-desktop-icons false
else
  gsettings set org.gnome.desktop.background show-desktop-icons true
fi
```

2) Add this to your i3config file (use whatever key you like), keep in mind this conflicts with the default Display settings on regolith
```sh
# Show desktop
 bindsym $mod+d exec "$HOME/scripts/config/show_desktop.sh"

```

3) That's it, this is the result
![image](https://user-images.githubusercontent.com/21349875/79629550-0c63ea80-8121-11ea-8783-adb59fc16cf3.png)

Some comments:
 - It will be treated as a window, so, as soon as you open something, it's not going to go away, so that's when you should press <Super> + d to hide it
- I know newer versions of Gnome might conflict with this little hack, so I'm pretty sure that it won't be compatible in 20.04
- You can even create folders, open a terminal and change the background once the icons are being displayed! 
- Given the fact that it's just another window, it's only going to show up on the current workspace(and I actually like that)

Hope this helps any other geek searching for a similar solution!

**Comment by kgilmer** [comment]
Interesting, thanks for sharing this @nachovizzo !  For 20.04 I believe this will continue to work but the dconf path has changed to this: https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L67

If you would like to create a HowTo for others that may be interested in this, feel free to create a PR here: https://github.com/regolith-linux/website  Here would be an existing HowTo you could base yours from: https://github.com/regolith-linux/website/blob/master/content/en/docs/HowTo/change-workspace-icons.md
