### ISSUE TITLE
Make "software-properties-gtk" a recommandation of regolith-desktop

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#326]
Same remark as #322 : software-properties-gtk is currently a dependancy of regolith-desktop. I think it should be a recommandation instead.

(Unless, of course, I'm missing something critical)

**Comment by kgilmer** [comment]
Yep, I think it should be ok. 

https://github.com/regolith-linux/regolith-desktop/commit/6903cad67edad5810fc952902132192c4da31d89
