### ISSUE TITLE
help window covered by other windows

### ISSUE THREAD

**Issue by stephengeorgewest** [regolith-linux/regolith-desktop#33]
Being an i3 noob, the help box is helpful, but it gets covered up by the other windows. I can see the bottom of it in the gap when I have multiple windows open. I fiddled with ```/etc/xdg/conky/config``` and got it to display above, but it still wasn't helpful since my main screen is only 768px tall (crummy laptop), and cuts off the bottom (I guess that's how I noticed it in the gap...). I got it to display as it's own window to be moved around with Super-Shift-Arrows, but I still can't scroll down to see below "Lock Screen". I can plug in a decent monitor, then move it over there, but by now I've got it open in a text editor and can scroll in there, so it is kind of a moot point now.

**Comment by kgilmer** [comment]
Hi @stephengeorgewest , sorry to hear about your struggles with Regolith with the lower resolution.  I have not tested it out at all.  What would your ideal experience w/ the keybinding cheatsheet be? 

1. As-is but fits in VGA
2. Fits in VGA but is always on top
3. Content available elsewhere, such as web page.
4. Something else

**Comment by kgilmer** [comment]
Also, can you kindly share your conky edit that puts it above the other windows?

**Comment by stephengeorgewest** [comment]
I think the important parts would be make it scroll-able, so it fits any screen, but from my searches, conky doesn't seem to do scrolling. Also, making it a regular window makes it so the new user can practice with the help window. I think opening the website to a "quick reference page" would do all that, but the website theme doesn't match (maybe that is a good thing so we can figure out where the window ends). Also if it were on the website I could pull it up on my phone or some other computer for reference.

I commented out ```own_window_type override``` on line 13, and I can move it around like all the other windows. It still cuts off the bottom, I did some other things with ```own_window_hints``` and ```above```, but I don't remember what they were.

**Comment by kgilmer** [comment]
Good idea to all all keybindings to a reference page on the site.  I like your suggestion about keeping Conky in the foreground however that also has usability impact as new users maybe troubled that they cannot see their window because of the overlap.  As tiling window managers generally try to avoid this overlap, I'd like to explore other options for making these shortcuts more accessible to new users.

I would also like to restructure the shortcuts in some way that make them more easily viewable with a vertical resolution of 768.  I'm not sure yet how best to do this.

**Comment by PickingUpPieces** [comment]
I like the idea to have it always on top if you need it, since you can close it with the key binding really quick.
I think this issue could be resolved with #16 , with different options (Show/show not on startup; Always "highest layer" check option)

**Comment by kgilmer** [comment]
I agree that having it on top when you need it is far better than in the background where you cannot see it.  I've been thinking of adding a wallpaper that embeds shortcuts and other "first timer" information.  This could relegate the Conky dialog to only be called up with a hotkey, and have it be a floating window that is above others.
