### ISSUE TITLE
appearance is changed every reboot

### ISSUE THREAD

**Issue by verajosemanuel** [regolith-linux/regolith-desktop#330]
I like the Sweet Dark/Sweet Purple theme for windows and icons. Set via "Tweaks" every time I boot the themes are "paper" again,

How to make it permanent?

**Comment by kgilmer** [comment]
Hi @verajosemanuel :smile: .  To permanently change the theme in Regolith you want to set a Look, which controls colors, GTK theme, etc..  You can learn more about it here: https://regolith-linux.org/docs/customize/look/

**Comment by verajosemanuel** [comment]
Hi @kgilmer , not the theme in regolith but in applications. For instance, If I change icons and background for File manager (al windows buttons anf backgrounds in fact) using gnome tweaks,  the moment I reboot, it's set back to "Paper" icons again.

**Comment by kgilmer** [comment]
Ah, you need to specify the gtk theme and icon theme via Xresources.  

```bash
$ xrdb -query | grep theme
gnome.gtk.theme:	Ayu-Mirage-Dark
gnome.icon.theme:	Moka
```

See here to learn how to add an override: https://regolith-linux.org/docs/howto/override-xres/

**Comment by verajosemanuel** [comment]
❯  ~  ls ~/.config/regolith/Xresources
ls: cannot access '/home/jose/.config/regolith/Xresources': No such file or directory


should I create it?

**Comment by verajosemanuel** [comment]
After latest ubuntu upgrade, I'm back to this issue. Every reboot icon themes are changed to "paper" style. Overrided Xresources as your suggestion to no avail. Any other hint?
