### ISSUE TITLE
Stacked windows

### ISSUE THREAD

**Issue by timjrobinson** [regolith-linux/regolith-desktop#331]
Is there a way to get stacked windows like in i3? If not are there any plans to implement this?

I really miss the ability to stack windows. I'm using tabbed at the moment but I have multiple monitors and don't like how to move focus to another monitor I have to navigate through all the tabs on my current monitor first, because they are tabbed horizontally instead of stacked vertically.

**Comment by timjrobinson** [comment]
Nevermind, I just realized super + s is working for stacking now. Unsure why it wasn't earlier.

**Comment by timjrobinson** [comment]
This went away again in my 1.4 upgrade and I realized it started working because I added these two lines from my i3 config:

```
## Copied from i3, stacking and split modes.
bindsym $mod+s layout stacking
bindsym $mod+e layout toggle split
```

For future reference for anyone else that wants window stacking like in i3.

**Comment by djvdorp** [comment]
Thanks so much here @timjrobinson ! I was just about to open an issue for this.

Reference in the i3 guide: https://regolith-linux.org/docs/interface/advanced/#i3-wm-layout-mode 

`stacking`
    Only the focused window in the container is displayed. You get a list of windows at the top of the container.

**Comment by Philipp0205** [comment]
Use `bindsym $mod+s layout stacking` with care. It is bound to the sound settings now and binding in the i3 config (~/.config/regolith/i3/config) will create an duplicate binding error.
