### ISSUE TITLE
Use arrow to skip words at VIM

### ISSUE THREAD

**Issue by cunhazera** [regolith-linux/regolith-desktop#333]
I generally use my arrow keys to move between words inside vim, but with Regolith it deletes my code. Can I change at inside regolith config?

**Comment by mmoutenot** [comment]
@cunhazera hey there. I just tested this out with `vim` without any custom `.vimrc` and I'm not seeing any non-default behavior for the arrow keys. Can you check to make sure you don't have a .vimrc defined?

**Comment by cunhazera** [comment]
Yeah, that was the problem! Thank you.
