### ISSUE TITLE
Documentation on using this for Raspberry Pi 4?

### ISSUE THREAD

**Issue by JKSenthil** [regolith-linux/regolith-desktop#334]

**Comment by kgilmer** [comment]
Hi @JKSenthil , yes Rasberry Pi 4 support is available currently in the `ppa:regolith-linux/stable` PPA.  Once 1.4 is released, this change will propogate to `ppa:regolith-linux/release`.  See the website for instructions on how to install Regolith via PPA.

**Comment by kgilmer** [comment]
re-opening to add documentation to the site.
