### ISSUE TITLE
<super> + l is locking the screen rather than navigating to relative window

### ISSUE THREAD

**Issue by NeilsC** [regolith-linux/regolith-desktop#335]
Hi all. Just started using regolith and looks great so far. I'm having an issue navigating between windows. < super > k, < super > j, and < super > h all work properly and allow me to navigate between windows, but when I press < super > l, the screen locks.

**Comment by baldrailers** [comment]
@NeilsC There’s a default keyboard shortcut settings that you can change  to unbind the META-l. You can find it in the Settings app of ubuntu. Hope that helps

**Comment by NeilsC** [comment]
This fixed my issue. Thanks!

**Comment by PabloDinella** [comment]
just a little tip for searchers like me: after re-setting you lock screen shortcut, you need to refresh the session (<super> + shift + r) to make <super> + l work as expected :)
