### ISSUE TITLE
Scrolling while hovering over i3xrocks items opens a window

### ISSUE THREAD

**Issue by grzkv** [regolith-linux/regolith-desktop#336]
Scrolling the mouse wheel while hovering over `i3xrocks` widgets opens corresponding windows. This happens for the time widget and nm widget for me.

I would expect a window to open only when left-clicking.

**Comment by moritzheiber** [comment]
@grzkv We'll have this fixed with the new release :+1:

**Comment by kgilmer** [comment]
This change is building into `unstable` now.
