### ISSUE TITLE
Items on i3 bar are not visible

### ISSUE THREAD

**Issue by lukasfrana** [regolith-linux/regolith-desktop#337]
Hi,
I just installed fresh Ubuntu 20.04 and Regolith, but I cannot see items on the right of bottom bar. I haven't changed any config.

This is how looks right end:
![Screenshot from 2020-04-26 02-05-12](https://user-images.githubusercontent.com/29776261/80293775-a3085b00-8762-11ea-9415-e67eb8c59a2b.png)

Thanks

**Comment by lukasfrana** [comment]
Sorry, my fault. You made changes, but it is in the docs.

**Comment by kgilmer** [comment]
A lot of people are hitting this issue :cry: , please let us know if you have ideas on making it easier for others.

**Comment by lukasfrana** [comment]
I was confused, because you have screenshot on your homepage with a number of blocks installed (and also few images in Visual tour section with older look). Maybe try to put disclaimer about this on the download page, because people are copy pasting the commands from it. 

I must thank you for all the work you did. New version is awesome. I really like new font (it's similar to JetBrains Mono IMO).

**Comment by kgilmer** [comment]
Thanks, I'd forgotten about the screenshots. :facepalm:   Just updated now, thanks.  It **is** actually JetBrains Mono...glad you like it!
