### ISSUE TITLE
Regolith 1.4 upgrade fails on Ubuntu 19.10 (unmet dependencie ... regolith-look-lascaille )

### ISSUE THREAD

**Issue by sorokod** [regolith-linux/regolith-desktop#340]
Following instructions in Upgrades section in https://regolith-linux.org/docs/getting-started/install/ 

	$ sudo apt dist-upgrade
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	You might want to run 'apt --fix-broken install' to correct these.
	The following packages have unmet dependencies.
	 regolith-styles : Depends: regolith-look-lascaille but it is not installed
	E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**Comment by farsil** [comment]
Try `$ sudo apt update` before calling `dist-upgrade`. If it doesn't work, try manually installing `regolith-look-lascaille`.

**Comment by kgilmer** [comment]
I believe this is resolved, as @sorokod opened another issue regarding i3xrocks.  If not, kindly re-open.
