### ISSUE TITLE
No prompt for encryption after reboot

### ISSUE THREAD

**Issue by lukasfrana** [regolith-linux/regolith-desktop#342]
I am using fresh installation of Regolith ISO.

If I perform hard reset (holding power off button for 5 sec), I am able to see a prompt for disk encryption and also `Ubuntu 20.04` test is in the center of the screen.

If I normally reboot system, the text is in the left upper corner and prompt is missing. But I can write my password and hit Enter. So it works even if it's not shown.

**Comment by kgilmer** [comment]
This issue can be fixed by installing the `plymouth-theme-ubuntu-logo` package.

**Comment by kgilmer** [comment]
I have added a similar package to the `regolith-system` package dependencies, so you should get this fix for free once the update makes it's way to the `release` PPA.
