### ISSUE TITLE
Two / Three finger tap on touchpad not supported on R1.4 using Ubunu 20.04

### ISSUE THREAD

**Issue by jsosulski** [regolith-linux/regolith-desktop#343]
Hi, I just installed a fresh Ubuntu 20.04 on my machine and then installed right afterwards the Regolith Desktop 1.4 using your provided ppa.
While in Ubuntu Desktop, I can use two-finger taps / three-finger taps for right / middle click on my XPS 13 (9343) machine, this does not work in Regolith Desktop.

My first suspect was `unclutter` but after deactivating it, I still have the same issues. Do you have any ideas?

Btw.: There are 2 positions in which unclutter is started, I do not know if both are needed. 
1. START_UNCLUTTER is true in /etc/default/unclutter  2
2. In the default i3 config.

**Comment by Miro-Andrin** [comment]
I don't know if this is related, but i also had a problem when configuring my touchpad on my XPS computer on a fresh iso install. For me it was not the multi finger gestures that did not work, but the selection of Natural Scroll.

**Comment by lukasfrana** [comment]
@jsosulski same here. Three finger gesture is not working. I also think that touchpad sensitivity settings is not working.

**Comment by kgilmer** [comment]
I am able to use two-finger scroll, tap to click, and edge scrolling features on 20.04.  I do not see any gesture settings in gnome-control-panel for 3 finger gestures.  Where do you set this?

**Comment by pvnieo** [comment]
In fact, I had the same problem. You simply need to re-activate it from the settings.

**Comment by lukasfrana** [comment]
@pvnieo Where in the settings?

**Comment by pvnieo** [comment]
@lukasfrana  I'm using ubuntu 20.04, so see in "settings/Mouse & Touchpad".
![image](https://user-images.githubusercontent.com/22404728/80381122-bfaaad00-88a0-11ea-8dc6-797ccf3e77d3.png)

**Comment by kgilmer** [comment]
I was able to resolve this issue by removing the package `xserver-xorg-input-synaptics`.  Can anyone here verify if this works for them as well?  I believe it requires a reboot, after performing `sudo apt remove xserver-xorg-input-synaptics`.

**Comment by lukasfrana** [comment]
Yes, it works! Thank you very much.

**Comment by Miro-Andrin** [comment]
> I was able to resolve this issue by removing the package `xserver-xorg-input-synaptics`. Can anyone here verify if this works for them as well? I believe it requires a reboot, after performing `sudo apt remove xserver-xorg-input-synaptics`.

That also solved my natural scrolling issues.

**Comment by jc00ke** [comment]
> I was able to resolve this issue by removing the package `xserver-xorg-input-synaptics`. Can anyone here verify if this works for them as well? I believe it requires a reboot, after performing `sudo apt remove xserver-xorg-input-synaptics`.

Isn't `libinput` the new(-ish) hotness?

**Comment by kgilmer** [comment]
I don't know much about this layer of the OS.  Do you have any links to share @jc00ke ?

**Comment by jc00ke** [comment]
I remember years ago removing the `synaptics` driver and using `libinput` but I don't remember the resources. The [Arch wiki](https://wiki.archlinux.org/index.php/libinput) is a good place to start.

```
» apt list | rg libinput

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libinput-bin/focal,now 1.15.5-1 amd64 [installed,automatic]
```

With `xserver-xorg-input-synaptics` uninstalled and not overriding `libinput-bin` natural scrolling works for me again.

**Comment by kgilmer** [comment]
`xserver-xorg-input-synaptics` removed in Regolith 1.4.1 ISO.
