### ISSUE TITLE
error installing regolith-look-lascaille

### ISSUE THREAD

**Issue by Craskermasker** [regolith-linux/regolith-desktop#346]
Preparing to unpack .../regolith-look-lascaille_2.4.19-1_amd64.deb ...
Unpacking regolith-look-lascaille (2.4.19-1) ...
dpkg: error processing archive /var/cache/apt/archives/regolith-look-lascaille_2.4.19-1_amd64.deb (--unp
ack):
 trying to overwrite '/usr/share/backgrounds/ESP_016895_1525_desktop.jpg', which is also in package rego
lith-assets 1.09-1ubuntu1~ppa1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/regolith-look-lascaille_2.4.19-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Hi after running yesterday's regolith updates, I'm getting this error - is it due to the same background image being referenced from multiple packages?

**Comment by Craskermasker** [comment]
package versions:

regolith-styles:
  Installed: 2.4.19-1
  Candidate: 2.4.19-1
  Version table:
 *** 2.4.19-1 500
        500 http://ppa.launchpad.net/regolith-linux/release/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status

regolith-look-lascaille:
  Installed: (none)
  Candidate: 2.4.19-1
  Version table:
     2.4.19-1 500
        500 http://ppa.launchpad.net/regolith-linux/release/ubuntu eoan/main amd64 Packages

**Comment by kgilmer** [comment]
Hi @Craskermasker , did you run `dist-upgrade`?  I'm not sure why you would be getting this error as the latest versions of these packages do not contain a file conflict.  I suggest you remove regolith-look-cahuella manually w/ `dpkg` and then continue with the upgrade.  Once complete you can re-add the package if you prefer that look over lascaille.

**Comment by Craskermasker** [comment]
fixed by removing packages using:
`sudo dpkg --purge --force-depends regolith-look-lascaille regolith-look-cahuella regolith-styles regolith-assets`
then fixing broken packages using 
`sudo apt --fix-broken install`
