### ISSUE TITLE
Taking screenshot freezes all input

### ISSUE THREAD

**Issue by mmoutenot** [regolith-linux/regolith-desktop#348]
I did not have this issue before upgrading to Focal. Shift+PrtScn previously allowed me to select an area to take a screenshot.

After upgrading, when I take a screenshot of the Chrome browser, keystrokes and mouse input seem to be ignored. Some visual elements on the screen (i.e. time) update but I can't interact with the computer. In each case this has happened (every time I've tried to take a screenshot like this) I've had to hard restart via the power button.

**Comment by kgilmer** [comment]
Hi @mmoutenot , I just tried this quickly on my 20.04 dev machine and didn't encounter any issue.  Perhaps it's video driver related?  Just guessing...

**Comment by mmoutenot** [comment]
I tried it more today. Crazy -- it consistently happens after I select an area overlapping Chrome, but not other applications.

I'll dig in more. I had to switch to lightdm because of flickers caused by the default on some gnome tools (specifically when I selected dropdown menus), maybe related.

These niche graphics bugs are always the most fun :)

**Comment by kgilmer** [comment]
The flickering issue sounds like a compositor problem to me.  Perhaps you've already tried but if not, try installing `regolith-compositor-none` and see if that improves the situation.

**Comment by finnbar** [comment]
I have a similar issue - after taking a second screenshot with Ctrl+Shift+PrintScn, the keyboard locks up with (what I think is) Ctrl+Shift+PrintScn held - if you click a tab in Firefox for example, it will select all tabs between your current one and the selected one.

Example steps that show this breaking on my machine:
1. Log in, open Files.
2. Take a screenshot with Ctrl+Shift+PrintScn
3. Take another screenshot in the same way.
4. Try to click on a file or two. They should both be selected, along with all files between them, as if you have Ctrl+Shift held.

This is on a clean 20.04 machine with `regolith-compositor-none`, with some minimal changes to theming and nothing else. I've got NVIDIA proprietary drivers enabled (GeForce 940M, nvidia-driver-440 package).

**Comment by garrickhutcheson** [comment]
Just to throw my two cents in, I am experiencing a similar bug with using ctrl+shift+printscrn and then attempting to paste images in to discord. I am on the stable branch of regolith on ubuntu 20.04. 
For what its worth I also have an Nvidia graphics card. Mine is a gtx 970 using nvidia driver 435.21. 
Maybe not the most graceful thing but i am still able to access a tty with ctrl+alt f3 to kill my desktop session and log in again, instead of restarting my entire computer.

**Comment by kgilmer** [comment]
Thank you for the detailed bug reports.  I have a machine w/ an nvidia graphics card and will attempt to reproduce.

**Comment by chuahou** [comment]
I experience a similar issue but with less regularity as finnbar and garrickhutcheson. When using screenshot commands that copy to the clipboard:

1. Screenshot to clipboard
1. Ctrl+V to application (tried in Firefox, Telegram, GIMP)
1. **Sometimes**, nothing will happen
1. Attempting to take another screenshot will lead to a state where UI elements will continue to update but no input, keyboard or mouse, will be processed
1. The only input I've managed to get working is Alt+SysRq+(R E I S U B)

Unfortunately this happens irregularly, but what does happen with consistency is that if the paste fails, taking another screenshot definitely leads to the frozen state.

My graphics card is a 1050 Ti using nvidia-driver-440.

**Comment by muktupavels** [comment]
Could be https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/50.

**Comment by chuahou** [comment]
Good find @muktupavels! It does seem like a good match to my issue, if not the
original issue creator's issue.

**Comment by muktupavels** [comment]
Please open bug here - https://bugs.launchpad.net/ubuntu/+source/gnome-flashback. If possible using SRU Template - https://wiki.ubuntu.com/StableReleaseUpdates#SRU_Bug_Template. Fill things that you know, don't worry about other things.

**Comment by muktupavels** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-flashback/+bug/1876731

**Comment by moritzheiber** [comment]
@mmoutenot Could you please try out these upgrade steps: https://github.com/regolith-linux/regolith-desktop/issues/406#issuecomment-629674629 and report back whether it fixes your issue?

**Comment by mmoutenot** [comment]
@moritzheiber Sorry for the delay. I had some long running calculations and couldn't risk a reboot.

I've followed the recommendation in #406 and indeed was able to take a number of consecutive screenshots without issue! Hooray! Closing for now.

![image](https://user-images.githubusercontent.com/339996/82828393-ee577b80-9e7e-11ea-8bce-277d9908bab6.png)
