### ISSUE TITLE
Update notification system docs

### ISSUE THREAD

**Issue by grzkv** [regolith-linux/regolith-desktop#354]
https://regolith-linux.org/docs/howto/replace-notification-system/ does not include instructions for config modification, required restart, and launching `dunst` on i3 start.

I guess the notification system change procedure as described will not work.

**Comment by grzkv** [comment]
I can pick this up.

**Comment by kgilmer** [comment]
Meaning you'll create a PR w/ updated documentation?  If so, yes please!  :smile:

**Comment by grzkv** [comment]
@kgilmer Yes.

**Comment by kgilmer** [comment]
Any update @grzkv ?

**Comment by grzkv** [comment]
I plan to do this update today or tomorrow.

**Comment by kgilmer** [comment]
We had a bug against this page and so updated the docs today.  Feel free to create a PR for any details we may have missed @grzkv :smile:

**Comment by grzkv** [comment]
Thanks!
