### ISSUE TITLE
Problems after removing Synaptics input driver

### ISSUE THREAD

**Issue by mantomas** [regolith-linux/regolith-desktop#357]
After fresh install from ISO (Asus UX360U) I have problem with touchpad. Hotkeys show graphics, but didn't switch on/off. The same in settings (Win+C) - on/off has no effect. After searching, I find removing deprecated driver xserver-xorg-input-synaptics stops blocking libinput from use and touchpad on/off works great.
Don't know what else was Synaptics driver used for (it is important for DE?), but since then, rotating screen in tablet mode freezes the screen in rotated position and pointer does not correspond with screen orientation. I did not test screen rotation before removing that driver, so there is possibility it is related to something else.
Last thing related to input drivers, there is no setting for controlling touchscreen - it is working but cannot be switched off.

**Comment by mantomas** [comment]
I experiment with reinstall the Synaptics driver: after reboot I am able to rotate screen (but pointer position is mapped wrong), also I am able return from lock screen (without synyptics there was no prompt for password input). My touchpad is always on.
Any workaround to leave synaptics driver, but bypass libinput to touchpad (and touch-screen maybe?)?

**Comment by kgilmer** [comment]
Thanks for the details @mantomas , I just learned about the issue with xserver-xorg-input-synaptics and touchpad settings today.  I must have missed it when reading your issue originally.  I will roll a new release without that package installed in the coming weeks.  Regarding your computer, does it have Synaptics touchpad hardware?

**Comment by mantomas** [comment]
Hello @kgilmer  - I'm not sure, what do You mean "Synaptics touchpad hardware"? In terms of manufacturer,
? I don't know how to find it. LSHW does not show touchpad at all.

**Comment by kgilmer** [comment]
I'm guessing it doesn't matter, and that the `xserver-xorg-input-synaptics` package is not needed regardless of hardware.  I just checked my Thinkpad X1 6g and I see:

```bash
$ xinput 
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=11	[slave  pointer  (2)]
⎜   ↳ TPPS/2 Elan TrackPoint                  	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=10	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=13	[slave  keyboard (3)]
```

So it seems that I have a synaptics touchpad but do not use that package.  I'm thinking it's probably fine to leave it uninstalled.

**Comment by mantomas** [comment]
OK, I removed the package. Touchpad functionality is better without it. But then it comes back to display issue - there is no touch-screen settings at all, and I cannot turn off orientation sensor - without synaptics driver, when I accidentally rotate laptop it freezes in rotated position and I must reboot. Maybe it will be good to start new tread about touch-screens/orientation sensors.
I don't know if in Regolith 1.3 is some touchscreen settings, but when I tested it live, that was the reason I decided to install Regolith - rotating screen, proper cursor orientation, all worked great. I do not use tablet mode often, but sometimes its great just for reading documents or showing photos.
My xinput output is here:
`$ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech Wireless Mouse                 	id=11	[slave  pointer  (2)]
⎜   ↳ ELAN1300:00 04F3:3028 Mouse             	id=13	[slave  pointer  (2)]
⎜   ↳ ELAN1300:00 04F3:3028 Touchpad          	id=14	[slave  pointer  (2)]
⎜   ↳ FTSC1000:00 2808:5120                   	id=15	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Asus Wireless Radio Control             	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=10	[slave  keyboard (3)]
    ↳ USB2.0 HD UVC WebCam: USB2.0 HD         	id=12	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=16	[slave  keyboard (3)]
    ↳ Asus WMI hotkeys                        	id=17	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=18	[slave  keyboard (3)]`

**Comment by kgilmer** [comment]
Hmm, ok.  I'd like to understand what input packages you have installed.  Here's what I have, how about you?

```bash
$ apt list | grep xserver-xorg-input-

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

xserver-xorg-input-aiptek/bionic 1:1.4.1-2build1 amd64
xserver-xorg-input-all/bionic-updates 1:7.7+19ubuntu7.1 amd64
xserver-xorg-input-all-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-all-hwe-18.04/bionic-updates,now 1:7.7+19ubuntu8~18.04.3 amd64 [installed,automatic]
xserver-xorg-input-elographics/bionic 1:1.4.1-1build6 amd64
xserver-xorg-input-evdev/bionic 1:2.10.5-1ubuntu1 amd64
xserver-xorg-input-evdev-dbg/bionic 1:2.10.5-1ubuntu1 amd64
xserver-xorg-input-evdev-dev/bionic,bionic 1:2.10.5-1ubuntu1 all
xserver-xorg-input-evdev-dev-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-evdev-dev-hwe-18.04/bionic-updates,bionic-updates 1:2.10.6-1~18.04.1 all
xserver-xorg-input-evdev-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-evdev-hwe-16.04-dbg/bionic 3:14.1 amd64
xserver-xorg-input-evdev-hwe-18.04/bionic-updates 1:2.10.6-1~18.04.1 amd64
xserver-xorg-input-evdev-hwe-18.04-dbg/bionic-updates 1:2.10.6-1~18.04.1 amd64
xserver-xorg-input-joystick/bionic 1:1.6.3-1build1 amd64
xserver-xorg-input-joystick-dev/bionic,bionic 1:1.6.3-1build1 all
xserver-xorg-input-joystick-dev-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-joystick-dev-hwe-18.04/bionic-updates,bionic-updates 1:1.6.3-1build1~18.04.1 all
xserver-xorg-input-joystick-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-joystick-hwe-18.04/bionic-updates 1:1.6.3-1build1~18.04.1 amd64
xserver-xorg-input-kbd/bionic 1:1.9.0-1 amd64
xserver-xorg-input-libinput/bionic 0.27.1-1 amd64
xserver-xorg-input-libinput-dev/bionic,bionic 0.27.1-1 all
xserver-xorg-input-libinput-dev-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-libinput-dev-hwe-18.04/bionic-updates,bionic-updates 0.28.1-1~18.04.1 all
xserver-xorg-input-libinput-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-libinput-hwe-18.04/bionic-updates,now 0.28.1-1~18.04.1 amd64 [installed,automatic]
xserver-xorg-input-mouse/bionic 1:1.9.2-1 amd64
xserver-xorg-input-mtrack/bionic 0.3.1-1build2 amd64
xserver-xorg-input-mtrack-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-multitouch/bionic 1.0~rc3-1 amd64
xserver-xorg-input-mutouch/bionic 1:1.3.0-1build9 amd64
xserver-xorg-input-synaptics/bionic 1.9.0-1ubuntu1 amd64
xserver-xorg-input-synaptics-dev/bionic,bionic 1.9.0-1ubuntu1 all
xserver-xorg-input-synaptics-dev-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-synaptics-dev-hwe-18.04/bionic-updates,bionic-updates 1.9.1-1ubuntu1~18.04.1 all
xserver-xorg-input-synaptics-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-synaptics-hwe-18.04/bionic-updates 1.9.1-1ubuntu1~18.04.1 amd64
xserver-xorg-input-void/bionic 1:1.4.1-1build3 amd64
xserver-xorg-input-void-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-wacom/bionic 1:0.36.1-0ubuntu1 amd64
xserver-xorg-input-wacom-hwe-16.04/bionic 3:14.1 amd64
xserver-xorg-input-wacom-hwe-18.04/bionic-updates 1:0.36.1-0ubuntu1~18.04.1 amd64
xserver-xorg-input-xwiimote/bionic 0.5-1build3 amd64
```

**Comment by mantomas** [comment]
I have pure install from Regolith ISO (+updates), then I removed the synaptics input driver. Here is my output:

> xserver-xorg-input-all-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-all/focal,now 1:7.7+19ubuntu14 amd64 [instalovaný,automaticky]
xserver-xorg-input-evdev-dbg/focal 1:2.10.6-1 amd64
xserver-xorg-input-evdev-dev-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-evdev-dev/focal,focal 1:2.10.6-1 all
xserver-xorg-input-evdev-hwe-18.04-dbg/focal 3:14.5 amd64
xserver-xorg-input-evdev-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-evdev/focal 1:2.10.6-1 amd64
xserver-xorg-input-joystick-dev-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-joystick-dev/focal,focal 1:1.6.3-1build1 all
xserver-xorg-input-joystick-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-joystick/focal 1:1.6.3-1build1 amd64
xserver-xorg-input-kbd/focal 1:1.9.0-1build1 amd64
xserver-xorg-input-libinput-dev-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-libinput-dev/focal,focal 0.29.0-1 all
xserver-xorg-input-libinput-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-libinput/focal,now 0.29.0-1 amd64 [instalovaný,automaticky]
xserver-xorg-input-mouse/focal 1:1.9.3-1build1 amd64
xserver-xorg-input-mtrack-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-mtrack/focal 0.3.1-1build2 amd64
xserver-xorg-input-multitouch/focal 1.0~rc3-2 amd64
xserver-xorg-input-synaptics-dev-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-synaptics-dev/focal,focal 1.9.1-1ubuntu3 all
xserver-xorg-input-synaptics-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-synaptics/focal 1.9.1-1ubuntu3 amd64
xserver-xorg-input-void/focal 1:1.4.1-1build3 amd64
xserver-xorg-input-wacom-hwe-18.04/focal 3:14.5 amd64
xserver-xorg-input-wacom/focal,now 1:0.39.0-0ubuntu1 amd64 [instalovaný,automaticky]
xserver-xorg-input-xwiimote/focal 0.5-1build3 amd64

**Comment by mantomas** [comment]
I have done some more testing and results are:

Regolith 1.3 live ISO - touchpad works great, no synaptics drivers used, automatic screen rotation functional but pointer orientation is wrong

Ubuntu 20.04 live ISO - touchpad OK, automatic screen rotation great, even with pointer correctly oriented

Regolith 1.4 - touchpad works after synaptics remove, but auto-screen rotation freezes and pointer is messy

So my thinking is: Ubuntu 20.04 has all drivers correct, so I should install Ubuntu desktop (to cover all its dependencies and install packages, which are not included in Regolith 1.4 since it is not based on Ubuntu...) or maybe better solution is to completely install Ubuntu (better not) and Regolith desktop over it using PPA?

**Comment by kgilmer** [comment]
That's great information @mantomas , thank you!  I will be sure to include this fix in the next ISO release.

**Comment by kgilmer** [comment]
Regolith 1.4.1 ISO fixes this issue I believe.  Installing Regolith via PPA will offer better general compatibility with Ubuntu.  The ISO is for those that favor less resource utilization.
