### ISSUE TITLE
Regolith not installing the required package files.

### ISSUE THREAD

**Issue by SantiagoGuiral** [regolith-linux/regolith-desktop#358]
I installed regolith in ubuntu 19.10 and it was working well but I have to uninstall it, but now I'm trying to installed in ubuntu 20.04 and it's not working. I can log in using regolith but the only file available is the config file in the /etc/regolith/i3/config. All the other required files are not in their corresponding folder even if the installation tells me that I already have installed the necessary dependencies. I would like to know what I have to do to install correctly regolith with all the files available and working. 

Thanks.

**Comment by kgilmer** [comment]
Hi @SantiagoGuiral I have had this problem before too.  For me, manually deleting the directory after uninstallation and/or using `apt pruge` instead of `apt remove` resolved the issue.  More info is available here: https://regolith-linux.org/docs/getting-started/install/#edits-to-etcregolith-files

**Comment by SantiagoGuiral** [comment]
I followed the steps from the link and I was able to get some files from the packages, but even if the dependencies or packages are installed there still empty directories, for example, the style or Compton directories.

**Comment by kgilmer** [comment]
Hmm, I wish I knew why the package manager was acting like this.  What if you uninstall all regolith packages (`apt list --installed | grep regolith-`) , then delete the `/etc/regolith` directory, then reinstall regolith-desktop and any other packages you had removed?

**Comment by kgilmer** [comment]
any update @SantiagoGuiral ?

**Comment by SantiagoGuiral** [comment]
It worked following the last steps you told me, thank you for your help.

**Comment by avranju** [comment]
I seem to be running into this now. I upgraded from 19.10 to 20.04 and since then my Regolith session has refused to work. I have tried the steps mentioned above but for some reason after install my `/etc/regolith` folder looks like this:

```
drwxr-xr-x     - root 23 May 18:42  /etc/regolith
drwxr-xr-x     - root 23 May 18:42  ├── compton
drwxr-xr-x     - root 23 May 18:42  ├── i3
drwxr-xr-x     - root 23 May 18:41  ├── i3xrocks
drwxr-xr-x     - root 23 May 18:42  │  └── conf.d
.rw-r--r--   615 root  7 May  8:37  │     ├── 01_setup
.rw-r--r--    92 root  8 May  7:28  │     └── 80_rofication
drwxr-xr-x     - root 23 May 18:42  ├── styles
drwxr-xr-x     - root 23 May 18:42  │  └── lascaille
.rw-r--r--    22 root  3 May 10:26  └── version
```
As you can tell, the `styles` folder for example is empty.

**Comment by kgilmer** [comment]
Hi @avranju , another user has reported that a different approach worked for them.  Can you try:

```bash
$ sudo dpkg --purge --force-all regolith-styles
$ sudo apt install regolith-styles
```

And see if your `/etc/regolith/styles` directory looks better?  If so try the same approach with other Regolith packages `regolith-i3-gaps-config`, `regolith-i3xrocks-config`.

**Comment by avranju** [comment]
Thanks for your suggestion @kgilmer! That did seem to help, so now `/etc/regolith` looks like this:

```
/etc/regolith
├── compton
├── i3
├── i3xrocks
│  └── conf.d
│     ├── 01_setup
│     ├── 30_net-traffic
│     ├── 40_cpu-usage
│     ├── 80_rofication
│     └── 90_time
├── styles
│  ├── gnome
│  ├── i3-wm
│  ├── i3xrocks
│  ├── lascaille
│  │  ├── color
│  │  ├── i3-wm
│  │  ├── rofi.rasi
│  │  ├── root
│  │  ├── st-term
│  │  ├── theme
│  │  └── typeface
│  ├── rofi
│  ├── root
│  └── st-term
└── version
```

This is better than before. But the `i3` folder is empty. Which is probably the reason why I get the following message at the bottom:

> _Error: status_command not found or is missing a library dependency (exit 127)_

I ran `apt install i3status` and then I started getting a status bar. Looks like a default configuration of `i3` is being applied from `/etc/i3/config`
