### ISSUE TITLE
Workspace switching using a Swiss keyboard layout

### ISSUE THREAD

**Issue by daenuprobst** [regolith-linux/regolith-desktop#36]
On the Swiss keyboard layout, "+" is entered using "Shift+1". This leads to problems when switching to workspace number 1 using "Super+1". Instead of switching to the workspace, the window margin is increased. Moving the window to workspace 1 using "Super+Shift+1" works as expected.

**Comment by kgilmer** [comment]
Uh oh, yep I can see how that would be a problem @daenuprobst .  It seems that the cleanest fix would be to remap gaps keys to something other than [+]/[-].  Do you have a suggestion on keys that would be more natural to increase/decrease the window gaps?

**Comment by kgilmer** [comment]
Will leave this open until tomorrow unless additional feedback.

**Comment by daenuprobst** [comment]
Might be something to document, but the issue is solved.
