### ISSUE TITLE
Weather blocklet icon is a pointy finger

### ISSUE THREAD

**Issue by pmahnke** [regolith-linux/regolith-desktop#362]
I just pulled in the latest weather blocklet `i3xrocks-weather (3.0.13-1)` and now it has replaced the weather icon with a pointy finger icon - on two computers!

![image](https://user-images.githubusercontent.com/441217/80749785-ec6bf800-8b1e-11ea-92d3-97c7ae8e9495.png)

I am running Ubuntu 20.04 LTS and regolith unstable.

**Comment by kgilmer** [comment]
Thanks for helping us test in `unstable` @pmahnke !
