### ISSUE TITLE
Default gnome screen-lock keybinding conflicts with navigation keys

### ISSUE THREAD

**Issue by buck10** [regolith-linux/regolith-desktop#363]
The Super-l key combination is assigned to the gnome screen-lock by default and conflicts with the keyboard navigation Super-l in Regolith. This can be corrected by issuing:

`gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "['']"`

and reloading Regolith. Note, this will disable the default gnome keybinding for activating the screen-lock.

This was on a fresh install of Regolith 1.4.

EDIT: removed extra . in command above.

**Comment by kgilmer** [comment]
Thank you for the clear steps to resolve the issue @buck10 .  I checked on my fresh install but <super>i works as expected (toggle bar visibility).  Did you install other desktop sessions or something else that may have updated your keybindings?

**Comment by DanielPower** [comment]
I'm also having this issue. Installed via PPA on a fresh Ubuntu 20.04 install

**Comment by buck10** [comment]
No, I didn't install anything other than the base installation from the ISO. Downloaded from the releases page, wrote to usb using dd, installed to a new partition on my hdd, logged into the new install then checked the keys. I've reinstalled to verify what I was seeing and the results have been the same, in that the gnome keybindings take precedence to the Regolith ones at least with regards to this key combination.

**Comment by kgilmer** [comment]
Interesting, thanks for the details @buck10 .  Still not sure why I would not see this from a fresh install myself.  Was the system you installed on completely wiped or did you maybe keep some partition like `/home` from a previous install?

**Comment by buck10** [comment]
Shouldn't have been anything there. Was a new partition and I'm not sharing a home directory between any of the installs on this drive.

Of note, when starting the ISO and trying Regolith instead of installing, the Super-l key doesn't work either. It doesn't start the screen saver, but it doesn't switch to the window to the right either. Oddly, after running Regolith from the drun menu and returning to testing out the OS instead of rebooting, the super-l key works correctly in the live environment. Rebooting and running regolith from the new install still has the same issue of the super-l starting the gnome lock screen.

**Comment by XeroOl** [comment]
I also had this issue, installed from the PPA

**Comment by buck10** [comment]
Update, it seems that this issue only occurs on the first login after a fresh install. It seems to correct itself if you logout and log back in again. Is it possible that what I am seeing is related to this line in the description of the load sequence in the documentation? Not sure if it is relevant, but might explain why I'm seeing the problem and why it goes away.

[6. Compare current Xresource db against last saved hash, if different, reload GNOME settings from Xresources.
](https://regolith-linux.org/docs/reference/configurations/)

**Comment by kgilmer** [comment]
Hmm, that's interesting.  It's a good guess regarding the session load, but in this case I believe that the flags directory is what is gating Regolith to change the keybinding value, see here: https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L57

If somehow that flags file (`~/.config/regolith/flags/first-time-setup-r1-4`) exists on your first session, then the keybinding will not be updated.  But, that should not happen a the file is created by this script after executing the code within the predicate.  So, still a mystery...

**Comment by jimfarrand** [comment]
I see this issue (or a closely related one) but not on the first log-in.  Periodically, the GNOME keybinding takes over - my session will be fine for days and then suddenly &lt;super&gt;l rebinds to lock screen, for no reason that I can discern.  Previously I had been fixing this by logging out and then back in - restarting i3wm or reloading the config (or both) don't fix the problem.

I've applied @buck10's fix now, so hopefully that is the end of it - thanks buck!  Slight correction though - I need to remove the final period in that command to get it to work, ie:

`gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver "['']"`

**Comment by jajpater** [comment]
Same problem here - fresh install of regolith via the ppa on Ubuntu 20.04 - mod+l rebinds after a while.

**Comment by kgilmer** [comment]
I believe this issue will be resolved in the next Regolith release, as we'll be using gsettings session overrides instead of brute-force updating of global gsettings values.

**Comment by kgilmer** [comment]
This should be resolved in Regolith 1.5.x as we changed strategies for setting dconf.
