### ISSUE TITLE
System indicators not visible on i3bar in Regolith on Ubuntu 20.04

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#364]
I'm creating a fresh issue to track this in particular.  After some experimentation and looking back on some commits, I believe that the reason that i3bar does not display system indicators is that `gnome-flashback` implemented this facility in 3.36, and is "stealing" the indicators from dbus, preventing them from being shown on i3bar (this is just a guess, I'm not clear on the IPC mechanisms used for system indicators).

Experiments to support this:
1. can view system indicators on i3bar if launch applet with it's own dbus instance.
2. on Ubuntu 19.10, system indicators become visible if the `system-indicator` daemon is killed.
3. `system-indicator` service does not run in Regolith on Ubuntu 20.04

I believe [this comment](https://gitlab.gnome.org/GNOME/gnome-flashback/issues/18#note_674491) from Alberts Muktupāvels ( @muktupavels ) explained this situation, but at the time I didn't understand the implication.

Looking at the [initial commit](https://gitlab.gnome.org/GNOME/gnome-flashback/commit/8851723cb9beb7e7d78423e4b65c379109d2ecc4) that adds system indicators to gnome-flashback, there does not seem to be a way of turning the feature off.  I'm not sure of the best solution to this issue at the moment.

**Comment by kgilmer** [comment]
An experiment that seems to contradict the above; running `gnome-panel` in Regolith and then running `nm-applet` does not result in it being drawn in gnome-panel (or i3bar).

**Comment by muktupavels** [comment]
`system-indicators` that you linked is new `gnome-panel` module that provides new applet for `gnome-panel`. It does not steal anything... And more importantly, is not used in GNOME Flashback session on Ubuntu. :)

Ubuntu has `indicator-applet` / `indicator-applet-complete` that shows indicators from Ubuntu. This applet itself also is not problem. :)

What is `system-indicator` service/daemon? Do you mean `indicator-application-service`? If that is started I can see it causing problems. Especially with `nm-applet`... Ubuntu builds it with `--with-appindicator=ubuntu` so it uses `libappindicator` not `GtkStatusIcon`. `libappindicator` does not follow Status Notifier specification. So if indicator detects `org.kde.StatusNotifierWatcher` D-Bus name it will assume that there is host that will display indicator using `Status Notifier Item`...

Not that `indicator-application-service` is not only thing that can provide `Status Notifier Watcher`... GNOME Flashback also has service for it. And there might be other things that provides it too...

To make sure that `nm-applet` and similar indicators build with `libappindicator` uses `GtkStatusIcon` you need to ensure that your session does not have `org.kde.StatusNotifierWatcher` D-Bus service running.

If `indicator-application-service` is not running in Ubuntu 20.04 then I will assume that you have that service from `gnome-flashback`. Ubuntu in past changed `status-notifier-watcher ` default to `false`. But we started to use GSettings per-desktop overrides to change default only for GNOME Flashback session. You can check that with `XDG_CURRENT_DESKTOP=GNOME dconf-editor` and then with `XDG_CURRENT_DESKTOP=GNOME-Flashback:GNOME dconf-editor`... Navigate to `org/gnome/gnome-flashback` and in first case you will that status-notifier-watcher is enabled by default and in other it is disabled by default.

Per-desktop GSettings overrides is nice way to adjust upstream defaults without affecting other desktop environments if settings are unchanged by user. See `https://git.launchpad.net/~ubuntu-gnome-flashback/gnome-flashback/tree/debian/gnome-session-flashback.gsettings-override`. `:GNOME-Flashback` is part what create override per-desktop. and that value must be desktop name that is in `XDG_CURRENT_DESKTOP` .

`dbus-launch` "works" because it starts new session bus and it does not have `Status Notifier Watcher` meaning indicator will fallback to `GtkStatusIcon`.

Making sure there is no `Status Notifier Watcher` service / D-Bus name will fix problem with `nm-applet` and other indicators / tray icons that are build with `libappindicator`.

Story probably does not end here... If you were relying on bluetooth, power, input-sources, sound `GtkStatusIcon`s from `gnome-flashback` I have bad news - these were turned into `system-indicators` applet for `gnome-panel`...

**Comment by muktupavels** [comment]
Not related to this issue, but might cause problems - https://gitlab.gnome.org/GNOME/gnome-flashback/-/merge_requests/27. Depending what you set for `XDG_CURRENT_DESKTOP`.

GNOME Flashback installs two autostart files - https://gitlab.gnome.org/GNOME/gnome-flashback/-/tree/master/data/autostart, both are started only under GNOME-Flashback desktop.

Oh, found https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback-session.desktop#L7. So should not be problem. :)

I would suggest to use `DesktopNames=Regolith;GNOME-Flashback;GNOME;` so you get `XDG_CURRENT_DESKTOP` as `Regolith:GNOME-Flashback:GNOME`. This way you could create/install per-desktop GSettings overrides to change defaults for your session only without changing user settings like you do in https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback.

I would not be happy if trying i3 session would change my settings...

**Comment by mjgritli** [comment]
Hello Team Regolith
Here is what I found, after trying both Regolith 1.3 (19.10) and 1.4 (20.04)
in 19.10, everything is working smooth, all app indicators show just fine, perfect, even keyboard layout is included by the system.
in 20.04 however, only some apps show although I've installed the same packages on both VMs
please see the attached pictures.
![Screenshot_20200501_130617](https://user-images.githubusercontent.com/10092152/80802645-318c3a80-8bb0-11ea-8e06-34a653c3c27f.png)
![Screenshot_20200501_130521](https://user-images.githubusercontent.com/10092152/80802648-32bd6780-8bb0-11ea-8531-9beb84645528.png)

I'm really looking forward to fixing this issue on 20.04 before I upgrade.
PS. I'm having the same issue on my main laptop, installed via PPA over my Kubuntu 20.04

**Comment by kgilmer** [comment]
Thank you @muktupavels for the illuminating and detailed description of the issue.  It is very helpful for me to understand the problem, and learn more about GNOME / XDG in general.  @mjgritli , yep I think we can get a fix for this issue soon thanks to @muktupavels .  :smile:

**Comment by kgilmer** [comment]
The following steps allowed me to view `nm-applet` indicator without a stand-alone dbus:

```bash
$ sudo apt remove indicator-application
$ gsettings set org.gnome.gnome-flashback status-notifier-watcher false
```

And then log back in.

**Comment by mjgritli** [comment]
> The following steps allowed me to view `nm-applet` indicator without a stand-alone dbus:
> 
> ```shell
> $ sudo apt remove indicator-application
> $ gsettings set org.gnome.gnome-flashback status-notifier-watcher false
> ```
> 
> And then log back in.

Thanks, this really worked,
issue the command of gsetting, immediately showed all systray icons on 20.04

**Comment by muktupavels** [comment]
https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/ca6928bd169902897cfee222f01fbfceb92512f8
https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/ca1d4e44ade545c43f28512e24075a8ab3fc8a58

Keyboard Layout indicator / GtkStatusIcon is removed from `gnome-flashback`. Functionality has been moved to System Indicators applet for `gnome-panel`. GNOME Flashback provides `org.gnome.Flashback.InputSources` D-Bus interface that can be used to create status icon as separate application.

**Comment by callebjorkell** [comment]
I can also confirm that changing the gsettings worked. I did not have indicator-application installed. Thanks for figuring this out so quickly! :bow:

**Comment by ozgreat** [comment]
> The following steps allowed me to view `nm-applet` indicator without a stand-alone dbus:
> 
> ```shell
> $ sudo apt remove indicator-application
> $ gsettings set org.gnome.gnome-flashback status-notifier-watcher false
> ```
> 
> And then log back in.

That's don't work for me. Indicators still doesn't appear

**Comment by nicolas471** [comment]
> The following steps allowed me to view `nm-applet` indicator without a stand-alone dbus:
> 
> ```shell
> $ sudo apt remove indicator-application
> $ gsettings set org.gnome.gnome-flashback status-notifier-watcher false
> ```
> 
> And then log back in.

Thanks, this works for me!

**Comment by moritzheiber** [comment]
Unfortunately, the `gsettings` line didn't solve the problem for me as well. This is a brand-new Regolith 1.4 (20.04) installation.

**Comment by moritzheiber** [comment]
Unfortunately, the `gsettings` line didn't solve the problem for me as well. This is a brand-new Regolith 1.4 (Ubuntu 20.04) installation.

**Comment by paolomainardi** [comment]
hi everyone, i am quite new to this DE so sorry in advanced for any noob questions :)

I am on 20.04 and trying to have applet on the traybar, but nothing happen.
I've followed the commands above (indicator-application wasn't installed in a fresh 20.04 installation), but this is the result:

![Screenshot from 2020-05-03 14-09-31](https://user-images.githubusercontent.com/8747/80913946-a09c9700-8d48-11ea-93e7-111884e2a150.png)

What i should see in a normal condition ?

**Comment by kgilmer** [comment]
Hi @paolomainardi , an update is being published today that should address this issue.  After upgrading to 1.4.1, log back and try again.

**Comment by williamgrimes** [comment]
I'm having the same issue on `ubuntu 18.04` with `regolith 1.3`, already tried this:

```
$ sudo apt remove indicator-application
$ gsettings set org.gnome.gnome-flashback status-notifier-watcher false
```
Did not work and `nm-applet` gives:
```(nm-applet:10294): Gtk-WARNING **: 11:14:53.007: Can't set a parent on widget which has a parent```

The problem started after an `sudo apt-get upgrade` to the following:
```
regolith-gnome-flashback:amd64 (2.4.5-1ubuntu1~ppa1, 2.4.12-1)
regolith-compositor-compton-glx:amd64 (1.0.5-1ubuntu1~ppa1, 1.0.6)
regolith-i3xrocks-config:amd64 (2.2.14-1ubuntu1~ppa1, 3.0.17-1)
```

I guess I will try a fresh install

**Comment by williamgrimes** [comment]
> I'm having the same issue on `ubuntu 18.04` with `regolith 1.3`, already tried this:
> 
> ```
> $ sudo apt remove indicator-application
> $ gsettings set org.gnome.gnome-flashback status-notifier-watcher false
> ```
> 
> Did not work and `nm-applet` gives:
> `(nm-applet:10294): Gtk-WARNING **: 11:14:53.007: Can't set a parent on widget which has a parent`
> 
> The problem started after an `sudo apt-get upgrade` to the following:
> 
> ```
> regolith-gnome-flashback:amd64 (2.4.5-1ubuntu1~ppa1, 2.4.12-1)
> regolith-compositor-compton-glx:amd64 (1.0.5-1ubuntu1~ppa1, 1.0.6)
> regolith-i3xrocks-config:amd64 (2.2.14-1ubuntu1~ppa1, 3.0.17-1)
> ```
> 
> I guess I will try a fresh install
> 
> These are my regolith packages:
> 
> ```
> |/ Name                                   Version                  Architecture             Description
> +++-======================================-========================-========================-==================================================================================
> un  regolith-compositor                    <none>                   <none>                   (no description available)
> ii  regolith-compositor-compton-glx        1.0.6                    amd64                    Regolith configuration for Compton
> un  regolith-compton-config                <none>                   <none>                   (no description available)
> un  regolith-conky-config                  <none>                   <none>                   (no description available)
> ii  regolith-desktop                       2.49-1ubuntu1~ppa1       amd64                    Regolith Desktop
> ii  regolith-ftue                          1.0.10-1                 amd64                    Regolith first time user experience
> ii  regolith-gnome-flashback               2.4.12-1                 amd64                    Regolith customized gnome-flashback session
> ii  regolith-i3-gaps-config                2.3.6-1ubuntu1~ppa1      amd64                    Regolith i3-gaps config file
> un  regolith-i3-wm                         <none>                   <none>                   (no description available)
> ii  regolith-i3xrocks-config               3.0.17-1                 amd64                    Regolith configuration for i3xrocks launcher
> ii  regolith-look-cahuella                 2.3.5-1ubuntu1~ppa1      amd64                    Regolith R1.3 look
> ii  regolith-rofication                    1.2.0-1                  amd64                    Rofication notification system
> ii  regolith-st                            0.8.2-1ubuntu20ppa5      amd64                    simple terminal emulator for X
> ```

Fixed by upgrading to regolith 1.4 (reinstalling) 

https://github.com/regolith-linux/regolith-desktop/issues/318#issuecomment-614062309

**Comment by kgilmer** [comment]
This issue is resolved in Regolith 1.4.1.

**Comment by muktupavels** [comment]
> Story probably does not end here... If you were relying on bluetooth, power, input-sources, sound `GtkStatusIcon`s from `gnome-flashback` I have bad news - these were turned into `system-indicators` applet for `gnome-panel`...

https://github.com/muktupavels/sound-applet

Is there need for other removed applets? Above is quick version as response to Debian bug - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961332.

**Comment by kgilmer** [comment]
It's good to know that using gnome-panel with i3 is a working configuration.  As mentioned in the linked bug, Regolith like other typical i3 setups does not use gnome applets or indicators.  i3bar (ui component) calls a variation on i3blocks (status indicator scheduler) which invokes various scripts and renders the results in the bar.  Here is a summary of all the indicators available in Regolith, including sound: https://github.com/regolith-linux/regolith-i3xrocks-config/blob/master/debian/control

It would be nice to have options for richer UI and configuration for status indicators but unsure of the most suitable approach.  There are several bar UI components, each w/ their own set of status indicators, UI interaction flow, etc..

**Comment by CodeByCorey** [comment]
This issue is closed and says has been fixed with 1.4.1 but I am still having the issue.

On a fresh install using the ISO, the system indicators are not showing.
I tried following all the above steps but it doesn't seem to work.

**Comment by CodeByCorey** [comment]
Nevermind, I realized my i3 config has tray defaulted to `None`

Fixed with:
```
echo "i3-wm.bar.trayoutput: primary" >> ~/.config/regolith/Xresources
```

**Comment by erikh** [comment]
the solution from @CodeByCorey fixed this for me, please add it to your documentation (I couldn't find it)

**Comment by moritzheiber** [comment]
@erikh `primary` is the default since the 1.5.0 release :blush:

**Comment by biocyberman** [comment]
I have the same problem with Regolith 1.6 and Ubuntu 21.04. What I found out is that there is a conflict of shortcut key for language switching and regolith shortcut key. This helps to fix the problem:
1. start the indicator manually: `/usr/libexec/ibus-ui-gtk3 &`
2. Right click on the indicator and choose `Preference`. 
3. Change shortcut key for `Next input method` to something else, for example `Alt + Shift + Space`. 
4. I also have the following line added to `~/.config/regolith/Xresources`: `i3-wm.program.1: /usr/libexec/ibus-ui-gtk3`. 
4. Restart the computer. And the indicator will show up by itself.
