### ISSUE TITLE
[fixed] Regolith PPA incompatible with PopOS20 Upgrade

### ISSUE THREAD

**Issue by sethgoodluck** [regolith-linux/regolith-desktop#367]
Have really enjoyed regolith thus far. For some conveniences I had installed the PopOS distro of linux and ran the regolith desktop ppa. After the recent upgrade from PopOS, there are several bugs that make the ppa unusable 

1. All text in all menu screens is displayed as unicode blocks 
2. A "desktop" with icons looks to be living on screen 1 that cannot be closed

I'd love to continue using the ppa for regolith. Happy to provide more insight or to wait for updates...

Repro Steps
1. Download and install latest PopOS ubuntu distro 
2. Download and install Regolith desktop ppa 
3. Log out, switch desktop to regolith and log in
4. Observe the bugs 
----> To logout, super search logout. 

--------------------------
**fix**

I backed up my data, downloaded the PopOs20  iso, flashed it to a bootable, and did a fresh install of the PopOS 20. 

This followed by a fresh Regolith PPA install fixed the issue.

**Comment by mhsiggers** [comment]
I got the same issues by installing the pop_os shell, I think.  Uninstalling didn't fix it.  
I have also just upgraded to Regolith 1.4 and to Ubuntu 20.04 (from 19.10), so I'm not sure this what had caused the changes. 

The 'desktop' might almost be a feature. It can be moved to other workspaces, and tiles like any other container. I'm not sure that I hate it.

**Comment by kgilmer** [comment]
Thanks for documenting the fix @sethgoodluck . :smile:   For my understanding, just installing Regolith into a fresh install of Pop was the solution?

**Comment by sethgoodluck** [comment]
> Thanks for documenting the fix @sethgoodluck . smile For my understanding, just installing Regolith into a fresh install of Pop was the solution?

Bingo. For some reason, upgrading to Pop20 from Pop19 and installing regolith was giving me weird problems. Installing Pop20 fresh and then the regolith ppa was totally painless.
