### ISSUE TITLE
Compton user config refresh is erratic

### ISSUE THREAD

**Issue by romzie** [regolith-linux/regolith-desktop#371]
I created a user config for compton/picom in `~/.config/regolith/compton/config` with custom opacity and blur.
If I reload the regolith look using `regolith-look refresh`, it affects the state of currently opened windows randomly (some lose their blur transparency).

I don't know on which side the problem is (regolith or picom) or even if it is fixable but if there is a way to fix this, please tell me.

Little video to show the problem.
https://gfycat.com/plainellipticaldutchsmoushond

Otherwise I will move my user config to `/etc/regolith/compton/config` so it does not get reloaded every time I do `regolith-look refresh`.

**Comment by kgilmer** [comment]
Hmm, it's probably a bug in Regolith.  Thanks for the detailed report @romzie .  Can you add your picom config so I can try to reproduce the issue?

**Comment by romzie** [comment]
For sure, [here it is](https://pastebin.com/yZtTUMpX).

**Comment by kgilmer** [comment]
It seems that compton has to be restarted after i3 refresh.

**Comment by kgilmer** [comment]
We could handle this with shell scripts but this seems like an init.d or systemd thing (restarting system services).  I will need to do some more reading.

**Comment by romzie** [comment]
I tried copying my compton config to `/etc/regolith/compton/config` and removing the `~/.config/regolith/compton` folder but the behavior on reload is still the same.

Have you found a workaround that I could use for the time being ? Or can you ping me when you find one, thank you !

**Comment by romzie** [comment]
If it is of any relevance for you, I may add that windows and terminals open in another workspace are not affected by the blur removal. Only windows on current workspace when refresh is executed are affected.

**Comment by kgilmer** [comment]
Hi @romzie , thanks for the additional info.  The `regolith-look` script will need to be able to restart the compositor.  I'll need to add hooks for that to happen.  In the mean time as a workaround you can manually restart the compositor by killing and launching in the termail.  Or just avoid running `regolith-look refresh`.  :smile:

**Comment by romzie** [comment]
Restarting compton manually works like a charm, thank you :)

**Comment by skippednote** [comment]
Hi @kgilmer I'm trying a similar thing where I'm enabling transparency in my terminal but refreshing i3 reverts those changes. I copied over the Compton file to ~/.config/compton/config but it doesn't help. Trying a similar thing for switching wallpaper as well.

**Comment by moritzheiber** [comment]
We are restarting `picom` now whenever `regolith-look refresh` is run. Closing.
