### ISSUE TITLE
Option to Specify Temperature Unit (Weather)

### ISSUE THREAD

**Issue by ajpen** [regolith-linux/regolith-desktop#372]
Am a metric guy that struggles to get Fahrenheit numbers. 

I was able to change it by updating `/usr/share/i3xrocks/weather` but it would be great if it was in the next update so I don't lose my changes. Also saves the next metric guy some time.

What i did was added `i3xrocks.weather.units` to `~/.config/regolith/Xresources` (set to m for Celsius)

Then I had to modify `/usr/share/i3xrocks/weather` to send the unit parameter to wttr.in:

> /usr/share/i3xrocks/weather

```
#!/bin/bash
LABEL_ICON=${icon:-$(xrescat i3xrocks.label.weather)}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

# Information on the various formats: https://github.com/chubin/wttr.in
VALUE_WEATHER_FORMAT=${weather_format:-$(xrescat i3xrocks.weather.format "1")}

# weather temperature units
VALUE_WEATHER_UNITS=${weather_units:-$(xrescat i3xrocks.weather.units "m")}

# Defaults to IP address location
VALUE_WEATHER_LOCATION=${weather_location:-$(xrescat i3xrocks.weather.location "")}
VALUE_WEATHER_ERROR_MESSAGE=${error_message:-$(xrescat i3xrocks.weather.error_message "")}

WEATHER_DATA=$(curl -sS wttr.in/${VALUE_WEATHER_LOCATION}?/${VALUE_WEATHER_UNITS}'&'format="$>

echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" colo>

if [ ! -z "$button" ]; then
    /usr/bin/i3-msg -q exec xdg-open https://wttr.in/${VALUE_WEATHER_LOCATION}
fi

```

**Comment by kgilmer** [comment]
Great, thanks for the details @ajpen !  I'm thinking we can also extract the temperature metric from the [user's locale](https://github.com/regolith-linux/regolith-i3xrocks-config/blob/master/scripts/time#L8), so we don't even require the user to think about it.

**Comment by kgilmer** [comment]
I would suggest that you create a PR for your updates, but there is another large PR for this same code so it would have to be redone directly after.  I've linked the other PR in the issue above, we'll see what happens there.

**Comment by ajpen** [comment]
Okay. I'll consider the PR.

**Comment by kgilmer** [comment]
How's this look @ajpen ?  https://github.com/regolith-linux/regolith-i3xrocks-config/pull/72

**Comment by ajpen** [comment]
@kgilmer solid. Only concern would be if someone resides in the US but prefers Celsius (which actually happens to be me)

**Comment by kgilmer** [comment]
I believe that concern is addressed @ajpen by the first conditional on line 30.  If the user explicitly sets the unit via Xresources, further checks (specifically the locale/country check) are not performed.  So in the case of someone in the US preferring metric (I also sit in this boat actually), they would need to specify `i3xrocks.weather.units: m` in their Xresource override file.  

Make sense or did I miss something? I can't add you as a reviewer to the PR for some reason but perhaps you can create a review against it yourself, not sure.

**Comment by ajpen** [comment]
@kgilmer ahh I missed that. It's perfect, thanks!

**Comment by kgilmer** [comment]
Hmm, yeah that's probably true.  I guess if you had forked the repo and submitted a PR perhaps then you'd be added somehow as a contributer.  I'm not entirely sure how the rules work at this level in github.  

In any case, thanks again for your ideas and you'll be able to set your temp unit to Celsius in Regolith 1.5.

**Comment by ajpen** [comment]
Appreciate it!
