### ISSUE TITLE
gdm3 black screen at boot, with a workaround

### ISSUE THREAD

**Issue by mjgritli** [regolith-linux/regolith-desktop#374]
Dear Regolith team ...

Lastnight I made a fresh install, everything worked fine, including the fix for system tray ...
As Regolith shiiped with lightdm, I didn't like it to be honest.

I've installed gnome-tweaks to be able to change some themes, icons, which installed gdm3 automatically. I enabled gdm3 and continued.
upon next reboot, my laptop stays at a black screen.
When I went to tty2 I got the welcome message to login (I don't login). When I go back to tty1 I see the gdm3 screen and login normally.
Is this a bug somehow ... I've tried so many times, 
btw, it works with lightdm, but not gdm3
please help.

**Comment by kgilmer** [comment]
Hmm, I just tried installing gdm3 on a fresh install of Regolith 1.4.1 and did not encounter the blank screen issue you describe @mjgritli .  I can try and help you troubleshoot, if you want to send me the contents of `/var/log/syslog` from the time that gdm3 begins to load until the completion of the login.  I am not sure I can fix your issue though, as gdm3 launching occurs before the Regolith DE is initialized.

**Comment by mjgritli** [comment]
Thank you for your warm reply.

Although I tried regolith on a VM as well before making the switch, I didn't get this issue. but real life :) 
However, I had went through the logs, I couldn't find anything noticeable.
during troubleshoots with a friend, i tred:
- manually disable lightdm and enable gdm (same result, see attachment)
- edited the grub config to inlude "nomodeset" which did enable gdm3 to load fine, but disabled all display drivers
- enabling lightdm works, i takes a second to load, but works ...

I've uploaded a screenshot of that happens
the copy of syslog (cat /var/log/syslog | grep gdm3 > Downloads/syslog-gdm3), if you suggest any other way to filter the logs, I'd be happy to send more, or I can send the full log 22M
I've re-enabled lightdm for now ... but would like to get back to gdm as well.
Thank you again
![Screenshot_20200505_090428_com facebook orca](https://user-images.githubusercontent.com/10092152/81043595-cf368100-8eb2-11ea-99b6-754d98ec4159.jpg)

**Comment by kgilmer** [comment]
Hmm, I don't see anything obviously wrong with your log file.  It is supported that Regolith works from gdm3, but am unsure of why your computer is having this problem.  Another way to solve the problem may be to install Ubuntu 20.04, and then install the Regolith desktop onto that.  That should allow you to run w/ gdm3 without the issues you describe here.

If you want to try that, after installing Ubuntu 20.04, follow these steps: https://regolith-linux.org/docs/getting-started/install/#option-2-ppa

**Comment by mjgritli** [comment]
> Hmm, I don't see anything obviously wrong with your log file. It is supported that Regolith works from gdm3, but am unsure of why your computer is having this problem. Another way to solve the problem may be to install Ubuntu 20.04, and then install the Regolith desktop onto that. That should allow you to run w/ gdm3 without the issues you describe here.
> 
> If you want to try that, after installing Ubuntu 20.04, follow these steps: https://regolith-linux.org/docs/getting-started/install/#option-2-ppa

Thanks, I just thought of doing so.
Will keep you posted after I try
Thanks again for your time

**Comment by mjgritli** [comment]
Hi again
A fresh install of ubuntu and ppa install of regolith works just fine
Thank you, I'm closing this issue
