### ISSUE TITLE
"Live" content shown on lock screen after suspend

### ISSUE THREAD

**Issue by moritzheiber** [regolith-linux/regolith-desktop#376]
I have a weird artifact appearing on my screen when waking my laptop from suspend: The i3bar is showing, including "live", updating content on it:

![output](https://user-images.githubusercontent.com/616813/81148436-919e2a80-8f7c-11ea-8aed-f61dbc5ea8ec.gif)

(nevermind the misaligned UI login widget, I'll probably file a separate bug for that)

I cannot "interact" with the bar as far as I can tell, e.g. a click on an element does not trigger any UI actions, but it could potentially expose information to third parties that aren't otherwise allowed to use my laptop.

This does not happen if I simply "lock" my screen using a keyboard shortcut, it only happens when the computer is woken from suspend.

My expectation would be that the lock screen for waking from suspend doesn't expose any UI elements.

**Comment by kgilmer** [comment]
Yes, this is a long-standing issue and I believe it's due to a race between the lock screen and window manager.

Can you check if `gnome-screensaver` is installed, and if so, remove it, and log back in and see if the problem persists?

**Comment by moritzheiber** [comment]
`gnome-screensaver` is not installed. This is a fresh 1.4 installation from the beginning of this week.

**Comment by muktupavels** [comment]
Most likely bug in `gnome-flashback`, please open upstream issue here - https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues.

**Comment by moritzheiber** [comment]
Re-filed here: https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/56

**Comment by moritzheiber** [comment]
I'm closing this since this appears to be solved with the latest release of gnome-flashback on `proposed` Focal Fossa (3.36.3-0ubuntu1).

**Comment by kgilmer** [comment]
Thank you for verifying @moritzheiber !
