### ISSUE TITLE
Settings / Users / "edit my account" / Fingerprint Login / "Enable" not working

### ISSUE THREAD

**Issue by savaged** [regolith-linux/regolith-desktop#377]
Unable to activate fingerprint reader for Authentication at Login. Instead, when attempting to enable fingerprint login, one gets a dialogue: 
"Could not access any fingerprint readers
  Please contact your system administrator for help."

## Steps to reproduce
- Fresh install of Regolith OS on Lenovo x220i
- dmenu: Settings
- Users
- Unlock
- Fingerprint Login   Disabled -> [click]

**Comment by moritzheiber** [comment]
@savaged What type of fingerprint reader/device attached to the reader are you using?

**Comment by savaged** [comment]
Sorry; should have included that. I'm using a Lenovo x220i

**Comment by moritzheiber** [comment]
Can you provide us with the output of `lsusb`? Also, is `fprintd` installed?

**Comment by savaged** [comment]
I just have the defaults for Regolith OS, I haven't installed fprintd

```
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 006: ID 04f2:b217 Chicony Electronics Co., Ltd Lenovo Integrated Camera (0.3MP)
Bus 001 Device 008: ID 046d:c077 Logitech, Inc. M105 Optical Mouse
Bus 001 Device 007: ID 0a5c:21ec Broadcom Corp. 
Bus 001 Device 005: ID 17ef:1009 Lenovo 
Bus 001 Device 004: ID 0a5c:217f Broadcom Corp. BCM2045B (BDC-2.1)
Bus 001 Device 003: ID 147e:2016 Upek Biometric Touchchip/Touchstrip Fingerprint Sensor
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by moritzheiber** [comment]
The good news is: that's a supported fingerprint reader. The bad news is that the required libraries and integrations might be missing right now to use it properly. Could you try installing `fprintd`?

**Comment by savaged** [comment]
> The good news is: that's a supported fingerprint reader. The bad news is that the required libraries and integrations might be missing right now to use it properly. Could you try installing `fprintd`?

ran `sudo apt install fprintd` and now I'm in business! Thanks

**Comment by moritzheiber** [comment]
@kgilmer Maybe you want to add `fprintd` as a recommended dependency somewhere?

**Comment by kgilmer** [comment]
`fprintd` does not pull in any other dependencies so I added it as a top level dependency to the R1.4.1 ISO.  I'm expecting that users installing from PPA will already have that package installed.  Kindly re-open if I've missed something.
