### ISSUE TITLE
Keybindings as Xresources

### ISSUE THREAD

**Issue by AussieGuy0** [regolith-linux/regolith-desktop#378]
I was wondering about the feasibility of exposing the keybindings of Regolith as Xresources. 

I would like to change a couple of the default keybindings that Regolith provide. Unfortunately, this would require copying over the entire `/etc/regolith/i3/config` file, which would then need to be updated for new Regolith releases. 

Having the keybindings as Xresources would allow them to be easily changed depending on user preference. This would match how other settings can be changed, like font and i3-bar position.

**Comment by gdeflaux** [comment]
@kgilmer I think this would be worth considering. I am happy to take a stab at this, also because it would allow Regolith On Stage to provide that feature in a simple and upgrade friendly manner.

**Comment by kgilmer** [comment]
It would be great if we could get this to work, I agree and thanks for the feedback @AussieGuy0 .  I think @cheginit and I tried this several months back but were unable to specify a variable to define a keybinding.  But, perhaps we missed something or didn't consider a different approach.  If you can get it working, let's do it!

**Comment by ukaszg** [comment]
how about a different approach? I believe it would be more easy to configure. Just create a bunch of scripts with i3-msg that change the desktop etc. and bid them all in gnome-control-center, we'd have keybinds changeable by clicking.

**Comment by moritzheiber** [comment]
@kgilmer As far as I remember we have elected to _not_ use `Xresources` for this given purpose (because it has too many side-effects and copious potential for shooting yourself in the foot) and the recommended way of changing keybindings is through staging configuration files. If this is the case, can we close this issue?

**Comment by kgilmer** [comment]
Yes, to the degree we can (there are limitations to variable expansion within the i3 config system that limits us) all keybindings can be overridded via Xresources.  Example:

```
set_from_resource $i3-wm.binding.move_down i3-wm.binding.move_down Shift+j
```

so setting `i3-wm.binding.move_down` allows one to remap the down action to another keybinding. 

Closing.
