### ISSUE TITLE
Multiple monitors on 19.04?

### ISSUE THREAD

**Issue by jzelner** [regolith-linux/regolith-desktop#38]
Is the fix for multiple monitors in the 19.04 based Regolith distro? Just tried that one off the live usb, and had this same issue. Should I try 18.04? Thanks!

**Comment by kgilmer** [comment]
I responded to your question here:
https://github.com/regolith-linux/regolith-desktop/issues/12#issuecomment-502925652

**Comment by kgilmer** [comment]
Assuming fixed, please re-open if you're still having problems.
