### ISSUE TITLE
Falil mounting regolith-20.04.0-1.4-desktop-amd64.iso in Virtualbox CD 

### ISSUE THREAD

**Issue by damufo** [regolith-linux/regolith-desktop#384]
**Describe the bug**
No mount iso (regolith-20.04.0-1.4-desktop-amd64.iso
![imaxe](https://user-images.githubusercontent.com/4057369/81531926-db638800-9363-11ea-9daf-62ca6cf93cd7.png)
) to install

**To Reproduce**
Load iso in CD

**Screenshots**
![imaxe](https://user-images.githubusercontent.com/4057369/81531681-714ae300-9363-11ea-94fc-0790c2af86b3.png)

**Installation Details**
 - Regolith Install Type: [ISO]
 - Regolith Version: [e.g. 1.4]
 - Host OS: [Ubuntu 20.04]

**Additional context**
Failed to open the disk image file /home/dddd/descargas/isos/regolith-20.04.0-1.4-desktop-amd64.iso.

Could not get the storage format of the medium '/home/dddd/descargas/isos/regolith-20.04.0-1.4-desktop-amd64.iso' (VERR_NOT_SUPPORTED).

Código resultado: VBOX_E_IPRT_ERROR (0x80BB0005)
Compoñente: MediumWrap
Interface: IMedium {ad47ad09-787b-44ab-b343-a082a3f2dfb1}
Receptor: IVirtualBox {d0a0163f-e254-4e5b-a1f2-011cf991c38d}
Receptor RC: VBOX_E_OBJECT_NOT_FOUND (0x80BB0001)

Virtualbox version:6.1

![imaxe](https://user-images.githubusercontent.com/4057369/81531901-d0a8f300-9363-11ea-8fef-4daf22c8dd29.png)

**Comment by moritzheiber** [comment]
I have done exactly what you're trying to do and succeeded, so the problem has to lie somewhere else.

Please make sure you've downloaded the ISO correctly by verifying its MD5 checksum (`66bfe821c9e0ebf92d1184c5df4cb381`). You can either use `md5sum <iso>` directly and verify the checksums manually or use the following command to let `md5sum` do the trick for you:
```
echo "66bfe821c9e0ebf92d1184c5df4cb381  /path/to/iso/file" | md5sum -c -
```

_Note: Mind the two (2) spaces after the checksum, in between the checksum and the file._

**Comment by damufo** [comment]
echo "66bfe821c9e0ebf92d1184c5df4cb381  regolith-20.04.0-1.4-desktop-amd64.iso" | md5sum -c -
regolith-20.04.0-1.4-desktop-amd64.iso: FAIL
md5sum: WARNING: 1 computed checksum did NOT match

thanks, i will try to download again

**Comment by moritzheiber** [comment]
What you have pasted here only has a single space in between the checksum and the ISO file. Just making sure you're not doing all of it for nothing.

**Comment by moritzheiber** [comment]
@damufo Can we close this issue?

**Comment by damufo** [comment]
Sorry. Yes, re download and work fine.
Very thanks!!
