### ISSUE TITLE
Plot window doesn't disappear after closing

### ISSUE THREAD

**Issue by pvnieo** [regolith-linux/regolith-desktop#385]
Hi,
I'm using the library pyvista on python3 to plot some 3D shapes. This librabry create a new window where it plots shape (like matplotlib or opencv). The execution goes fine, but when I want to exit the ploting window (for that, I just need to press "Q"), the window became black (I can't see the plot anymore), and when I want to force close it (by Win + Shift + Q), it doesn't close, and the space it occupied can't be used by other windows.

**To Reproduce**
Just install `VTK` and `pyvista`, and excute the following code:
```
import pyvista as pv
from pyvista import examples

filename = examples.planefile
mesh = pv.read(filename)
cpos = mesh.plot()
```
After that, press "Q" to quit.

**Expected behavior**
I expect the new window to be shut.

**Screenshots**
This is a screenshot of the ploting window.
![Screenshot from 2020-05-11 14-14-24](https://user-images.githubusercontent.com/22404728/81560584-ffd65900-9391-11ea-893f-a6c0890aa4de.png)

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by priestoferis** [comment]
I'm guessing if you log in into Ubuntu instead of Regolith and do this on the same system, Q will exit the plot? For me, pressing Q will not even turn the screen black.

**Comment by kgilmer** [comment]
Closing due to lack of response.
