### ISSUE TITLE
Provide a way for uses to see status of package updates across PPAs

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#386]
Testing and package promotion process is not visible to users unless they are scanning the PPA indexes.  Users should be able to:

1. See the package version differences between various PPAs (unstable -> stable -> release)
2. See changelog associated with each version so that they can understand what's changed
3. (Optional) get an ETA for when promotions to the next level for a given package should be available

The solution should be simple and linkable.  Ideally the user can step back in time (version control).  The solution should not require a large number of manual steps.

**Comment by moritzheiber** [comment]
@kgilmer I think we can close this .. ? As far as I remember you've created a site for this .. ?

**Comment by kgilmer** [comment]
Yes, it's here: https://regolith-linux.org/regolith-builder/index.html

Closing, thanks.
