### ISSUE TITLE
Regolith ignores the gnome settings "natural scrolling" option

### ISSUE THREAD

**Issue by scmbradley** [regolith-linux/regolith-desktop#389]
Whether I have natural scrolling turned on or off in the gnome options, scrolling behaves the same way.  I don't know when this started being an issue, since I am only using the touchpad while my wireless mouse is recharging.

**Comment by kgilmer** [comment]
Hi @scmbradley , depending on how you installed Regolith you may have an input driver issue.  Can you try uninstalling this package: `sudo apt remove xserver-xorg-input-synaptics`, logging back in, and see if the behavior persists?

https://github.com/regolith-linux/regolith-desktop/issues/360

**Comment by scmbradley** [comment]
That seems to work now.

**Comment by newptcai** [comment]
This one also work -- https://askubuntu.com/questions/912669/i3-synclient-has-no-natural-scrolling
