### ISSUE TITLE
/etc/regolith files don't get written

### ISSUE THREAD

**Issue by djuelg** [regolith-linux/regolith-desktop#392]
Hi,

I used Regolith 1.2 and Ubuntu 18.04. Today I uninstalled Regolith 1.2 and made a dist upgrade to Ubuntu 20.04 which worked.

Then I tried to reinstall Regolith with the new ppa using the release channel. But the installation is somehow buggy. I think I messed something up within the /etc/regolith folder, since very few files are written to it:

```sh
djuelg@endor  ~  tree /etc/regolith 
/etc/regolith
├── compton
├── i3
├── i3xrocks
│   └── conf.d
│       ├── 01_setup
│       ├── 30_net-traffic
│       ├── 40_cpu-usage
│       ├── 80_battery
│       ├── 80_rofication
│       └── 90_time
├── styles
│   └── lascaille
└── version

6 directories, 7 files
 djuelg@endor  ~  cd  /etc/regolith 
 djuelg@endor  /etc/regolith  ll
total 36
drwxr-xr-x   6 root root  4096 Mai 13 20:33 .
drwxr-xr-x 146 root root 12288 Mai 13 20:33 ..
drwxr-xr-x   2 root root  4096 Mai 13 20:33 compton
drwxr-xr-x   2 root root  4096 Mai 13 20:33 i3
drwxr-xr-x   3 root root  4096 Mai 13 20:33 i3xrocks
drwxr-xr-x   3 root root  4096 Mai 13 20:33 styles
-rw-r--r--   1 root root    22 Mai  3 19:26 version
```

Do you have any suggestions what I could do? I already tried the following chain of commands to reinstall:

- `sudo apt purge regolith-*`
- `rm -Rf ~/.config/regolith`
- `sudo rm -Rf /etc/regolith`
- `sudo apt purge i3-gaps-wm`
- `sudo apt purge i3xrocks`

So more less I was deleting everything I could think of. Then I tried to reinstall using `sudo apt install --reinstall regolith-desktop` but the result was the same...

**Comment by kgilmer** [comment]
@djuelg everything I would suggest it looks like you've already tried.  It's odd to me that after entirely removing `/etc/regolith` and purging the packages that after reinstalling `regolith-desktop` you would continue to have issues with apt writing files to `/etc`.  I have had this issue but `purge` and `rm -Rf` always got me back to sanity.  I'll do some searching but don't have a fix for you at the moment.

**Comment by edo9k** [comment]
Same here. I tried reinstalling multiple times. I tried adding items to the bar manually following the configuration section of the website. The bar only shows the number of the current desktop, nothing else, all config file changes are ignored.

The same weird behavior on Mint 19.3 and Ubuntu 18.04.

**Comment by moritzheiber** [comment]
We've had a few releases in the meantime. Should this issue still persist please open a new report with more up to date information. Thanks!
