### ISSUE TITLE
Download and Release links: Small Heads Up

### ISSUE THREAD

**Issue by lfom** [regolith-linux/regolith-desktop#393]
Hello, there! Thanks for this project. A small heads up report about the [website](https://regolith-linux.org/):
1. Download still links to tag 1.4 instead of the newest 1.4.1
2. 1.4.1 isn't listed yet in the Releases menu

Regards

**Comment by kgilmer** [comment]
That explains why everyone is still downloading 1.4...thanks for the heads-up @lfom !
