### ISSUE TITLE
Installing dunst results in left over rofication config

### ISSUE THREAD

**Issue by cjohnston1158** [regolith-linux/regolith-desktop#394]
**Describe the bug**
Installing dunst results in rofication being uninstalled, as expected, however, it seems to leave the i3xrocks config resulting in command not found in syslog:

May 13 14:56:16 . i3-gnome-flashback.desktop[13770]: /bin/sh: 1: rofication-status: not found
May 13 14:56:16 . i3-gnome-flashback.desktop[2968]: <3>[rofication] Command 'rofication-status' not found or missing dependency

**To Reproduce**
https://regolith-linux.org/docs/howto/replace-notification-system/

**Expected behavior**
No errors

**Installation Details**
 - Regolith Install Type: Stable PPA
 - Regolith Version: [e.g. 1.4]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 20.04]

**Comment by moritzheiber** [comment]
You probably didn't specify to `--purge` `regolith-rofication` specifically, which means its configuration files are being left behind in `/etc/regolith/i3xrocks/conf.d`. Please check if you have the file `/etc/regolith/i3xrocks/conf.d/80_rofication`. If you do, removing it should get rid of the error you posted above.

**Comment by cjohnston1158** [comment]
@moritzheiber yes, it was left over, and yes, --purge would have done it, however, the [instructions ](https://regolith-linux.org/docs/howto/replace-notification-system/) say:

> Install dunst: sudo apt install dunst. This should cause rofication to be uninstalled.

So if it isn't possible to "just work" following the instructions, then the instructions should be fixed.
