### ISSUE TITLE
Background is being reset and i3bar is empty after shutdown

### ISSUE THREAD

**Issue by Mona144** [regolith-linux/regolith-desktop#395]
I have been using regolith for a few weeks now and noticed that my background is being reset from time to time, but this time it is not only my background but also my i3 bar that changed, meaning it is completely empty and has a different style suddenly.

I installed regolith on top of Xubuntu using PPA and haven't tinkered with the config files that much so far, especially not in the last few days.

Regolith Install Type: PPA
Regolith Version: 1.4
PPA url: ppa:regolith-linux/release
Host OS (for PPA): Ubuntu 18.04

This is my first issue I'm writing and I am not sure what information I need to provide, so please let me know whatever you need!

**Comment by kgilmer** [comment]
Hi @Mona144 , there was a recent update to 1.4.1.  There were some bug fixes related to settings and so part of the upgrade process was to re-apply some gsettings upon login.  Have you staged your own i3 or i3xrocks config files?  A suggested approach is to follow [these steps](https://regolith-linux.org/docs/getting-started/install/#upgrading-with-customizations) to get back to a default configuration, then reapply any updates with [Xres overrides](https://regolith-linux.org/docs/howto/override-xres/), which are more resilient to package updates that full copies of config files.

Regarding the background image, using Settings to configure the wallpaper should be fine in most cases.  Upon upgrades this is also reset.  You can prevent this by providing the path to your wallpaper via Xres overrrides.  [See here](https://regolith-linux.org/docs/reference/xresources/) for available overrides.

**Comment by Mona144** [comment]
Thanks for your quick reply!
I followed those steps and now have at least a a few items back in my i3bar! I think the rest is just something that I have messed up somehow, I'll just tinker around a little more.
