### ISSUE TITLE
Nightshift stays on after hibernate

### ISSUE THREAD

**Issue by cheginit** [regolith-linux/regolith-desktop#402]
**Describe the bug**
When nightshift is activated and the system goes to hibernation, the nightshift won't be deactivated until you log out.

**To Reproduce**
Turn on nightshift, hibernate the system, wake it up, try turning off/on nightshift from power setting.

**Expected behavior**
Nightshift should turn off automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/13016644/81956212-a9a32900-95d0-11ea-8a3c-32e23f8971bb.png)

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 1.4.1
 - PPA url: ppa:regolith-linux/unstable
 - Host OS (for PPA): Ubuntu 20.04

**Comment by kgilmer** [comment]
I'm guessing this is an issue with gnome-flashback but unsure.

**Comment by moritzheiber** [comment]
I've described [how to test a newer release of `gnome-flashback` here](https://github.com/regolith-linux/regolith-desktop/issues/406#issuecomment-629674629). You could give it a try and see whether it fixes your problem.

**Comment by moritzheiber** [comment]
Also, as with [the other Nightshift related bug](https://github.com/regolith-linux/regolith-desktop/issues/403#issuecomment-629172812), this is likely related to `gsd-color`/`colord` not receiving certain events it needs in order to change the screen's color profile.

**Comment by cheginit** [comment]
@moritzheiber Thanks for the suggestion but it's fixed now, don't know how though. I don't remember changing anything related to `gnome-flashback`. Maybe there's been an update since then?

**Comment by moritzheiber** [comment]
It could've been a transient update for another dependency or GNOME component, e.g. `gnome-control-center`. As this is clearly related to components managing the display I wouldn't be surprised. It's mostly fixed for me as well, just not 100%. The issue re-appears every so often, but since I know it's being worked (and there's a workaround) on it doesn't bother me that much.

Do you think we can close this issue?

**Comment by cheginit** [comment]
I see. Over the past couple of days I haven't had any issues. Yes, I will close it.

**Comment by ArchiFleKs** [comment]
Hi, I still have the issue on regolith 1.6 ubuntu 21.04

**Comment by kgilmer** [comment]
Specifically after resuming from hibernation @ArchiFleKs or something else?

**Comment by ArchiFleKs** [comment]
Sorry. Yes hibernation or when disconnecting from second screen.  It get stuck in whatever state it is in (on or off). Until I kill lsd color
