### ISSUE TITLE
Nightshift is only active on one display

### ISSUE THREAD

**Issue by jensens** [regolith-linux/regolith-desktop#403]
**Describe the bug**

Nightshift is only active on one display. At night time only one display goes in blue-reduced mode, the other one stays bright. In this case my 4k display is fine and my notebook display stays bright.

**To Reproduce**
Install two displays, enable nightshift, wait for night (or trigger mode manually).

**Expected behavior**
Both displays are in night mode.

**Installation Details**
 - Regolith Install Type: [ISO]
 - Regolith Version: [1.4]

**Comment by moritzheiber** [comment]
This is most likely a GNOME issue. Here are a few possible angles:

https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/39
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/486
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/60

Generally, it should work if you're killing `gsd-color` (as a workaround). The bug has something to do with `gsd-color` not being notified of some state changes.

**Comment by moritzheiber** [comment]
I've described [how to test a newer release of `gnome-flashback` here](https://github.com/regolith-linux/regolith-desktop/issues/406#issuecomment-629674629). You could give it a try and see whether it fixes your problem.

**Comment by jensens** [comment]
Indeed, the fresh release fixes it. Thanks!
