### ISSUE TITLE
support for xrandr before i3 starts

### ISSUE THREAD

**Issue by clarkevans** [regolith-linux/regolith-desktop#404]
**Background**
Sometimes there are xrandr commands that need to be run that cause resizing, mirroring and other display configuration.  These commands need to be done after XWindows is running but before any sort of sizing calculations are done in a display manager. 

**Bug Explanation**
Currently, if you downgrade a display resolution setting, various artifacts happen, such as the status bar being in the middle of the screen, or half of the screen not visible on the display.  Note that commands can be added in standard i3 setup and i3status bar, but, with Regolith it creates artifacts for me. 

**To Reproduce**
Take a standard setup, and add an i3 command to lower a resolution of one of your displays, for example, /usr/bin/xrandr --output HDMI-1 --mode 800x600

**Expected behavior**
The expected behavior is that the status bar and things just work with that resolution.  What happens is that sizing things seem to be off.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: what's in the PPA on 2020-05-14
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Additional context**
I was able to work around it by adding the randr commands right before i3 was started in the i3-gnome-flashback file.  Hence putting a hook there, to run a custom shell script, should work

**Comment by jensens** [comment]
I would say the place for a check if a hook is present and then running the hook is here: https://github.com/regolith-linux/regolith-gnome-flashback/blob/c9750df6a134d0cce57fc44802c91c701a9fc5ac/i3-gnome-flashback#L139

I would place a script in i.e. ``~/.config/regolith/i3/before-startup.sh`` (for discussion).
If the script exists and is set executable, run it.

This also needs to be documented.

**Comment by kgilmer** [comment]
I believe it was established in Slack that xrandr and gnome is not combatible, and not loading xrandr upon session start resolves the issue.  Kindly re-open if I misunderstood.

**Comment by jensens** [comment]
Running xrandr before i3 starts did not works for me.

Btw.: It is compatible and fractional scaling works. I just need to run the script (with a keybinding) and all is fine. 

OT: I now removed the script and found very small fonts (100%) or very large fonts (200%).
Then I installed gnome-tweak-tool to increase font size, which helps a lot. Now I am on 100% and I am almost happy.

**Comment by moritzheiber** [comment]
Since I was pointed to this thread by another user, here's a working method to "solve" the intention of this enhancement request:
```
$ cat /usr/share/lightdm/lightdm-gtk-greeter.conf.d/display.conf
[SeatDefaults]
display-setup-script=<your-command-here>
```

I use it to set my laptop's screen to 1080p resolution upon session manager startup:

```
[SeatDefaults]
display-setup-script=xrandr --output eDP-1 --primary --mode 1920x1080
```

**Comment by kgilmer** [comment]
Maybe this could go into a HOWTO @moritzheiber ?
