### ISSUE TITLE
Battery percentage not showing in Ubuntu 20.04

### ISSUE THREAD

**Issue by HadiModarres** [regolith-linux/regolith-desktop#405]
with the latest regolith on Ubuntu 20.04 the laptop battery percentage on status area is gone, how can I fix it?

**Comment by kgilmer** [comment]
Hi @HadiModarres :smile:  , follow these steps to restore the battery status indicator:

```bash
$ sudo apt install i3xrocks-battery
$ regolith-look refresh
```

**Comment by HadiModarres** [comment]
Hi mate, still ejoying regolith everyday :) 

Thanks that did it.

**Comment by crichtonsfidget** [comment]
@kgilmer and @HadiModarres, thanks for this query. I am new to Regolith (and Linux), and I am thankful for your efforts.

**Comment by kryzar** [comment]
Hi. The package `i3xrocks-battery` is unavailable for me, despite the fact that other *i3xrocks* packages are available:

```shell
~ sudo apt install i3xrocks-battery
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package i3xrocks-battery
~ sudo apt install i3xrocks
i3xrocks              i3xrocks-net-traffic  i3xrocks-time
i3xrocks-cpu-usage    i3xrocks-rofication
```

I am using Ubuntu 21.10 and Regolith 1.6.0.
