### ISSUE TITLE
with mirrored monitors, login dialogue is positioned off screen on lock screen 

### ISSUE THREAD

**Issue by clarkevans** [regolith-linux/regolith-desktop#406]
**Describe the bug**
When using a mirrored display, when one display (2560x1440) is bigger than the other (1920x1200), the login dialogue on the lock screen is not visible.  Some report that it's visible but not center aligned, perhaps they don't have such a large resolution difference.  This is not severe since, even if it's off screen, the focus is properly set and you can type in your password.

**To Reproduce**
Have a system with two displays, where the larger of the two is your primary display.  The smaller one is simply a mirror, that I use for teaching other people, in my case, it's my programming pair.
Go into the gnome settings displays. Set at single display with the large screen on a resolution compatible with the smaller display, go to the lock screen, and notice that the login dialogue is perfectly positioned.  Then, go back to settings, and mirror the displays. Notice that the larger screen is still at the resolution of the smaller screen. In this case, when you go into the lock screen, either the dialogue is missing completely or it is off centered (as reported by other users).  

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version:  1.4.1
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA):  Ubuntu 20.04

**Additional context**
Originally I used xrandr to configure the displays, but that causes significant issues.  This problem seems to happen even when using gnome itself to configure the screen mirroring.

**Comment by moritzheiber** [comment]
Please give `gnome-flashback` from the `proposed` repository a try.

1. Add "Proposed" to your software repositories in the settings
2. Add the following content into a file (e.g. `focal-proposed-400`) in the `/etc/apt/preferences.d/` directory:
```
Package: *
Pin: release a=focal-proposed
Pin-Priority: 400
```
3. Run `apt update`
4. Install `gnome-flashback` from the `proposed` repository:
```
apt install gnome-flashback/focal-proposed
```

The updated gnome-flashback package contains a lot of fixes for various issues and it did fix the same bug for me you're describing here.

**Comment by clarkevans** [comment]
How do I do step #1?  I can do 2-4 but I get...
`
root@galois:/etc/apt/preferences.d# apt install gnome-flashback/focal-proposed
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Release 'focal-proposed' for 'gnome-flashback' was not found
`

**Comment by jensens** [comment]
From what I remember for (1) I editing ``/etc/apt/sources.list.d/regolith-linux-ubuntu-release-focal.list`` and  appending a proposed like so: ``deb http://ppa.launchpad.net/regolith-linux/release/ubuntu focal main proposed`` but this did not work (error on `apt update` `deb http://ppa.launchpad.net/regolith-linux/release/ubuntu focal main proposed`).

Instructions welcome!

**Comment by cjohnston1158** [comment]
Add the following line (using your preferred mirror) to /etc/apt/sources.list:

deb http://us.archive.ubuntu.com/ubuntu/ focal-proposed main restricted universe multiverse

**Comment by clarkevans** [comment]
Thanks.  So, I did this, and rebooted.  The issue remains.
```
# apt-get install gnome-flashback/focal-proposed
gnome-flashback is already the newest version (3.36.3-0ubuntu1).
```
Should I be using a different PPA?  I'm still on the release PPA.

**Comment by moritzheiber** [comment]
You can use the UI: https://wiki.ubuntu.com/Testing/EnableProposed

The instructions are for Xenial, but the UI should look the same for Focal. Once you’ve checked the box just exit the dialogue, it’ll prompt you to refresh your package sources. You can continue with the other steps afterwards.

**Comment by moritzheiber** [comment]
@clarkevans That's unfortunate. I think you'll need to report this issue upstream then, with [gnome-flashback](https://gitlab.gnome.org/GNOME/gnome-flashback/).

**Comment by clarkevans** [comment]
Thank you. Done.  https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/58

**Comment by troglobit** [comment]
Yup, the workarounds listed in this thread do indeed work!  They also fix the problem of suddenly having two login-boxes after lock/sleep.  Love the active community around Regolith! <3

**Comment by moritzheiber** [comment]
@troglobit Are you referring to the particular issue the author has reported or another bug?

**Comment by troglobit** [comment]
@moritzheiber The issue reported.

**Comment by moritzheiber** [comment]
@troglobit Good to know, thanks!

**Comment by captainmannering** [comment]
I have had an issue similar to the original poster. If my laptop is connected to 2 external monitors (in addition to the laptop's built in screen) and then I put my computer to sleep, remove the external monitors (using a Thunderbolt dock), and then wake the laptop up again there are 2 problems:
1 - (always) the screen shows all of the windows that were on the computer when it slept, instead of covering them with a lock screen or similar
2 - (usually) the login window is nowhere to be seen. I suspect it is trying to appear on an external monitor that no longer is attached. As a result I seem to have no choice but to forcibly power off the computer and restart.

Is there any magic key combination to force the desktop to reset itself whilst the screen is locked?

**Comment by kgilmer** [comment]
I have had luck at times switching to a TTY and then back to the X session, it's possible it would help in this case.

```
<ctrl><alt>F1
<ctrl><alt>F7
```

Also, there may be some th3 related scripts or configuration changes you can make to deal with this. I have a thinkpad and a lenovo tb3 (version 2) dock, and do not encounter this issue, fwiw.

**Comment by muktupavels** [comment]
https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/cdc534a3b0f4abe4e02a5397466ae094ee3d7fdc
https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/1495cd45f150795bda34dfea292f8c1ad8905a50

**Comment by troglobit** [comment]
@muktupavels Nicely done! :+1:

**Comment by moritzheiber** [comment]
We're likely going to have to wait for another updated release of `gnome-flashback` before this bug is ultimately resolved :slightly_smiling_face:

**Comment by muktupavels** [comment]
@troglobit Did you test fixes?

@moritzheiber Waiting == will never happen! I don't plan to make new 3.36.x or older version releases just because there are some fixes... So someone needs to ask for new release and be ready to create SRU bugs (when using Ubuntu) and verify them.

**Comment by moritzheiber** [comment]
@muktupavels Totally makes sense. Once we have at least confirmation I'll be happy to volunteer my time to ask for a release and file the SRU bug upstream :slightly_smiling_face:

**Comment by troglobit** [comment]
@muktupavels Nope, and I likely will not find the time. Sorry :/

**Comment by clarkevans** [comment]
I want to thank you all for looking at this. I currently don't have dual-screen setup to verify a fix.  I'm loving Regolith; thank you so very much.

**Comment by muktupavels** [comment]
I pushed fix also to gnome-3-36 branch so it will be in next 3.36 release.

**Comment by moritzheiber** [comment]
This should be fixed by using the latest `gnome-flashback` release. Feel free to re-open if it isn't.
