### ISSUE TITLE
Modifing Xresources has no effect on i3-wm

### ISSUE THREAD

**Issue by cmF3** [regolith-linux/regolith-desktop#408]
**Describe the bug**
Setting Xresources for i3-wm has no effect

**To Reproduce**
Add this to ~/.config/regolith/Xresources to produce a 10 px wide red border
```
echo 'i3-wm.window.border.size: 10' >> ~/.config/regolith/Xresources
echo 'i3-wm.client.focused.color.border: #FF0000' >> ~/.config/regolith/Xresources
regolith-looks refresh
```
Note that there is no 10 px wide red border

**Expected behavior**
A 10 px wide red border

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: latest release
 - PPA url: default
 - Host OS (for PPA): Ubuntu 20.04

**Comment by kgilmer** [comment]
I was unable to reproduce your issue.  The key for the border color is slightly different though.  Here's what I did:

```bash
$ echo 'i3-wm.window.border.size: 10' >> ~/.config/regolith/Xresources
$ echo 'i3-wm.client.focused.color.child_border: #FF0000' >> ~/.config/regolith/Xresources
$ regolith-look refresh
```

![image](https://user-images.githubusercontent.com/49683/82160298-2b9d8700-9849-11ea-9628-361af71e08c8.png)
