### ISSUE TITLE
PropertyNotify received for unknown window 02c0001d

### ISSUE THREAD

**Issue by cjohnston1158** [regolith-linux/regolith-desktop#411]
**Describe the bug**
Not sure yet what is causing this, but seeing the following error in syslog:
```
May 19 05:27:02 kachemak i3-gnome-flashback.desktop[3109]: [../../i3-gaps-wm-4.17.1/i3bar/src/xcb.c:985] ERROR: PropertyNotify received for unknown window 02c0001d
May 19 05:27:03 kachemak i3-gnome-flashback.desktop[3109]: [../../i3-gaps-wm-4.17.1/i3bar/src/xcb.c:985] ERROR: PropertyNotify received for unknown window 02c00026
May 19 05:27:03 kachemak i3-gnome-flashback.desktop[3109]: [../../i3-gaps-wm-4.17.1/i3bar/src/xcb.c:985] ERROR: PropertyNotify received for unknown window 02c00031
```

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: [e.g. 1.4] 1.4.1
 - PPA url: Stable
 - Host OS (for PPA): Pop!_OS 20.04

**Comment by moritzheiber** [comment]
Are you using any customization? I fear you'll have to be a little more specific about your setup. Also, it would be good to know whether or not you can trace this back to certain behavior within your environment (window focus, click events etc.)

**Comment by kgilmer** [comment]
Hmm, yeah googling around there doesn't seem to be a specific easily identifiable root-cause.  Perhaps tail and grep syslog on a fresh login and see if there is an app behavior that correlates to the message?

**Comment by moritzheiber** [comment]
@cjohnston1158 Is this this relevant?

**Comment by kgilmer** [comment]
Closing for lack of response
