### ISSUE TITLE
The prompt for wifi password never comes up- therefore can't connect to any wifi networks 

### ISSUE THREAD

**Issue by jivanmukti** [regolith-linux/regolith-desktop#413]
**Describe the bug**
Unable to connect to any wifi networks using the settings panel because the prompt for password never comes up. Bypassed this by connecting via the terminal.

**To Reproduce**
Press super+w, and click on any wifi network to connect. 

**Expected behavior**
Prompt for password should appear.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: default: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by kgilmer** [comment]
Hi @jivanmukti :smile: .  The UI for wifi passwords does not pop-up a password dialog.  To add a password to a wifi access point, click the "gear" icon to the right of the SSID.  In the dialog, go to the "Security" tab and enter the password there.

**Comment by jivanmukti** [comment]
That solved it, thanks @kgilmer !

**Comment by moritzheiber** [comment]
@kgilmer Q: Is this a general GNOME issue or gnome-flashback specific? I think that's fairly confusing, as folks are clearly expecting a different behavior? If it's gnome-flashback specific I'd probably file a feature request with them .. ?

**Comment by kabeersvohra** [comment]
> Hi @jivanmukti smile . The UI for wifi passwords does not pop-up a password dialog. To add a password to a wifi access point, click the "gear" icon to the right of the SSID. In the dialog, go to the "Security" tab and enter the password there.

Hey @kgilmer, I was just wondering why this didn't happen for gnome flashback? I usually find myself spending 5 minutes clicking a new Wifi network before remembering that I need to add the password in the settings of the network, however in normal Ubuntu it would create the dialog box. Not a big deal at all but thanks :)

**Comment by kgilmer** [comment]
Hiya @kabeersvohra :) , well if you run `nm-applet` in the background then you'll get a password prompt for wifi.  In fact most recent versions of Regolith work like this by default.

**Comment by kabeersvohra** [comment]
ah, I do need to upgrade my version of Regolith, thanks a lot for the update Ken :)
