### ISSUE TITLE
after upgrading ubuntu, desktop appears as a new window

### ISSUE THREAD

**Issue by verajosemanuel** [regolith-linux/regolith-desktop#424]
After upgrading to Focal Fossa and updating regolith, the Desktop appears as a window at boot and I'm unable to close it.

**To Reproduce**
upgrade ubuntu
upgrade regolith
reboot

**Installation Details**
 - Regolith Install PPA
 - Regolith Version: 1.41
 - PPA url:  ppa:regolith-linux/release
 - Host OS  Ubuntu 20.04

![2020-05-25_10-55](https://user-images.githubusercontent.com/15836677/82796741-56559400-9e76-11ea-8453-a23c5a2c6f39.png)

**Comment by moritzheiber** [comment]
Could you please remove the `~/.config/regolith/flags` directory and then logout and back in?

**Comment by verajosemanuel** [comment]
Solved! thanks
