### ISSUE TITLE
How do we shift focus out notifications windows?

### ISSUE THREAD

**Issue by jivanmukti** [regolith-linux/regolith-desktop#426]
**Describe the bug**
Whenever I open a notification window such as file search or notification viewer, I can't close the window with super+shift+q. This ends up typing "Q" in the prompt instead. I also can't switch focus to another window using super+shift+f because it inputs "F." Currently I have to click outside the window for it go away window, but I'd prefer a fully keyboard based method to change the focus. Is there such a way?

**To Reproduce**
Press super+n and then super+shift+q

**Expected behavior**
I'm expecting super+shift+q to quit the notification window.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by moritzheiber** [comment]
As per the documentation, to exit the window press `Esc`: https://regolith-linux.org/docs/interface/notifications/

**Comment by jivanmukti** [comment]
That solved it, thank you.
