### ISSUE TITLE
Looking for a way to change the Login screen to any image

### ISSUE THREAD

**Issue by Nero-1984** [regolith-linux/regolith-desktop#427]
Looking for a way to change the Login screen to any image or otherwise further customize the login screen.

 - Regolith Install Type: ISO
 - Regolith Version: 1.4
 - PPA url: [default: ppa:regolith-linux/release]

**Comment by moritzheiber** [comment]
Have you tried choosing a new backgroumd image in GNOME Control Center?

**Comment by Nero-1984** [comment]
I have, the wallpaper changes, the login screen background does not.

**Comment by moritzheiber** [comment]
Regolith uses [LightDM, with its GTK greeter](https://wiki.ubuntu.com/LightDM), as its display manager, so you may drop a configuration file into `/etc/lightdm/lightdm.conf.d/` which ends in `.conf` and add the following content:
```
background=/full/path/to/your/wallpaper
```
Restarting LightDM/rebooting your computer should yield a login screen with the right wallpaper now.

Reference: https://wiki.ubuntu.com/LightDM#Changing_the_Wallpaper

**Comment by Nero-1984** [comment]
Thank you.

**Comment by moritzheiber** [comment]
Can we close this report?

**Comment by Nero-1984** [comment]
yes thank you
