### ISSUE TITLE
Does installing PPA on Xubuntu also install Gnome / Ubuntu desktop?

### ISSUE THREAD

**Issue by kmatt** [regolith-linux/regolith-desktop#43]
With a fresh Xubuntu 19.04 VM installed Regolith and rebooted. Noted that Ubuntu is now an option at login along with Regolith and Xubuntu/Xfce.

Is this expected, perhaps some Ubuntu dependencies?

Interested as Gnome forces some background processes, Evolution factories, etc.

**Comment by kgilmer** [comment]
Interesting, I have not seen that before.  You can remove the package `ubuntu-session` to remove the stock Ubuntu session.  I'm not aware of any resources it would consume if you're not using it, but it's hard to say for sure.  Run this from a terminal if you'd like to remove it:
```
sudo apt remove ubuntu-session
```

**Comment by kmatt** [comment]
Removing ubuntu-session cleaned it up. For reference here are the options when installing Xubuntu 19.04 into a new VM, after installing from the Regolith PPA, and after removing the Ubuntu session:

![VirtualBox_Xubuntu1904_19_06_2019_12_37_54](https://user-images.githubusercontent.com/435936/59785261-5b878780-9292-11e9-9c21-e4af869e47a1.png)

![VirtualBox_Xubuntu1904_19_06_2019_12_55_56](https://user-images.githubusercontent.com/435936/59785267-604c3b80-9292-11e9-8c9b-287452bdb753.png)

![VirtualBox_Xubuntu1904_19_06_2019_12_58_07](https://user-images.githubusercontent.com/435936/59785277-6510ef80-9292-11e9-8f53-f192381cccb0.png)
