### ISSUE TITLE
Using workspace layouts, workspace/monitor specification and Workspace Icon change not working together

### ISSUE THREAD

**Issue by alcarnes** [regolith-linux/regolith-desktop#430]
I am attempting to do 3 main things with my workspaces.  1) redefine the icons 2) place the workspaces on specific monitors 3) load layouts for the workspaces.  I am using a small override in the ~/.config/regolith/i3/config file and a ~/config/regolith/Xresources file for the rest  from which I am copying a script to load the layout.

Added to config file:
```
############################################################################### 
# Monitor / Workspace config 
# 
############################################################################### 
set $monitor_one "DP-0" 
set $monitor_two "HDMI-0" 
workspace 1 output $monitor_one 
workspace 3 output $monitor_one 
workspace 5 output $monitor_one 
workspace 7 output $monitor_one 
workspace 2 output $monitor_two 
workspace 4 output $monitor_two 
workspace 6 output $monitor_two 
workspace 8 output $monitor_two
```
Xresources file: 
```
i3-wm.bar.trayoutput:   primary
i3-wm.gaps.inner.size: 20
i3-wm.program.1: /usr/bin/nm-applet
i3-wm.program.2:  /home/acarnes/.config/i3/i3_restore.sh
i3-wm.workspace.01.name: 1:<span font_desc='FontAwesome Regular 14'>     </span>
i3-wm.workspace.02.name: 2:<span font_desc='FontAwesome Regular 14'>     </span>
i3-wm.workspace.03.name: 3:<span font_desc='FontAwesome Regular 14'>     </span>
i3-wm.workspace.04.name: 4:<span font_desc='FontAwesome Regular 14'>     </span>
i3-wm.workspace.05.name: 5:<span font_desc='FontAwesome Regular 14'>     </span>
i3-wm.workspace.06.name: 6:<span font_desc='FontAwesome Regular 14'>     </span>
```
Script to load Layout:
```
#!/usr/bin/bash
i3-msg "workspace number 1; append_layout /home/acarnes/.config/i3/layouts/1.json"
terminator &
terminator &
terminator &
terminator &
terminator &
terminator &
terminator &
terminator &
i3-msg "workspace number 2; append_layout /home/acarnes/.config/i3/layouts/2.json"
firefox &
i3-msg "workspace number 3; append_layout /home/acarnes/.config/i3/layouts/3.json"
flatpak run org.eclipse.Java -data /home/acarnes/eclipse-workspace &
sleep 4
i3-msg "workspace number 4"
zoom zoom &
discord discord &
sleep 4
i3-msg "workspace number 5"
spotify &
```

The only thing that doesn't seem to work is the icons aren't being changed on the bar for the workspaces.  If I fiddle with not doing layout loading and montior specifying sometimes some of the icons load but never all of them.

Note:  I just tried commenting out the monitor specifying and layout loading and the icons for the workspaces are showing up correctly.  The sleep in the bash script was to allow time for applications to begin to open before creating the new workspaces.  In addition i tried an initial sleep in the bash script of 10 seconds to see if it was starting to load the layout before the workspaces had been fully defined.  Not even sure if that could be an issue but I was trying various things.

_Originally posted by @alcarnes in https://github.com/regolith-linux/regolith-desktop/issues/412#issuecomment-632983670_

**Comment by alcarnes** [comment]
@kgilmer In response to the question you asked previosly, If I push the browser to another workspace and back to the original the icon appears.  It is almost as if there is an order of operations thing.  I.E. it is loading the layout before the icon change has been configured/loaded.

**Comment by kgilmer** [comment]
It's odd @alcarnes .  I don't have any solutions for you at the moment.  One way of verifying the race theory would be to write out the value of a problematic workspace label to a file, to confirm when it's changing.  You can do this with xrescat: `xrescat i3-wm.workspace.01.name >> /tmp/debug.txt`

**Comment by mrzor** [comment]
When you use `workspace number n` in your script, chances are the new styling has not been applied.
I wrote a little script to solve a similar problem. I reckon calling my script at the end of yours should solve your icon issues.
It's at https://gist.github.com/mrzor/aa13ca447ccbeefbefee93def29b7f35
Good luck!

**Comment by kgilmer** [comment]
Thanks providing a suggested fix @mrzor .  @alcarnes let us know if you're able to test this out and if it resolves your issue or not...

**Comment by moritzheiber** [comment]
We haven't heard back from you on this in a while, so I'm assuming this was either fixed by a comment/suggestion in this thread or is not longer relevant. Closing.
