### ISSUE TITLE
apt-get upgrade stuck at: setting up regolith-desktop(2.64-1focal1)

### ISSUE THREAD

**Issue by K-Kouts** [regolith-linux/regolith-desktop#433]
**Describe the bug**
apt is stuck trying to upgrade regolith from what i understand. i tried ctrl c, ctrl z but these created other issues. i tried reinstalling but apt must first be configured, which when done with sudo dpkg --configure -a brings us to the issue at hand(stuck at setting up regolith).

**To Reproduce**

**Expected behavior**
Standard update and upgrade

**Screenshots**

**Configuration file(s)**
No custom config

**Installation Details**
 - Regolith Install Type: [ISO/PPA]
 - Regolith Version: 1.4, i think
 - PPA url: ppa:regolith-linux/unstable
 - Host OS (for PPA): Ubuntu 20.04

**Additional context**

**Comment by moritzheiber** [comment]
This is a known issue on `unstable` and will be fixed by https://github.com/regolith-linux/regolith-desktop/pull/432

**Comment by moritzheiber** [comment]
The package is pushed to `unstable` now. Please give it a try.

**Comment by K-Kouts** [comment]
Fixed! Thank you!
