### ISSUE TITLE
Convert Regolith package repos to use gbp

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#434]
The `gbp` tool makes packaging w/ git repos more consistent and less error prone.  To use it we'll most effectively we should follow the branch name conventions and add gbp.conf files as needed.  

https://honk.sigxcpu.org/piki/projects/git-buildpackage/

```
regolith-compositor-*
regolith-desktop
regolith-ftue
regolith-gnome-flashback
regolith-i3-gaps-config
regolith-i3xrocks-config
regolith-rofi-config
regolith-rofication
regolith-styles
regolith-system
```

**Comment by kgilmer** [comment]
`regolith-desktop` converted.  Branches are bionic, eoan, and debian.  gbp.conf files added to specify that package is "native".

**Comment by kgilmer** [comment]
`regolith-ftue` change pushed.  everything in master.

**Comment by kgilmer** [comment]
`regolith-gnome-flashback` change done, also w/ gsettings overrides and disambiguation from `i3-gnome-flashback` complete.

**Comment by kgilmer** [comment]
`regolith-i3-gaps-config` complete.

**Comment by kgilmer** [comment]
Getting weird build errors w/ `regolith-i3xrocks-config`, will have to investigate when i have more time:

```
$ gbp buildpackage --git-tag
gbp:info: Exporting 'HEAD' to '/tmp/debian-pkg-builds/regolith-i3xrocks-config-tmp'
gbp:info: Moving '/tmp/debian-pkg-builds/regolith-i3xrocks-config-tmp' to '/tmp/debian-pkg-builds/regolith-i3xrocks-config-3.0.30'
gbp:info: Performing the build
debuild: fatal error at line 679:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
gbp:error: 'debuild -i -I' failed: it exited with 255
```

This works fine w/ builddeb and can't get any more info about the error atm.

**Comment by kgilmer** [comment]
It was `.gitattributes` that was causing the build error.  Removed the file and finished `regolith-i3xrocks-config` migration.

**Comment by kgilmer** [comment]
`regolith-rofi-config` is done.

**Comment by kgilmer** [comment]
@farsil expressed interest in migrating `regolith-rofication` so skipping that one.  `regolith-styles` complete.

**Comment by kgilmer** [comment]
`regolith-system` complete.

**Comment by kgilmer** [comment]
`regolith-compositor-*` pushed

**Comment by moritzheiber** [comment]
@kgilmer What's the status of this? I think we're pretty much done, right?

**Comment by kgilmer** [comment]
Yes, thanks afaik everything is using gbp now.  Closing.
