### ISSUE TITLE
How to change super modifier?

### ISSUE THREAD

**Issue by yssoe** [regolith-linux/regolith-desktop#437]
I use a kinesis keyboard so the windows super key is on the same side of the enter key so i want to modify this to ctrl or alt

how do i do this i search and i find this

https://regolith-linux.org/docs/howto/super-to-alt/  

but that documentation is not there anymore

thanks

**Comment by moritzheiber** [comment]
It has moved here: https://regolith-linux.org/docs/getting-started/configuration/#keybindings
