### ISSUE TITLE
PPA r1.3 404 not found for Ubuntu Focal (20.04)

### ISSUE THREAD

**Issue by jskierbi-signavio** [regolith-linux/regolith-desktop#439]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)

- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I'm using r1.3 stable PPA, after updating to 20.04 I'm getting:
```
http://ppa.launchpad.net/regolith-linux/r1.3/ubuntu focal Release                                  
  404  Not Found [IP: 91.189.95.83 80]
```

**To Reproduce**
Install Ubuntu 20.04, add r1.3 ppa (as documented here: https://regolith-linux.org/docs/getting-started/install/#ppa-sources, run `sudo apt update` -> error occurs.

**Expected behavior**
PPA works as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/49191181/83444310-8212e400-a44b-11ea-8b42-1cd1abf93f6d.png)

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.3
 - PPA url: ppa:regolith-linux/r1.3
 - Host OS (for PPA): Ubuntu 20.04

**Comment by cjohnston1158** [comment]
I don't believe that 1.3 is supported on 20.04

**Comment by moritzheiber** [comment]
Yes, Focal Fossa is only supported with Regolith 1.4x. Please upgrade to the latest release :slightly_smiling_face: 

https://regolith-linux.org/docs/getting-started/install/#regolith-13---regolith-14
