### ISSUE TITLE
Media Keys with Gnome-flashback/Regolith/i3

### ISSUE THREAD

**Issue by leosunmo** [regolith-linux/regolith-desktop#44]
After installing Regolith on top of my regular Ubuntu 19.04 installation the Media keys stopped working. This was somewhat expected as I've had this issue in the past, and only stock Gnome seems to work perfectly for me out of the box.
a
I should clarify that it's only Play/Pause and Next/Previous track that doesn't work, **volume up/down** works as **expected**.

Some clues here https://askubuntu.com/questions/848856/gnome-settings-daemon-grabs-multimedia-keys-and-drops-mute-since-upgrade-16-04

We'll probably need to mess with Gnome-flashback to patch in this behaviour, some more clues from Arch: https://aur.archlinux.org/packages/gnome-settings-daemon-compat/

There might be a canonical i3 way or doing this, I'm not sure, that might be a lot easier! A quick Google gave me https://github.com/acrisci/playerctl, which would probably solve my particular issue since I use Spotify, but it would be nice to roll a universal solution in to Regolith.

**Comment by kgilmer** [comment]
Hmm, I'm not sure how I can reproduce this issue.  Are you using a keyboard with extra dedicated media keys or are they mapped to function keys?

Either way, yes you can explicitly define actions for specific key combinations and add them to your i3 config.  This section in the i3 User Guide covers the topic: https://i3wm.org/docs/userguide.html#keybindings.  Essentially you can use a program to find out the keycode and then in your config have it execute some command when that key is pressed.

**Comment by leosunmo** [comment]
This is just the "normal" media keys, and I just managed to fix it by rebooting _twice_ for some reason. So that's nice I guess, but I'm none the wiser as to why they stop working suddenly.

**Comment by leosunmo** [comment]
I'd still like to know what picks up on these key presses and how they get sent/picked up by the correct media application.

**Comment by leosunmo** [comment]
![Screenshot from 2019-06-19 16-58-07](https://user-images.githubusercontent.com/13341934/59737951-a4036d00-92b3-11e9-8984-dadadf67929c.png)
Ran `xwinifo` and it looks like `gnome-flashback` does handle the media keys, so I guess I'll have to go down that path instead. Thanks!

**Comment by kgilmer** [comment]
Hi Leo, looks like you're on your way and yes it's my estimation as well that gnome-flashback is handling this logic.  For what it's worth the [developers on that project](https://gitlab.gnome.org/GNOME/gnome-flashback/issues/) have been very helpful to me in the past.
