### ISSUE TITLE
A blank window will spark out when clicking the mouse

### ISSUE THREAD

**Issue by goshinh** [regolith-linux/regolith-desktop#441]
**Describe the bug**
When I click the mouse,a blank window will come out.I gonna crazy.

**Screenshots**
![Peek 2020-06-03 08-41](https://user-images.githubusercontent.com/1208604/83583426-e7afbf00-a576-11ea-954f-d42261696e71.gif)

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 18.04.2]

**Comment by kgilmer** [comment]
Hi @goshinh , my first guess is a compositor issue.  Can you try installing `regolith-compositor-none` and see if the problem goes away after logging back in?

More info: https://regolith-linux.org/docs/customize/compositors/

**Comment by moritzheiber** [comment]
We haven't heard back from you about this issue for a while, so I'm assuming it has either been fixed by what Ken suggested or is no longer relevant.
