### ISSUE TITLE
let set_look() overwrite the user Xresources file

### ISSUE THREAD

**Issue by iSmashButtons** [regolith-linux/regolith-desktop#444]
- [x] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the solution you'd like**
I want to be able to easily switch between *looks* with a single command: `regolith-look set [look]`.

**Describe alternatives you've considered**
commented-out lines 76-79 of `regolith-look` script.

**Additional context**
By reading the [look documentation](https://regolith-linux.org/docs/customize/look/), one is given the impression a user can simply switch from one *look* to another with the command `regolith-look set [look]`. However, this is not possible because the script will exit if it finds that `$HOME/.Xresources-regolith` already exists. Why not just overwrite this file?

The documentation does not mention you must first delete your `~/.Xresources-regolith` file before switching your *look* with `regolith-look set`. Instead of typing one command to switch looks, I have to type three.

- `rm ~/.Xresources-regolith`
- `regolith-look set [look]`
- `regolith-look refresh`

I removed lines 76-79 from the `regolith-look` script (first `if` statement in the `set_look` function), and now the script will overwrite my `~/. Xresources-regolith` file, with a new `include` pointing to the installed *look* I specified. I have not yet noticed any ill side-effects from doing this. The `if` statement checking for this file in the script seems unnecessary.

**Comment by kgilmer** [comment]
Hi @iSmashButtons , yep sounds good.  Thanks for creating the feature request.

**Comment by iSmashButtons** [comment]
Hi all. Remember when I said I found no side-effects from commenting-out that if-statement? Well, I am a bit embarrassed now that I've spent a few hours adding to my Xresources, only to have it overwritten when I switched looks with `regolith-look set`. Now I understand why that check is there, and it should probably stay there, so I am closing this issue.

**Comment by kgilmer** [comment]
well I think we can still make the workflow more concise w/ a bit of attention on the script.  Out of curiosity @iSmashButtons, you're aware of adding Xresource overrides in `~/.config/regolith/Xresources` as an alternative to adding things to `~/.Xresources-regolith`?

**Comment by iSmashButtons** [comment]
Yes, I just became aware of that this morning as I was reading more docs. I just upgraded from an older version of regolith where `regolith-look` wasn't a thing. A lot has changed with this project since the last time I visited, and it all looks very good. I love Regolith, you guys are doing a great job 😄 👍 .
