### ISSUE TITLE
External monitor turns black for 1 sec on specific actions

### ISSUE THREAD

**Issue by RGring** [regolith-linux/regolith-desktop#445]
Hi,
First of all thanks for the nice work. It is exactly what I was looking for.
Unfortunately when I have an external monitor attached, on some actions it happens, that my screen of the external monitor turns black for approx. 1 sec. Actions that trigger this are: starting the settings application, starting vlc or the worst getting a notification from Microsoft teams. Do you have an idea what that could be?

**Comment by priestoferis** [comment]
I think it is most likely a compositor issue. You can try changing to a different one, you can find info about that here: https://regolith-linux.org/docs/customize/compositors/

**Comment by RGring** [comment]
I tried the xcompmgr compositor... unfortunately that didn't help. Is there another compositor, you can recommend trying out?

**Comment by priestoferis** [comment]
Maybe try `apt install regolith-compositor-none`? If it still doesn't go away at least we'll know it is not the compositor.

**Comment by kgilmer** [comment]
@RGring after changing the compositor, you'll need to log back in before the change takes effect.

**Comment by moritzheiber** [comment]
We haven't heard back on this issue for a while, I'm assuming it's either fixed or no longer relevant. Closing.
