### ISSUE TITLE
armv7l packages missing

### ISSUE THREAD

**Issue by cmF3** [regolith-linux/regolith-desktop#446]
Hi.
The PPA does not contain packages for armv7l.
This is very sad.

**Comment by kgilmer** [comment]
Hi @cmF3 , which of these would make you happy?

```
 AMD x86-64 (amd64)
 ARM ARMv8 (arm64)
 ARM ARMv7 Soft Float (armel)
 ARM ARMv7 Hard Float (armhf)
 Intel x86 (i386)
 PowerPC (powerpc)
 PowerPC64 Little-Endian (ppc64el)
 RISC-V 64-bit (riscv64)
 IBM System z (s390x)
```

**Comment by cmF3** [comment]
armhf would make me very happy.
By the way, amd64 is already supported.

**Comment by kgilmer** [comment]
Ok.  I've enabled armhf build targets in the PPA configuration.  I'll let you know when packages are available.

**Comment by kgilmer** [comment]
(Yes, I just pasted every build target available via Lauchpad due to lazyness)

**Comment by moritzheiber** [comment]
`armhf` is enabled for all supported versions on the `release` PPA (which is what I checked). Closing.
