### ISSUE TITLE
after upgrading to 1.4.1 i3xrocks will showing

### ISSUE THREAD

**Issue by ellsium** [regolith-linux/regolith-desktop#451]
- [ y] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner) similar issue but nor resolving my case
- [y ] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ y] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
i3xrocks removed after upgrading to 1.4.1. I have tried installing them but they still dont show. i check my i3 config and i still have the old version.

i have search for the latest /etc/regolith/i3/config file but only found older ones.

does anyone have a link for the latest config?

Thank you

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: [ISO/PPA]
 - Regolith Version: [e.g. 1.4]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 20.04]

**Additional context**

**Comment by priestoferis** [comment]
I don't know what went wrong, but this is the repo for the i3xrocks configs: https://github.com/regolith-linux/regolith-i3xrocks-config. Which version were you upgrading from?

**Comment by ellsium** [comment]
came up from 1.3. Thank you for the link. will diff the two. do you have /etc/regolith/i3config also. mine is really messed up.

**Comment by priestoferis** [comment]
Sure, that one's here: https://github.com/regolith-linux/regolith-i3-gaps-config. Otherwise, still not sure what could have gone wrong :)

**Comment by ellsium** [comment]
@priestoferis thank that fixed it. perfect have a great day

**Comment by ellsium** [comment]
Was hoping that would fix getting rid of the transparent window that is there on start up and cant be closed. right clicking this window (transparent no border or titlebar) gives me a a menu. one option is new folder. when i click it a dialog opens to type folder name. then when i click ok nothing happens. is this a new feature?

**Comment by kgilmer** [comment]
Hi @ellsium , this is due to a change in gnome-flashback.  Regolith will fix your session if you delete the Regolith flags directory and log back into your session.  

```bash
$ rm ~/.config/regolith/flags
```

Kindly reopen the issue if that does not fix it for you.
