### ISSUE TITLE
Ability to remove gvfs

### ISSUE THREAD

**Issue by sjuswede** [regolith-linux/regolith-desktop#452]
I put this issue up on Slack, and was requested to create an issue.

I run Regolith on a very low resource chromebook converted to full Linux. I want to keep the resource usage and number of daemons down, for several reasons.

One of the standard things I do on a machine like that is remove gvfs, since I have no use of that on a low resource machine which interacts with the outside world solely using ssh.

Unfortunately, doing that on Regolith will remove pretty much everything, since the core system requires gnome-terminal and nautilius. I use urxvt, and on this system I do not even use a file manager, so uninstalling those would be fine - but they take the entire regolith base package with them.

It would be wonderful if this could be solved, so I don't have to go back to hand-hacking from a raw text install. Regolith scratches so many of my itches otherwise, it's amazing.

**Comment by kgilmer** [comment]
This has been addressed in the various regolith meta packages.  For example, `regolith-desktop-standard` does not have a hard dependency on `nautilus`.  I suggest you go with `regolith-desktop-minimal`.
