### ISSUE TITLE
Disable "desktop window"

### ISSUE THREAD

**Issue by ellsium** [regolith-linux/regolith-desktop#454]
- [y ] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [y ] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the solution you'd like**

When the OS loads it creates a desktop as a window, where one may store folders. I find i lose virtual desktop 1 due to this desktop window feature taking up space. I have searched but there seems to be no mention of this, nor anyone else wanting to disable it.
How can i disable this? is it part of lightdm as it is not a i3xrocks feature?

Thank you for your help and the best linux experience in 20 years.

**Describe alternatives you've considered**
Was maybe going to try removing desktop 1 in the i3/config

**Additional context**

**Comment by kgilmer** [comment]
Hi @ellsium , I'm guessing this occurred after an upgrade.  Some GNOME flags need to be reset, please perform the following steps:

1. remove the directory `~/.config/regolith/flags`
2. log back into your session

Kindly re-open this issue if that does not resolve your issue, and happy to hear that you're liking Regolith!

**Comment by ellsium** [comment]
Thank you for the response. That solved it. FYI i upgrade one system and one was a new install. both gave the desktop.

Liking it! loving it. its perfect. Thank you for your vision and hard hard work! Well done.

**Comment by eloipereira** [comment]
I'm getting the same issue after upgrading to 20.04 and removing the `~/.config/regolith/flags` didn't solve it. Any ideas?

**Comment by kgilmer** [comment]
Hi, does `gsettings set org.gnome.gnome-flashback desktop false` work @eloipereira ?

**Comment by eloipereira** [comment]
> Hi, does `gsettings set org.gnome.gnome-flashback desktop false` work @eloipereira ?

@kgilmer yes that worked. I had to set a few other variables as well but all looks good now. Thanks a lot.
