### ISSUE TITLE
desktops are duplicated

### ISSUE THREAD

**Issue by verajosemanuel** [regolith-linux/regolith-desktop#459]
**Describe the bug**
I usually start my workday opening a bunch of terminals. (dual monitors) so a pair of them are in monitor 1 (desktop 1) and another pair in monitor 2 (desktop 2).

when I press $mod+1 to go to desktop 1, a new desktop 1 is created empty. The bar is showing two  number 1 desktops.
I can move windows to desktop 1 pressing $mod+Shift+1 (window by window) and then just one desktop 1 is available for the rest of the session.

**To Reproduce**
Open a pair of windows
press $mod+1

![2020-07-06_15-42](https://user-images.githubusercontent.com/15836677/86601703-ecb2c480-bfa1-11ea-8061-67c711757d95.png)

**Expected behavior**
Only one desktop per number is expected.

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [ 1.4]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [ubuntu Focal Fossa]

**Comment by CommonTroll** [comment]
This could potentially be an i3 config issue, if you've modified your i3 config could you post it?

**Comment by verajosemanuel** [comment]
yes, I've added the keybinds below.

The rest is plain fresh vanilla installed config.

`bindsym $mod+u exec ~/.dotfiles/scripts/rofi-bluetooth
 bindsym $mod+s exec cat ~/.config/rofi/rofi-shortcuts/rofi-shortcuts.conf | rofi -i -dmenu -p "shortcuts"
 bindsym $mod+z exec /usr/bin/python3 ~/.dotfiles/scripts/clip-snippet.py type ~/.dotfiles/scripts/snippets.yml
 bindsym $mod+Shift+z exec /usr/bin/python3 ~/.dotfiles/scripts/clip-snippet.py copy ~/.dotfiles/scripts/snippets.yml
 bindsym $mod+b exec /usr/bin/firefox-trunk
 bindsym $mod+y exec rofi -show ssh -theme $rofiTheme
 bindsym $mod+d exec ~/.dotfiles/scripts/i3-display-swap.sh
 bindsym $mod+F12 exec rofi -show drun -show-icons -theme $rofiTheme
 bindsym $mod+F11 exec rofi -show run -theme $rofiTheme
 bindsym $mod+F10 exec --no-startup-id rofi -modi combi -combi-modi window -show combi
 bindsym $mod+F9 exec rofi-pass.sh -show run -theme $rofiTheme
 bindsym Mod1+Tab exec rofi -show window -theme $rofiTheme
 bindsym $mod+w exec rofi-web-search.sh -show run -theme $rofiTheme
`

**Comment by kgilmer** [comment]
Hmm, I use Regolith w/ 2 and 3 monitor setups and do not experience this issue.  This could be related to something that creates or modifies workspaces without the styling label.  [See here](https://github.com/regolith-linux/regolith-desktop/issues/430#issuecomment-655619143) for a possible fix.

**Comment by moritzheiber** [comment]
So, if you've reset the `$ws1` variable (which you have [in your custom configuration](https://github.com/verajosemanuel/.config/blob/master/config#L90)) and you're using a space in the name (e.g. "1 something") you have to put the assignments you're using them with in quotation marks, e.g. on [line 165](https://github.com/verajosemanuel/.config/blob/master/config#L165):
```
bindsym $mod+1 workspace number "$ws1"
```
I believe i3 doesn't recognize the whole name as one unit because of the space and discards the rest, leading to "`1`" being the default, and "` 1 `" being the actual workspace name you're switching to it. #430 is also definitely related.

**Comment by verajosemanuel** [comment]
> So, if you've reset the `$ws1` variable (which you have [in your custom configuration]
All that name settings are commented, so I assume is not affecting in this issue

**Comment by kgilmer** [comment]
[Here is where](https://github.com/verajosemanuel/.config/blob/master/config#L68) your workspace labels are defined.  What does `xrescat i3-wm.workspace.01.name` return?

**Comment by verajosemanuel** [comment]
` xrescat i3-wm.workspace.01.name 
1:<span font_desc='JetBrains Mono Medium 13'> 1 </span>%  `

yeah but I assume that is the default definition from fresh vanilla regolith config file. I did not touch it.

**Comment by kgilmer** [comment]
Here is what I have.  Where is that trailing `%` coming from?

```bash
$ xrescat i3-wm.workspace.01.name
1:<span font_desc='JetBrains Mono Medium 13'> 1 </span>
```

**Comment by verajosemanuel** [comment]
It appears at the end when firing the command. Not a typo

**Comment by kgilmer** [comment]
Ok well I don't know why that's happening on your computer @verajosemanuel but it's likely that would cause the behavior of your issue as your workspace names are not valid Pango markup.

**Comment by verajosemanuel** [comment]
I’m Going to remove and reinstall with fresh configure files.

**Comment by mvartanyan** [comment]
Affects me as well. Some popups are appearing on duplicate screens. Typically, the duplicate desktops will have less space around their number in the selector area. Multi-monitor setup (four virtual screens made with xrandr on a very large screen), but otherwise a vanilla setup.

**Comment by kgilmer** [comment]
@verajosemanuel any update after reinstallation?  @mvartanyan what do you mean by pop up?  A screenshot of your problem would be helpful to understand.

**Comment by kgilmer** [comment]
Closing for lack of response
