### ISSUE TITLE
VPN does not work

### ISSUE THREAD

**Issue by dvf** [regolith-linux/regolith-desktop#460]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Ubuntu 20.04

There are three problems here:
- After adding a VPN in settings, it toggles immediately to "off". I fixed that problem by following the steps in https://github.com/regolith-linux/regolith-desktop/issues/277. 
- But now I'm unable to edit the settings of the VPN. If I remove a route in the VPN settings and click "Apply" the window goes blank.
  ![image](https://user-images.githubusercontent.com/1169974/86956952-f5350780-c127-11ea-958a-fee1a54b2e0c.png)
  ![image](https://user-images.githubusercontent.com/1169974/86956967-fa925200-c127-11ea-82de-bf23cced91b3.png)
- If there's a misconfiguration of the VPN, I'm not sure where to find the error without jumping into the logs. Perhaps I'm a noob and haven't set things up correctly but I couldn't find anything in the documentation.

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 20.04

I'm in love with regolith (thank you for developing such an awesome system) :pray: any help here would be appreciated.

**Comment by priestoferis** [comment]
I have the same issue, I didn't think it is a regolith issue, although I might not be right with that. I use the CLI interface as a workaround for now (it works and I haven't bothered trying to go further than that).

**Comment by kgilmer** [comment]
@dvf were you able to use @priestoferis 's suggestion w/ the CLI interface?  I recall some users had better luck w/ VPN by running `nm-applet` in the background, but I do not use a VPN myself.

**Comment by grerrg** [comment]
Are you using wireguard- or openvpn-client?
I couldn't connect via the `network-manager` too. In my case, with openvpn-client, i connected via cli and had to setup DNS in `network-manager`. Works fine.

**Comment by ferdinandyb** [comment]
In the meantime I actually started using `nm-applet` for the VPN which works fine.

**Comment by moritzheiber** [comment]
I'm closing this for now as this is probably dependent on GNOME Flashback (i.e. you'd have to file this issue upstream) and there's a workaround which works and has been mentioned in the comments.
