### ISSUE TITLE
`~/.regolith-gnome-backup` file not found while uninstalling regolith

### ISSUE THREAD

**Issue by jadia** [regolith-linux/regolith-desktop#461]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
The file backup file for gnome settings is not present at `~/.regolith-gnome-backup`. 
Gnome settings are not restored after uninstalling Regolith.

**To Reproduce**

1. Install Regolith using PPA on Ubuntu 20.04.  
2. Follow the uninstallation steps given here : [https://regolith-linux.org/docs/getting-started/install/#uninstallation-of-regolith-desktop](https://regolith-linux.org/docs/getting-started/install/#uninstallation-of-regolith-desktop)
3. `source ~/.regolith-gnome-backup` command did not run successfully.

**Expected behavior**
Gnome settings prior to installing Regolith should have been restored. 

**Screenshots**
A screenshot of my terminal after the uninstallation.
![Screenshot from 2020-07-09 10-47-13](https://user-images.githubusercontent.com/7502844/87000050-c07d8a80-c1d1-11ea-8c16-36ee65e4e3cf.png)

**Configuration file(s)**
No customization from my side. 

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: Did not check. Whatever PPA provided as on 09-07-2020.
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 20.04]

**Additional context**
The following commands did help me get back my default theme and icons. 

```bash
gsettings reset org.gnome.desktop.interface gtk-theme
gsettings reset org.gnome.desktop.interface icon-theme
gsettings reset org.gnome.desktop.wm.preferences button-layout
```
I manually changed the terminal theme to default.

**Comment by moritzheiber** [comment]
I think this has changed and the documentation does not reflect the new behavior. I'm assigning this to @kgilmer to make sure we've got our bases covered.

**Comment by kgilmer** [comment]
Hi @jadia , sorry for the trouble.  The file `~/.regolith-gnome-backup` may have a suffix on it, check your home dir for variations depending on which version of Regolith you installed.  As @moritzheiber mentioned, some changes are happening in this area but since you installed from the `release` PPA these changes would not impact you.

If you do not have any regolith backup file, that's puzzling.  This is the first mention of a problem with it since the feature was added afaik.

**Comment by kgilmer** [comment]
I realize that since you've uninstalled Regolith that you're probably not keen to spend time troubleshooting this issue, so I'll close it.  If you are, or have any other information of questions, feel free to re-open.
