### ISSUE TITLE
"Desktop window" 

### ISSUE THREAD

**Issue by ElCbo** [regolith-linux/regolith-desktop#462]
Hi folks,
did not find an answer so I need to ask. I'm running regolith desktop 2.63-1focal1 on Ubuntu 20.04 LTS.
I have this "Desktop"  window which can't be closed, albeit I can push it to scratchpad.

I used regolith on Ubuntu 18.10 before and there wasn't this window. Any idea how to get rid of it?

Attached a screenshot with the desktop window in the top left corner.

Best regards
Christopher
![Bildschirmfoto von 2020-07-10 19-30-31](https://user-images.githubusercontent.com/67418740/87182152-ded3ab00-c2e3-11ea-8db3-ad4dc241e536.png)

**Comment by hypergig** [comment]
That is totally a failed application, this use to happen to me all the time with Alacritty and I will `killall alacritty` and it wold be fixed. If you `xprop` it what does it say?

**Comment by ElCbo** [comment]
Hi, thanks, good point with xprop
```
xprop
_NET_WM_USER_TIME(CARDINAL) = 85902
_NET_WM_WINDOW_OPACITY(CARDINAL) = 4294967295
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0xa00001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DESKTOP
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 10485765, 10485766
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0xa00004
WM_CLIENT_LEADER(WINDOW): window id # 0xa00001
_NET_WM_PID(CARDINAL) = 1857
WM_LOCALE_NAME(STRING) = "de_DE.UTF-8"
WM_CLIENT_MACHINE(STRING) = "helios"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 1920 by 1080
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "gnome-flashback", "Gnome-flashback"
WM_ICON_NAME(STRING) = "Desktop"
_NET_WM_ICON_NAME(UTF8_STRING) = "Desktop"
WM_NAME(STRING) = "Desktop"
_NET_WM_NAME(UTF8_STRING) = "Desktop"

```

after killing gnome-flashback the window disappeared.
Any Idea how to prevent gnome-flashback from loading?

**Comment by hypergig** [comment]
oh my gosh... this is totally a very real (gross) bug... gnome flashback should never have a window.. so that is super odd

**Comment by CommonTroll** [comment]
I fixed this issue by removing the contents of `~/.config/regolith/flags/` and re-logging. I believe the issue is caused by how Regolith handles updates as unintrusively as possible, causing some settings to not be automatically reset upon updating.

**Comment by ElCbo** [comment]
@CommonTroll Thanks. This totally worked!

**Comment by fredRos** [comment]
I had the same issue after upgrading from Ubuntu 18.04 to 20.04 

> after killing gnome-flashback the window disappeared.

but then you can't log out using the usual regolith way. And you probably lose many other features provided by gnome-flashback

Killing just the window with Super Alt Q only helps temporarily, as the window reappears.

>  fixed this issue by removing the contents of ~/.config/regolith/flags/ and re-logging

This didn't help me. 

> I believe the issue is caused by how Regolith handles updates as unintrusively as possible, causing some settings to not be automatically reset upon updating.

this and https://regolith-linux.org/docs/howtos/configure-wallpaper/ gave me the right hints. 

I fixed the problem by configuring gnome-flashback  properly. Apparently the settings changed with the distribution upgrade

```
at 10:36:14 ❯ gsettings set org.gnome.gnome-flashback.desktop draw-background false 

at 10:36:27 ❯ gsettings set org.gnome.gnome-flashback.desktop show-icons  false 
```
no logging out or restarting required
