### ISSUE TITLE
cannot start polybar

### ISSUE THREAD

**Issue by RafalSkolasinski** [regolith-linux/regolith-desktop#464]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

Polybar does not start. It throws following errors
```
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
error: module/xbacklight: Could not get data (err: XCB_NAME (15))
error: Disabling module "xbacklight" (reason: Not supported for "eDP-1")
warn: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
error: Disabling module "wlan" (reason: Invalid network interface "net1")
error: Disabling module "eth" (reason: Invalid network interface "ens2")
error: module/mpd: Connection refused
warn: Systray selection already managed (window=0x3c0000c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e238)
warn: Dropping unmatched character  (U+e0ca)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e238)
warn: Dropping unmatched character  (U+e0ca)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
error: module/mpd: Connection refused
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e237)
warn: Dropping unmatched character  (U+e0ca)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
error: module/mpd: Connection refused
error: module/mpd: Connection refused
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e028)
warn: Dropping unmatched character  (U+e026)
warn: Dropping unmatched character  (U+e236)
warn: Dropping unmatched character  (U+e0ca)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e10c)
error: module/mpd: Connection refused
```

**To Reproduce**
1. Ubuntu 20.04
2. Follow steps from wiki: https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Swap-out-i3bar-for-Polybar
3. Cry

**Expected behavior**
Polybar starts and life is awesome

**Screenshots**

**Configuration file(s)**
Errors visible even when starting polybar from CLI as 
```
polybar example
```
with unmodified polybar config

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [e.g. 1.4]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 20.04]

**Additional context**
```
satriani ➜  ~ cat /etc/apt/sources.list.d/kgilmer-ubuntu-speed-ricer-focal.list                                                                                
deb http://ppa.launchpad.net/kgilmer/speed-ricer/ubuntu focal main
# deb-src http://ppa.launchpad.net/kgilmer/speed-ricer/ubuntu focal main
```

**Comment by kgilmer** [comment]
I am not a polybar expert but it seems from your paste that the errors are related to polybar front-end modules trying to attach to daemons and failing.  Also, you don't specify if the command returns with an exit code or if there may be additional error text that may be relevant.  I would suggest using a polybar config that is minimal and does not contain modules for which I do not have the backend packages installed.  Also, paste the full text from the command to aid in troubleshoot.

Also, kindly keep in mind that this Polybar package is provided as a convenience to general Ubuntu users, and is not really supported as part of Regolith in the same manner that default packages (such as i3 bar) are.

**Comment by Nesaijn** [comment]
It would still be helpful to see your polybar configs but can also be solved without.
Make sure you have the right fonts installed. That would get rid of the "warn: Dropping unmatched character ..." warnings.
Siji Fonts needs to be installed. They are for the icons that show up next to the modules.
On Ubuntu it seems to be in the `x11-utils` package. So run:
```
sudo apt install x11-utils
```
You can see the fonts needed in the config. The lines start with "font-x = ..." where x is a number starting at 0.

It seems that you don't have mpd installed, that is why mpd fails:
`error: module/mpd: Connection refused`

You can take that module out by removing it in the config. There is a comment where it says "Modules Location"
There should be a line with: "modules-left", "modules-center" or "modules-right" and remove mpd from that line.

Regarding these two lines:
```
error: Disabling module "wlan" (reason: Invalid network interface "net1")
error: Disabling module "eth" (reason: Invalid network interface "ens2")
```

You have to replace the example interfaces given in the config with your own.
run `ip -br a s`. Depending on what you are using, wifi or ethernet, this one should be shown as `UP`. Here is my example:
```
$ ip -br a s
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp6s0           UP             192.168.0.74/24
```
On the left is the interface name, with which you have to replace the one in the config.
In my case where I use ethernet I would have to go to the ethernet module in polybar config (which starts where the line says `[module/eth]`) and replace the option `interface = ens2` with yours. In my case:
`interface = enp6s0`

The same steps apply to wifi but for the wifi module (`[module/wifi]`).

That should get rid of the most errors and warnings. After you have fixed these you can show the remaining errors and warnings.

**Comment by RafalSkolasinski** [comment]
Thank you @Nesaijn, I gonna check your suggestions. 

I didn't use `polybar` in the past and simply wanted to try it out. 
I have a default config obtained following steps from Regolith wiki:
```
$ cp /usr/share/doc/polybar/config.gz .
$ gunzip config.gz  # You will want to edit this file at some point to configure Polybar
```
so no customisation there.

**Comment by Nesaijn** [comment]
Sometimes the maintainers of the packages do some changes to the default configurations so that it better suits their system etc., that's why. 
Report back after you tried. This is normal Polybar behaviour and has porobably nothing to do with regolith.

**Comment by kgilmer** [comment]
Closing as not an issue w/ Polybar but in just using the default config which isn't supported in Regolith (Polybar generally, or the default config in particular).
