### ISSUE TITLE
Intellij pop window issue

### ISSUE THREAD

**Issue by sandeepchitturi** [regolith-linux/regolith-desktop#465]
Hello, 
I have strange issue with intellij, when i click on commit button. This commit files window is stuck in upper left most corner and i am also not able resize intellij.my laptop resolution is  Please find the screen of the issue below:
![Screenshot from 2020-07-21 18-12-56](https://user-images.githubusercontent.com/2590549/88057020-17df0b80-cb7f-11ea-96b8-652af1c34d69.png)
Please find resolution and sys config below:
![Screenshot from 2020-07-21 18-17-23](https://user-images.githubusercontent.com/2590549/88057071-2b8a7200-cb7f-11ea-878e-f467569a67c6.png)
![Screenshot from 2020-07-21 18-17-51](https://user-images.githubusercontent.com/2590549/88057076-2d543580-cb7f-11ea-9bb0-71fc8ab7d83f.png)

**Comment by GijsVermarien** [comment]
Have you tried pressing mod + shift + j, then the screen can go from floating to tiling. Otherwise you could try pressing mod + r and then resizing the window using h and j, so it becomes small enough for you to use in floating mode.

**Comment by priestoferis** [comment]
If you press super you can drag it into view. If this is general problem you can add something to your i3 config to put it always where you want it.

**Comment by sandeepchitturi** [comment]
Thanks super + drag solves my problem
