### ISSUE TITLE
Regolith Desktop Clean Install Issue

### ISSUE THREAD

**Issue by dtsdwarak** [regolith-linux/regolith-desktop#466]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

## Describe the bug
Issue with Regolith Desktop 1.4 upgrade. Unable to use Regolith.

## To Reproduce

After a botched upgrade to Regolith Desktop 1.4, I tried to clean up the complete install as follows - 

```bash
$ rm -rf ~/.regolith-gnome-backup
$ rm -rf ~/.config/regolith
$ rm -rf ~/.config/i3
$ sudo rm -rf /etc/regolith/
$ sudo apt remove i3*
$ sudo apt purge i3*
$ sudo apt-get purge i3-wm
$ sudo apt-get purge --auto-remove i3-wm

# Remove all packages that appear for the following commands
$ apt list --installed | grep regolith
$ apt list --installed | grep ^i3
```

Post that I encountered "status command not found or is missing a library dependency", for which I installed the following as per the [Reddit reference](https://www.reddit.com/r/linuxquestions/comments/6942tr/i3_error_status_command_not_found_or_is_missing_a/) and [Issue #167](https://github.com/regolith-linux/regolith-desktop/issues/167).

```bash
$ sudo apt install i3status suckless-tools i3blocks
```

I still see issues in launching the desktop. The desktop is still loading and not able to interact with it except Win+Shift+E to shut down the machine and even the i3-bar looks very vanilla.

### Post `i3blocks` installation

![Screenshot from 2020-07-22 22-21-18](https://user-images.githubusercontent.com/2745182/88207414-636fe300-cc6d-11ea-8240-acd816dd05b3.png)

## Installation Details
 - Regolith Install Type:PPA
 - Regolith Version: 1.4
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 18.04

**Comment by kgilmer** [comment]
Hi @dtsdwarak :smile: .  If your goal is to reinstall Regolith, you don't need any of `i3status suckless-tools i3blocks`.  You shoudn't have problems keeping them installed but they are not used by Regolith.  See here for details on how to restore your installation: https://regolith-linux.org/docs/getting-started/install/#reinstallation

Kindly reopen the ticket if the instructions do not work for you.

**Comment by dtsdwarak** [comment]
Hi @kgilmer 

Not sure how I missed this. Thanks a ton. Installation works as expected.
