### ISSUE TITLE
Xresources documentation incorrect rofi icon theme key

### ISSUE THREAD

**Issue by drewofdoom** [regolith-linux/regolith-desktop#467]
The Xresources documentation lists the `rofi.drun-icon-theme` key, but this key should actually be `rofi.icon-theme` in order to function.

Tested with Pop icon theme on Pop!_OS 20.04.

**Comment by kgilmer** [comment]
Hi @drewofdoom , thanks for the report.  This has actually already [been fixed](https://github.com/regolith-linux/regolith-desktop/issues/350) but has not made it into a release yet.
