### ISSUE TITLE
my configured bar position is ignored

### ISSUE THREAD

**Issue by verajosemanuel** [regolith-linux/regolith-desktop#468]
**Describe the bug**
Modified my config file with some custom bar position, but they are ignored upon restart

**To Reproduce**
1. create a custom file in  ~/.config/regolith/i3/config  this way

cp /etc/regolith/i3/config ~/.config/regolith/i3/config

2. Add some custom : set bar to top position
3. restart system

**Expected behavior**
My desktop shows bar at top.

**Configuration file(s)**

set_from_resource $i3-wm.bar.position i3-wm.bar.position top

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [e.g. 1.4]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 20.04]

Removed /etc/regolith/i3/config
Removed /etc/i3/config 
To no avail. bar position preference is ignored

**Comment by moritzheiber** [comment]
What does the output of `i3 -moreversion` look like?

**Comment by moritzheiber** [comment]
It's also important to note that you don't need to stage the complete configuration file to just modify the bar position. As the configuration states at the top:

```
# This configuration file utilizes Xresource variables to enable users to
# change the configuration without having to make a copy of this config file.
# The benefit to not copying this file is easier upgrading in the future.
# To update a value in this config without making a copy, update the Xresource 
# value in the file ~/.config/regolith/Xresources.
# 
# For example, to change the bar position to the top of the screen this is the
# i3 config entry:
# set_from_resource $i3-wm.bar.position i3-wm.bar.position bottom
#
# So add this line to ~/.config/regolith/Xresources to change it's value:
# i3-wm.bar.position: top
```

**Comment by verajosemanuel** [comment]
I know but the bar position is not the only customization. I reworked the entire config and is easier to copy and change all keybinds instead of Xresources as the syntax seems different to me

Binary i3 version:  4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17.1 (2019-08-30) (pid 3835)abort…)
Loaded i3 config: /home/jose/.config/regolith/i3/config (Last modified: lun 27 jul 2020 10:31:48, 959 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

**Comment by kgilmer** [comment]
Unfortunately there is no (known) way with the current i3 config file format to use Xresources for keybindings.  To change or add additional key bindings you will have to create a user copy of the i3 config file.

**Comment by moritzheiber** [comment]
I'm going to close this since the original issue appears to have been resolved. Feel free to open another bug (aside from #469, which you already opened) if there is another issue that wasn't recognized.

**Comment by verajosemanuel** [comment]
this failed after rebooting the machine

**Comment by kgilmer** [comment]
@verajosemanuel if you're still having problems, please re-open the ticket, explain specifically what is not working, include logs, screenshots, or error messages if you have them available.
