### ISSUE TITLE
Xresources settings ignored

### ISSUE THREAD

**Issue by verajosemanuel** [regolith-linux/regolith-desktop#469]
**Describe the bug**
Xresources configs are ignored.

**To Reproduce**
1. Set a pair of modifications to settings in Xresources file. (Icon theme and top bar)
2. Restart machine

**Expected behavior**
Icon theme changed and bar is at the top

**Configuration file(s)**
cat ~/.config/regolith/Xresources

```
gnome.gtk.theme: Sweet-Dark

gnome.gtk.icons: Sweet-Purple

i3-wm.bar.positiion: top
```

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [e.g. 1.4]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 20.04]

**Additional context**
Checked if themes are installed and I could set it using gnome tweaks ok, but is changed on every reboot.

![2020-07-29_09-03](https://user-images.githubusercontent.com/15836677/88767975-abfe3380-d17a-11ea-964f-545d2b3aa1fc.png)

**Comment by moritzheiber** [comment]
@verajosemanuel In [this comment](https://github.com/regolith-linux/regolith-desktop/issues/468#issuecomment-664209997) you said changing the bar position worked, but here you're saying it doesn't. Just wanted to clarify what specifically is or isn't working.

Also, could you verify the current values of the Xresources you mentioned with `xrescat`? e.g. `xrescat gnome.gtk.theme`. Thanks!

**Comment by verajosemanuel** [comment]
Yes It did, but now is not working. (after reboot)

**Comment by verajosemanuel** [comment]
xrescat gnome.gtk.theme
Sweet-Dark%

**Comment by moritzheiber** [comment]
Is that with the percentage signs at the end?

You can also verify whether the file parses correctly with `xrdb -merge`:

```
xrdb -merge ~/.config/regolith/Xresources
```
If it doesn't give an error it's loading the file correctly. However, the names as you pasted them wouldn't set the theme correctly as they aren't matching (because of the percentage sign).

**Comment by verajosemanuel** [comment]
> Is that with the percentage signs at the end?
> yes, I dont know why the percentage sign but double checked in editor and after the last character there is nothing else.

> You can also verify whether the file parses correctly with `xrdb -merge`:
> 
> ```
> xrdb -merge ~/.config/regolith/Xresources
> ```
Nothing is shown

**Comment by moritzheiber** [comment]
So, just to make sure, after having used `xrdb -merge` you will need to restart i3 for the changes to take effect. You can also just use `regolith-looks refresh` (which is doing both, the merge and restart for you). The documentation is here: https://regolith-linux.org/docs/customize/styles/

My guess is that there's something in your custom i3 configuration that's preventing the changes from being applied correctly. Do you think you could upload it somewhere?

**Comment by verajosemanuel** [comment]
regolith-look refresh 

to no avail. Still default themes

**Comment by moritzheiber** [comment]
As I said, I think at this point it's better to take a look at the configuration file. Maybe also the `Xresources` file since the percentage signs are a little dubious.

**Comment by verajosemanuel** [comment]
Here
https://github.com/verajosemanuel/.config

**Comment by moritzheiber** [comment]
Thanks!

Your `Xresources` file has a typo at [line 1](https://github.com/verajosemanuel/.config/blob/master/Xresources#L1). It should be `i3-wm.bar.position` instead of `i3-wm.bar.positiion`. That should fix the position variable and the right position should get picked up if you change [line 532](https://github.com/verajosemanuel/.config/blob/master/config#L532) back to its original value at line 531.

As for the theme: How did you install it? I'm guessing it doesn't ship with the regular repositories Ubuntu provides .. ?

**Comment by moritzheiber** [comment]
Additionally, applying the theme would only change GTK windows (as its a GTK theme) not the look of i3 itself. Just to be clear and setting expectations :sweat_smile:

**Comment by moritzheiber** [comment]
Okay, so you only want to override the icon theme?

The Xresources key for the icon theme is `gnome.icon.theme`, so the resulting override would look like this:

```
gnome.icon.theme: Sweet-Purple
```
(assuming you've installed the icon theme into the right location, [as mentioned in its README](https://github.com/EliverLara/Sweet-folders#important))

**Comment by moritzheiber** [comment]
@verajosemanuel Let me know if you have an update for us. Otherwise I'll close this report tomorrow.

**Comment by verajosemanuel** [comment]
worked! thanks a lot!

**Comment by moritzheiber** [comment]
Okay, glad I could help. Maybe in the future, try finding us on Slack, it'll help us coordinate on solving issues like this faster and sooner :slightly_smiling_face:

**Comment by verajosemanuel** [comment]
Sure!
