### ISSUE TITLE
Provide dotfiles for people wanting the Regolith look

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#47]
Because Regolith is customization on existing open source projects, many of the dotfiles are [hidden away in the repos as patch files](https://github.com/regolith-linux/regolith-i3/tree/master/debian/patches).  These are not readily shareable.  Ideally there would be some automated way of extracting these files but that's a lot of work.  A simpler approach that's just as effective would be to extract the dotfiles from an install, and put them on the website for people to view and copy. 

This would require creating a PR in the https://github.com/regolith-linux/regolith-linux.github.io repo, saving the dotfiles in the `/assets` directory, and linking to them from the `internals.md` page in a "dotfiles" section.

**Comment by moritz-weber** [comment]
Just a shot in the dark, but I think this could be achieved with a CI system that spins up a fresh Ubuntu, installs the packages and extracts the dotfiles. I don't know, if this could automatically push the dotfiles to a repository (I'm not sure, how this system would authenticate itself).

**Comment by kgilmer** [comment]
Yeah that would work @moritz-weber but it's a lot of work just to retrieve some files from git.  I think a simple script that pulls the packages down from git, runs `quilt push -a` on each package and then copies specific files to an output dir would be a simpler approach.

**Comment by appelgriebsch** [comment]
I would like to submit a PR that adds a keybinding to the i3 config for toggling between tabbed and split mode:
```
# toggle tabbed mode
bindsym $mod+t layout toggle tabbed split
```

But I can't find the correct repo to clone, adapt and make PR for it...

**Comment by kgilmer** [comment]
I've created a howto for this: https://regolith-linux.org/howto.html#i3-config

Happy to help if something is confusing or not working.  Looking forward to your PR!

**Comment by MerlinElMago** [comment]
As of today, I'm having issues with Regolith not accepting the user defined config files, but defaulting to the ones saves in /etc/regolith. How can I revert this? 

As a side info:
I have my config files saved in a folder on my home partition linking the regular files to them. This way I can edit them as a regular user (opposing to the files saved in etc) and if a packed ever everwrites my configs, they would be asafe in my home folder withstanding even a reinstall of the system.

**Comment by kgilmer** [comment]
Hi @MerlinElMago , sorry for the confusion.  A refactoring change was recently added to Regolith to make it more consistent with Linux conventions.  Depending on how old your config file is, you may just be able to copy it to `~/.config/regolith/i3/config`.  (The file path changed).  

A config file as symlink is not supported at this time.  I [created an issue](https://github.com/regolith-linux/regolith-desktop/issues/98) to change that behavior.  You can watch the issue to know when the feature is available.  In any case, Regolith with not overwrite your config files in the `~./config` directory so you're safe to make copies there until symlinks are supported.

If you'd like more background as to why this change happened, you can [read here](https://www.freelists.org/post/regolith-linux/Config-versioning) and [this page](https://regolith-linux.org/troubleshooting.html#where-is-config) gives more details about how to migrate your existing setup to the new approach.  If you would like to be notified in advance before changes occur in Regolith (although I do not expect to move the config file paths ever again), please [subscribe to the mailing list](https://www.freelists.org/list/regolith-linux).

**Comment by kgilmer** [comment]
I was wrong about symlink support.  It should work now, I just tested it on my machine.
