### ISSUE TITLE
next-workspace and own names for workspaces conflict

### ISSUE THREAD

**Issue by ukaszg** [regolith-linux/regolith-desktop#470]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [X] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
running:
$ /usr/share/i3xrocks/next-workspace                                                                                                                                                
Traceback (most recent call last):
  File "/usr/share/i3xrocks/next-workspace", line 23, in <module>
    font = workspaces[0].name.split("'")[1]
IndexError: list index out of range

it happens because I have set different names for the workspaces:
$  cat ~/.config/regolith/Xresources 
#define QUOTE(x) Q(x)
#define Q(x) #x
#define WORKSPACE_NAME(INDEX, FONT, COLOR, GLYPH) INDEX:<span font_desc=FONT> INDEX </span><span foreground=COLOR>GLYPH</span>
#define typeface_bar_glyph Source Code Pro Medium 13
#define glyph_font QUOTE(typeface_bar_glyph)
#define typeface_bar pango:Terminus (TTF) Medium 10, Material Design Icons 10
#define typeface_rofi Terminus (TTF) Medium 10
#define typeface_terminal Terminus (TTF) Medium:pixelsize=14:antialias=true:autohint=true
#define typeface_wm pango:Terminus (TTF) Medium 10

i3-wm.font: typeface_wm
i3-wm.bar.font: typeface_bar
i3xrocks.value.font: typeface_bar

i3-wm.bar.position: top
i3-wm.bar.trayoutput: primary
i3-wm.gaps.focus_follows_mouse: yes
i3-wm.next-workspace.key: p

i3-wm.workspace.01.key: grave
i3-wm.workspace.02.key: 1
i3-wm.workspace.03.key: 2
i3-wm.workspace.04.key: 3
i3-wm.workspace.05.key: 4
i3-wm.workspace.06.key: 5
i3-wm.workspace.07.key: 6
i3-wm.workspace.08.key: 7
i3-wm.workspace.09.key: 8
i3-wm.workspace.10.key: 9
i3-wm.workspace.01.name: 0
i3-wm.workspace.02.name: 1
i3-wm.workspace.03.name: 2
i3-wm.workspace.04.name: 3
i3-wm.workspace.05.name: 4
i3-wm.workspace.06.name: 5
i3-wm.workspace.07.name: 6
i3-wm.workspace.08.name: 7
i3-wm.workspace.09.name: 8
i3-wm.workspace.10.name: 9
i3-wm.workspace.11.name: 10
i3-wm.workspace.12.name: 11
i3-wm.workspace.13.name: 12
i3-wm.workspace.14.name: 13
i3-wm.workspace.15.name: 14
i3-wm.workspace.16.name: 15
i3-wm.workspace.17.name: 16
i3-wm.workspace.18.name: 17
i3-wm.workspace.19.name: 18
i3-wm.workspace.20.name: 19
gnome.wallpaper:
i3-wm.program.1: /usr/bin/nm-applet
i3-wm.program.2: /usr/bin/env wp.py
i3xrocks.date.format2: %a %d %B %H:%M
i3xrocks.volume.step: 6
===END OF PASTE===
ignore the fact that grave conflicts with next-workspace key, I have modified that key

**To Reproduce**
set workspace keys/names as in description of the bug
run commandline /usr/share/i3xrocks/next-workspace

**Expected behavior**
Does not throw an error

**Configuration file(s)**
see description

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [1.4.1]
 - PPA url: [default: ppa:regolith-linux/unstable]
 - Host OS (for PPA): [Ubuntu 20.04]

**Additional context**

**Comment by priestoferis** [comment]
@ukaszg So as far as I can see, you removed the formatting which the script is trying to grab? But for you, it would also give the wrong name to the workspaces, since it uses the number to name it, but you basically renumbered the entire thing.

If you just wanted a solution, where workspaces are numbered from 0, you can add an i3-wm.workspace.00.name and the appropriate command change in your i3 config.

Otherwise still working on how to fix this, I would need access to the xresources from the server to properly allow for renaming.

**Comment by priestoferis** [comment]
@ukaszg Can you check if the solution in https://github.com/regolith-linux/regolith-i3xrocks-config/pull/82 works for you? Here's the script: https://github.com/priestoferis/regolith-i3xrocks-config/blob/master/scripts/next-workspace

**Comment by moritzheiber** [comment]
This should be fixed with the latest release.
