### ISSUE TITLE
Allow users to override resetting the gnome-terminal profile automatically in the regolith-look script.

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#471]
Acceptance Criteria:  Users that have customized their gnome-terminal profile should not need to make any changes after specifying an Xresource override (TBD).

**Comment by kabeersvohra** [comment]
@kgilmer sorry for the question but where can I set this so that my gnome-terminal profile stays on reboot? I tried adding `gnome.terminal.update false` to `~/.Xresources-regolith` which didn't do anything

**Comment by st--** [comment]
@kabeersvohra I've only just started using regolith but I think a) you probably want to edit ~/.config/regolith/Xresources instead (see https://regolith-linux.org/docs/howto/override-xres/) and b) I think the syntax for Xresources is `gnome.terminal.update: false` (or anything other than `true`) - this does work for me!

**Comment by kabeersvohra** [comment]
@st-- thank you, this worked :)
