### ISSUE TITLE
Always fun to upgrade Linux version

### ISSUE THREAD

**Issue by gigglearrows** [regolith-linux/regolith-desktop#473]
Its always fun to upgrade to major ubuntu versions with regolith linux :) I need to spend soo much time configuring things and backing up config files (because i have customized my regolith linux a bit ofc). Just upgraded to ubuntu 20.04, and now nothing works :P Rofi doesnt work, no icons are showing on the task bar, i do not have the correct theme etc. But i think this is just that it has new locations of config files or something. Ill check that out when I got some time :) Now I see that you have switched to lightdm instead of Gnome display manager? What if I liked gnome and want to keep using Gnome as display manager? Should i then revert everything back to an older version and not upgrade regolith linux ever? 

Is it possible for you to provide a guide on how to upgrade properly, where the location of config files are. Do we still use Xresources etc. ? 
Thanks

**Comment by gigglearrows** [comment]
What was the reason of switching to lightdm? Only to make it a bit more lightweight?

**Comment by gigglearrows** [comment]
I think the new default look, looks soo much worse now. Is it still possible to use the cool theme with the different colored squares and numbers on bottom left side (the multiple desktops)

**Comment by gigglearrows** [comment]
I am considering to just reinstall my whole regolith ubuntu installation just to get rid of old regolith-related files that are not used anymore, and to just get a clean installation so I can manually edit config files with the extra stuff I use. Might be the simplest solution, but we'll see ^^

**Comment by moritzheiber** [comment]
Please try asking these questions on Slack instead of filing an issue. There's nothing specific in this report that we could address or improve.

**Comment by gigglearrows** [comment]
@moritzheiber didnt know you had a slack, will find it

**Comment by kgilmer** [comment]
@gigglearrows did you check regolith-linux.org for Ubuntu upgrade instructions?  Do you recall where you looked before you concluded there was nothing available?  Did you [find this](https://regolith-linux.org/docs/getting-started/install/#upgrading-ubuntu) but for some reason didn't work for you?

Regarding changing the looks, see here: https://regolith-linux.org/docs/customize/look/

And any other suggestions you may have to make documentation more easily discoverable or more effective are welcome :smile:
