### ISSUE TITLE
Regolith uninstall leaves GNOME in a screwed-up state.

### ISSUE THREAD

**Issue by umanwizard** [regolith-linux/regolith-desktop#474]
I just installed Regolith from the PPA, then uninstalled it because I can't set a different DPI per monitor (not sure why; I'm able to in stock Ubuntu both in X11 and Wayland).

I then attempted to uninstall via the instructions here: https://regolith-linux.org/docs/getting-started/install/#uninstallation-of-regolith-desktop but I don't have a `~/.regolith-gnome-backup` file. Instead, I have `.regolith-gnome-backup-r1-4`. Okay, I tried sourcing that. Most stuff has gone back to normal, except:

(1) The terminal still uses the Regolith theme, but now that I have uninstalled Regolith, the fonts it relies on are missing, so it looks unusably bad. Luckily, I figured out how to revert to the original theme.
(2) The "Trash" and "Home Directory" icons on my desktop now look completely different - not sure if they are Regolith theme or stock Gnome theme.
(3) The "Ubuntu Software" icon is also wrong
(4) I don't know what else might be screwed up... considering just reinstalling Ubuntu on the machine from scratch.

If Regolith is unable to be uninstalled without reverting everything to how it was before, please warn people about this prominently on the home page.

**Comment by umanwizard** [comment]
Update: after changing all "Themes" settings to "Yaru" in "Gnome Tweaks -> Appearance", things seem back to normal.

**Comment by kgilmer** [comment]
Hi @umanwizard , sorry for the trouble and glad to hear you eventually got it fixed up.  The backup file should have contained your gnome theme settings, not sure why it didn't work for you.  The next Regolith release changes the way in which gnome settings are managed and this backup procedure will be deprecated.

**Comment by umanwizard** [comment]
Thanks!

**Comment by runekaagaard** [comment]
Same thing happened to me. Changing themes to Yaru in Gnome Tweaks did not help.

**Comment by kgilmer** [comment]
As of Regolith 1.5, the regolith desktop session no longer modifies GNOME settings.
