### ISSUE TITLE
Transparent blackscreen after wakeup from display blank & suspend

### ISSUE THREAD

**Issue by aurabindo** [regolith-linux/regolith-desktop#476]
**Describe the bug**
Translucent blackscreen upon resume from suspend and wake up from Blank screen

**To Reproduce**
Leave the system idle for screen blank to trigger

**Expected behavior**
Display clearly visible after screen turn on.

**Configuration file(s)**
No custom configuration except for keyboard shortcut changes.

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: 1.4.0.3-1
 - PPA url: default: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Additional context**

Upon wakeup from blank or suspend, The unlock screen is faintly visible, and I can log back in, but the screen stays at about 80% transparent. Logout would fix the issue. But switching to a different vt and black does not fix the issue.

Please let me know what logs would help in narrowing the issue

**Comment by aurabindo** [comment]
Apparently I dont get this behavior anymore. Wakeup from sleep works fine!

**Comment by ninjarogue** [comment]
@aurabindo @moritzheiber  what is the fix? When I close my laptop and reopen it after a while, the screen is just black. I have to manually shut off my laptop and turn it back on again.

**Comment by aurabindo** [comment]
There was no fix as far as I can remember. Your issue could be a kernel problem as well. What graphic card are you having ?

**Comment by ninjarogue** [comment]
@aurabindo GeForce Nvidia

**Comment by aurabindo** [comment]
Try adding "drm.debug=0x156 log_buf_len=20M" to your kernel cmdline and capture the dmesg. You'll probably see some errors there if the black screen is because of a kernel issue.
