### ISSUE TITLE
regolith-look refresh returns a error concerning missing required dependencies

### ISSUE THREAD

**Issue by MorpheusH3x** [regolith-linux/regolith-desktop#477]
**Describe the bug**
On the command `regolith-look refresh` I got a error concerning some missing required dependencies.

**To Reproduce**
Made the howto [Change the Default Window Gap](https://regolith-linux.org/docs/howto/default-gap/)
And at the second step my unwanted behavior occurs.

**Expected behavior**

**Screenshots**
There is my terminal:
```
morpheush3x@laptop ~ $ regolith-look refresh
[WARN] Missing required dependencies: \e[0;34mdconf\e[0m
[ERR] Required dependencies were not fulfilled: dconf expr gsettings uuidgen
```

**Configuration file(s)**
I have a non-changed configuration apart the HowTo guide new line (there was not here before I add it by my own).

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Linux Mint 19 Tara x86_64

**Additional context**
I try to write clearly as I can.
If needed ask my more informations.

**Comment by kgilmer** [comment]
Hi @MorpheusH3x , you just need to install the missing dependencies.  Try `sudo apt install dconf expr gsettings uuidgen`.  I'm guessing that Linux Mint does not include these programs, whereas they are generally provided by default in Ubuntu.  Keep in mind that some users run Regolith on Linux Mint but it is not a tested host OS for Regolith.
