### ISSUE TITLE
Workspace 1 shows desktop icons after upgrade to Linux Mint 20

### ISSUE THREAD

**Issue by sqhn** [regolith-linux/regolith-desktop#478]
Hello

I was using Regolith on Linux Mint 19.x without any issues. Since I upgraded to 20.x, the first workspace shows the default Gnome desktop like any other application (cf. screenshot). I can move it to scratchpad but I cannot quit it. Do you know where it comes from and if I can kill it?

![Screenshot from 2020-08-16 10-18-27](https://user-images.githubusercontent.com/59039427/90330159-f3722580-dfaa-11ea-82dc-fc06573e2166.png)

Thanks
Steven

**Comment by moritzheiber** [comment]
Please try to follow the guidelines that are posted in the bug report template. Numerous people have asked the same thing in Slack before and there are also a number of bugs that are following the same patterns (literally, searching for "icons" or "desktop icons" turns up 42 closed reports). To resolve this please have a look at e.g. https://github.com/regolith-linux/regolith-desktop/issues/347

If the issue persists, try asking on Slack or file a new bug report. Thanks!

**Comment by sqhn** [comment]
Thank you! Sorry, I forgot to look for closed issues...
