### ISSUE TITLE
Cannot Permanently Change Wallpaper

### ISSUE THREAD

**Issue by drewofdoom** [regolith-linux/regolith-desktop#48]
Users can change the wallpaper in the i3-regolith config, but that change will be overridden on screen change with the default random wallpapers. Users need a way to change their wallpaper, or at least documentation on the various places to update the `feh` command flags.

**Comment by kgilmer** [comment]
Ooof, great catch @drewofdoom .  Yes just editing the config isn't sufficient but I didn't realize that the monitor hotplug fix, as a side effect now duplicates the wallpaper configuration into two places.  The missing piece for you is likely `/usr/bin/wallpaper-refresh.sh`.  

As you say, the wallpaper configuration should be consolidated and documented so it's easy for people to change it.

**Comment by kgilmer** [comment]
I also noticed that the params passed to `feh` differ between the two scripts which needs to also be addressed.

**Comment by kgilmer** [comment]
I added a howto entry that explains the file edits that need to be performed to update the wallpaper as-is, but I see this as a serious bug and expect to fix it in the next few days.

**Comment by drewofdoom** [comment]
A couple of simple, alternate methods:

- Set a user environment variable for feh to pickup - .profile?
- simple file containing only the path of the desired wallpaper - either pipe into feh or make the file a symlink and point feh at it.

Any of those options would eventually benefit from a utility to graphically select a wallpaper. Perhaps using something like `nitrogen` would be better, as it already has a wallpaper picker and can restore the user settings with a simple `nitrogen --restore`?

**Comment by afterthought325** [comment]
Since you are already using a lot of stuff through gnome, why not use the background set in the control center? I believe you could just grab it using `gsettings get org.gnome.desktop.background picture-uri` and then set the wallpaper using feh?
e.g "gsettings monitor org.gnome.desktop.background picture-uri | awk '{ print $2}' | feh -bg-scale -f-" should monitor changes to the background made via the various gnome ways (control center, etc) and then set the background via feh to match.

**Comment by drewofdoom** [comment]
One other problem with that approach. Not every user will want to use the scale flag. I, for example have a rotated 16:9 monitor and use `bg-fill` instead of scale. 

I do like the idea of pulling the Gnome background, though. Would probably need a way to monitor that gsettings entry so the wallpaper changes when a selection is made, though.

**Comment by afterthought325** [comment]
Yeh, I've been playing around with finding a way to monitor that all morning. It's been trouble. 
`gsettings monitor org.gnome.desktop.background picture-uri` almost does what we need. but it never returns, so when you try and pipe it on, it never gets piped to sed for some odd reason. Its probably just my ignorance though, so if someone else can figure  that part out, it would be a much cleaner solution than my little while loop.

**Comment by kgilmer** [comment]
@afterthought325 fantastic idea!  While it is a bit of a functional regression in terms of not supporting the "random wallpaper on login" feature, it makes everything simpler and more consistent.  I think this is the best solution given what we know at this point.  @drewofdoom thanks for your continued investigation as well.  I also have monitors in a variety of configurations and think we can specify the feh parameters vix Xresources.  I was able to adapt @afterthought325 's approach to get it mostly working w/ xargs:

```
 gsettings monitor org.gnome.desktop.background picture-uri | xargs -I {} sh -c "feh --bg-scale {};"
```

I spent a few minutes trying to get the awk command to work but had no luck and in any case feh happily ignores it.

**Comment by kgilmer** [comment]
@drewofdoom I should also say thanks for your suggestions above.  I played around a bit with nitrogen but it was crashy for some reason, and I'm not a fan of the old-school UI.   I did some reading on Xresources last night and was really happy to see it allows for modular configuration.  I wish I had known about this X facility last year!

**Comment by kgilmer** [comment]
In order to have the Regolith wallpapers selectable from within gnome-control-panel I need to ship an addiitonal xml file that simply lists the wallpaper files with some additional metadata to `/usr/share/gnome-background-properties`.

**Comment by kgilmer** [comment]
눈_눈 This is a bit embarrassing that I didn't think of this sooner but `feh` can just be ripped out entirely. So, this is my what I plan:

1. remove `feh` from Regolith
2. remove [this line](https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L17) from regolith-gnome-flashback
3. ship a background manifest file in `regolith-assets`
4. set the wallpaper on first-time login for the background as is [already done for the lockscreen.](https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L29)

I'm hoping that I also can remove the monitor hotplug fix as I'm expecting that gnome manages this itself.  So, all in all this is a big reduction in complexity, makes configuration more consistent, allows users to easily change their wallpaper.  The only downside is the randomized part.  But, this could be re-implemented by simply choosing a background at login and setting it via `gsettings`.  

Any concerns or thoughts?

**Comment by kgilmer** [comment]
Hmm, and then there is this thing which appears to be a way of scripting background slideshows.  Maybe a nice thing to consider in the future: `/usr/share/backgrounds/contest/bionic.xml`.

**Comment by drewofdoom** [comment]
I'm not a huge fan of the randomized wallpaper bit, to be honest. It's a neat feature, but ultimately less useful than the ability for a user to select their own wallpaper with a nice interface in my own (biased) opinion. If the Gnome wallpaper function can stand up on its own, my +1 definitely goes to that!

**Comment by kgilmer** [comment]
`regolith-unstable` now has has all changes mentioned above.  @drewofdoom are you able to test by switching to the unstable PPA, updating your packages, moving or renaming your ~/.config/i3-regolith/config file, and rebooting?

**Comment by kgilmer** [comment]
Tested on fresh install of Ubuntu 18.04.  Works as expected.

**Comment by kgilmer** [comment]
Tested on fresh install of Ubuntu 19.04.  Works as expected.

**Comment by eldelacajita** [comment]
I came here to report this issue and found this thread. 

> are you able to test by switching to the unstable PPA, updating your packages, moving or renaming your ~/.config/i3-regolith/config file, and rebooting?

Did this on my install (a VM with the `regolith-19.04.0-2019.05.26-desktop-amd64` image) and now it **works as expected**. Nice improvement!

**Comment by kgilmer** [comment]
Fantastic feedback @eldelacajita , thank you.  I will push this feature to `regolith-stable` this weekend if no issues are found.

**Comment by kgilmer** [comment]
Pushed to `regolith-stable` last night.  Verified working as expected in fresh install from PPA on Ubuntu 18.04.  There is one issue in that the change to allow all wallpapers to be selected from within gnone-control-center is not available yet.  Will push this change to stable later today.

**Comment by kgilmer** [comment]
This should be resolved.  To get this update you may have to remove (Regolith will re-add at next login) or change your `~/.config/i3-regolith/config` file.  Compare your copy with what's in `/etc/i3/config`.  Fresh installs of Regolith either via PPA or updated to latest from LiveCD should get this update without any complications.
