### ISSUE TITLE
CAPS LOCK indicator does not appear on the i3 bar even after installing i3xrocks-key-indicator

### ISSUE THREAD

**Issue by tur1ngb0x** [regolith-linux/regolith-desktop#481]
- [✓] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [✓] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [✗] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
CAPS LOCK indicator does not appear on the i3 bar even after installing `i3xrocks-key-indicator`.

**To Reproduce**
1. On a clean install of Regolith 1.4.1 `sudo apt install i3xrocks-key-indicator`
2. (optional) `cp /etc/regolith/i3xrocks/conf.d/20_key-indicator ~/.config/regolith/i3xrocks/conf.d/20_key-indicator`
3. Reboot machine.
NOTE: If one skips step 2, even then CAPS LOCK indicator is not visible.

**Expected behavior**
After toggling CAPS LOCK, the indicator should be visible on the i3 bar.

**Screenshots**
![Screenshot from 2020-09-03 22-58-57](https://user-images.githubusercontent.com/25666761/92147741-28023000-ee39-11ea-9163-96c05343f838.png)

**Configuration file(s)**
1. Tried using no user config file. Everything set to defaults. CAPS LOCK indicator is not visible.
2. Tried using my own config file. CAPS LOCK indicator is not visible.
https://gist.github.com/tur1ngb0x/64755065a20034f7382cb357a695b7f1

**Installation Details**
 - Regolith Install Type: `regolith-20.04.0-1.4.1-desktop-amd64.iso`
 - Regolith Version: 1.4.1
 - PPA url: `http://ppa.launchpad.net/regolith-linux/release/ubuntu focal InRelease`
 - Host OS (for PPA): N/A

**Additional Context**
CAPS LOCK indicator worked earlier (with and without user config Xresources file) when I installed Regolith on top of Ubuntu 20.04 LTS and Linux Mint 20 Cinnamon using Regolith stable PPA.

**Comment by kgilmer** [comment]
Hi @tur1ngb0x , what do you get when you run `$ /usr/share/i3xrocks/key-indicator` from a terminal?

**Comment by tur1ngb0x** [comment]
@kgilmer Here is the output of `$ /usr/share/i3xrocks/key-indicator`

`<span color="#1F2430"></span><span color="#1F2430"></span>`

![Screenshot from 2020-09-06 12-18-04](https://user-images.githubusercontent.com/25666761/92319922-10929500-f03b-11ea-9f27-8a755a0f6a9f.png)

**Comment by tur1ngb0x** [comment]
**Update:**

I tried re-installing Regolith 1.4.1 using the ISO, and the issue seems to be fixed. It works even with or without `~/.config/regolith/Xresources` file.

![Screenshot from 2020-09-06 17-53-38](https://user-images.githubusercontent.com/25666761/92325669-10f65480-f06a-11ea-9b32-1df6ec7187e9.png)
