### ISSUE TITLE
Allow users to change looks without using the command line.

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#483]
Simple and consistent approach would be to use Rofi.

**Comment by twvd** [comment]
Just an idea: would it make more sense to make a 'Regolith settings' rofi menu and make the look picker a submenu, rather than give it its own keybind?

A lot of (non-standard productivity) keybinds may get confusing at some point, plus you may run out of options.

**Comment by kgilmer** [comment]
Hi @twvd !  Well given the number of keys + the modifier keys there are plenty of keybindings options for this, but regarding your main point, what other options would you like to see in such a menu other than specifying the look?

**Comment by kgilmer** [comment]
Closing as feature complete and no response to question.
