### ISSUE TITLE
UI problems after deep sleep

### ISSUE THREAD

**Issue by SL7** [regolith-linux/regolith-desktop#484]
**Describe the bug**
When I wait long enough until my machine falls to sleep, after the wake I get some UI bugs. My Brave browser starts producing weird graphical output, my terminal in and output is delayed or until I start typing it doesnt show what it outputted earlier.

**To Reproduce**
1. Wait for machine to go into sleep.
2. Wake and log back in
3. See Screen bugs.  
  
**Installation Details**
Installed Regolith via ISO.  

**Hardware:**
CPU: AMD Ryzen 9 3900X
GPU: GTX 1660Ti
RAM: 16Gb Corsair RAM
Installed on SSD.  

Edit:
Using Alacritty as Terminal
Installed Nvidia driver-430 myself.

**Comment by newvicklee** [comment]
I had this issue with Brave browser as well after a recent update. I suspect it could be an issue with the latest Chromium update since this issue also appeared with Chrome. But when I used Firefox, I didn't get these problems.

**Comment by SL7** [comment]
So I think I fixed it. I lookes at the drivers Regolith uses for my Nvidia Graphics Card and it were these open source driver. I changed it to propietary and now it seems to work.
I already suspected it is something with the nvidia drivers cause alacritty started lagging and it is GPU accelerated.

**Comment by kgilmer** [comment]
Glad to hear you fixed your issue @SL7 .  Yes, Regolith doesn't provide any special support for any graphics hardware.
