### ISSUE TITLE
Canonical method to set caps lock to control key on regolith 20.04.1

### ISSUE THREAD

**Issue by davidthewatson** [regolith-linux/regolith-desktop#485]
- [*] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [*] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [*] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Is your feature request related to a problem? Please describe.**
I use the caps lock as the ctrl key on every machine I use. On most machines, this is straightforward regardless of their operating system or window manager. On regolith, searches for solutions produce many disparate results which are not clear given the intersection of regolith, i3, and ubuntu post 20.04.1. The question I am begging is that given the merge of those components plus X eccentricities, where should the problem of key mapping be solved? The most obvious location is in the settings, but keyboard shortcuts do not reveal a solution, as they would with other systems, i.e. it may be difficult to get to, but at least it's there.

**Describe the solution you'd like**
I'd like the documentation to contain a result for the search "caps" or "ctrl" that tells me the best way to set the caps lock as the ctrl key permanently, preferably through the GUI, but command line config via text is fine if it were clearly documented for this stack.

**Describe alternatives you've considered**
https://www.google.com/search?channel=fs&client=ubuntu&q=regolith+20.04+caps+lock+control

**Additional context**
I'm happy to contribute the documentation change myself. It's possible that this is just a problem with search indexes being up-to-date. There may be many ways to achieve the desired result, but none of them appears canonical. The search for a solution produces many user reports of solutions that don't work or are out-of-date. I'd like to help.

**Comment by kgilmer** [comment]
Hi @davidthewatson , thanks for your detailed report.  It can be difficult to know what set of instructions may work for Regolith.  It's relatively new and has some ways to go for broad adoption.  Additionally, it uses some desktop components that are less popular than the typical gnome-shell and KDE setups.  Generally speaking, I look for advice for Ubuntu in general.  If the content does not make explicit use of gnome-shell, it may work for Regolith.  If the question is specific to i3 then general i3 advice will probably apply to Regolith as well. 

In your particular case, [please see this page](https://opensource.com/article/18/11/how-swap-ctrl-and-caps-lock-your-keyboard).  I tested it and was able to get the behavior you're looking for.  If you'd like to create PR for a howto for others, we'd love the contribution!

**Comment by davidthewatson** [comment]
Hey @kgilmer Thanks for your reply!

I think when you mentioned this:

https://opensource.com/article/18/11/how-swap-ctrl-and-caps-lock-your-keyboard

You meant to run gnome-tweak-tool so that's what I did and indeed, my caps lock is now behaving as control! Thanks!

So the _what_ is satisfied, I think my original commentary was more directed toward usability concerns around _how_ to make the change without choice paradox, side effects, or confusion. One challenge is that, while there are ways to checkpoint, backup, and restore config state in apt, none of them are as smooth as say fedora silverblue's use of libostree, where it's all happening under the covers with neat command line abstractions to button up the process.

Thus, when I did:

```sudo apt install gnome-tweak-tool```

I got 54 MBs of packages which dragged in a lot of dependencies that are reminiscent of what I think regolith was trying to move away from in the move to lightdm from gdm3 (and I worry have side effects), for instance. Which is why I got the dialog asking me to choose one or the other. As an experienced user, it wasn't a big deal, but after I made the right choice based on your release notes from earlier this year, I then discovered upon running gnome-tweak-tool that the keyboard modification dialog painted with no navigation whatsoever (buttons, close X, nothing - esc key didn't work nor did the typical close keystrokes). This left me running xkill from the command line and clicking the dialog, which, of course, killed the whole gnome-tweak-tool.

Fortunately, the caps lock -> ctrl behavior persisted beyond killing gnome-tweak-tool but I'm sure this isn't the user experience that we aspire to.

If you meant with the link for me to do something else like mod a config file, let me know.

Thanks!

**Comment by kgilmer** [comment]
Hi @davidthewatson , glad the **what** is identified.  As I understand it, gnome-tweak-tool and gnome-settings are mainly just front-ends to gsettings/deconf, which represent gsettings schemas as defined in Gnome.  I believe all of the settings changes that you can do w/ the tweak tool can also be done via gsettings changes.  And, gsettings supports loading and saving of configurations as well.  The gsettings command line tool will recursively iterate across the tree and you can use grep to search for what you're looking for.  In the case of looking for your caps lock remapping,  I was not able to find it that way but a search for `gsettings ctrl key remapping` yielded [quick results](https://askubuntu.com/a/633539/834410).  

In general there are two primary sources of configuration state in Regolith: Xresources and dconf/gsettings.  I can't think of a UI configuration off the top of my head that does not come from one of these two sources.

**Comment by davidthewatson** [comment]
Thanks, again @kgilmer 

That was super-helpful. 

Turns out this gsettings command:

```gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"```

works reliably on regolith 20.04.1 with updates and survives reboot.

I'm good to go. Thank you!

**Comment by suryaaditya** [comment]
`gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"`
this command makes caps as control modifier, but how do we make original ctrl_modifier to caps? i.e swap keys with gsettings?

**Comment by RonaldDijks** [comment]
Hi everyone! Bit late to the party, but you can swap caps and escape with: 
`gsettings set org.gnome.desktop.input-sources xkb-options "['caps:swapescape']"`
