### ISSUE TITLE
i3xrocks-net-traffic indicator dissapears when any speed is 0

### ISSUE THREAD

**Issue by pedrokost** [regolith-linux/regolith-desktop#487]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

The net-traffic indicator appears and dissapears all the time. There is a bug in the script which makes it exit early when any of the speeds (RN, TN or AN) are 0.

**To Reproduce**

Your internet shouldn't be causing any traffic

**Expected behavior**

The indicators should remain visible even if speeds are 0.

**Screenshots**

I've manually modified the script (/usr/share/i3xrocks/net-traffic), to print the variable RN, TN and AN, as shown in the screenshot below. Lines 174-182 have been added for troubleshooting:

![Screenshot from 2020-09-30 23-35-20](https://user-images.githubusercontent.com/725286/94742502-1186c000-0376-11eb-98d6-1d4103500972.png)

The following screenshot shows that when any of the values are 0, the script exits early and does not print the stats.

![Screenshot from 2020-09-30 23-30-24](https://user-images.githubusercontent.com/725286/94742472-05026780-0376-11eb-8c84-81c4aaebc26c.png)

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 1.4.1

**Additional context**

This [reddit thread](https://www.reddit.com/r/i3wm/comments/fwj7r9/net_traffic_block_keeps_appearing_and_disappearing/) from 5 months ago seems to be reporting the same problem.

**Comment by moritzheiber** [comment]
I'll close this in favor of regolith-linux/regolith-i3xrocks-config#73
