### ISSUE TITLE
Disable Auto- arrange on desktop

### ISSUE THREAD

**Issue by NevenJagodar** [regolith-linux/regolith-desktop#489]
Intuitive way to disable Auto-arrange on desktop would be nice (to put icons where ever user wants and not to rearrange icons when one file is erased)

**Comment by muktupavels** [comment]
https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/41

**Comment by moritzheiber** [comment]
I'm closing this issue because there's literally nothing we can on our side here since this is entirely dependent on GNOME Flashback implementing this feature.
