### ISSUE TITLE
Key Super doesn't work

### ISSUE THREAD

**Issue by ulliBlue** [regolith-linux/regolith-desktop#490]
Hi,

I am just installed twice Regolith 1.4.1, both times the super key didn't work. I although installed Regolith on virtualbox, the same result. I am using the German keyboard.

**Comment by kgilmer** [comment]
Hmm, I'm not sure what the problem would be @ulliBlue .  It could be that VirtualBox isn't passing the Super key to the VM, but I am only making a guess.  You could try swapping to the alt key, and see if that works for you.  Look here for information on how to make the change:

1. https://github.com/regolith-linux/regolith-i3-gaps-config/blob/master/config#L42
2. https://regolith-linux.org/docs/howto/override-xres/#example---use-alt-instead-of-win-as-super

**Comment by ostanislaw** [comment]
@ulliBlue Please make sure you have not enabled "game mode" accidentally. I had such issue once. And after seeing such suggestion at some support (stackoverflow or something like that) I've just disabled the game mode on my keyboard with a dedicated button (HyperX Alloy Elite). It's low chance you have a "stupid" game mode button but please be informed just in case. In such case it is handled internally by keyboard and no keyevent is sent to system.

**Comment by kgilmer** [comment]
Closing, assuming fixed.
