### ISSUE TITLE
Fractional Scaling menu doesn't come

### ISSUE THREAD

**Issue by vishxm** [regolith-linux/regolith-desktop#491]
- 

- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)

- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
In Ubuntu, after opting fractional scaling, a radio list gets presented. In that list, several percentages are there ranging from 100-200%. But in regolith, even after opting for fractional scaling, no list is available. The options for scaling before and after switching on the fractional scaling are 100% and 200%.

**To Reproduce**
Steps to reproduce the behaviour: Simply switch on the fractional scaling feature and see that no additional options are made available after that.

**Expected behaviour**
A list with options like 125%, 150%, 175% should be available. 

**Screenshots**
![image](https://user-images.githubusercontent.com/35566657/96275109-f8754480-0fee-11eb-9b58-b4be25d03f4b.png)

**Configuration file(s)**
No configuration has been done. The system is running on default settings.

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 1.4
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 20.04 focal

**Additional context**

**Comment by moritzheiber** [comment]
I believe this is an issue with `gnome-flashback`, but I might be wrong ..

**Comment by kgilmer** [comment]
Yes, I believe so as well.  I'm guessing that fractional scaling is provided by `gnome-shell`, it's window manager, or some other Gnome-3 thing that isn't part of `gnome-flashback`.  Setting DPI can be done via Xresources: https://computingforgeeks.com/how-to-set-correct-screen-dpi-in-linux-xresources/

**Comment by muktupavels** [comment]
Fractional scaling is Ubuntu only thing (Ubuntu specific patches)...

**Comment by twvd** [comment]
From experience I can tell you it's better to just ignore that setting and use the Xresources method. It works better.

(Well, somewhat.. Display scaling is a huge pain on Linux, regardless of the DE, it seems. Certain applications still misbehave)

**Comment by parkan** [comment]
> Yes, I believe so as well. I'm guessing that fractional scaling is provided by `gnome-shell`, it's window manager, or some other Gnome-3 thing that isn't part of `gnome-flashback`. Setting DPI can be done via Xresources: https://computingforgeeks.com/how-to-set-correct-screen-dpi-in-linux-xresources/

this has no effect, using ~/.config/regolith/Xresources has some (scales certain menus), neither has the desired effect (150% scaling analogous to the 200% scaling in the gnome menu)

**Comment by Philipp0205** [comment]
Is there any update on this? I really would like to scale one high-res monitor to 125%.

**Comment by kgilmer** [comment]
Regolith will be limited in DPI settings until/if we move to a window-manager/compositor that supports these features.  You're seeing these unavailable features in control panel because that was written to integrate with other window managers that support those features.  Ideally we could remove UI for features that Regolith components don't support but a way of doing that without forking `gnome-settings` has not been found.

FWIW In Regolith 2 the Xresource settings will be a bit simplified, so adding the DPI stuff into `~/.Xresources` should have the intended effect.

**Comment by samsja** [comment]
Thank you for your answers, it is very clear !

**Comment by JohannesPertl** [comment]
Any updates on this issue?

**Comment by kgilmer** [comment]
Hi @JohannesPertl , this is not likely to change until a Wayland version of Regolith is available.  The underlying X11 components that Regolith currently uses does not offer this feature.

**Comment by twvd** [comment]
I've been using Wayland (sway) for a while now and DPI/scaling works amazingly well compared to X11. Everything scales effortlessly to any desired value without any blurryness, different scales for different monitors, etc.

Regolith using sway would be amazing :)

**Comment by kgilmer** [comment]
Due to some really amazing work by Regolith contributor @SoumyaRanjanPatnaik , rapid progress is being made on a Sway-based variant of Regolith.

**Comment by samsja** [comment]
Hey @kgilmer, I am wondering if this is possible know, I saw that the sway relogith github has been archived
