### ISSUE TITLE
Regolith on Ubuntu 20.10 shows incorrect icons in i3bar

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#492]
**Describe the bug**

![regolith-groovy](https://user-images.githubusercontent.com/49683/97095503-f0cc2600-1614-11eb-9c6b-68f28866b1c5.png)

**To Reproduce**
Install Regolith on Ubuntu 20.10

**Expected behavior**
Icons are as in previous Regolith versions

**Comment by kgilmer** [comment]
It looks like the material design web icons package from which the font used to render icons on the bar has changed such that the glyph mappings have changed.  

There are two obvious ways to resolve this: create groovy forks of every package that uses the material design icon font, or backport the updated version of the material design fonts to Bionic and Focal.

For users encountering this issue, a quick workaround is to install and select a Regolith look that uses another font for icons, such as Nord or Solarized-dark.

**Comment by keawade** [comment]
I'm seeing this issue as well.

Default settings i3 bar:
![Screenshot from 2020-10-25 10-54-14](https://user-images.githubusercontent.com/7308850/97112138-a13b3800-16b0-11eb-8c80-64b71a7ff805.png)

Some more incorrect icons as listed by `xrdb -query`:
![Screenshot from 2020-10-25 10-54-42](https://user-images.githubusercontent.com/7308850/97112140-a1d3ce80-16b0-11eb-9bfb-a032f9213ea3.png)

**Comment by p3k** [comment]
i’m seeing this in the bar after upgrade to 1.5 – related? (it’s ubuntu 18.04, though.)

![image](https://user-images.githubusercontent.com/16631/98841767-dda8bb00-2448-11eb-85b6-a709c56fb997.png)

**Comment by kgilmer** [comment]
Hi @p3k , no I believe your issue is unrelated.  My guess is that you do not have any typeface Xresources set.  I would try moving any of your Xresource customization after 1.5 upgrade and reintegrating them.

**Comment by moritzheiber** [comment]
@kgilmer As far as I can tell this fix has been shipped, right?

**Comment by kgilmer** [comment]
Yes, thanks.  Closing.
