### ISSUE TITLE
Can't change rofi theme after stating in Xresources 

### ISSUE THREAD

**Issue by Vruttant** [regolith-linux/regolith-desktop#493]
So my Xresources file (located in .config/regolith/Xresources) looks like:

> gnome.wallpaper: /home/(username)/Downloads/Wallpapers/simple_log.png
> rofi.drun-icon-theme: Papirus
> gnome.icon.theme: Papirus
> rofi.show-icons: true

What change i was expecting?
- rofi's icon theme to be changed.

What went wrong?
- rofi's icon theme didn't changed and remained to the stock one (Moka).

**Comment by moritzheiber** [comment]
I think this is an error in the docs. Can you try with `rofi.icon-theme` please?

**Comment by Vruttant** [comment]
> I think this is an error in the docs. Can you try with `rofi.icon-theme` please?

Hey thanks for your prompt reply! This fixed the issue.
