### ISSUE TITLE
Make picom available for more than bionic

### ISSUE THREAD

**Issue by mrzor** [regolith-linux/regolith-desktop#494]
**Problem**
When using the stable PPA, `picom` won't install on focal (presumably, not on anything but bionic). As a result, package `regolith-compositor-picom-glx` cannot be installed.

**Solution**
`picom` needs to be packaged for focal - I presume the same issue will arise for groovy, for which support is in the works I believe.

**Workaround**
Fetch the package manually, `sudo apt remove compton`, `sudo dpkg -i <debfile>`, `sudo apt install regolith-compositor-picom-glx regolith-desktop` (removing compton will uninstall regolith-desktop)

**Additional context**
This feels connected to #419 in spirit.

**Comment by moritzheiber** [comment]
The package is available as `regolith-compositor-picom-glx` now. Thank you for your patience :slightly_smiling_face:!
