### ISSUE TITLE
Append to i3 config via resources

### ISSUE THREAD

**Issue by morten-b** [regolith-linux/regolith-desktop#496]
- [x] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

I would like to make addition to i3 config without having to edit the config file itself.

This could be done with something like:
```
set_from_resource $i3-wm.append.1 i3-wm.append.1 :
set_from_resource $i3-wm.append.2 i3-wm.append.2 :
set_from_resource $i3-wm.append.3 i3-wm.append.3 :
$i3-wm.append.1 
$i3-wm.append.2
$i3-wm.append.3
```

**Comment by moritzheiber** [comment]
We've decided to lobby for such a feature upstream instead, maybe you want to lend it some support: https://github.com/i3/i3/issues/4192

The way you're suggesting here, I think, could lead to _a lot_ of breakage and it's not what the Xresources method was designed for.

**Comment by morten-b** [comment]
> We've decided to lobby for such a feature upstream instead, maybe you want to lend it some support: [i3/i3#4192](https://github.com/i3/i3/issues/4192)

Thanks for the response. I've placed a vote
