### ISSUE TITLE
Loosing bar info and some style when logging out

### ISSUE THREAD

**Issue by mikaben89** [regolith-linux/regolith-desktop#497]
Hi !
I installed Regolith on my existing Ubuntu 20.4. Works like a charm but when I logout and log back in I loose a lot of things:
The bar informationn first and then I think I also loose some style (like the rofi default theme becomes white).
I followed advice from many threads like this [one](https://github.com/regolith-linux/regolith-desktop/issues/457?_pjax=%23js-repo-pjax-container) and this [one ](https://github.com/regolith-linux/regolith-desktop/issues/178)
And I have tried to remove clean and reinstall regolith (which made it work perfectly until my next logging out)
Here's attached a pic of my dekstop (with the empty info bar)
![Capture d’écran du 2020-11-03 18-06-09](https://user-images.githubusercontent.com/9348099/98017732-f4736000-1dff-11eb-95e4-d1eb9c2cc7dc.png)
Here are my i3xrocks modules 
```
apt search i3xrocks-                
En train de trier... Fait
Recherche en texte intégral... Fait
i3xrocks-battery/focal,now 3.0.21-1 amd64  [installé]
  Indicator to show battery status.

i3xrocks-cpu-usage/focal,now 3.0.21-1 amd64  [installé]
  Indicator to show CPU load.

i3xrocks-focused-window-name/focal 3.0.21-1 amd64
  Indicator to show focused window name.

i3xrocks-key-indicator/focal 3.0.21-1 amd64
  Indicator for caps and num lock status.

i3xrocks-keyboard-layout/focal 3.0.21-1 amd64
  Indicator to show keyboard layout.

i3xrocks-media-player/focal 3.0.21-1 amd64
  Indicator to manage media playback.

i3xrocks-memory/focal,now 3.0.21-1 amd64  [installé]
  Indicator to show memory utilization.

i3xrocks-net-traffic/focal,now 3.0.21-1 amd64  [installé]
  Indicator to show network I/O status.

i3xrocks-nm-vpn/focal 3.0.21-1 amd64
  Network manager VPN indicator.

i3xrocks-openvpn/focal 3.0.21-1 amd64
  Indicator to show openvpn status.

i3xrocks-temp/focal 3.0.21-1 amd64
  Indicator for system temperature.

i3xrocks-time/focal,now 3.0.21-1 amd64  [installé]
  Indicator to show date and time.

i3xrocks-volume/focal,now 3.0.21-1 amd64  [installé]
  Indicator to show volume.

i3xrocks-weather/focal,now 3.0.21-1 amd64  [installé]
  Indicator to show local weather.

i3xrocks-wifi/focal 3.0.21-1 amd64
  Indicator to display wifi router name.

```

Here's the output of  `i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d `
```
i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d 
/home/*****/.config/regolith/i3xrocks/conf.d: No such file or directory
<2>invalid Xresource key: "xresource:i3xrocks.value.color"
<3>failed to load config file 01_setup
<2>Failed to load configuration.
```

If anyone has any clue of what to do to fix this that would be great

Thanks in advance !

**Comment by moritzheiber** [comment]
Have you tried moving your `~/.config/regolith` directory out of the way and "starting fresh"? You can then put your settings back one by one and try to find out which of them is causing the issue.

From what it looks like you're either setting the value `i3xrocks.value.color` incorrectly or the relevant installed and selected style doesn't ship with it.

**Comment by mikaben89** [comment]
Hi @moritzheiber Thanks for your answer !
I tried your solution but it didn't fix the problem. Even if the regolith config dir is recreated it still shows an empty bar and a weird style. 
About `i3xrocks.value.color`, I didn't touch any config file. (Just created an ~/.Xresources-regolith with  `i3-wm.bar.position bottom: top` in it but that is it.
Still don't understand why everything breaks when I loggin out and in.

**Comment by moritzheiber** [comment]
Have you modified any of the files in `/etc/regolith`? And which style are you using?

**Comment by moritzheiber** [comment]
By the way, the key should read `i3-wm.bar.position: top`. If you have the word `bottom` in there as well your Xresources configuration is not readable.

**Comment by kgilmer** [comment]
Based on `<2>invalid Xresource key: "xresource:i3xrocks.value.color"` there is a pretty strong evidence that there is an Xresource file with invalid formatting.  You can search thru your files and any with lines of this value, prefix with `!` to turn them into comments.  Log back in and if you still have an issue run the i3xrocks command from above again, reopen this issue, and paste the output here.
