### ISSUE TITLE
Upgrading with Customizations and forgotten ~/.config/regolith/Xresources file

### ISSUE THREAD

**Issue by ostanislaw** [regolith-linux/regolith-desktop#499]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Documentation page after upgrade from 1.41 to 1.50
https://regolith-linux.org/docs/getting-started/install/#regolith-141---regolith-15
According to the "Upgrading with Customizations":
after move of 2 files we will start "stock" Regolith config after restart. It's not true, the most important and suggested customizations are done in following file:
~/.config/regolith/Xresources

**To Reproduce**
Follow "Upgrading with Customizations" instruction

**Expected behavior**
Behavior accordant to description

**Screenshots**
N/A

**Configuration file(s)**
N/A

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.50
 - PPA url: default: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Additional context**
N/A

**Comment by moritzheiber** [comment]
The documentation clearly states that you should also move away the `~/.config/regolith` folder, which is the correct sequence of actions. This includes the file you presume is more important.

**Comment by ostanislaw** [comment]
Yes, it's move of directory. Sorry. I thought if is just single config file move.
