### ISSUE TITLE
Support Ubuntu 19.04 in PPA

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#5]
Requires porting them in launchpad and then having someone test the results.  Will go into regolith-unstable until confirmed working.

**Comment by kgilmer** [comment]
Regolith packages have been copied to Ubuntu 19.04 version in the [regolith-unstable PPA](https://launchpad.net/~kgilmer/+archive/ubuntu/regolith-unstable/).  Needs testing.

**Comment by winduptoy** [comment]
With a fresh install of 19.04, I am unable to use the "Super+Space" command to open the run dialog. All other keyboard shortcuts listed in the help dialog work.

In gnome-control-center I disabled the "Super+Space" keyboard shortcut for toggling input modes, but that did not solve it.

**Comment by kgilmer** [comment]
Interesting ok thanks for the info @winduptoy .  I'll investigate.

**Comment by kgilmer** [comment]
Hi @winduptoy I finally got Regolith installed (from the unstable ppa) and do not see the problem that you reported with super+space.  I have not played with it much and want to see if the multimonitor bugs reported elsewhere have been fixed.

I wonder if you made any i3 config changes (~/.config/i3-regolith/config) that may be causing the problem?  Also, perhaps you can try launching `rofi` manually to bisect the issue into either window-manager or rofi domain...

```
$ cat ~/.config/i3-regolith/config  | grep rofi
# rofi app and window launchers
bindsym $mod+space exec rofi -show drun -theme regolith-theme
bindsym $mod+Shift+space exec rofi -show run -theme regolith-theme
bindsym $mod+w exec rofi -show window -theme regolith-theme

kgilmer@dogma:~$ rofi -show drun -theme regolith-theme
```

**Comment by kgilmer** [comment]
The wallpaper is overwritten upon login when installing Regolith on Ubuntu 19.04.  I'm guessing this is a regression in gnome-flashback and have filed an issue: https://gitlab.gnome.org/GNOME/gnome-flashback/issues/17

**Comment by kgilmer** [comment]
gnome-flashback requires a different key than what I was setting to prevent it from writing gnome wallpaper.  Not sure why it worked in 3.28 but it the fix is verified.

**Comment by kgilmer** [comment]
Closing as fixed based on my testing.  Kindly re-open if there continue to be issues.

**Comment by reuben77** [comment]
Supe + space gives an error with rofi

Failed to open theme
Error no such file or directory

**Comment by kgilmer** [comment]
Hi @reuben77 , what is the output of `i3 --moreversion`?  Are you using your own Xresource definitions?  If you can join the slack channel that's the best way of getting troubleshooting help: https://regolith-linux.herokuapp.com/
