### ISSUE TITLE
Add Contributing Guide

### ISSUE THREAD

**Issue by humb1t** [regolith-linux/regolith-desktop#502]
- [x] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Is your feature request related to a problem? Please describe.**
`README.md` contains a link to `CONTRIBUTING.md` which is missing. So willing to contribute I can't find a good place to start.

**Describe the solution you'd like**
Receive `CONTRIBUTING.md` with some initial information on how to start contribution.

**Describe alternatives you've considered**
Maybe information already presented somewhere so only the link target in `README.md` can be changed.

**Comment by moritzheiber** [comment]
Excellent find, thank you. I'll try to come up with something.
