### ISSUE TITLE
latest packages cause Advanced Network Configuration to quit in VMWare

### ISSUE THREAD

**Issue by psifertex** [regolith-linux/regolith-desktop#503]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
"Advanced Network Configuration" utility is consistently crashing. Happened after I upgraded in my ISO based VM so I re-installed a fresh VM of 20.10, installed via PPA, and I'm seeing the same behavior. Screenshot below. 

**To Reproduce**
Install fresh Ubuntu 20.10 VM
Follow regolith instructions install instructions via PPA
Login to regolith session
Wait

Alternatively, install an ISO 20.04 VM and follow the apt update / apt upgrade instructions for the latest regolith packages. Same behavior, I only did the fresh PPA to verify it.

**Expected behavior**
No crashing

**Screenshots**
![Screen Shot 2020-11-11 at 3 32 45 AM](https://user-images.githubusercontent.com/140215/98788593-202db180-23cf-11eb-8b8b-95441651616e.png)

**Configuration file(s)**
Only thing I changed was terminal font size and set a background image (again, similar to the docs), fairly certain this is unrelated.
```
$ cat .config/regolith/Xresources 
gnome.terminal.font:	JetBrains Mono 16
```

**Installation Details**
 - Regolith Install Type: BOTH
 - Regolith Version: 1.5
 - PPA url: default: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.10 for PPA install, 20.04 for ISO install

**Additional context**
Only happened after a recent apt update && apt upgrade in the ISO install.

**Comment by moritzheiber** [comment]
Can you verify that this is not happening under a regular Ubuntu session (Unity et al)? I wouldn't know how this is specifically connected with Regolith and its update.

**Comment by psifertex** [comment]
Good question. It's not 100% reliable unfortunately, but I did just reboot in to a regular session and use it for a while without issue.

Also, the only packages I noticed updating on the 20.04 VM were the regolith ones which definitely strikes me as pointing more toward that. Seems odd that both the ISO install and a 20.10 PPA install would exhibit the same behavior at the same time for something related to the base OS. Could possibly be something related to do with being in a VM? But I'm not sure why that would impact things. Next time I'll check out the stack trace and see if anything network related is implicated or if it's something UI related. 

It's worth noting that the network was fine even if I didn't restart it, but I did lose the little network manager icon in the very corner of the info bar.

**Comment by moritzheiber** [comment]
Interesting, does the "Advanced Network Configuration" app have a tray icon? It could be that the tray is "dying" unexpectedly and takes the "Advanced Network Configuration" app with it .. :thinking:

**Comment by psifertex** [comment]
Yes, it does. In fact I just noticed that sometimes it silently dies too. I don't get the popup, but the icon goes away. 

Here's my default info bar:

![Screen Shot 2020-11-11 at 11 39 13 AM](https://user-images.githubusercontent.com/140215/98838625-87208a00-2412-11eb-9de3-fdd5f08ff35c.png)

If I click the network icon on the left, the network traffic section disappears for a few seconds and returns (not sure if unintended or not?)

![Screen Shot 2020-11-11 at 11 39 28 AM](https://user-images.githubusercontent.com/140215/98838645-91db1f00-2412-11eb-8d97-58defb36d818.png)

And then after a while it just re-appears like in the first screenshot.

Ahh, that might be related to the following syslog message:

```Nov 11 11:39:23 streambox regolith.desktop[2335]: /usr/share/i3xrocks/net-traffic: line 35: INT_TYPE: unbound variable
Nov 11 11:39:23 streambox regolith.desktop[1872]: <3>[net-traffic] Command '/usr/share/i3xrocks/$BLOCK_NAME' exited unexpectedly with code 1
```
I expect that's reltaed to the traffic monitor disappearing/reappearing but not the networkmanager crashes. 

Sorry, I'm very new to i3, don't know much about how the tray works/what is supposed to be there. 

I'll post another screenshot showing when the icon on the right disappears but I wonder whether there's a better log mechanism? Just went looking through syslog for anything NetworkManager related and don't see anything that looks useful right now.

**Comment by moritzheiber** [comment]
The tray "applet" disappearing (the one which "belongs" to i3xrocks) isn't necessarily a "bad thing" since it'll fade in and out depending on how much traffic you're seeing. So that's normal, mostly. However, make sure you've updated to the latest version(s) of the package(s) (released sometime yesterday) because there are fixes for the i3xrocks-specific packages in there, in particular the `net-traffic` package.

As for the "Advanced Network Configuration", just to be clear, that's an "app" that's installed inside your VMWare virtual machine to do .. what? Give you statistics? Or maybe I misunderstood what we're talking about .. ?

**Comment by moritzheiber** [comment]
(Also, if you think it can be helpful, join us (me) on our Slack, it's easier to do a back and forth on some of these issues and update tickets afterwards)

**Comment by moritzheiber** [comment]
After debugging this with @psifertex in Slack (thanks for helping us out here!) I can confirm that this is a bug in the net-traffic applet, which was fixed with regolith-linux/regolith-i3xrocks-config#86 and should be shipped with the next release (or already be in `unstable`, not sure).

The other issue is likely related to #505 and will likely be fixed when we switch over to the newer i3 release.

@psifertex Can we close this for now? You can open a follow-up issue should the related fixes not solve your original issue(s) :slightly_smiling_face:

**Comment by psifertex** [comment]
Absolutely. Thanks for following up.
