### ISSUE TITLE
Sys tray gets killed on i3 restart

### ISSUE THREAD

**Issue by mohanraghug** [regolith-linux/regolith-desktop#505]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Whenever i3 is restarted using super+shift+r the applications in the systray like nm-applet are killed automatically

**To Reproduce**
Just restart i3 using super+shift+r while nm-applet is running.

**Screenshots**
Before restart
![Screenshot from 2020-11-12 23-04-56](https://user-images.githubusercontent.com/37501116/98975188-d1515a80-253b-11eb-8711-12c410555e7b.png)

After restart
![Screenshot from 2020-11-12 23-05-17](https://user-images.githubusercontent.com/37501116/98975210-d7dfd200-253b-11eb-8e24-e27ac5669161.png)

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: [ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 20.04

**Comment by moritzheiber** [comment]
There is a potential fix for this in the latest i3 version available. I would suggest we update to 4.18.3 in order to give it a try.

**Comment by sitepodmatt** [comment]
https://github.com/i3/i3/issues/4159

This also applies to monitor hotplug too.. Others distros seem to have patched or move forward, Ubuntu seems to be lagging here

**Comment by sitepodmatt** [comment]
I tested the i3 binaries of 4.19 ripped out from https://debian.sur5r.net/, manually extracted to /usr/bin and this seems to fix the systray issues. Not a perfect solution as had to cancel out the gaps.

**Comment by ristomatti** [comment]
I had this issue while using Ubuntu release or stable PPA versions but the issue disappeared after installing from the unstable PPA.

**Comment by moritzheiber** [comment]
i3 4.19.x is staged in `unstable` and should fix this issue, I'm marking this as resolved in the 1.5.1 milestone

**Comment by moritzheiber** [comment]
1.5.1 is shipped. We believe this to be fixed.
