### ISSUE TITLE
[Screen Issues] I often get issues with screen updates. 

### ISSUE THREAD

**Issue by Devpineapple** [regolith-linux/regolith-desktop#506]
- [ x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
The Bug is simple to describe, somethimes my screen just stops updating some parts of the applictation(s).
**To Reproduce**
Unknown
**Expected behavior**
I expected to see the whole application respond to the screen update.
**Screenshots**

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.
I added the regolith styles folder presently
I added i3xrocks-battery package

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.5
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Elementary OS 5.1.7 Hera (Ubuntu 18.04)

**Additional context**

**Comment by moritzheiber** [comment]
Could you try switching to the `none` compositor?

```
apt install regolith-compositor-none
```
and then logout and log back in again?

**Comment by Devpineapple** [comment]
I will try it right now.

**Comment by Devpineapple** [comment]
Hey it worked! Thank you!

**Comment by Devpineapple** [comment]
It kinda worked... But still i am having issues while dragging objects like text or images.

**Comment by moritzheiber** [comment]
You're using a very old version of Ubuntu (although it's a LTS release). Could you try to at least update to their [Hardware Enablement (HWE) stack](https://ubuntu.com/kernel/lifecycle)?

Also, which graphics card are you using and what driver?

**Comment by Devpineapple** [comment]
I am using an Nvidia Quadro P520, with the 440 Nvidia proprietary drivers. I gonna try updating the HWE stack later.

**Comment by Devpineapple** [comment]
Ok, so now i checked the HWE stack status, and it said this:
`workstation@ThinkPad-P43s:~$ hwe-support-status --verbose 
Only LTS releases have Hardware Enablement stacks
`

**Comment by Devpineapple** [comment]
I changed compositors, and i think it fixed. Gonna let you know if there is errors, but for now i will close the issue.

**Comment by moritzheiber** [comment]
Thanks for confirming that the issue appears to be resolved.

As to your earlier posting, the message from `hwe-support-status` is expected since you're using Elementary and not a regular Ubuntu version. It's safe to install the HWE stack for `Bionic` though:

```
sudo apt-get install --install-recommends linux-generic-hwe-18.04 xserver-xorg-hwe-18.04
```

Also, on top of that, you could try updating your proprietary NVIDIA driver. You just have to have [the `focal-updates` repository part enabled](https://help.ubuntu.com/community/Repositories/Ubuntu#Updates_Tab) in the "Software" settings and the install the package `nvidia-driver-450`.

**Comment by RafalSkolasinski** [comment]
@Devpineapple Which compositor you got best results with in the end? Also do you use any of 
- Sync to VBlank
- Allow Flipping
- Force (full) composition pipeline 
settings in nvidia drivers?

I am just trying to figure out similar problem...
