### ISSUE TITLE
Conflicting shortcuts between gnome-shell and regolith

### ISSUE THREAD

**Issue by paolomainardi** [regolith-linux/regolith-desktop#507]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

Having defined shortcuts defined on Gnome, have precedence on the Regolith ones.

An example:

![image](https://user-images.githubusercontent.com/8747/99191044-5cb03300-276a-11eb-89a6-f723f8d0fced.png)

This one overrides Rofi shortcuts making them unusable.

**To Reproduce**

* Login in a gnome-shell session
* Open gnome control panel and set a shortcut `MOD + Space`
* Log out from gnome shell and log in to Regolith
* `MOD + Space` not works

**Expected behavior**

We should detect any overridden keyboard shortcut and warn the user.
Another way could be that Regolith will overwrite in any case default shortcuts.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.5
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 20.04

**Comment by kgilmer** [comment]
Interesting problem.  It's not clear to me how we would resolve this as this is a "feature" of gsettings/dconf as I understand it.  By setting a shortcut in gnome-shell in the non-regolith session you're saying you want to override the default value.  The regolith component that is reading this is `gnome-flashback` I'm guessing.  Can you verify by [running `xev` or something else](https://superuser.com/questions/248517/show-keys-pressed-in-linux) that reports which program is consuming the key press?

**Comment by kgilmer** [comment]
I believe this issue is resolved in regolith 1.5 with gsettings overrides.

**Comment by technic** [comment]
I have an ubuntu with Gnome desktop, and I installed regolith from the ppa. After start shortcuts involving `Super+Space` doesn't work.
