### ISSUE TITLE
Permanent Desktop window

### ISSUE THREAD

**Issue by sandeepchitturi** [regolith-linux/regolith-desktop#509]
Hi After i upgraded to ubuntu 20 and upgraded to latest version regolith, i am getting desktop window as default when i logged regolith linux, like below
![Screenshot from 2020-11-20 10-29-55](https://user-images.githubusercontent.com/2590549/99761156-65628980-2b1b-11eb-8fd3-d94182043190.png)

**Comment by kgilmer** [comment]
Hi @sandeepchitturi , this is due to changes in gnome-flashback across Ubuntu versions.  To fix this issue, remove the directory `~/.config/regolith/flags` and log back into the Regolith session.

**Comment by sandeepchitturi** [comment]
I removed and log back again but it issue still persists i did a sudo rm -rf

**Comment by kgilmer** [comment]
Hmm, I'm not sure why that would be the case.  Another way you can fix this is by manually updating the gsettings values that control this feature.  See this file for the Regolith-specific gsettings that are supposed to be applied upon login (which seem to have not happened correctly in your case): https://github.com/regolith-linux/regolith-default-settings/blob/master/debian/regolith-default-settings.gsettings-override

I believe the setting you're looking for is the first.  The items in brackets are the schema, and the items below are keys.  What do you get when you run:

```
$ gsettings get org.gnome.gnome-flashback desktop
```

Assuming you get a `true`, then run this to set it to false:

```
$ gsettings set org.gnome.gnome-flashback desktop false
```

And have a look at the other settings in that file, you may need to update more of them manually to completely resolve your issue.

Either way let me know how it goes, we'll get your system fixed up one way or another.  Also feel free to join us on slack for more help.

**Comment by sandeepchitturi** [comment]
That fixed thanks Ken.
