### ISSUE TITLE
Regolith does not set x-terminal-emulator back to original after uninstall

### ISSUE THREAD

**Issue by samlobel** [regolith-linux/regolith-desktop#51]
I tried out regoltih (it's great, but not what I'm looking for). I eventually uninstalled it, but then realized that the process started for x-terminal-emulator stayed as regolith-st, instead of changing back to xterm.

Not a huge deal, but it was annoying to manually change back.

**Comment by kgilmer** [comment]
Thanks for the feedback @samlobel .  Do you mean that `regolith-st` stayed installed on your system after removing `regolith-desktop` and continued to be the default terminal, or that it was removed and x-terminal-emulator became broken?  And/or can you explain how you changed it back?

**Comment by kgilmer** [comment]
Closing tomorrow if no response.

**Comment by kgilmer** [comment]
The `regolith-st` package is not autoremoved when `regolith-desktop` is uninstalled.  I'm guessing this is because of the `update-alternatives` mappings that are created as part of the install.  However, once all regolith packages have been removed from the system, I have verified that x-terminal-emulator is restored to it's pre-Regolith state.  

Created another ticket to update uninstall documentation.

**Comment by tabatalisboa** [comment]
Hi @kgilmer , I'm with the same problem. How can I remove "all regolith packages [...] from the system"?

**Comment by kgilmer** [comment]
Hi @tabatalisboa , you can see all the packages installed with:
```
apt list --installed | grep regolith
```

If you see none, then you're good.  If you see some packages, just do:
```
sudo apt remove <package name>
```

And that should be it.  Let me know if you still have troubles!  :smile:

**Comment by tabatalisboa** [comment]
Hey @kgilmer thanks for helping out.
I got an error:
`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

but I don't have the `Regolith Terminal anymore`. I might have done something right in btw.

**Comment by mrshappy0** [comment]
I'm having issues with this as well. I've tried the uninstall directions and other suggestions but nothing works. When I run `apt list --installed | grep regolith` I will get an entire list of installed packages. I tried the next command to run the remove the packages but I'm honestly not sure what the names of the packages are.

**Comment by kgilmer** [comment]
`sudo apt purge regolith-*` should remove all regolith packages, and then `sudo apt autoremove` should remove any transitive dependencies.

**Comment by mrshappy0** [comment]
Yep that worked! Thanks @kgilmer .
