### ISSUE TITLE
Ghosting of terminal + interface

### ISSUE THREAD

**Issue by fostiropoulos** [regolith-linux/regolith-desktop#510]
**Describe the bug**
Sometimes the terminal and the interface doesn't update. Only happens to a portion of the screen or terminal window. For example, I can run 'clear' on terminal and it will still have the previous text/commands. Moreover whatever I type will not be displayed because the previous text is on higher z-index. I would have to switch windows/workspaces for this to correct.

**To Reproduce**
Difficult to reproduce since it happens randomly. Moreover whenever I try to take a screenshot it corrects itself.

**Expected behavior**
No ghosting.

**Screenshots**
 whenever I try to take a screenshot the bug is fixed.

**Configuration file(s)**
No customization 

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [1.5]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 18.04]

**Comment by kgilmer** [comment]
Hi @fostiropoulos , if you're using NVidia HW w/ the proprietary driver this may be of interest: https://github.com/regolith-linux/regolith-compositor-picom-glx/issues/2

If not, please add details regarding your video sw and hw configuration.

**Comment by fostiropoulos** [comment]
@kgilmer Seems to be the case. But the instructions on what to do are not clear to avoid this issue. Is compositor installed by default? I created a config file and entered the config option but doesn't seem to resolve the issue.

**Comment by fostiropoulos** [comment]
There was some confusion on where the picom config was. The docs https://regolith-linux.org/docs/reference/configurations/ 
suggested it was at /etc/regolith/compton/config but was actually at /etc/regolith/picom/config

**Comment by kgilmer** [comment]
@fostiropoulos thanks for mentioning the documentation issue.  I'll fix that now.
