### ISSUE TITLE
Toggle bar make the system logout

### ISSUE THREAD

**Issue by vzlcn0** [regolith-linux/regolith-desktop#512]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
toggling status bar make the system logout. (Win + i)
or when using ```regolith-look refresh```

**To Reproduce**
I just install fresh regolith-desktop on Ubuntu 18 using the following instructions: [Install](https://regolith-linux.org/docs/getting-started/install/).

Then I moved the config files for both i3 and 3xrocks from /etc to .config/ as descried in the official documentation. 

Then I connect a new monitor to the system, which worked fine.
but when I disconnect the HDMI cable, the system logout to Ubuntu lockscreen.

I thought it was from the multi monitors but after some debugging I found out when I toggle the status bar (Win + i) twice the system logout.

using ```regolith-look refresh``` also make the same behavior. 

I try to remove all i3xrocks/0#_ files to check if one of them making this issue, but it did not work.

**EDIT:** (Win + Ctrl+ r) and (Win + Shift + r) cause the same behavior when pressed twice or more in a row.

**Expected behavior**
The system will not logout, and should toggle the status bar.

**Screenshots**
-

**Configuration file(s)**
```
# move workspace to left and right monitors
bindsym $mod+Shift+bracketleft move workspace to output left
bindsym $mod+Shift+bracketright move workspace to output right
```

to the i3 config file, and I try to comment them, it did not work

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [1.5]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 18.04]

**Additional context**
-

**Comment by moritzheiber** [comment]
It sounds like i3 is crashing. Is there anything in the system-wide logs?

**Comment by vzlcn0** [comment]
related logs from journalctl after the crash:

```
Nov 24 19:00:43 k gnome-flashback[4195]: The program 'gnome-flashback' received an X Window System error.
                                         This probably reflects a bug in the program.
                                         The error was 'RenderBadPicture (invalid Picture parameter)'.
                                           (Details: serial 2725 error_code 143 request_code 139 (RENDER) minor_code 7)
                                           (Note to programmers: normally, X errors are reported asynchronously;
                                            that is, you will receive the error a while after causing it.
                                            To debug your program, run it with the GDK_SYNCHRONIZE environment
                                            variable to change this behavior. You can then get a meaningful
                                            backtrace from your debugger if you break on the gdk_x_error() function.)
Nov 24 19:00:43 k nm-applet[4257]: The program 'nm-applet' received an X Window System error.
                                   This probably reflects a bug in the program.
                                   The error was 'RenderBadPicture (invalid Picture parameter)'.
                                     (Details: serial 466 error_code 143 request_code 139 (RENDER) minor_code 7)
                                     (Note to programmers: normally, X errors are reported asynchronously;
                                      that is, you will receive the error a while after causing it.
                                      To debug your program, run it with the GDK_SYNCHRONIZE environment
                                      variable to change this behavior. You can then get a meaningful
                                      backtrace from your debugger if you break on the gdk_x_error() function.)
Nov 24 19:00:44 k gnome-flashback[5140]: The program 'gnome-flashback' received an X Window System error.
                                         This probably reflects a bug in the program.
                                         The error was 'RenderBadPicture (invalid Picture parameter)'.
                                           (Details: serial 1066 error_code 143 request_code 139 (RENDER) minor_code 7)
                                           (Note to programmers: normally, X errors are reported asynchronously;
                                            that is, you will receive the error a while after causing it.
                                            To debug your program, run it with the GDK_SYNCHRONIZE environment
                                            variable to change this behavior. You can then get a meaningful
                                            backtrace from your debugger if you break on the gdk_x_error() function.)
Nov 24 19:00:44 k gnome-session-binary[3976]: CRITICAL: We failed, but the fail whale is dead. Sorry....
Nov 24 19:00:44 k gnome-session-binary[3976]: Unrecoverable failure in required component gnome-flashback.desktop
```

**Comment by kgilmer** [comment]
This would lead me to believe it could be a graphics hardware/driver issue.  You could try installing `regolith-compositor-none` but if that doesn't resolve it then I'd see if there are driver updates available for your video hardware.

**Comment by moritzheiber** [comment]
Especially if you're using a LTS release, switching to the HWE stack could make a profound difference: https://ubuntu.com/kernel/lifecycle

**Comment by vzlcn0** [comment]
> This would lead me to believe it could be a graphics hardware/driver issue. You could try installing `regolith-compositor-none` but if that doesn't resolve it then I'd see if there are driver updates available for your video hardware.

unfortunately installing ```regolith-compositor-none``` did not solve it.

> Especially if you're using a LTS release, switching to the HWE stack could make a profound difference: https://ubuntu.com/kernel/lifecycle

I checked, I have HWE.


Regarding the drivers, my system up-to-date, I didn't install any proprietary drivers for my GPU. I try switching between Intel and AMD GPU using ```DRI_PRIME=#``` both have the same issue.

Do you think installing AMD proprietary drivers will fix it?

**Comment by kgilmer** [comment]
Sorry @vzlcn0 I don't have any specific things to suggest here.  Driver changes may make a difference, but I'm just guessing at this point.  We'd appreciate it though if you do find a solution to report back here for future users.

**Comment by moritzheiber** [comment]
We have the newest i3 release staged in the `unstable` PPA, would you be able to give it a try and see whether it solves your issue?

**Comment by kgilmer** [comment]
FYI `i3-gaps` 4.19 is [now available](https://regolith-linux.org/regolith-builder/index.html) in `stable` from past Sunday.

**Comment by moritzheiber** [comment]
So, technically, this could be resolved now, @vzlcn0 .. could you try updating and see whether your issue still occurs?

**Comment by allumik** [comment]
I am not OG but update on stable fixed the issue for me, although I am also running it on debian, so I wouldn't call this solved.

**Comment by vzlcn0** [comment]
fixed for me on stable, thank guys
