### ISSUE TITLE
Can we have one workspace  floating, while other  workspace tiling. 

### ISSUE THREAD

**Issue by feima0011** [regolith-linux/regolith-desktop#515]
Can we have one workspace full floating, while other  workspace tiling. 

I am using matlab to plot figures, and it is easy to adjust the figure size in floating mode.
adjusting figure size in tiling mode is hard.

**Comment by moritzheiber** [comment]
Whatever i3 supports is also supported by Regolith's session. Please check on the [i3 documentation](https://i3wm.org/docs/userguide.html) to find out whether this particular feature is supported or not :slightly_smiling_face:
