### ISSUE TITLE
Some tray programs crash when i3bar visibility is toggled

### ISSUE THREAD

**Issue by korakinos** [regolith-linux/regolith-desktop#516]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Some programs in the system tray (confirmed: nm-applet, volumeicon, pa-applet) crash when the visibility of i3bar is toggled (default shortcut: $mod+i):

```
$ nm-applet

(nm-applet:19897): Gdk-CRITICAL **: 10:10:44.725: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
	
(nm-applet:19897): Gdk-WARNING **: 10:10:46.721: GdkWindow 0x5e00006 unexpectedly destroyed

(nm-applet:19897): Gdk-ERROR **: 10:10:46.729: The program 'nm-applet' received an X Window System error.
This probably reflects a bug in the program.
The error was 'RenderBadPicture (invalid Picture parameter)'.
  (Details: serial 357 error_code 143 request_code 139 (RENDER) minor_code 7)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

```
$ volumeicon

(volumeicon:21009): Gdk-WARNING **: 10:15:50.015: GdkWindow 0x5a00002 unexpectedly destroyed

(volumeicon:21009): Gdk-ERROR **: 10:15:50.034: The program 'volumeicon' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 306 error_code 3 request_code 61 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.
```

```
$  pa-applet
Failed to grab XF86AudioRaiseVolume
Failed to grab XF86AudioLowerVolume
Failed to grab XF86AudioMute
Available sink: alsa_output.pci-0000_00_1f.3.analog-stereo
Available sink: PulseEffects_apps
Available sink: PulseEffects_mic

(pa-applet:20880): Gdk-WARNING **: 10:15:38.456: GdkWindow 0x5a00002 unexpectedly destroyed

(pa-applet:20880): Gdk-ERROR **: 10:15:38.458: The program 'pa-applet' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 308 error_code 3 request_code 61 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
```

**To Reproduce**
1. Start one of the affected programs (from terminal or menu).
2. Toggle visibility of i3bar (doesn't matter if invisible or visible to begin with).
3. Instant crash.

**Expected behavior**
No crash.

**Installation Details**
 - Regolith Install Type: ISO (upgraded Ubuntu since original install)
 - Regolith Version: **The file /etc/regolith/version says 1.4.1, but there is also a (etc/regolith/version.dpkg-new with 1.5.0. Did something go wrong in an update?)**
 - PPA url:  ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04.1

**Comment by mathiasj33** [comment]
I'm also having this issue since my upgrade to Regolith 1.5. For me, `/etc/regolith/version` is 1.5 and not 1.4.1. I have installed Regolith via the package instead of the ISO if that helps.

**Comment by kgilmer** [comment]
Hi @mathiasj33 , I believe an update to i3-gaps-wm version 4.19 will resolve this issue.  That version is currently available in the `stable` PPA, and will be promoted to the `release` PPA with Regolith 1.5.1.

**Comment by moritzheiber** [comment]
We believe this to be fixed now that 1.5.1 has been shipped.

**Comment by mathiasj33** [comment]
Yes it's fixed now, thank you!

**Comment by korakinos** [comment]
Indeed it is, thanks!
