### ISSUE TITLE
Unclutter and regolith-ftue

### ISSUE THREAD

**Issue by DLongoni** [regolith-linux/regolith-desktop#518]
I'm having some troubles figuring out how unclutter is supposed to be executed at startup.

In my case, it gets executed because of the /etc/X11/Xsession.d/90unclutter entry, and it takes the configuration file in /etc/default/unclutter

On the other hand, in the i3 config I see:
set_from_resource $i3-wm.program.unclutter i3-wm.program.unclutter /usr/bin/regolith-ftue /usr/bin/unclutter -b
exec --no-startup-id $i3-wm.program.unclutter

So, how am I supposed to properly override unclutter configuration? Right now, if I set START_UNCLUTTER="false" in /etc/default/unclutter the program won't start at all, so I don't understand what the i3 config entry is supposed to do. 

I searched the doc and couldn't find anything about unclutter and regolith-ftue. Can you point me to some resource on the topic?

Thanks

**Comment by moritzheiber** [comment]
I think you might have some old configuration files still lying around (potentially from editing them in place instead of staging them?). For me the configuration doesn't contain anything `regolith-ftue` related:

```
$ grep unclutter config
set_from_resource $i3-wm.program.unclutter i3-wm.program.unclutter /usr/bin/unclutter -b
exec --no-startup-id $i3-wm.program.unclutter
```

If you want to override the `unclutter` settings, just set the `Xresources` definition for `i3-wm.program.unclutter` to something else

**Comment by moritzheiber** [comment]
(Also, the `Xsession` entry doesn't belong to the `unclutter` package Regolith ships, but rather to the regular unclutter, which conflicts with `regolith-unclutter-xfixes` .. i.e. the configuration file in `/etc` isn't used, I think)

**Comment by DLongoni** [comment]
@moritzheiber thanks for the reply. I am on a fresh complete distro install (1.4). I guess then upgrading to 1.5 should fix these unclutter issues as you mention. 

I am trying to stage everything I can in .Xresources , this is mostly why I was asking. I wanted to avoid editing the X11/Xsesison.d/ config. I'll look into the upgrade to 1.5. Thanks again

**Comment by moritzheiber** [comment]
Makes sense. Please open another issue should the problem you're having persist. Enjoy!
