### ISSUE TITLE
Printing test page crashes gnome-control-center

### ISSUE THREAD

**Issue by thistlillo** [regolith-linux/regolith-desktop#521]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Install a wireless printer (in my case Canon MG3550) and print a test page. The gnome-control-center crashes.

**To Reproduce**
- Install a fresh Ubuntu 20.04
- Install Regolith using PPA method described in section "Regolith Desktop via Repository (PPA)" at [https://regolith-linux.org/docs/getting-started/install/](https://regolith-linux.org/docs/getting-started/install/)
- install a network printer (in my case Canon MG3550) and print a test page
- gnome-control-center crashes (see attached smartphone photo)

**Expected behavior**
No crash

**Screenshots**
[https://ibb.co/d03Fb4b](https://ibb.co/d03Fb4b)

**Configuration file(s)**
Added `use-damage = false` because I was experiencing flickering issues.

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [1.5]
 - PPA url: [ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 20.04]

**Additional context**
- If I repeat the same sequence of operations using an Ubuntu session, everything works fine.
- In order to have the control center window disappear, I need to kill it (kill -INT) using a shell.

**Comment by moritzheiber** [comment]
Can you verify this is happening under a "regular" GNOME/Ubuntu session as well?

**Comment by thistlillo** [comment]
May be I did not understand your question. In that case, please do not get upset :-)

If you are asking me to repeat those steps in a default Ubuntu session, then, as I said in the "Additional context" of my original post, the error does not occur. If I need to do further tests, I would be glad to accomplish.

**Comment by moritzheiber** [comment]
My apologies, you did a better job at this than I anticipated (which is entirely on me, mea culpa).

Anything else in the system's logs that might indicate as to why `gnome-control-center` might be crashing?

(I'm tempted to close this as `wontfix` because there's hardly anything we can do about `gnome-control-center` crashing apart from telling you file an issue "upstream" :disappointed:)

**Comment by kgilmer** [comment]
Closing for lack of response.  Feel free to reopen if still an issue.
