### ISSUE TITLE
i3xrocks seg fault with regolith-looks enabled

### ISSUE THREAD

**Issue by geolaw** [regolith-linux/regolith-desktop#524]
- [X ] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ X ] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ X ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I enabled a regolith-look theme,

# regolith-look set nord 
and then every time I restart I get "Error: status command process exited unexpectedly (exit 139)"  in the i3bar at the bottom of the screen

![Screenshot_2020-12-14_14-32-21](https://user-images.githubusercontent.com/1840954/102267132-6e126980-3ee7-11eb-81e9-bd36bc3db423.png)

If I run via the command line :
#  i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d

I get a seg fault
[strace.txt](https://github.com/regolith-linux/regolith-desktop/files/5698310/strace.txt)

**To Reproduce**
# regolith-look set nord 
reboot and log back in

i3xrocks fails to load in 

**Expected behavior**
expected the i3xrocks to load properly

**Screenshots**

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: [ISO/PPA] PPA
 - Regolith Version: [e.g. 1.4] 
#dpkg -l |grep regolith-desktop
 ii  regolith-desktop                           2.92-1groovy                             amd64        metapackage for Regolith desktop environment

 - PPA url: [default: ppa:regolith-linux/release]
$ cat apt/sources.list.d/regolith-linux-ubuntu-release-groovy.list
deb http://ppa.launchpad.net/regolith-linux/release/ubuntu/ groovy main

 - Host OS (for PPA): [e.g. Ubuntu 20.04]
Ubuntu 20.10
**Additional context**

After troubleshooting this, I found that if I edited out the last 2 lines of /etc/regolith/i3xrocks/conf.d/01_setup that everything would launch properly.
That lead me to looking at where i3xrocks.value.color was getting set 
if I copied the "color" file from one of the styles 
e.g. 
# cp /etc/regolith/styles/nord/color /etc/regolith/styles/ 
restore the 01_setup file and then logged out and back in - everything loaded correctly.

**Comment by kgilmer** [comment]
Hi @geolaw , thanks for the detailed bug report.  Regarding the last two lines of `01_setup`, I'm guessing something is wrong w/ the Xresource values for either `i3xrocks.value.color` or `i3xrocks.label.color`.  When your system is in the bad state, what does running `xrescat` w/ those two parameters return?

**Comment by geolaw** [comment]
I think you can probably write this one off as not reproducable  :-)
I went back and tried to undo any changes I made yesterday

removed the /etc/regolith/styles/colors
created a couple new users to start "fresh", applied a regolith-look, logged out, rebooted, etc ... 

I cannot break the i3bar again -

**Comment by geolaw** [comment]
Weird thing today - I added a config option to move my Vinagre window to $ws3 and restarted and this issue came back.

I captured the xrescat commands as well as another strace.

[typescript.txt](https://github.com/regolith-linux/regolith-desktop/files/5716381/typescript.txt)

I think the problem is the .Xresources-regolith file in my home directory is not getting read in. 
If I prefix .config/regolith/Xresources with the one line from .Xresources-regolith and win+shift+r reload, boom, everything loads correctly.
Rebooted and also everything loads correctly.
![Screenshot_2020-12-18_10-05-46](https://user-images.githubusercontent.com/1840954/102629057-a3ea6480-4118-11eb-964d-bece82f99b9f.png)

**Comment by kgilmer** [comment]
`~/.Xresources-regolith` is loaded in `/usr/bin/regolith-session-init`.  Not sure why this would not be working for you, I haven't heard of anyone having a problem before.  Regarding the segfault, I wasn't able to determine anything definitive from your terminal output, but thanks for supplying that.  Can you just run `xrdb -query` and paste the results?

**Comment by geolaw** [comment]
Yeah, I can confirm I see it there : 
 grep USER_XR /usr/bin/regolith-session-init
USER_XRESOURCE_FILE="$HOME/.Xresources-regolith"
USER_XRESOURCE_OVERRIDE_FILE="$HOME/.config/regolith/Xresources"
USER_XRESOURCE_SEARCH_PATH="$HOME/.config/regolith/Xresources.d"
if [ -f "$USER_XRESOURCE_FILE" ]; then
    xrdb -I$USER_XRESOURCE_SEARCH_PATH -merge $USER_XRESOURCE_FILE
if [ -f "$USER_XRESOURCE_OVERRIDE_FILE" ]; then
    xrdb -I$USER_XRESOURCE_SEARCH_PATH -merge $USER_XRESOURCE_OVERRIDE_FILE

So it should be loading both  ~.Xresources-regolith and .config/regolith/Xresources

Maybe it's a timing issue of some kind?

This morning it loaded up just fine - like I said, I only made a minor config change 
to assign a class to a specific workspace when it popped back up:
for_window [class="Vinagre"] move to workspace $ws3

I will keep an eye on it and collect the xrdb -query output if it happens again.  
I only usually use this desktop computer monday - friday so my updates may be limited to that. 

Thanks

**Comment by moritzheiber** [comment]
It's important to mention that the configuration change you mentioned in your last message has to go into [a staged version of the i3 configuration file and *not* into any of the `Xresources` definitions](https://regolith-linux.org/docs/howto/stage-configs/#i3-config)!

I'll close this for now. Should you have anything more specific to report please let us know. If in doubt, roll back all of your customizations and add them back bit by bit to figure out which part is causing your issues.

**Comment by scmbradley** [comment]
Ah interesting. Sadly, I can't use that solution because I [can't install regolith-look packages...](https://github.com/orgs/regolith-linux/discussions/826)
