### ISSUE TITLE
Documentation instructures for removal of regolith

### ISSUE THREAD

**Issue by ThSGM** [regolith-linux/regolith-desktop#525]
First of all, thank you to you and the community for the development and work on this wonderful package. Like many users, Regolith provides a soft introduction to i3wm. Now that I am a bit more comfortable with i3, I am pondering whether I would like to go back to stock Gnome and to try using the manual version of i3.  

For those of us who installed the PPA version, can you please provide uninstallation instructions?

**Comment by kgilmer** [comment]
Hi @ThSGM , sure the uninstallation instructions are here: https://regolith-linux.org/docs/getting-started/install/#uninstallation-of-regolith-desktop

Good luck on your Linux desktop adventure!  :smile:

**Comment by trinh** [comment]
Hi @kgilmer 

Thanks! I was just a little bit worried about the various [threads](https://github.com/regolith-linux/regolith-desktop/issues/474) [that](https://github.com/regolith-linux/regolith-desktop/issues/62) [popped](https://askubuntu.com/questions/1151443/problems-removing-regolith-lnux) up, but I'm guessing that it's all largely been fixed. 

I guess the strategy will be to apply that purge command and just begin moving elements from the .config files (if desired) into the new i3wm install.

**Comment by ThSGM** [comment]
Hi @kgilmer

Thanks! I was just a little bit worried about the various threads that popped up, but I'm guessing that it's all largely been fixed.

I guess the strategy will be to apply that purge command and just begin moving elements from the .config files (if desired) into the new i3wm install.
