### ISSUE TITLE
how i can hide Menu bar

### ISSUE THREAD

**Issue by arbims** [regolith-linux/regolith-desktop#526]
- [ ] I Install regolith-linux

But when i open terminal i have this
![Screenshot from 2020-12-18 21-23-50](https://user-images.githubusercontent.com/22614888/102658273-8dbfc100-4177-11eb-88b9-a38e31ee4862.png)

how i can hide menu bar

**Comment by kgilmer** [comment]
Check and see if you have a 'Regolith' profile in `gnome-terminal`.  If not run `/usr/bin/create-regolith-term-profile` and check again.

**Comment by moritzheiber** [comment]
I'm closing this because the remedy Ken mentioned is likely going to solve your issue. Please re-open if it doesn't.

**Comment by vanboom** [comment]
I just upgraded Ubuntu from 18 to 20 and `regolith-desktop-complete` and am getting the same issue.  Creating the profile did not work and the profile settings have no control for the window manager decorations.  

My /etc/regolith/i3/config runs /usr/bin/x-terminal-emulator but it appears that I am getting a gnome-terminal on WIN SHIFT ENTER.  Thanks for any tips or hints.

**Comment by MattF-NSIDC** [comment]
How is this problem solved with Regolith 2.2? I don't have a `/usr/bin/create-regolith-term-profile` script.

**Comment by MattF-NSIDC** [comment]
We fixed it! I think `regolith-look refresh` and then reboot were what resolved our issue.
