### ISSUE TITLE
Can't launch VS Code's integrated terminal if VS Code is launched with regolith's global app launcher

### ISSUE THREAD

**Issue by spencerwooo** [regolith-linux/regolith-desktop#527]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

I can't launch VS Code's integrated terminal if I were to invoke VS Code from Regolith's global app launcher.

**To Reproduce**

<kbd>Super</kbd> + <kbd>Space</kbd>, search for `visual studio code`, press <kbd>enter</kbd> to launch VS Code, <kbd>Ctrl</kbd> + <kbd>`</kbd> to launch integrated terminal.

**Expected behavior**

Integrated terminal to launch.

**Screenshots**

Integrated terminal hangs instead of launching:

![image](https://user-images.githubusercontent.com/32114380/103133333-dbdb4400-46e4-11eb-93d8-301ccd44fb00.png)

Integrated terminal launched if VS Code is ran from command `code` or with [Albert](https://albertlauncher.github.io/).

![image](https://user-images.githubusercontent.com/32114380/103133365-03caa780-46e5-11eb-8f24-deb6df09827b.png)

**Configuration file(s)**

<details>
<summary>Only some font and theme customizations here.</summary>

Config file `~/.config/regolith/Xresources`:

```
gnome.wallpaper:
i3-wm.bar.position: top
i3-wm.gaps.inner.size: 8
gnome.gtk.theme:	Ayu-Mirage-Darker

gnome.icon.theme:	Tela
rofi.icon-theme:	Tela

St.font:	Ubuntu Mono:pixelsize=16:antialias=true:autohint=true
gnome.terminal.font:	UbuntuMono Nerd Font Mono 12
i3-wm.bar.font:	pango:Ubuntu Mono 12, Material Design Icons 12
i3-wm.font:	pango:Ubuntu Mono 12
i3-wm.workspace.01.name:	1:<span font_desc='Ubuntu Mono 12'> 1 </span>
i3-wm.workspace.02.name:	2:<span font_desc='Ubuntu Mono 12'> 2 </span>
i3-wm.workspace.03.name:	3:<span font_desc='Ubuntu Mono 12'> 3 </span>
i3-wm.workspace.04.name:	4:<span font_desc='Ubuntu Mono 12'> 4 </span>
i3-wm.workspace.05.name:	5:<span font_desc='Ubuntu Mono 12'> 5 </span>
i3-wm.workspace.06.name:	6:<span font_desc='Ubuntu Mono 12'> 6 </span>
i3-wm.workspace.07.name:	7:<span font_desc='Ubuntu Mono 12'> 7 </span>
i3-wm.workspace.08.name:	8:<span font_desc='Ubuntu Mono 12'> 8 </span>
i3-wm.workspace.09.name:	9:<span font_desc='Ubuntu Mono 12'> 9 </span>
i3-wm.workspace.10.name:	10:<span font_desc='Ubuntu Mono 12'> 10 </span>
i3-wm.workspace.11.name:	11:<span font_desc='Ubuntu Mono 12'> 11 </span>
i3-wm.workspace.12.name:	12:<span font_desc='Ubuntu Mono 12'> 12 </span>
i3-wm.workspace.13.name:	13:<span font_desc='Ubuntu Mono 12'> 13 </span>
i3-wm.workspace.14.name:	14:<span font_desc='Ubuntu Mono 12'> 14 </span>
i3-wm.workspace.15.name:	15:<span font_desc='Ubuntu Mono 12'> 15 </span>
i3-wm.workspace.16.name:	16:<span font_desc='Ubuntu Mono 12'> 16 </span>
i3-wm.workspace.17.name:	17:<span font_desc='Ubuntu Mono 12'> 17 </span>
i3-wm.workspace.18.name:	18:<span font_desc='Ubuntu Mono 12'> 18 </span>
i3-wm.workspace.19.name:	19:<span font_desc='Ubuntu Mono 12'> 19 </span>
i3xrocks.value.font:	UbuntuMono Nerd Font Mono 12
rofi.font:	Ubuntu Mono 16
```

</details>

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.5
 - PPA url: default: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Additional context**

None.

**Comment by moritzheiber** [comment]
The indicator for me here is that the terminal doesn't seem to find a shell to execute and you're using `zsh` instead of `bash` (which, I think, is the default for VSCode). I cannot reproduce your issue, _but_ I'm also using `bash` and _not_ zsh.

You wouldn't be able to try this with an account that has `bash` set as its default shell, would you?

**Comment by moritzheiber** [comment]
You could also try playing around with these VSCode settings for the terminal: https://code.visualstudio.com/docs/editor/integrated-terminal

**Comment by spencerwooo** [comment]
I actually wanted to use `code --log trace` to see the actual logs when I launch VS Code's integrated terminal (as suggested here: [Troubleshoot Terminal launch failures](https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch)), but I didn't find a way to pass arguments to the app launcher when launching VS Code. Any suggestions on how I can edit the actual commands when the app launcher launches VS Code?

**Comment by spencerwooo** [comment]
Ok I can't seem to reproduce the problem after rebooting, logging in and out, and/or restarting regolith session. I'm going to close this for the time being.

**Comment by malalejandra** [comment]
In case anyone still has this issue: ticking "Terminal › Integrated: Inherit Env" in VSCode settings worked for me!
