### ISSUE TITLE
Indicator for horizontal/vertical/tabbed/stacked

### ISSUE THREAD

**Issue by ThSGM** [regolith-linux/regolith-desktop#529]
Like (apparently) many people, I would really appreciate indicators for the current window's orientation. Apparently these were suggested in [this i3 development thread](https://github.com/i3/i3/issues/1067) and if I understand the stream of comments correctly, some people had managed to propose some patches. 

![7ae2f284-92f1-11e6-95aa-3788a16d0b85](https://user-images.githubusercontent.com/3396578/103248519-d0954c00-4962-11eb-99f7-24ed2053f900.png)

I'm wondering if anybody can decipher what was the end result from that thread and if that proposed patch could be implemented within the regolith-desktop branch as well.

**Comment by kgilmer** [comment]
Hi @ThSGM this is actually already in effect in Regolith, however it's easy to miss.  Take a look at the screenshot.  I've removed gaps for effect but you can see that the selected terminal window is in `horizontal` mode.

![image](https://user-images.githubusercontent.com/49683/103255765-75059700-493f-11eb-938d-3640a04c1501.png)

You may want to increase the window border thickness to make it more apparent.  This can be achieved with [Xresource overrides](https://regolith-linux.org/docs/howto/override-xres/) and I believe the property you are looking for is `i3-wm.window.border.size`.  Here's an example:

```bash
~$ echo "i3-wm.window.border.size: 10" >> ~/.config/regolith/Xresources 
~$ regolith-look refresh
> Updating already existing 'Regolith' profile
[SUCCESS] Reinstalled Regolith GNOME Terminal version 0.1.0 for the 'Regolith' profile!
```

![image](https://user-images.githubusercontent.com/49683/103255904-fb21dd80-493f-11eb-9000-c4dcc7d465b4.png)

**Comment by ThSGM** [comment]
Hi, great, thank you. 

Just for others looking, the colour for the indicator is via

`i3-wm.client.focused.color.indicator:#f92672`

set within the Xresources file. 

@kgilmer do you know if there is a way to get some sort of indicator for tabbed settings? I guess the simple answer might be 'no'. At the moment, it is with the indicator colour 'off' which will do. Not as pretty though.
