### ISSUE TITLE
Regolith display management crashes

### ISSUE THREAD

**Issue by arroadie** [regolith-linux/regolith-desktop#53]
This is a fresh install with some files restored from backup
This doesn't happen on the regular Ubuntu / gnome session

```
➜  ~ gnome-control-center
(gnome-control-center:2945): display-cc-panel-WARNING **: 08:05:10.287: no sunset data, using 16.00
(gnome-control-center:2945): display-cc-panel-WARNING **: 08:05:10.288: no sunrise data, using 8.00
(gnome-control-center:2945): GLib-GObject-CRITICAL **: 08:05:10.301: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
[1]    2945 segmentation fault (core dumped)  gnome-control-center
➜  ~ uname -a
Linux grpndev 5.0.0-19-generic #20-Ubuntu SMP Wed Jun 19 17:04:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by arroadie** [comment]
let me know what more I can provide

**Comment by kgilmer** [comment]
Fresh install means that you installed via the LiveCD?  Version 1.1?  I will have to look into the crash in more detail.  It's really odd that ubuntu-session would not crash but regolith-session does.

**Comment by arroadie** [comment]
Fresh install from a live CD, yeah. Using version 1.1 (with disco)
Apparently it was something on ubuntu's side, since yesterday by the end of the day I made an update and it fixed the issue...
If it's relevant, I used the minimal installation
Unfortunately I can't provide more information since it's not happening anymore.

**Comment by kgilmer** [comment]
Ok good to know @arroadie .  I'll close the issue for now.  If I find in testing that I can reproduce the issue with the minimal install selection I'll reopen.
