### ISSUE TITLE
High CPU usage when disconnected from any network

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#532]
I was surprised to discover that my laptop was heating as soon as I was disconnecting it from the network. I investigated and can confirm that, as soon as I disable the wifi with NM, Xorg and i3bar processes start to eat bteween 40% and 50% of the CPU. (30% for Xorg, 15% for i3bar).

This is completely reproducable and without any software launched other than a terminal. I enable wifi : CPU usage drops. I disable it, CPU usage start to rise. This is immediate.

**Comment by kgilmer** [comment]
I am experiencing something similar when my cisco VPN connection is active on my work machine.  My theory that the net-traffic script is erroring out and the change from a static interval to `repeat` is causing a tight infinite loop, consuming CPU cycles.  

```
kggilmer@u88a1ad37470a5a:~$ /usr/share/i3xrocks/net-traffic 
cat: /sys/class/net/unspec/statistics/rx_bytes: No such file or directory
kggilmer@u88a1ad37470a5a:~$ ping yahoo.com
PING yahoo.com (98.137.11.163) 56(84) bytes of data.
64 bytes from media-router-fp74.prod.media.vip.gq1.yahoo.com (98.137.11.163): icmp_seq=1 ttl=40 time=42.1 ms
^C
--- yahoo.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 42.169/42.169/42.169/0.000 ms
kggilmer@u88a1ad37470a5a:~$ ls /sys/class/net/
cscotun0/  enp0s31f6/ lo/        wlp5s0/    
kggilmer@u88a1ad37470a5a:~$ less /usr/share/i3xrocks/net-traffic 
kggilmer@u88a1ad37470a5a:~$ ip route show default | awk 'NR==1 { print $5 }'
unspec
kggilmer@u88a1ad37470a5a:~$ ip route show default 
default dev cscotun0 proto unspec scope link 
default via 192.168.1.1 dev enp0s31f6 proto dhcp metric 100​
```

**Comment by kgilmer** [comment]
One strategy that comes to mind is to trap any error condition within the `net-traffic` script and sleep some interval before returning.  Maybe there is something better...

**Comment by kgilmer** [comment]
@ploum can you run `/usr/share/i3xrocks/net-traffic` from a terminal when your machine is in the bad state and post what the script returns?

**Comment by kgilmer** [comment]
Generally speaking, unless there is a way to reliably capture all error paths in the `net-traffic` script, this bug cannot be conclusively fixed without changing the interval type back to a fixed constant.

Perhaps related: https://github.com/vivien/i3blocks/issues/160

**Comment by ploum** [comment]
Hi ken, it doesn’t return anything. :-(

(btw, I found this bug from my brand new X1 carbon. I joined the crew thanks to your tips ;-) )

**Comment by kgilmer** [comment]
I believe @ploum and my situation is slightly different.  In my case a network device is found but doesn't provide the expected path.  In the disable wifi case it's simply that the script is returning because no network device is found which causes the i3blocks to then immediately re-call the script.

The following change to `/usr/share/net-traffic` fixes the 'disable wifi' issue for me.  Am not on work machine to verify the other case but would expect it to also be fixed.

```diff
diff --git a/scripts/net-traffic b/scripts/net-traffic
index f905d22..ee597b6 100755
--- a/scripts/net-traffic
+++ b/scripts/net-traffic
@@ -2,6 +2,7 @@
 
 set -Eeu -o pipefail
 
+set -x
 # Note: net-traffic uses interval type 'repeat' so cannot use button events.
 # See https://github.com/vivien/i3blocks#interval
 
@@ -16,10 +17,14 @@ NUMFMT="numfmt --to iec --format %f --padding 5"
 
 # determine the net interface name
 IF="${BLOCK_INSTANCE:-$(ip route show default | awk '!/(ppp|tun|tap)/ { print $5 }')}"
-[ "$IF" = "" ] && exit
 
 IF_PATH="/sys/class/net/${IF}"
 
+if [[ "$IF" == "" || ! -d "$IF_PATH" ]]; then 
+  sleep 10
+  exit 1
+fi
+
 if [ -d "${IF_PATH}/wireless" ]; then
   NIC=${label_icon:-$(xrescat i3xrocks.label.wifi )}
 else
```

**Comment by kgilmer** [comment]
Welcome to the X1 club @ploum !  

Yes in your case makes sense it doesn't return anything.  I'll prep a PR.

**Comment by ploum** [comment]
I confirm that your patch fixes the issue. Awesome. Reverting it to wait for a proper package update

**Comment by kgilmer** [comment]
PR open for review.  Proposed solution building into `unstable` now.

**Comment by kgilmer** [comment]
Verified that fix addresses my VPN issue as well.  Fix has been promoted to `stable`.
