### ISSUE TITLE
i3xrocks-net-traffic is missing dependancy to bc

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#533]
Installing i3xrocks-net-traffic doesn’t display anything. After investigating a bit, I found out that the package "bc" must be installed for the applet to work.

Simple fix : add dependancy to bc for i3xrocks-net-traffic package.

**Comment by moritzheiber** [comment]
`bc` is a core dependency of pretty much all of the standard Ubuntu packaging. Did you uninstall `bc` forcefully?

**Comment by ploum** [comment]
No. Installed a fresh Regolith on a new laptop. Upgraded to 1.5. That’s pretty much everything. Of course, I had to install a few packages (including Firefox which was surprisingly not there).

Anyway, I feel it should explicitely be part of net-traffic as net-traffic will not work without it (but my whole system is working fine)
