### ISSUE TITLE
High CPU usage after removing `i3xrocks-net-traffic`

### ISSUE THREAD

**Issue by ajpen** [regolith-linux/regolith-desktop#535]
- [ x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
`i3bar`, `journald` and `xorg` always have high ( ~95%) CPU usage upon boot. I checked journald and the follow message repeats almost 500 times in a second:
```
Jan 16 10:08:25 anfernee regolith.desktop[2350]: <3>[net-traffic] Command '/usr/share/i3xrocks/$BLOCK_NAME' not found or missing dependency
Jan 16 10:08:25 anfernee regolith.desktop[1386520]: /bin/sh: 1: /usr/share/i3xrocks/net-traffic: not found

```

**To Reproduce**
1. Install Ubuntu 20.10 Gnome
2. Install regolith desktop.
3. Login to regolith desktop
4. run `sudo apt remove i3xrocks-net-traffic`
5. run `regolith-look-refresh`
6. If it doesn't happen immediately, log out and log in.

**Expected behavior**
Some heavily applications (like google chrome) will become very laggy. `htop` will show on avarge 90% CPU usage for `i3bar` and `xorg`, and around 20-50% or higher CPU usage for `journald`. 

**Screenshots**
CPU Usage:
![Screenshot from 2021-01-18 11-06-48](https://user-images.githubusercontent.com/4834786/104940631-03d66400-5980-11eb-8bb9-476fc8512ace.png)

Journald messages:
![Screenshot from 2021-01-18 11-05-54](https://user-images.githubusercontent.com/4834786/104940650-0c2e9f00-5980-11eb-8ab9-f0c1ff438b68.png)

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [2.106-1groovy]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 20.10]

**Comment by ajpen** [comment]
It might be related to #532

**Comment by moritzheiber** [comment]
Please make sure to `purge` the package, since otherwise the configuration files in `/etc` are left behind. Also, should you have staged your configuration files, please make sure to remove the relevant parts for `net-traffic`.

```console
$ apt install --reinstall i3xrocks-net-traffic
$ apt purge i3xrocks-net-traffic
```

The effect you're describing should no longer be the case afterwards.

**Comment by moritzheiber** [comment]
(Also, #532 is unrelated)

**Comment by ajpen** [comment]
I end up removing the net-traffic config in `/etc/regolith/i3xrocks/conf.d/` and logging out. That fixed it. You're right; It was config related.

Maybe add a note to the documentation about how to remove status indicators? Somewhere around [here I guess?](https://regolith-linux.org/docs/howto/add-remove-blocklets/) I didn't see a guide and thought a simple `apt get remove` would suffice.

**Comment by kgilmer** [comment]
@ajpen FYI: https://github.com/regolith-linux/website/pull/70  Feel free to comment if you have better suggestions for removal docs.

**Comment by moritzheiber** [comment]
Merged!

**Comment by ajpen** [comment]
> @ajpen FYI: [regolith-linux/website#70](https://github.com/regolith-linux/website/pull/70) Feel free to comment if you have better suggestions for removal docs.

Looks good to me! Thanks!

**Comment by newptcai** [comment]
> I end up removing the net-traffic config in `/etc/regolith/i3xrocks/conf.d/` and logging out. That fixed it. You're right; It was config related.
> 
> Maybe add a note to the documentation about how to remove status indicators? Somewhere around [here I guess?](https://regolith-linux.org/docs/howto/add-remove-blocklets/) I didn't see a guide and thought a simple `apt get remove` would suffice.

This really solves my high CPU problem. I almost gave up regloith because this! Thanks.
