### ISSUE TITLE
Shifting an application to Desktop 8 doesn't work

### ISSUE THREAD

**Issue by MaestroGlanz** [regolith-linux/regolith-desktop#536]
I can access Desktop 8 by super+8. But shifting a application to it by super+alt+8 doesn't work. Any other number works.

Just tested: super+alt+0 => desktop 10 doesn't work either.

**Comment by kgilmer** [comment]
Hi @MaestroGlanz , this definitely works so I'm guessing you may have another global keybinding assigned.  You can check https://regolith-linux.org/docs/getting-started/configuration/#keybindings for some details on checking if it's GNOME, but it could be some other program running on your system as well.
