### ISSUE TITLE
Dark gray background not suitable for some applications

### ISSUE THREAD

**Issue by MaestroGlanz** [regolith-linux/regolith-desktop#537]
Inkscape is almost not usable with the dark window setup. 

There should be a bright mode, which is bound to the containing shell.
i.e. super+shift+L changes the shell to bright mode. Any application started from that shell will be in bright mode.

You can also bind it to the window.

**Comment by kgilmer** [comment]
You can try another Regolith Look (which typically contain bundled GTK themes): https://regolith-linux.org/docs/developer/looks/

But also I think there are issues with Snap-based applications.  I'm not sure if your running Inkscape from a snap but you may have better luck w a deb install version, or perhaps there is a way to let the snap package use your system GTK theme.  As-is, there is no fix we can make to Regolith to address this.
