### ISSUE TITLE
[Discussion] Zutty as a terminal?

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#541]
This ticket is there only as a source of discussion. It can be closed at any time.

I remember that, years ago, the terminal of choice for Regolith was a quite controversial. Bugs, speed, integration. Some other controversial stuff had happened too (I’ve read that the Suckless team has been criticized for using some nazi iconography. I don’t know the whole story but the fact is that some people are uncomfortable using SL tools such as ST terminal).

I don’t know if the debate has been definitely settled by I came across Zutty, which looks quite interesting.

https://tomscii.sig7.se/zutty/

The comparison with other terminals is a must-read.

https://tomscii.sig7.se/2020/12/A-totally-biased-comparison-of-Zutty

**Comment by moritzheiber** [comment]
While I'm not opposed to discussing alternatives to GNOME Terminal, I'm fairly certain due to the [limitations mentioned on the Zutty website](https://tomscii.sig7.se/zutty/#Omissions%20and%20limitations) it won't become a default for Regolith, which has to support most of the features Zutty considers "optional" or obsolete (particularly, scroll back/buffer or right-to-left text).

**Comment by ploum** [comment]
I missed that very important point, you are right. Thanks for clarifying, I’m closing this.

**Comment by kgilmer** [comment]
Huh, interesting.  I had no idea of any of that grossness of the suckless project.  But, in fact it was in building and thinking about how "normal people" might use suckless tools like `st` was an early motivation for me to work on what became Regolith.  I think st was my first debian package.  The suckless website and docs have this unmistakable elitist vibe to them ("if you can't write C you're a worthless human being etc etc").  I wanted to counter that in some way.  I may not have done a very good job of it but my trying to be inclusive and "newb friendly" came as a direct result to my perception of the suckless project and what I think is wrong with it.

I don't get many complaints about `gnome-terminal` and I think despite a slightly slower boot up, it's a good fit for most users.  But, there's nothing saying we can't provide something for the super-minimalists out there at some point in the future.  Good to know about zutty, thanks for the info!
