### ISSUE TITLE
Close rofication window after deleting the last notification

### ISSUE THREAD

**Issue by csala** [regolith-linux/regolith-desktop#543]
- [x] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Is your feature request related to a problem? Please describe.**

When clearing all the notifications from rofication the window stays open at the end, empty, until the user exits it pressing Esc or clicking outside of the window.

**Describe the solution you'd like**

I think the workflow would be more efficient if the window closed itself automatically when there are no notifications left.

Notice that the window should be able to be opened anyway if there are no notifications at all in order to avoid a seemingly unresponsive software scenario in which the window closed itself when opening it with no notifications.

**Additional context**

I just created this PR which implements the proposed solution: https://github.com/regolith-linux/regolith-rofication/pull/8

**Comment by moritzheiber** [comment]
@kgilmer I think this one's for you

**Comment by kgilmer** [comment]
PR has been merged, closing.
