### ISSUE TITLE
Macro keyboard touch toggle the helper menu

### ISSUE THREAD

**Issue by Pierre-Monier** [regolith-linux/regolith-desktop#545]
**Describe the bug**
I have fancy keyboard with macro keys. When I tap one of this macro keys, it trigger the registered macro combination, but it also trigger `shift + super + ?` and open the helper menu. If the helper menu is already open, tapping a macro touch close it

**To Reproduce**
Register a macro on macro key and trigger this macro

**Expected behavior**
When we tap a macro touch it should only exec the registered macro, no the registered macro + `shift + super + ?`

**Screenshots**
on this [video](https://youtu.be/QHfHSr10aBk) I registerd a macro combintation which is `alt + s`, this shortcut open android studio. We can see that it open android studio and also the helper menu.

**Installation Details**
 - Regolith Install Type: [ISO]
 - Regolith Version: [1.4.1]

**Additional context**
My keyboard is the Corsair k55

**Comment by kgilmer** [comment]
I am not sure how your keyboard could be conflicting with Regolith specifically, but you can resolve this issue by setting the helper menu to a different keybinding.  You can add an Xresource override for `i3-wm.binding.help` ..for example to `Shift+>` or disable it altogether by setting Xresource override `i3-wm.program.help`.
