### ISSUE TITLE
System Journal Spamed by regolith desktop

### ISSUE THREAD

**Issue by nachovizzo** [regolith-linux/regolith-desktop#546]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
The system journal gets full of msg coming from regolith, which doesn't appear to be a problem but it makes a search through the journal impossible, in addition, the size of the journal gets big really quickly.

**To Reproduce**
`journalctrl -r`

**Expected behavior**
Only see important msgs

**Screenshots**
![image](https://user-images.githubusercontent.com/21349875/106922387-5009fe00-670d-11eb-8187-842efd99e9f8.png)

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files that might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Comment by cjohnston1158** [comment]
I believe this is a duplicate of #538

**Comment by nachovizzo** [comment]
Yes it is, after I've commented out the `set -x` the msgs disappeared.

Sorry I couldn't find this eariler
