### ISSUE TITLE
syslog full of  /usr/share/i3xrocks/next-workspace-widget: not found

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#550]
/var/log/syslog is full of /usr/share/i3xrocks/next-workspace-widget: not found

It seems to happen for each i3xrocks *not* installed. I had the error for CPU-usage and memory. Installing the widgets solved the issue. So it seems that something is not handling well that i3xrocks widget are installed then removed.

**Comment by moritzheiber** [comment]
Unfortunately, uninstalling blocklets needs to happen using either `apt purge` or the `--purge` parameter for `apt remove`, otherwise there are configuration files left behind in `/etc`. If you re-install these blocklets and then use `apt remove --purge <blocklet>` this issue will be gone.

**Comment by ploum** [comment]
It makes sense but this does not solve my issues. I did like you said and checked that the files are not in /etc/regolith/i3xrocks/conf.d/

I still have the error in the logs.

**Comment by moritzheiber** [comment]
Do you maybe have staged configurations for i3xrocks?

**Comment by ploum** [comment]
Nope. At least, I never created one and cannot find one in my .config  (.config/regolith only has the "flags" folder)

**Comment by kgilmer** [comment]
The root of the error messages comes from when i3 invokes i3xrocks.  So first, let's see what you get for `i3-msg -t get_config | grep status_command`.  For me, I see `i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d`.  

For me, I don't have any customization, so the user directory does not exist, meaning all of my config partials live in `/etc/regolith/i3xrocks/conf.d`.  From me, looks like:

```bash
ls /etc/regolith/i3xrocks/conf.d/
01_setup                10_next-workspace   20_key-indicator  30_bluetooth     30_net-traffic  40_cpu-usage  40_openvpn  50_disk-capacity  80_battery     80_todo    90_time
10_focused-window-name  20_keyboard-layout  20_weather        30_media-player  30_wifi         40_nm-vpn     40_temp     50_memory         80_rofication  80_volume
```

Depending on what you see, one of the files here references `next-workspace-widget`.  You can find out like this:

```bash
$ find /etc/regolith/i3xrocks/conf.d/ | xargs grep -HsF next-workspace-widget
/etc/regolith/i3xrocks/conf.d/10_next-workspace:[next-workspace-widget]
```

So, if I delete `/etc/regolith/i3xrocks/conf.d/10_next-workspace` and restart i3, the syslog spam would go away (if I was experiencing the same issue).

**Comment by ploum** [comment]
Ok, the important point I completely overlooked is "restart i3". As I never restart my laptop, I never restarted i3. Sorry for the noise.
