### ISSUE TITLE
No Alternative Boot Options After Regolith Installation

### ISSUE THREAD

**Issue by marauder316** [regolith-linux/regolith-desktop#552]
- [ ] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ ] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

Since I installed Regolith a few weeks ago, I haven't been able to boot into Linux Mint, still installed on my laptop, a ~2012 Macbook Pro. When I used multiple other distros, Grub worked fine and showed me the multiple OSes installed on the HDD, but now, there's no options; it just boots straight into Regolith.

**To Reproduce**

Restart/shut down and turn laptop back on.

**Expected behavior**

After installation, I expected Regolith to show Grub boot options like every other time before installation.

**Screenshots**

I'm sorry, screenshots are unavailable.

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

I've installed  various apps and whatnot, but they were all done *after* installation. They thus have no effect on the problem.

**Installation Details**
 - Regolith Install Type: [ISO/PPA] **ISO after live-boot from USB**
 - Regolith Version: [e.g. 1.4] **1.5.3**
 - PPA url: [default: ppa:regolith-linux/release] **Default**
 - Host OS (for PPA): [e.g. Ubuntu 20.04] **20.04**

**Additional context**

**Comment by kgilmer** [comment]
Hi @marauder316 , hmm, that's odd.  The Regolith ISO installer is just a customized version of the regular Ubuntu installer and in my testing I have not seen this issue.  I guess the first question is if the other OS paritions still exist on your machine.  I'm unsure of your level of expertise and risk-taking so do not want to give you any specific instructions.  If the other OS partitions still exist on your drive, then you should be able to restore your grub menu with a boot repair utility.  If the the partitions are no longer on your machine than i'm guessing that the drive was repartitioned when you installed Regolith and in that case I believe they are lost.

LMK if you'd like particular instructions on further troubleshooting.

**Comment by marauder316** [comment]
Yeah, my Mint install is still there, and I access some files from time to time.

With proper instructions I could probably get what I need working again.
