### ISSUE TITLE
Unmet dependencies while installing a Compton compositor

### ISSUE THREAD

**Issue by Panagiss** [regolith-linux/regolith-desktop#553]
I wanted to switch compositor (currently Picom), cause i see screen tearing on Chromium and a bit of broken textures on gitkraken(snap) but nothing serious. My biggest problem was screen tearing on Chromium. So i decided to change compositor. But this happened :
 
```
sudo apt install regolith-compositor-compton-glx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-compositor-compton-glx : Depends: compton but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.5.3
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by kgilmer** [comment]
Hmm, for some reason your system doesn't want to install `compton`.  What does it respond with after `sudo apt install compton`?

**Comment by Panagiss** [comment]
Downloaded and installed. So i don't know why it's fine with ```sudo apt install compton``` and not with ```sudo apt install regolith-compositor-compton-glx```.

Another thing a bit more offtopic is that with compton i got a lot more of screen tearing.... especially in chromium...

**Comment by Panagiss** [comment]
I have played with compositors a bit more and i found that when i installed xcompmgr with ```sudo apt install regolith-compositor-xcompmgr```, i saw that it was marked as installed if you see the photo here:
![image](https://user-images.githubusercontent.com/56695201/111124087-bf7ad500-8578-11eb-8930-846fb9a28557.png)

But when i installed again compton, i didn't see that. Maybe it has to do with the fact that i used ```sudo apt install compton``` and not ```sudo apt install regolith-compositor-compton-glx``` .... I don't know to be honest

**Comment by Panagiss** [comment]
I finally was able to install Compton using the ```sudo apt install regolith-compositor-compton-glx``` .  I don't know how but it worked.
Also a big thing to take in mind is that now i think i'm ** free of screen tearing**. At least for now.
![image](https://user-images.githubusercontent.com/56695201/111125188-04533b80-857a-11eb-91df-7c5b0a0f4633.png)

With ```sudo apt install compton``` i didn't see the _installed_ as shown in the photo. Now i see it.

So take in mind that **Picom has some serious screen tearing**, just like **Xcompmgr**. But **Compton** saved it for me.

Im using a GTX 1050 TI if that helps somehow

**Comment by kgilmer** [comment]
It's also possible to customize the configuration of each compositor.  See https://regolith-linux.org/docs/customize/compositors/#overriding-a-compositor-configuration  for details.  You may have more luck with a customized Picom configuration over Compton, as the former is an active project: https://github.com/yshui/picom

Closing as original issue is no longer present.
