### ISSUE TITLE
Neo keyboard layout and keybindings

### ISSUE THREAD

**Issue by aut0** [regolith-linux/regolith-desktop#554]
Hi,

First of all thanks for the great project. It's really nice. I have a small issue that I don't know how to resolve. I use the neo keyboard layout and it has a totally different mapping when compared to qwerty or qwertz. I come from i3 and I'm somewhat used to the keybindings. There the binding is to the key on the keyboard and not to the entered symbol, e.g. Super + the button that is labeled Q on the keyboard. In neo the button labeled Q produces an X, when pressed. So I want to bind to the keycode and not the keysym if that makes sense. Especially for the vim-like bindings I think it makes sense. Now, when I use neo layout in Ubuntu with regolith it will bind to the keysym, meaning that e.g. I have to press Super+Shift+P to produce Super+Shift+Q.

Is there a way to change that or do I have to remap every single keybinding?

Thanks and BR,
Lukas

**Comment by kgilmer** [comment]
Hi Lukas, hmm, this is a new one to me.  Well, the i3 config file can use simple variables in many places, in fact Regolith can load most keybindings from Xresources.  If you can figure out how to represent the keycode in a variable then you may be able to simply specify the overrides.  But if not, Regolith is using "stock" i3-gaps.  So, you can still make it work, but you'll have to do more manual merging and editing of the i3 file when Regolith upgrades occur.

HTH,
ken

**Comment by aut0** [comment]
It would be great if regolith woulld have an i3 configuration file alternative in /etc/regolith/i3/ that uses bindcode instead of bindsym. Is that available somewhere or would you be willing to merge it, if I made it?

**Comment by kgilmer** [comment]
Hi @aut0 I cannot promise it but if it looks generally useful for Regolith users at the very least I can package it in an alternative i3 config file.  Users could install it as an optional add-on.  If there is a better integration strategy that doesn't cause risk or regression to existing users I would do that too.
