### ISSUE TITLE
Regolith disappeared after restart and possibly after "apt autoremove"

### ISSUE THREAD

**Issue by Panagiss** [regolith-linux/regolith-desktop#555]
I used Regolith on top of Ubuntu for a month now with good experience. 
After some time i tried to spawn a new workspace and i didn't see it. Then i tried to spawn the help guide with win + shift + ? but it wouldn't spawn either. 
So i tried to find the keybinding to restart. I pressed win + shift + r and i saw my background change to the default one.

So later i turned it of with win + shift  + p. When i turned it back on i logged in and i went straight to my Ubuntu X11 setup. I was surprised. I logged out and went to the settings icon and Regolith had been disappeared !!

Don't know why. I'm going to try to reinstall it i guess...

Update:  I reinstalled Regolith using ```sudo apt install regolith-desktop-standard``` and it actually downloaded lot's of data. 
So that means that somehow there where deleted.... and later i remembered that i actually run ```sudo apt update ``` and ``` sudo apt autoremove```. So could ```autoremove``` command mess Regolith?

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4 (think so)
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by kgilmer** [comment]
Hi @Panagiss , I'm not sure what happened in your case.  Regarding `autoremove`, any packages that were installed as a transitive dependency will be removed if that original package has been uninstalled.  So if you had installed `regolith-desktop-standard` as a "side effect" of another package, and then uninstalled that other package, then this could explain the behavior.

Also, Ubuntu itself may uninstall packages from PPAs during upgrades.  The good news is that even if the packages are uninstalled (vs purged), the configuration files in `/etc` and your user directory are preserved so it should just be a simple matte of reinstalling the desktop package, which you did.  You may want to look in `/var/log/apt` if you want to see if there is evidence for how the situation happened.

**Comment by Panagiss** [comment]
I found these logs after i run ```autoremove``` :

> Start-Date: 2021-03-21  20:06:13
> Commandline: apt autoremove
> Requested-By: pss (1000)
> Remove: fonts-jetbrains-mono:amd64 (1.0.1-1regolith1), i3-snapshot:amd64 (1.0-1ubuntu1~ppa1), ayu-theme:amd64 (0.2.0-1ubuntu1~ppa1), regolith-ftue:amd64 (1.1.0-1), regolith-unclutter-xfixes:amd64 (1.5-2), regolith-default-settings:amd64 (1.0.3-1focal), i3xrocks-next-workspace:amd64 (3.5.7-1), libjsonrpc-glib-1.0-1:amd64 (3.34.0-1), regolith-i3-gaps-config:amd64 (2.8.4-1), regolith-gnome-flashback:amd64 (2.6.2-1), i3-next-workspace:amd64 (1.0.1-1), remontoire:amd64 (1.4.1-1), regolith-rofi-config:amd64 (1.3.1-1), rofi:amd64 (1.5.4-1), libxdo3:amd64 (1:3.20160805.1-4), xdotool:amd64 (1:3.20160805.1-4), libxcb-ewmh2:amd64 (0.4.1-1.1), regolith-look-lascaille:amd64 (2.6.16-1), python3-i3ipc:amd64 (2.1.1-1ubuntu1~ppa7), fonts-materialdesignicons-webfont:amd64 (1.6.50-3regolith3)
> End-Date: 2021-03-21  20:06:27

Don't know if it was a problem in my end or an unintended behavior, but these are the logs.

**Comment by abacao** [comment]
Happened the same to me

**Comment by kgilmer** [comment]
Thanks for the logs @Panagiss .  As you can see, `regolith-desktop[*]` is not in that list.  That is the "root dependency" from which everything else is bound.  If `regolith-desktop` is uninstalled, then the package manager will assume all dependencies that were installed along with it can also be removed.  Can you find another log entry in which `regolith-desktop` was removed?
