### ISSUE TITLE
i3xrocks.date.format Xresource won't change the time&date on bar

### ISSUE THREAD

**Issue by Panagiss** [regolith-linux/regolith-desktop#556]
I have made a ``` ~/.config/regolith/Xresources``` file to change some default Xresources configs. But changing the Time and Date format, won't change it on the bar at all.

My Date and Time format on the bar looks like this :
![image](https://user-images.githubusercontent.com/56695201/112023018-84aa0b80-8b3b-11eb-9f23-4cdd2bf8899a.png)

So i wanted to change that format and what i did was : ```echo "i3xrocks.date.format: + %d-%m-%YYYY %I:%M %p" >> ~/.config/regolith/Xresources``` and after i refreshed the session with ```regolith-look refresh``` but the format it's still the same!

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.5.3
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by moritzheiber** [comment]
The correct key is [`i3xrocks.date.format2`](https://regolith-linux.org/docs/howtos/time-format/) (at the bottom of the page).

Example:
```
i3xrocks.date.format2: %F %R%:z
```
