### ISSUE TITLE
No border for many applications

### ISSUE THREAD

**Issue by nik123** [regolith-linux/regolith-desktop#558]
Many applications do not have border when focused. The example of the problem you may see in [this reddit post](https://www.reddit.com/r/regolithlinux/comments/mbr4yc/no_border_for_gtk_applications/) (I'm not in any way related to it's author BTW). It seems the problem is relevant for default gnome applications (Calendar, Files, etc).

**Comment by kgilmer** [comment]
Hi @nik123 , I played around with it a little and couldn't find a solution that does not also render window title bars.  Have a look at this post: https://www.reddit.com/r/i3wm/comments/768yg5/no_border_on_some_apps/

You can limit the effect to specific windows w/ the class specifier.  The i3 user guide has details.

As far as I can tell, this is an issue of gtk apps and the i3 window manager.  I'm not aware of anything that I can do to fix this generally, but if something pops up I will update this ticket.

**Comment by 3mkay** [comment]
This class seems to work without showing window bars

`for_window [class=.*] border pixel 1`

Obviously, it's very greedy but shows it can be done.

**Comment by JustSaX** [comment]
> for_window [class=.*] border pixel 1

In which config file should this line be added? I tried to add it to `~/.config/regolith/Xresources` but it didn't work.

**Comment by ferdinandyb** [comment]
That's an i3 command, you need to put it in your i3 config.

**Comment by JustSaX** [comment]
Now it works. Thx!
