### ISSUE TITLE
Graphical glitches on few Snap apps

### ISSUE THREAD

**Issue by Panagiss** [regolith-linux/regolith-desktop#559]
I find that few apps like VS code, Chromium browser or Firefox appear to show some broken artifacts and have few graphical issues. There are not unusable but sometimes it's annoying and it's specifically with Regolith. If i switch back to normal Ubuntu gui, it's not an issue. 
Here is a small example on Firefox:
![Screenshot from 2021-03-29 16-31-21](https://user-images.githubusercontent.com/56695201/112845280-5d0ff180-90ad-11eb-83ff-bc0ea815a2de.png)

There are a few gui glitches on this photo but there can be a lot more especially on VS code.
Also im not sure if this has anything to do with SNAP. Because all these are app installed from Snap Store!

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.5.3
 - PPA url:  ppa:regolith-linux/release
 - Host OS (for PPA):  Ubuntu 20.04.1

**Comment by Panagiss** [comment]
Few more photo samples of gui glitches:
![Screenshot from 2021-03-30 21-57-02](https://user-images.githubusercontent.com/56695201/114989619-44bb1780-9ea0-11eb-8ee6-b32e915a0d7a.png)
![Screenshot from 2021-03-30 21-57-20](https://user-images.githubusercontent.com/56695201/114989635-497fcb80-9ea0-11eb-9960-60b7ce558dd1.png)

**Comment by kgilmer** [comment]
Odd, can you tell me which regolith-look you are using (specifically gtk theme) and compositor (`apt list --installed | grep compositor`).  Generally when users report issues like this it is due to some issue with their graphics driver and the compositor they are using.  You can see if the problem is related to the compositor by disabling (`apt install regolith-compositor-none`) or killing it.

**Comment by Panagiss** [comment]
I'm using _regolith-look-nord/focal,now 2.6.16-1 amd64 [installed] - Regolith R1.2 look_ and _regolith-compositor-picom-glx/focal,now 1.1.3-1 amd64 [installed]_

**Comment by kgilmer** [comment]
any update @Panagiss ?

**Comment by Panagiss** [comment]
These graphical glitches are gone with no compositor! The trade off is that that i have a big screen tearing line in the middle when playing video or swiping the browser image too fast.

**Comment by kgilmer** [comment]
@Panagiss have a look at the [picom compositor site](https://github.com/yshui/picom).  I think there is a good chance you can come up with a configuration that works with your system.  Depending on your hardware/driver setup, it's sometimes also possible to fix the screen tearing at the video driver level but varies.
