### ISSUE TITLE
Installing from PPA on linux mint 19.1 cinnamon

### ISSUE THREAD

**Issue by plagasul** [regolith-linux/regolith-desktop#56]
I tried to install Regolith from PPA on a Linux Mint 19.1 Cinnamon.

It works, but not 100%.

- Most noticeable problem is that there is a visible horizontal line 1/3 screen up from the bottom, and windows stop there, not stretching further, see images:

![image](https://user-images.githubusercontent.com/13966673/60395253-1fc1ad00-9b31-11e9-83c5-f4bf3bfa6d7c.png)
![image](https://user-images.githubusercontent.com/13966673/60395292-b1311f00-9b31-11e9-8edd-22889641143e.png)

- The status bar does not seem to show CPU and BATT.

- SUPER+C does not show config
- SUPER+E does not seem to logout, although 'i3-msg exit' works on CLI

- Since mint uses lightdm, I guess, during installation it asks me if I want to use lightdm or gdm by default, I chose lightdm and that is what is running.

-  I assume there is not way to change autostart programs by session. I have a conky I'd like to disable when running Regolith which autostarts as .desktop file

I haven't noticed yet any other problems.
No problems under cinnamon neither.

I can post a list of running processes on startup if that helps

Thank you very much.

**Comment by kgilmer** [comment]
Hi @plagasul thanks for all of the details in your bug report.  Regolith fails in interesting ways!  When I tested on Linux Mint I selected the gdm3 session manager.  Are you able to try that?  

Regarding autostart, I am not aware of any facility that would allow that selective filtering.  Is there something in the `.desktop` file that defines it as something that should start by default?  If not perhaps switching to gdm3 would prevent it from starting.  I don't know anything about lightdm unfortunately.

**Comment by plagasul** [comment]
Hello @kgilmer 

I tried using gdm to login, with the same results.

I assume the bar may be caused by a running program, what do you think? 

I am not so experienced in Linux yet, I am a bit confused about differences between DE, WM, DM... so, unsure, about what is running when I boot on Regolith other than i3gaps as WM, and that could cause that strange line.

May I ask where are the shortcuts defined so I can look at what is CTRL+C / +E running and why is not working?

Any idea what could be causing the i3bar not showing cpu etc ?

Perhaps I would be better off building a regolith-like session bottom up by using the config files that I see you are starting to add to the repo ?

Thank you very much for Regolith!

**Comment by plagasul** [comment]
And another update. Ctrl+C did not work because Gnome control center was NOT installed. I assume because it is supposed to already be there by default in an ubuntu installation ?

Installing it makes Ctrl+C work well.

**Comment by kgilmer** [comment]
Hi @plagasul , thanks for trying gdm3, and glad you found the source of the bar issue.  Keybindings are documented here: https://regolith-linux.org/keybindings.html

The bar issues may be a configuration issue if you have some other version of i3blocks installed.  The Regolith version of `/etc/i3blocks.conf` should look like this:
```
# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=40
markup=pango
color=#586e75

# CPU usage
#
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[cpu_usage]
label= 
interval=5
min_width=100%
#separator=false

# Battery indicator
#
# The battery instance defaults to 0.
[battery]
label= 
interval=30

# Date Time
#
[time]
label=
command=echo "<span font_desc='Source Code Pro Medium 13' color='#93a1a1'>`date '+ %m-%d %H:%M '`</span>"
#command=date '+ %m-%d %H:%M '
interval=60
```

**Comment by plagasul** [comment]
I can confirm the bar issue is related to missing packages.

CPU depends on 'sysstat', installing it works.
BATT depends on acpi, and mint seems to use it internally, so no acpi cli command. I could modify the i3-blocks script 'battery' to use these commands instead:

```
cat /sys/class/power_supply/BAT?/capacity
cat /sys/class/power_supply/BAT?/status
```
I said SUPER+E does not work, but that was a mistake on my part, as the binding to exit is Super+Shift+E and that DOES work.

When I get everything working I will come back here, recap and close if that is ok.

Thanks again.

**Comment by plagasul** [comment]
Another related issue I encountered is with the software app, which would seem to be Mint's default app, and that does not respond to window close keybinding as other windows. The only way to close it is by killing the window with MOD+Shift+Q (I believe is the right keybinding).

Additionally there is a separate 'software sources' app, I assume that also mint's default,  that does not launch at all, although I have not looked at logs for the particular reason.

I assume regolith uses ubuntu's default software center which would seem to be unavailable in mint's repos. I do not know if there is a particular gui app in ubuntu for dealing with software sources.

I can't think for a workaround for this, other than using cli.

Thanks

**Comment by kgilmer** [comment]
Hi @plagasul , feel free to reopen this issue if you're still having troubles with Regolith on Linux Mint.  While it's not a supported environment, I'll do what I can to help fix problems.
