### ISSUE TITLE
Fresh install: Super+Space does not have any effect. In fact, all keybindings containing Space are broken.

### ISSUE THREAD

**Issue by jlemonde** [regolith-linux/regolith-desktop#561]
Hi! 

I've just freshly installed Regolith onto my (not fresh) Ubuntu 20.10 in order to try, but it turns out that I can't launch any app other than terminals and browsers since the Super+Space command does not work. In fact, all keybindings featuring a space seem to be broken, e.g. searching files with Super+Alt+Space does not work either.

I hope there is a quick fix.

**Comment by kgilmer** [comment]
Hello @jlemonde , I'm guessing there is something on your system that's consuming some keybindings before Regolith components would get to them.  You could verify this by booting into the liveCD environment and see if the problem continues.  In any case, this is not a bug of the system but if you find some specific issue we can address in code or documentation please re-open the ticket.  Also if the liveCD also has the problem I'd be interested to know that as well.

**Comment by msp-matt** [comment]
I am having the same issue. I installed Regolith 1.6 from the ppa on an existing installation of Linux Mint 20.3.

I unset the keyboard shortcut that Mint had assigned to Super+Space (something about cycling through grouped windows in the panel), but Super+Space still doesn't do anything for me.

I understand that this is likely not an issue with Regolith, but I'm wondering if anybody knows a general way that I could find out what is intercepting this keybinding. I've googled around a bit and not been able to sort this out, so any help would be much appreciated.

**Comment by kgilmer** [comment]
Hi @msp-matt , yeah we just don't have the time/people to test on other Ubuntu variants at this time.  Regarding your issue, did you happen to see this?

https://unix.stackexchange.com/a/261383/356932

**Comment by msp-matt** [comment]
@kgilmer Thanks for the pointer. I've tried that but it produces quite a lot of output and I'm still trying to understand what it all means. I was hoping that it was the xbindkeys process, but that appears not to be the case. Anyway, I will post back here if I ever figure it out. It would be nice to be able to get this working.

**Comment by msp-matt** [comment]
Just going to keep putting debugging info here in case this looks familiar to anybody, or maybe it will help somebody in the future. As suggested in the StackExchange link that @kgilmer posted above, I tried this:
```
xdotool keydown Super+space; xdotool key XF86LogGrabInfo; xdotool keyup Super+space
```
Then I examined the logging info that appeared in `/var/log/Xorg.0.log`. There was a lot of stuff there, most of which I suspect is irrelevant. There are quite a number of lines that look like
```
Printing all registered grabs of client pid <PID> <EXECUTABLE>
```
where no grabs are actually registered for that client; I assume those can be ignored.

But then there are 153 registered grabs for the process `gnome-flashback`, which all look like this:
```
[   128.874]   grab 0x40a0010b (core), type 'KeyPress' on window 0x770
[   128.874]     detail 28 (mask 0), modifiersDetail 30 (mask 0)
[   128.874]     device 'Virtual core keyboard' (3), modifierDevice 'Virtual core keyboard' (3)
[   128.874]     core event mask 0x3
[   128.874]     owner-events true, kb 0 ptr 1, confine 0x0, cursor 0x0
```
For those events, only the `detail` and `modifiersDetail` values change, and there's nothing that says "Activating key" as in the linked StackExchange post.

Then there's 524 registered grabs for the process
```
i3 -c /etc/regolith/i3/config
```
which all look similar to the one I copied above, and then 4 more registered grabs for the process
```
/usr/bin/python3 /usr/bin/x-terminal-emulator
```
None of the rest of the processes have any registered grabs.

**Comment by msp-matt** [comment]
I tried this out in the live image of Linux Mint 20.3:

- Booted live image from USB.
- Installed `regolith-desktop-standard` from the PPA.
- `Super+Space` commands still have no effect.
- The results of using `xdotool` as outlined above were more or less the same.

So it appears that it's not just my setup, it's something more fundamental in Linux Mint that's interfering with these commands.

I understand you all don't have the resources to test every Ubuntu derivative, so please don't interpret anything here as criticism. This looks like a really cool project and I'm just disappointed that I can't seem to get it working with Mint.

**Comment by msp-matt** [comment]
I figured it out! This is likely not the preferred way of fixing it, but at least it gets to the heart of where the problem is.

There is a keyboard shortcut to switch input sources that is set to `Super+Space` by default, and it seems fairly difficult to disable it. I tried disabling it in the Keyboard Shortcuts part of the settings app, but that didn't do the trick (even after logging out/restarting). What I had to do in order to disable it was this:

- Open dconf editor
- Navigate to `org -> gnome -> desktop -> input-sources -> xkb-options`
- Set custom value of `[]` for this setting
- Save settings
- I can't remember if I had to log out and back in for this to take effect
 
The setting initially had two strings in it. One looked like `win_space_<something>` and I don't recall the other. I guess I should have deleted just the first one and checked whether that solved the problem; I suppose somebody could check that in the live image, but I'm not that motivated to do so at the moment.

**Comment by msp-matt** [comment]
OK, I went back to the live image and tested it. The initial value of the setting was
```
['grp:win_space_toggle', 'terminate:ctrl_alt_backspace']
```
Just deleting the first one of these two strings stops the OS from intercepting  `Super+Space` shortcuts, so the app launcher works.

Interestingly, the default value for this setting is just `[]` (according to what it says in dconf editor). So it must be that this is a choice that Mint is making somewhere.
