### ISSUE TITLE
Super + T spawns terminal instead of toggling window layout mode

### ISSUE THREAD

**Issue by Panagiss** [regolith-linux/regolith-desktop#563]
super + T changes the window layout to horizontal, vertical or into tabs. It works but sometimes, i don't know why, it just changes behavior and it spawns a new terminal. And the only thing i can do to make it work properly is to restart my PC.

Everything else works fine. super + ENTER spawns terminal and everything is OK. It's weird because this problem may occur once in a week let's say. It's really random and im not sure what is causing it... could i just hit something and made super + T change behavior ? Don't know 

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.5.3
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA):  Ubuntu 20.04

**Comment by kgilmer** [comment]
Yes, it sounds like something is overriding the keybinding.  Perhaps gnome?  You can check this in settings:

![image](https://user-images.githubusercontent.com/49683/115495856-62c8a500-a21d-11eb-8de2-da2dd76e7907.png)

**Comment by Panagiss** [comment]
When it happens again i'm gonna check the keybindings of gnome

**Comment by marauder316** [comment]
I had the same issue, and it was a GNOME shortcut. I find disabling all of them except the Ctrl+Alt+T for the terminal helps.

**Comment by kgilmer** [comment]
I'll close this for now but kindly re-open if the gnome keybindings were not the issue.
