### ISSUE TITLE
i3 Problems with Simulink

### ISSUE THREAD

**Issue by ltcmdata** [regolith-linux/regolith-desktop#565]
When using MATLAB/Simulink: opening new Simulink windows in tabbed mode results in strange behaviour. See also this Reddit thread: https://www.reddit.com/r/i3wm/comments/cz00me/how_to_deal_with_programs_that_do_not_deal_with/
The window is neither tabbed nor floating. When actively set floating and after that to tabbed everything is normal. However this is very annoying when opening many windows at once.

**Comment by kgilmer** [comment]
Hmm, perhaps you can set a rule in your i3 config so that it always floats?

**Comment by kgilmer** [comment]
closing for lack of response
