### ISSUE TITLE
Take ALT as Standard Sub Key instead of WIN

### ISSUE THREAD

**Issue by davidh38** [regolith-linux/regolith-desktop#568]
I suggest to take alt key as standard super key:

My argument for using alt is that with using the win key, you will twist you thumb in a unhealthy way. Since regolith is for power users, this is my suggestion, though i am guessing there are reasons for taking alt key (e.g. key shortcuts in browsers and shell)

**Comment by kgilmer** [comment]
Hi @davidh38 thanks for your suggestion.  I see your point ~ the left-hand alt is closer to the thumb than the WIN key, however as you mention there are a lot of conflicts there.  I'll close this issue as I would not wish to make such a big change to users by default.  For those that feel the same though, please upvote this issue so we can get a sense of how popular this idea is.
