### ISSUE TITLE
Android Emulator does not appear correctly

### ISSUE THREAD

**Issue by sidvenu** [regolith-linux/regolith-desktop#569]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
When we try to open Android Emulator, the rest of the screen other than the mobile display goes black and the controls are blacked out as well.

**To Reproduce**
- Install Android SDK
- Open Android Emulator

**Expected behavior**
No black screen. The controls should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/18738527/115231328-0be6a100-a133-11eb-9121-c5fe39eb2abb.png)

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: [ISO/PPA] PPA
 - Regolith Version: [e.g. 1.4] 1.5.3
 - PPA url: tdefault: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Additional context**
-

**Comment by kgilmer** [comment]
Likely this app is doing something that breaks tiling windows.  What happens when you set the window to floating mode?  `<super> <shift> f`

**Comment by Baryczka** [comment]
Probably setting in i3 config like `for_window [class="name_of_window"] floating enable` would help, but I'm not sure if android emulator has any WM_CLASS. You can check it with `xprop` tool by click on desired window to check it properties

**Comment by kgilmer** [comment]
Closing due to no response from issue creator.  Kindly reopen if issue still present.
