### ISSUE TITLE
PPA for Ubuntu 21.04

### ISSUE THREAD

**Issue by Pietryszak** [regolith-linux/regolith-desktop#571]
**Describe the bug**

The repository 'http://ppa.launchpad.net/regolith-linux/release/ubuntu hirsute Release' does not have a Release file.

$ sudo add-apt-repository ppa:regolith-linux/release
$ sudo apt install regolith-desktop-standard

**To Reproduce**
Just add ppa to repostitory list in Ubuntu 21.04

**Expected behavior**
Add ppa

**Screenshots**
![Zrzut ekranu 2021-04-22 o 23 02 38](https://user-images.githubusercontent.com/45850093/115784797-e241aa00-a3be-11eb-9265-74b8dbf6250a.png)

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [1.5.3]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [Ubuntu 21.04]

**Comment by cheginit** [comment]
The `release` PPA of Regolith for Hirsute is still under development and not stable. You can give Regolith for Hirsute a try using the [unstable](http://ppa.launchpad.net/regolith-linux/unstable/ubuntu/dists/hirsute/) branch `sudo add-apt-repository ppa:regolith-linux/unstable`. **Just be aware that this is an unstable and experimental version**, so I do not recommend using it on your work machine. Use it at your own risk.

**Comment by kgilmer** [comment]
Thanks @cheginit but in addition to `unstable` having 21.04 packages, `stable` does as well.  We suggest you use `stable` release for production machines.
