### ISSUE TITLE
Regolith cannot recongize ASUS G14 Nvidia GTX 1650ti even after installing driver

### ISSUE THREAD

**Issue by al3rez** [regolith-linux/regolith-desktop#572]
I need to thank you guys for  your sweet distro.

**Describe the bug**
I installed Regolith along  with Windows 10 (Secure boot disabled, Fast boot disabled) and it works fine with `nodemodeset` added to grub. After I install different versions of nvidia-drivers I end up with a boot screen (Republic of Gamers) and no  errors and I need to  remove nvidia drivers and add nomodeset again  to launch.

**To Reproduce**
Simply having a Nvidia GTX 1650Ti GPU

**Expected behavior**
I expected after installing the `ubuntu-drivers autoinstall` everything should be fine.

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: latest
 - Host OS (for PPA):  latest

**Comment by kgilmer** [comment]
Hi @al3rez, does the Nvidia driver work in the default Ubuntu session?

**Comment by al3rez** [comment]
Resolved! https://www.reddit.com/r/ZephyrusG14/comments/id4e2d/asus_g14_ubuntu_2004_setup/
