### ISSUE TITLE
Allow setting of workspace layout mode via Xresources

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#573]
From slack, user request to be able to set `workspace_layout` to `stacked` by default.

**Comment by geekthought** [comment]
How? It doesnt seem to work if i set the mode to stacking or tabbed in the i3 config?

**Comment by kgilmer** [comment]
To test this feature you can set the Xresource key of `i3-wm.workspace.layout` to one of `default|stacking|tabbed`.  Then refresh Regolith or log back in.  New windows will be opened in the specified layout mode.  I had to use an unused workspace to see the changes without logging back in (FYI).

Example:

`~/.config/regolith/Xresources`:

```
i3-wm.workspace.layout: tabbed
```

**Comment by geekthought** [comment]
Solved. Thank you
