### ISSUE TITLE
Night light doesn't stay on

### ISSUE THREAD

**Issue by TopherIsSwell** [regolith-linux/regolith-desktop#58]
When I turn on Night Light in the settings, the screen adjusts the gamma to a warmer tint, and then every 1-10 seconds it switches to/from no tint (night light off) and back. There doesn't seem to be any rhyme or reason to the timing between switches, but it does seem to stay longer on the no-tint setting. I think something else is adjusting the screen gamma and fighting with night-light. I am running the regolith packages on Ubuntu (not the Regolith ISO). I'm operating out of the PPAs, and running the latest available (regolith-desktop 2.07-1ubuntu1).

To reproduce, press $mod+d and set night-light to on.

The night-light function worked fine on Ubuntu proper before the Regolith install. I'm using a system 76 Lemur laptop in case hardware matters.

**Comment by plagasul** [comment]
I experienced something similar to this. Since I installed from PPA over linux mint 19.1 cinnamon, which as far as i know comes with Redshift package by default, I thought that perhaps there were two versions of Redshift in place? If I look at installed software I have both 'Redshift' and 'Redshift-gtk' installed... are those supposed to work side to side or perhaps I am right and I've got a dup here?

May it be that this is your case aswell? 

Which would mean... does Regolith come with its own Redshift ?

Thank you

**Comment by kgilmer** [comment]
Hi @TopherIsSwell and @plagasul .  I have just tried your Steps to Reproduce @TopherIsSwell and have not experienced any switching.  It seems to work as expected for me.  @plagasul may be on to something here, as I do not have any redshift package installed:

```
$ apt list --installed | grep -i redshift
$
```

Can you check and if so see if uninstalling any redshift packages fixes your problem?

**Comment by plagasul** [comment]
Hmm... 

Ok so Regolith uses gnome control center. I am unsure how much gnome there is in the system, but  night light is supposed to be a built-in feature in Gnome, possibly part of gnome flashback ?

If that is the case and it looks like it, then I would say that most probably the built-in night light is battling redshift... and that would not really be a bug would it? (real question)

I will also test this asap.

Thanks.

**Comment by kgilmer** [comment]
Right, I'm not sure to be honest where that's coming from, wither it's implemented within gnome-flashback or rather that's enabling some other component.  Out of curiosity I grepped through the gnome-flashback code but didn't find any matches to Night so I'm guessing it's the latter.

**Comment by plagasul** [comment]
I can confirm that if Redshift is installed and running, and night shift is activated, they seem to 'fight' each other, at times. Killing redshift and redshift-gtk processes solves it. I am not experiencing any glitches if I do that.

**Comment by kgilmer** [comment]
Great, good to know.  Thanks for the follow-up @plagasul .  Based on your description I believe this issue is resolved.  Please re-open however if this is not the case.
