### ISSUE TITLE
Desktop flicker after fullscreen in fc2 fbneo 480p using wine

### ISSUE THREAD

**Issue by BoyfriendDaPopstar** [regolith-linux/regolith-desktop#581]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues) (i dont have slack)

**Describe the bug**
After exiting fullscreen in fbneo on fightcade2 using 480p, the desktop started flickering. I tried to recreate this bug on base i3 but it worked fine

**To Reproduce**
pick a game
change fullscreen res to 480p
toggle fullscreen on then off

**Expected behavior**
should go back to desktop without rapid flicker

**Screenshots**
![Screenshot from 2021-06-09 21-41-35](https://user-images.githubusercontent.com/25411734/121459974-cfd0ff00-c971-11eb-96cf-aa575b9414db.png)

**Configuration file(s)**
default

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [e.g. 1.4]
 - PPA url: [default: regolith-linux/stable](installed on top of vanilla Ubuntu 20.04.2)
 - Host OS (for PPA): [Ubuntu 20.04]

**Additional context**

**Comment by kgilmer** [comment]
Hi @BoyfriendDaPopstar  often issues like this are due to problems between the compositor and your graphics driver.  Can you try disabling the compositor (`sudo apt install regolith-compositor-none`) and then log back in to your session to see if the problem is resovled?

**Comment by Twista** [comment]
Had a different issue - suddenly (might be caused by an update) - the UI becomes very laggy (e.g scrolling through websites)

disabling the compositor helped :)

**Comment by kgilmer** [comment]
Thanks for the tip @Twista .  I'm going to close this due to lack of response from original issue creator.

**Comment by BoyfriendDaPopstar** [comment]
sorry for the late response ill test that out now.

**Comment by BoyfriendDaPopstar** [comment]
changing the compositor broke the emulator now it doesnt want to load(it probably my fault though i think its config got reset). i try to see if i can do anything on my end
