### ISSUE TITLE
Can't connect to any wifi that opens website to connect like Starbucks

### ISSUE THREAD

**Issue by jivanmukti** [regolith-linux/regolith-desktop#586]
- [ X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [X ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I can connect to normal wifi fine, but I can't connect to any wifi that opens up a screen to connect like Starbucks wifi or cafe/hotel wifis.

**To Reproduce**
Open network manager, click on the wifi network.

**Expected behavior**
Browser opens to webpage where I click on some sort of connect to network button.

**Screenshots**

**Configuration file(s)**

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4.1
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by jivanmukti** [comment]
Am able to connect by typing "route -n" into the terminal and  entering the Gateway IP Address for Destination 0.0.0.0. Is there any way to have the prompt open without having to do this?

**Comment by ferdinandyb** [comment]
Does this work if you log into vanilla Ubuntu instead of Regolith?

**Comment by kgilmer** [comment]
Closing due to lack of response.
