### ISSUE TITLE
Xorg crashes in fresh install

### ISSUE THREAD

**Issue by pizzapim** [regolith-linux/regolith-desktop#589]
Regolith version: 1.6 (21.04)
Hardware: Lenovo Thinkpad X260, Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

Xorg crashes on me every time I start Regolith. I downloaded and installed a fresh copy of Regolith just now. Here is the crash report:
[_usr_lib_xorg_Xorg.0.crash.txt](https://github.com/regolith-linux/regolith-desktop/files/6758825/_usr_lib_xorg_Xorg.0.crash.txt)

**Comment by kgilmer** [comment]
Hmm, I'm not sure what to offer here as troubleshooting steps.  I have an X270 myself and do not experience any issues.  Are you installing from ISO or PPA?  If you boot into the ISO live environment does it also crash?

**Comment by nicekiwi** [comment]
I can't even boot properly after a fresh install of 1.6 :( 
![image](https://user-images.githubusercontent.com/738975/126433269-ca0360dc-e8e4-4206-900f-0259abcb63df.png)

**Comment by kgilmer** [comment]
This looks to be an installation issue.  The kernel cannot find the root filesystem.  You can boot from a USB drive containing the Regolith 1.6 installer to verify that your hardware is/is-not compatible with Regolith (really Ubuntu).
