### ISSUE TITLE
The time on the panel does not change.

### ISSUE THREAD

**Issue by nuxster** [regolith-linux/regolith-desktop#590]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
The time on the panel does not change.

**To Reproduce**
From time to time I notice this bug, I have no idea how to reproduce it. 

**Expected behavior**
The time on the panel must match the system time.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/18188233/124739777-dc218b00-df22-11eb-878a-d4bd1ca3e887.png)

**Configuration file(s)**

**Installation Details**
 - Regolith Install Type: [ISO]
 - Regolith Version: [1.6]
 - PPA url: [ ]
 - Host OS (for PPA): [Ubuntu 20.04]

**Additional context**
ii  regolith-i3xrocks-config                   3.6.4-1
ii  i3xrocks-time                              3.6.4-1

**Comment by kgilmer** [comment]
Very strange...during when the bar is not updating, can you run the bar command directly from a terminal?  I'm guessing there is some error that prevents the update.  bar command:

```
i3xrocks -u ~/.config/regolith/i3xrocks/conf.d -d /etc/regolith/i3xrocks/conf.d
```

**Comment by nuxster** [comment]
After several updates, the problem has ceased to appear. I have a suggestion that it has something to do with hibernation.
