### ISSUE TITLE
Disable Auto-Hiding Mouse

### ISSUE THREAD

**Issue by polaroidkidd** [regolith-linux/regolith-desktop#592]
I'm having trouble permanatly disableing the auto-hide for the mouse. I came across this issue https://github.com/regolith-linux/regolith-desktop/issues/410 (and commented on it, but I think Github doesn't create notifications for closed issues).

Here's my issue:

> I've followed these instructions but `unclutter` still runs at every start-up.
> 
> Additionally, once ran the above commands, Ubuntu claimed that the following packages were no longer needed
> 
> ```
> i3xrocks-next-workspace libconfig9 libjsonrpc-glib-1.0-1 libxcb-composite0 libxcb-damage0 libxcb-ewmh2 moka-icon-theme picom regolith-compositor-picom-glx regolith-default-settings regolith-ftue regolith-gnome-flashback
>   regolith-i3-gaps-config regolith-look-lascaille regolith-rofi-config regolith-styles regolith-unclutter-xfixes remontoire rofi x11-apps x11-session-utils xinit xorg
> ```
> 
> using `sudo apt autoremove -y` removed these packages, but after reboot I was unable to start a new session from login (which was kind of expected since it removed some core packages). I managed to fix it by `ctrl+alt+F1` and installing `regolith-desktop` again and rebooting again.

and

> thanks for looking into this. Here the results
> 
> ```
> ➜ apt list --installed | grep unclutter
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> regolith-unclutter-xfixes/focal,now 1.5-2 amd64 [installed,automatic]
> 
> ➜ cat /etc/regolith/version
> REGOLITH_VERSION=1.6.0%
> ```

BTW, great distro. I'm absolutely in love with it and recommend it to anyone whose interested in i3-wm!

**Comment by kgilmer** [comment]
Hi @polaroidkidd , thanks for the feedback.  I've added a howto to address this configuration topic: https://regolith-linux.org/docs/howtos/disable-unclutter/

Kindly reopen this issue if the steps do not resolve it.

**Comment by kgilmer** [comment]
Note that some applications may also be doing cursor hiding.  For example on my system `gnome-terminal` will hide the cursor if it is over the terminal window and I begin typing.  This is not a system-level setting.  I am not sure if this can be disabled.  Related: https://superuser.com/questions/902909/disabling-mouse-hiding-in-gnome-terminal-while-typing
