### ISSUE TITLE
Removing the Solarized Color Palette from the terminal 

### ISSUE THREAD

**Issue by Black-Phoenix** [regolith-linux/regolith-desktop#6]
Hey,
The solarized color palette installed looks great but interferes with my terminal theme + vim. Is there any way I can remove only that component of the color palette?

**Comment by kgilmer** [comment]
Hi @Black-Phoenix ... do you mean the color theme inside st, the terminal app?  If so, it can be done but it's a little more work than you might expect.  st's configuration is expressed in source code so to change the color theme you'll need to update the config.h file with your colors, recompile, and replace the binary provided by package `regolith-st` with your version.

Another approach would be to use a different terminal app that let's you change color palettes interactively, such as gnome-terminal.  

I will add a FAQ item for how to swap out terminals.

**Comment by Black-Phoenix** [comment]
Ya, I was talking about st. Swapping the terminal app would also work. Thank you!

**Comment by kgilmer** [comment]
Actually, I remember there is a patch for st to read config from a file rather than hardcoding in source.  This would be a good feature for a future version of Regolith.

**Comment by kgilmer** [comment]
The patch: https://st.suckless.org/patches/xresources/

**Comment by kgilmer** [comment]
@Black-Phoenix just FYI, there is a patch in the terminal that toggles between solarized dark and light if you press F6.
