### ISSUE TITLE
Battery icon not showing on the panel

### ISSUE THREAD

**Issue by joyetgeorge** [regolith-linux/regolith-desktop#608]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
My laptop battery icon and battery percentage is not showing in the panel
I also checked the /etc/regolith/i3xrocks/conf.d and there is no battery config file 

I even tried apt install i3xrocks-battery

Unable to locate package i3xrocks-battery

**Installation Details**
 - Regolith Install Type: [ISO]
 - Regolith Version: [1.6]
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 21.4]

**Comment by kgilmer** [comment]
Here is where the `i3xrocks-battery` package is located: https://launchpad.net/~regolith-linux/+archive/ubuntu/release/+sourcepub/12474924/+listing-archive-extra

If you're apt is unable to find it perhaps there is an issue with your repo sources.  What do you see when running `apt policy | grep regolith` from a terminal?

**Comment by kgilmer** [comment]
Closing due to lack of response.  Kindly reopen if there is additional information.

**Comment by Philipp0205** [comment]
For future readers: 

I think the issue here was that the launchpad ppa repository was not added to ubuntu so the packages will not show up using `apt search i3xrocks-`.

Fix:
```
sudo add-apt-repository ppa:regolith-linux/release
sudo apt update
sudo apt-get install i3xrocks-battery
```
