### ISSUE TITLE
100% CPU Usage by i3 and i3bar make

### ISSUE THREAD

**Issue by pythonInRelay** [regolith-linux/regolith-desktop#610]
![Screenshot from 2021-09-22 14-09-20](https://user-images.githubusercontent.com/58630825/134334643-adbfda88-a9cf-4848-bd7d-fd1acf60177f.png)

As shown above, i3 and i3bar are using all of my machines CPU. I don't understand the reason for this at all.

Here are my specs. The machine is a brand new Lenovo Thinkpad P15s Generation 2
![Screenshot from 2021-09-22 14-21-37](https://user-images.githubusercontent.com/58630825/134334912-e8ea9473-b1a2-483a-b2d2-b615a28a5cea.png)

**Comment by ploum** [comment]
Just to be sure : does it happen when you are disconnected ? (see #532 )
