### ISSUE TITLE
Missing i3 config folder and file

### ISSUE THREAD

**Issue by 3mkay** [regolith-linux/regolith-desktop#612]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
A folder and file is missing from the default configuration for i3

**To Reproduce**

After a fresh installation of Regolith 2.0 on Debian Bullseye, i3 reports that "You have an error in your i3 config file!" after clicking "show errors" the following ERROR report is displayed:

> realpath(/home/[username]/.config/regolith/i3/config.d/*): No such file or directory

**Expected behavior**
No error should appear

**Screenshots**

**Configuration file(s)**
N/A

**Installation Details**
 - Regolith Install Type: Apt source
 - Regolith Version: 2.0
 - PPA url: Not PPA
 - Host OS (for PPA): Debian Bullseye

**Additional context**
Installation completed as per README https://github.com/regolith-linux/package-repo

**Comment by 3mkay** [comment]
Immediate workaround is to create the folder and files as follows:

`mkdir -p ~/.config/regolith/i3/config.d`

`touch ~/.config/regolith/i3/config.d/config`

**Comment by kgilmer** [comment]
The fix is upstream in i3, I just have yet to build it into the repo.
