### ISSUE TITLE
Xresources cannot set workspace #3 name or background?

### ISSUE THREAD

**Issue by 825i** [regolith-linux/regolith-desktop#614]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I can name all workspaces except for some reason workspace 3 will not change its name from "3". When setting the background image via the normal i3 flag in Xresources this does not work either.

**To Reproduce**
Try to rename workspace 3 to anything and the name will not change.
Try to set a background image like I have shown in the screenshot below and it will not change from default.

**Expected behavior**
Should be able to change workspace name and background

**Screenshots**
![Screenshot from 2021-10-20 09-33-43](https://user-images.githubusercontent.com/58630825/138040905-18b15bee-1251-4e4d-a5f1-c7c958325a26.png)

**Configuration file(s)**
See screenshot

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 1.6

**Comment by lo-windigo** [comment]
Your configuration line for Workspace 3 starts with "i3-vm" when it should be "i3-wm".

**Comment by ferdinandyb** [comment]
As @lo-windigo pointed it it's clearly a typo in the config, so I'm going to close this issue. If the problem still persists after fixing the typo please feel free to reopen the issue with additional information.
