### ISSUE TITLE
Windows freeze and unresponsive, seemingly random

### ISSUE THREAD

**Issue by RJDan** [regolith-linux/regolith-desktop#616]
- [ x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
At seemingly random times the window rendering goes bad - like a strange mosaic of snippets from random open windows across all workspaces. The windows remain unresponsive (I can't open, close, switch or interact with) but the mouse continues to move without issue across my monitors. I can change workspace with the mouse scroll wheel but not with the keyboard. 
Rarely, it come back to life after a moment. Most of the time it does not wake up. If I close my lid the entire laptop freezes and I need to hard restart.

**To Reproduce**
Unfortunately I don't have a clear set of steps to reproduce the effect.
It has happened while editing online documents (Firefox and google docs), while backing up local data with BackInTime to an external harddrive, and while editing images in Inkscape. 

**Expected behavior**
The windows render properly and do not cause the computer to freeze.

**Screenshots**
Here are screenshots of the frozen windows and of the error messages after closing the laptop lid (it does not sleep):
[screenshots](https://photos.app.goo.gl/oopNA6rePR2icgtj6)

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.6
 - PPA url: default: ppa:regolith-linux/release
 - Host OS (for PPA):  Ubuntu 20.10

**Additional context**
I swapped to regolith in October 2021.
I am using dunst.
Asus A15 Ryzen 7 with radeon graphics
Nvidia 470 driver
Asus zenscreen MB16AMT with touch

**Comment by kgilmer** [comment]
Hi @RJDan , hmm this sounds like it could be a compositor issue.  I suggest to first disable the compositor to see if that is the root cause.  If so, there are a few compositors you can install as packages and you can also configure the compositor if it's required by your hardware/driver setup.  See here for details: https://regolith-linux.org/docs/customize/compositors/

If compositor is not the issue, kindly reopen this.
