### ISSUE TITLE
App Launcher doesn't open

### ISSUE THREAD

**Issue by amit-omb** [regolith-linux/regolith-desktop#620]
Hi! 
So I just installed and set up Regolith, and while all other keyboard shortcuts work without issue, pressing super+space doesn't open the App Launcher. 
I tried also overriding the 'Launch Search' keyboard shortcut from the settings to a different key combination, and it still does not work, further leading me to believe that the issue is with the app launcher itself and not the keyboard shortcuts themselves. 

OS Name: Ubuntu 21.10
GNOME Version: 40.4.0

Will appreciate any help!

**Comment by amit-omb** [comment]
Don't know how that's related, but after installing zsh,curl,git and ohmyzsh I tried again and it's working :shrug:

**Comment by SwithFr** [comment]
Fresh install on Ubunu 22.04 and same problem, super+space doesn't work.
