### ISSUE TITLE
Rocification cannot catch notificiations

### ISSUE THREAD

**Issue by newptcai** [regolith-linux/regolith-desktop#621]
I have installed regolith on ubuntu 20.04. After installation, I noticed that notification pop up windows still appear, instead of shown in rocification as described by the document. Please see the screenshot. Is there any way to diagnose this?

![Screenshot from 2022-01-14 06-49-23](https://user-images.githubusercontent.com/982197/149421612-c8b42d3e-99b6-4ba3-add2-72b0debad7b5.png)

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by cfsmp3** [comment]
In firefox - about:config

then 

alerts.useSystemBackend

make sure it's true.

**Comment by newptcai** [comment]
It is on. It is not only Firefox. Everything notification is shown in popup windows. It is system wide.

**Comment by newptcai** [comment]
I know the problem. I have `xfce-notify` installed. :joy:
