### ISSUE TITLE
Be able to remap "resize mode" keybinding

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#627]
In Regolith 1.6, "resize mode" Mod+r is hardcoded with no way of overwritting it in Xressources. 

(this is a problem with the "bépo" keyboard where the "R" is located on the Vi right arrow key ("L" on qwerty))

Also, a related issue : Regolith should drop default keybinding if they conflict with custom ones. Currently, adding a custom keybinding to Xressource involves remapping conflicting one, even if they are not used/needed.

Both issue might be addressed in 2.0

**Comment by ferdinandyb** [comment]
I don't think dropping a default keybinding in case the user adds a new one to the i3 config is possible. At least not without pre-parsing the i3 configs before i3.

**Comment by kgilmer** [comment]
Yes in this case it may be possible to uninstall the partial that is providing the keybinding and provide your own partial in `~/.config/regolith2/...` but if the keybinding happens to be expressed in the [root config file](https://github.com/regolith-linux/regolith-i3-config/blob/master/config) then the user must stage their own i3 config file entirely.

**Comment by kgilmer** [comment]
It is a gap that resize mode key cannot be overridden.  Will update config to allow key `i3-wm.binding.resize_mode` for that purpose.

**Comment by kgilmer** [comment]
See

```
set_from_resource $i3-wm.binding.resize_mode i3-wm.binding.resize_mode r
```

Also the `regolith-i3-resize` package can be removed and the user may specify any resize config they like.
