### ISSUE TITLE
Upgrading to Ubuntu Jammy + Regolith break i3 config

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#628]
I upgraded to Ubuntu Jammy and also upgraded to Regolith 2.0 to test the upgrade process. Wasn’t really smooth. 

Of course, this can be caused my my regolith 1.6 configuration but reporting anyway as, even if it is my fault, this can help someone in the future.

![regolith_bug_config](https://user-images.githubusercontent.com/1233155/161447070-824bda04-b580-4c59-9434-30e8bed57e07.png)

**Comment by kgilmer** [comment]
Can you describe any customizations you have, in particular anything with i3?

**Comment by ploum** [comment]
this is my .config/regolith/Xresources:

gnome.wallpaper:
i3-wm.program.1: /home/ploum/dev/i3-alternating-layout/alternating_layouts.py
i3-wm.program.2: /home/ploum/dev/offlinetools/capslock.sh
i3-wm.program.files: thunar
i3-wm.gaps.focus_follows_mouse: yes
i3-wm.gaps.smart: inverse_outer
#conversion to Bépo
i3-wm.binding.left: c
i3-wm.binding.right: n
i3-wm.binding.up: s
i3-wm.binding.down: t
i3-wm.binding.move_left: Shift+c
i3-wm.binding.move_right: Shift+n
i3-wm.binding.move_up: Shift+s
i3-wm.binding.move_down: Shift+t
i3-wm.binding.layout_mode: j
#to avoid conflict
i3-wm.binding.reload: Shift+h
i3-wm.binding.refresh: Shift+r
i3-wm.binding.settings: u
i3-wm.binding.sound: k
i3-wm.binding.files: Shift+ç
i3-wm.binding.focus_toggle: è
i3-wm.binding.sleep: Ctrl+%
i3-wm.binding.notification_ui: ê

**Comment by ploum** [comment]
I thought that this Xressource would not be loaded as it is not in the regolith2 folder

**Comment by ploum** [comment]
removing remontoire solves the issue. But reinstalling it, even after purging config file, is enough to create the problem. Seems to be a bug with remontoire.

**Comment by kgilmer** [comment]
Yes I agree that any Xresources in `~/.config/regolith/Xresources` should *not* be loaded from a Regolith 2 session.  LMK if this is what you are seeing.  I'll take a look at the remontoire issue.

**Comment by kgilmer** [comment]
This should be fixed by the above commit.
