### ISSUE TITLE
Strange value in i3xrocks after upgrading to Ubuntu Jammy/Regolith 2.0

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#629]
This is regolith 2.0 on jammy
![regolith_bug1](https://user-images.githubusercontent.com/1233155/161447172-f560acec-9d61-43a3-9cda-9ff510d318c5.png)

**Comment by kgilmer** [comment]
Hmm, perhaps the temp script is residual from Regolith 1.x..  I see this (which is broken in a different way): 

![image](https://user-images.githubusercontent.com/49683/161450643-9eb10506-afc6-4b7e-ab3a-d458f51c4553.png)

**Comment by kgilmer** [comment]
A fix is building into the repos now.

**Comment by kgilmer** [comment]
Note that with Regolith 2, we switched to using nerd fonts, so we can use a single font for both text and glyphs.  This means that the unicode for any given glyph has likely changed from anything specified in Regolith 1.x.

**Comment by ploum** [comment]
I dist-upgraded but there’s no change. Where could be the leftover of regolith 1?

**Comment by ploum** [comment]
I removed every regolith packages, including configurations, moved .config/regolith to .config/regolith1 and removed .Xressources. I still have the bug on Impish.

I don’t have it on Debian.

**Comment by p3k** [comment]
for the output below i was using this `Xresources` setting in regolith 1.6:

```yaml
i3xrocks.label.memory: 🐏
```

![Screenshot-2022-07-20-13-56-08](https://user-images.githubusercontent.com/16631/180441105-9608f762-623e-4a05-93d2-ecb368619322.png)

after upgrade to regolith 2 it looks like this (ignore the change of color):

![image](https://user-images.githubusercontent.com/16631/180441499-09cbfdb5-f8cd-4943-816d-05121a54e27a.png)

**Comment by p3k** [comment]
could we reopen this issue @kgilmer? or should i repost my comment to a new one?

**Comment by kgilmer** [comment]
@p3k so there was a change in fonts from 1.x to 2.x.  Before we were using font-awesome for glyphs in some cases, material web fonts in others.  Because these two fonts didn't have a consistent mapping it added complexity in setting the appropriate character based on what fonts were installed.  To simplify this we moved to nerdfonts.  Now, because the "normal" font is combined with the glphy font, there is no seperate font package to deal with.  However a consequence of this is that the 1.6 glyph mappings are no longer valid for 2.x installs.  So, to resolve this you need to [go here](https://www.nerdfonts.com/cheat-sheet) and find the glyph you want and then update your Xresource override accordingly.

**Comment by kgilmer** [comment]
So to specifically answer your question @pk3, this is expected (breaking) behavior that was introduced when we migrated to nerdfonts in the 2.0 release.

**Comment by p3k** [comment]
thanks for the insights @kgilmer

the icon i actually want to display is an emoji. the nerdfont does not seem to include emojis. thus, i assume i am limited to the icons provided by the nerdfont?

**Comment by kgilmer** [comment]
Yes, you're limited what nerdfont provides unless the emoji are also provided by a font and you move to that font in your i3bar font specification.  The Xresource key `gtk.monospace_font_name` controls the font specified to i3bar.

**Comment by p3k** [comment]
@kgilmer should this work to display an emoji in the i3bar? (because it does not for my ram emoji… still get `U0001f40f`)

```yaml
gtk.monospace_font_name: NotoColorEmoji 12
```

**Comment by kgilmer** [comment]
Sorry for the late reply, life has gotten busy recently.  For Regolith looks, only the nerdfonts emojis will work out of the box.  To use a different font such as `NotoColorEmoji` one would need to provide mappings for all [i3xrocks emoji entries](https://github.com/regolith-linux/regolith-look-default/blob/main/usr/share/regolith-look/default/i3xrocks).

```shell
$ apt list | grep ^fonts-nerd-font-

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

fonts-nerd-font-3270/unknown 2.1.0-2-1regolith all
fonts-nerd-font-agave/unknown 2.1.0-2-1regolith all
fonts-nerd-font-anonymouspro/unknown 2.1.0-2-1regolith all
fonts-nerd-font-arimo/unknown 2.1.0-2-1regolith all
fonts-nerd-font-aurulentsansmono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-bigblueterminal/unknown 2.1.0-2-1regolith all
fonts-nerd-font-bitstreamverasansmono/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-cascadiacode/unknown 2.1.0-2-1regolith all
fonts-nerd-font-codenewroman/unknown 2.1.0-2-1regolith all
fonts-nerd-font-cousine/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-daddytimemono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-dejavusansmono/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-droidsansmono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-fantasquesansmono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-firacode/unknown 2.1.0-2-1regolith all
fonts-nerd-font-firamono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-go-mono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-gohu/unknown 2.1.0-2-1regolith all
fonts-nerd-font-hack/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-hasklig/unknown 2.1.0-2-1regolith all
fonts-nerd-font-heavydata/unknown 2.1.0-2-1regolith all
fonts-nerd-font-hermit/unknown 2.1.0-2-1regolith all
fonts-nerd-font-ia-writer/unknown 2.1.0-2-1regolith all
fonts-nerd-font-ibmplexmono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-inconsolata/unknown 2.1.0-2-1regolith all
fonts-nerd-font-inconsolatago/unknown 2.1.0-2-1regolith all
fonts-nerd-font-inconsolatalgc/unknown 2.1.0-2-1regolith all
fonts-nerd-font-iosevka/unknown 2.1.0-2-1regolith all
fonts-nerd-font-jetbrainsmono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-lekton/unknown 2.1.0-2-1regolith all
fonts-nerd-font-liberationmono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-meslo/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-monofur/unknown 2.1.0-2-1regolith all
fonts-nerd-font-monoid/unknown 2.1.0-2-1regolith all
fonts-nerd-font-mononoki/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-mplus/unknown 2.1.0-2-1regolith all
fonts-nerd-font-opendyslexic/unknown 2.1.0-2-1regolith all
fonts-nerd-font-overpass/unknown 2.1.0-2-1regolith all
fonts-nerd-font-profont/unknown 2.1.0-2-1regolith all
fonts-nerd-font-proggyclean/unknown 2.1.0-2-1regolith all
fonts-nerd-font-robotomono/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-sharetechmono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-sourcecodepro/unknown,now 2.1.0-2-1regolith all [installed,automatic]
fonts-nerd-font-spacemono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-terminus/unknown 2.1.0-2-1regolith all
fonts-nerd-font-tinos/unknown 2.1.0-2-1regolith all
fonts-nerd-font-ubuntu/unknown 2.1.0-2-1regolith all
fonts-nerd-font-ubuntumono/unknown 2.1.0-2-1regolith all
fonts-nerd-font-victormono/unknown 2.1.0-2-1regolith all
```
