### ISSUE TITLE
[regolith 2] regolith desktop package miss dependencies

### ISSUE THREAD

**Issue by ploum** [regolith-linux/regolith-desktop#632]
If installing regolith-desktop, you will miss:

- i3xrocks
- regolith-lookdefault
- ilia
(so a bare i3)

note that installing i3xrocks is not enough as it doesn’t pull any block (maybe on purpose)

**Comment by kgilmer** [comment]
Hmm, I created a fresh copy of Focal, added the 2.0 repo, and installed the desktop:

```
$ sudo apt install regolith-desktop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfprint-2-tod1 libllvm9
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  ayu-theme fonts-nerd-font-jetbrainsmono gnome-flashback gnome-flashback-common i3-gaps-wm i3-next-workspace i3-snapshot i3xrocks
  i3xrocks-cpu-usage i3xrocks-net-traffic i3xrocks-time ilia libanyevent-i3-perl libanyevent-perl libasync-interrupt-perl libcommon-sense-perl
  libev-perl libev4 libgnome-panel0 libguard-perl libjson-xs-perl libjsoncpp1 libtypes-serialiser-perl libxcb-cursor0 libxcb-xinerama0 libxcb-xrm0
  libxdo3 python3-i3ipc python3-xlib regolith-compositor-none regolith-control-center regolith-default-settings regolith-ftue regolith-i3-compositor
  regolith-i3-config regolith-i3-ftue regolith-i3-gaps-partial regolith-i3-gnome regolith-i3-i3xrocks regolith-i3-ilia regolith-i3-rofication-ilia
  regolith-i3xrocks-config regolith-look-default regolith-rofication regolith-session-flashback sysstat xdotool xrescat
Suggested packages:
  libevent-perl libio-async-perl libpoe-perl libtask-weaken-perl gnome-software | gnome-packagekit gnome-user-share realmd libcanberra-gtk-module
  isag
The following NEW packages will be installed:
  ayu-theme fonts-nerd-font-jetbrainsmono gnome-flashback gnome-flashback-common i3-gaps-wm i3-next-workspace i3-snapshot i3xrocks
  i3xrocks-cpu-usage i3xrocks-net-traffic i3xrocks-time ilia libanyevent-i3-perl libanyevent-perl libasync-interrupt-perl libcommon-sense-perl
  libev-perl libev4 libgnome-panel0 libguard-perl libjson-xs-perl libjsoncpp1 libtypes-serialiser-perl libxcb-cursor0 libxcb-xinerama0 libxcb-xrm0
  libxdo3 python3-i3ipc python3-xlib regolith-compositor-none regolith-control-center regolith-default-settings regolith-desktop regolith-ftue
  regolith-i3-compositor regolith-i3-config regolith-i3-ftue regolith-i3-gaps-partial regolith-i3-gnome regolith-i3-i3xrocks regolith-i3-ilia
  regolith-i3-rofication-ilia regolith-i3xrocks-config regolith-look-default regolith-rofication regolith-session-flashback sysstat xdotool xrescat
```

I'm seeing all of it there.  What am I doing differently @ploum ?

**Comment by kgilmer** [comment]
FWIW the packages you mention are `Recommends`, did you configure `apt` to install install those?

**Comment by ploum** [comment]
No, I didn’t configure it to install recommendations (also, I’m in 22.04 beta).

**Comment by kgilmer** [comment]
Whoops I meant to say did you configure apt to *not* install `recommends`..I'm guessing no special configuration.  Will have to try and repo on 22.04.

**Comment by ploum** [comment]
If I’m right exploring dependencies :

- ilia and i3xrocks are only pulled by regolith-look-default
- regolith-look-default is not installed if another regolith-look package is already present.

I feel that regolith-desktop should directly depends on ilia and i3xrocks (after all, that’s the very definition of a regolith deskop, isn’t it?). 

Regolith-desktop should also propably depends of regolith-look-default as some other looks may not define every ressource and some fallback to look-default may be expected. (a bit like you cannot have GTK those days without having the adwaita theme).

**Comment by ploum** [comment]
(this is only done exploring packages with apt-cache show, I didn’t looked at the source of packages)

**Comment by kgilmer** [comment]
> regolith-look-default is not installed if another regolith-look package is already present.

Ah, that's likely the root of the issue. I did not think this case would happen but I was wrong.

> I feel that regolith-desktop should directly depends on ilia and i3xrocks (after all, that’s the very definition of a regolith deskop, isn’t it?).

In 2.x I'm leaving the door open for Regolith to be something entirely different, or at least that's the intention.  `regolith-session-flashback` is the root dependency of the "i3 - gnome" integration.  Another variant of `regolith-session` can be supplied at a later time that may bring in some other session, specifically something wayland-based.

> Regolith-desktop should also propably depends of regolith-look-default as some other looks may not define every ressource and some fallback to look-default may be expected. (a bit like you cannot have GTK those days without having the adwaita theme).

Yes I think the solution is to `require` `regolith-look-default` and `regolith-look` (virtual package) in `regolith-session-flashback`.  I need to check to see the appropriate debian `control` expression for that.

**Comment by ploum** [comment]
putting ilia and i3xrocks in regolith-session-flashback is probably good. But it feels strange to have them pulled by regolith-look-default.

**Comment by kgilmer** [comment]
The reason they are all attached to `regolith-look-default` is to give looks more freedom to specify whatever desktop components they want.  So, there could be one look using polybar, another using drun, dunst, etc..

**Comment by kgilmer** [comment]
I reverted my last approach, because it causes `regolith-look-default` to be a hard dependency.  This requires some programs to be installed that are not necessary.  I choose to provide a new virtual package as to not be mixed in with 1.x looks, which should also prevent the upgrade issue you encountered.

**Comment by kgilmer** [comment]
Dependency model is working as of official release of 2.0+.  Kindly reopen @ploum if you see otherwise.

**Comment by prismspecs** [comment]
Hm, I'm still getting this

```
The following packages have unmet dependencies:
 regolith-desktop : Depends: regolith-session-flashback but it is not going to be installed or
                             regolith-desktop-session

```
