### ISSUE TITLE
Enable floating mode for JetBrains IDE loading screens

### ISSUE THREAD

**Issue by tpb1908** [regolith-linux/regolith-desktop#634]
- [x] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic

**Is your feature request related to a problem? Please describe.**

JetBrains IDEs display a loading screen 

**Describe the solution you'd like**

Add the following checking for the startup windows of JetBrains IDEs 

```
for_window [class="jetbrains-.*" title="win0"] floating enable border none
```

The running IDE has the class `jetbrains-<ide-name>`, e.g. `WM_CLASS(STRING) = "jetbrains-webstorm", "jetbrains-webstorm"`. As such the title check is necessary to identify the loading window. 

`xprop` for loading window:
```
_NET_WM_DESKTOP(CARDINAL) = 4
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR
_NET_WM_PID(CARDINAL) = 280214
WM_CLIENT_MACHINE(STRING) = "desktop"
WM_PROTOCOLS(ATOM): protocols  
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x0, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 2680, 880
		program specified size: 640 by 400
		window gravity: NorthWest
WM_CLASS(STRING) = "jetbrains-webstorm", "jetbrains-webstorm"
WM_CLIENT_LEADER(WINDOW): window id # 0x3a00008
_NET_WM_NAME(UTF8_STRING) = "win0"
WM_NAME(STRING) = "win0"
```

`xprop` for IDE (excluding icons):

```
_NET_WM_USER_TIME(CARDINAL) = 6928539
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0x4c, 0x0, 0xa0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_DESKTOP(CARDINAL) = 4
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x1, 0x0, 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: False
                Initial state is Normal State.
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 26, 1
_NET_WM_PID(CARDINAL) = 280214
WM_CLIENT_MACHINE(STRING) = "desktop"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS
WM_CLASS(STRING) = "jetbrains-webstorm", "jetbrains-webstorm"
WM_CLIENT_LEADER(WINDOW): window id # 0x3a00008
_NET_WM_ICON_NAME(UTF8_STRING) = "<project name here>"
WM_ICON_NAME(COMPOUND_TEXT) =  "<project name here>"
_NET_WM_NAME(UTF8_STRING) =  "<project name here>"
WM_NAME(COMPOUND_TEXT) = "<project name here>]"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 3001, 26
                program specified location: 3001, 26
                program specified size: 1918 by 2130
                program specified minimum size: 338 by 0
                window gravity: NorthWest

```

**Comment by ferdinandyb** [comment]
Are you asking for this very specific thing to be included in the default regolith i3 config? I think in general, the solution would be to stage the config file and add any personalization you want to that.

**Comment by tpb1908** [comment]
@ferdinandyb I have included this change in my own config, and it's even simpler to add as a partial in Regolith 2. 

More generally, is there a particular reason that Regolith shouldn't have configurations for common applications, like [Manjaro i3 does](https://gitlab.manjaro.org/profiles-and-settings/desktop-settings/-/blob/master/community/i3/skel/.i3/config#L189). 

I understand not wanting to be opinionated about which applications should be floating (calculators, video calls etc), but fixing a (relatively) common suite of applications doesn't seem unreasonable.

**Comment by ferdinandyb** [comment]
@kgilmer what's your take?

**Comment by kgilmer** [comment]
Thanks for the info, it's interesting to peruse the Majaro's i3 config file.  Sort of like looking in the refrigerator when visiting a friends house..haha.  I think @tpb1908 is saying that this snippet would be a good i3 config partial for users and I agree.  IMO, these floating class declarations are purely opinions.  Personally I may prefer to have Pale Moon launch in regular mode.  And so I don't think it makes sense to add them en massed to the Regolith i3 config.

I do think if a sufficient subset of users which this was integrated, we could provide another partial that basically copies Manjaro's opinion on floating windows as a Regolith i3 config partial package.

Users wishing this should upvote this ticket.

**Comment by kgilmer** [comment]
Closing assuming @p3k's tip resolves @tpb1908 's issue.  Kindly re-open if this is not the case.  Regarding community-source list of apps to start in floating mode, if anyone is interested in this kindly add a dicussion topic here: https://github.com/orgs/regolith-linux/discussions
