### ISSUE TITLE
Second monitor is not recognized

### ISSUE THREAD

**Issue by m-ocean-it** [regolith-linux/regolith-desktop#636]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Regolith Linux 1.6 (20.04 UEFI)** on ThinkPad E15 Gen 2

Second monitor is not recognized (including when running `xrandr`). Which is weird, since it worked fine on regular Ubuntu and, also, on Regolith 1.6 (21.04). (I'd tried the 21.04 version but, for some reason, some bug didn't allow internet connection, so I went with 20.04 UEFI.)

I tried running `sudo ubuntu-drivers autoinstall` but it didn't find any additional drivers. Secure boot is disabled.

**Some additional info**

Tried connecting to my TV which always worked for me: same result, the OS doesn't recognize the screen.

And some commands' outputs:
```bash
$ xrandr
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 1920 x 1080, current 1920 x 1080, maximum 1920 x 1080
default connected primary 1920x1080+0+0 0mm x 0mm
   1920x1080     77.00*
```

```bash
$ lspci | grep VGA
VGA compatible controller: Intel Corporation Device 9a49 (rev 01)
```

**To Reproduce**
Fresh install of Regolith. (Then `sudo apt update && sudo apt upgrade`.)

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 1.6

**Comment by m-ocean-it** [comment]
Installing additional Intel drivers as described [here](https://www.linuxfordevices.com/tutorials/ubuntu/install-intel-graphic-drivers) didn't help.

**Comment by kgilmer** [comment]
Hi @m-ocean-it , if `xrandr` cannot see the hardware then in my estimation it's likely that the issue is at the driver level.  There may be a kernel update you could take to resolve the issue but it's just a guess.  You could install Ubuntu 22.04 and then Regolith into that environment.  You could verify that the monitor works in 22.04 by booting into the live environment first before installation.

**Comment by ferdinandyb** [comment]
@m-ocean-it Have you managed to resolve this issue or should we leave this ticket open?

**Comment by m-ocean-it** [comment]
Hi! I've had problems, but, in the end, [Regolith 2](https://regolith-desktop.com/) installed on top of Ubuntu 20.04 is so far flawless. So, I'm closing the issue. Thanks!
