### ISSUE TITLE
[Regolith2] systemd-oomd

### ISSUE THREAD

**Issue by miclaraia** [regolith-linux/regolith-desktop#637]
I recently upgraded to Ubuntu 22.04 and regolith2. I've been having issues where suddenly the entire X session would die, including all my user processes (e.g. my tmux sessions would die as well). I thought at first this might be related to a graphics driver, but I found these relevant lines in `/var/log/syslog` mentioning `systemd-oomd` before the most recent occurrence:
```
May  4 09:30:43 ----------- systemd-oomd[735]: Killed /user.slice/user-1000.slice/session-2.scope due to memory used (7422640128) / total (8199176192) and swap used (524283904) / total (524283904) being more than 90.00%
May  4 09:30:43 ----------- systemd[1]: session-2.scope: systemd-oomd killed 304 process(es) in this unit.
```

I found a similar discussion of this behavior [here](https://bugzilla.redhat.com/show_bug.cgi?id=1933494):
> It sounds like sway [and i3] doesn't separate applications into their own cgroups as KDE and GNOME do; this is a prerequisite for ideal operation. Per the feedback section in https://fedoraproject.org/wiki/Changes/EnableSystemdOomd you can spawn applications yourself into separate cgroups using `systemd-run` or you can opt out of the systemd-oomd policy by removing the systemd-oomd-defaults.

Relevant bug report in i3: https://github.com/i3/i3/issues/4298

Maybe it would make sense for the regolith to disable the `systemd-oomd` service when it's installed? At least until i3 sorts out implementing cgroups properly? The discussion linked above also mentions that other oom killers could be used instead
> If your DE is XFce (or Mate, LXDE etc) - use alternative killers. If you need userspace OOM killer with PSI support but your DE doesn't launch apps in separate cgroups you could use nohang-desktop (which supports PSI and doesn't kill the whole session).

**Comment by kgilmer** [comment]
Hi @miclaraia , thanks for the detailed report.  I am wondering how I can reproduce this problem..I don't think I've experienced this myself when testing `jammy`.  How much RAM does your system have?  Any tips to easily repro?

> Maybe it would make sense for the regolith to disable the systemd-oomd service when it's installed?

I've learned to be wary of making any system-wide changes to the host OS, it's very difficult to know what else may break as a result.  If this is a problem that is likely to be encountered by users often, then I think the first step would be to provide a howto on updating configuration manually to fix the problem.  Since I cannot reproduce it there isn't a way for me test steps to verify that the fix works.  If you're interested in writing something up for the website (a howto in markdown), let me know and I'll provide details.

**Comment by kgilmer** [comment]
It would be of great help if there was a way to reproduce this issue cleanly on any given system.

**Comment by mpareja** [comment]
Hi @kgilmer,

I just wanted to second @miclaraia's concern. You'll want to follow the [i3 issue closely](https://github.com/i3/i3/issues/4298) because without a change from them to spawn applications differently, then all regolith users will be potential victims of data loss due to having systemd-oomd enabled in Ubuntu. I've experienced this problem numerous times were my entire login session (and all active applications) are terminated:

```
$ journalctl -u systemd-oomd | grep Killed | grep -i session-
May 10 16:35:37 sonicpad systemd-oomd[606]: Killed /user.slice/user-1000.slice/session-25.scope due to memory used (32487882752) / total (33369427968) and swap used (1942372352) / total (2147479552) being more than 90.00%
May 11 11:13:08 sonicpad systemd-oomd[574]: Killed /user.slice/user-1000.slice/session-3.scope due to memory used (31491416064) / total (33369427968) and swap used (2004766720) / total (2147479552) being more than 90.00%
May 26 11:08:10 sonicpad systemd-oomd[631]: Killed /user.slice/user-1000.slice/session-3.scope due to memory used (30369116160) / total (33369432064) and swap used (2116259840) / total (2147479552) being more than 90.00%
Jun 06 11:05:50 sonicpad systemd-oomd[602]: Killed /user.slice/user-1000.slice/session-3.scope due to memory used (31142039552) / total (33369432064) and swap used (2111569920) / total (2147479552) being more than 90.00%
Jun 07 10:13:39 sonicpad systemd-oomd[602]: Killed /user.slice/user-1000.slice/session-67.scope due to memory used (32042946560) / total (33369432064) and swap used (2127314944) / total (2147479552) being more than 90.00%
Jun 08 10:35:34 sonicpad systemd-oomd[602]: Killed /user.slice/user-1000.slice/session-187.scope due to memory used (30072315904) / total (33369432064) and swap used (2082938880) / total (2147479552) being more than 90.00%
Jun 08 15:39:17 sonicpad systemd-oomd[602]: Killed /user.slice/user-1000.slice/session-341.scope due to memory used (32075808768) / total (33369432064) and swap used (1945272320) / total (2147479552) being more than 90.00%
Jun 13 11:32:12 sonicpad systemd-oomd[592]: Killed /user.slice/user-1000.slice/session-3.scope due to memory used (32184795136) / total (33369489408) and swap used (1933312000) / total (2147479552) being more than 90.00%
```

**Comment by mpareja** [comment]
Great to have Ilia using systemd-run. I imagine apps executed via i3 bindings aren't subject to the protection.

**Comment by kgilmer** [comment]
AFAIK they'd be be running in the same context as `i3`.  But when I think of the types of programs one would run from keybindings, I'm thinking of small "glue" programs that are relatively simple and short lived.  I guess if people have setups where they launch applications via keybindings this would a concern.  Do you have an example of a program launched by a keybinding that warrants additional memory considerations @mpareja ?

**Comment by mpareja** [comment]
I'm probably a bad example since I launch a lot via key bindings, but the biggest hitter would be a browser - and that's also likely to be the one that tanks memory.

**Comment by kgilmer** [comment]
Ah, well in this case @SoumyaRanjanPatnaik has already got us covered: https://github.com/regolith-linux/regolith-wm-config/pull/35.  LMK if you think of other cases where systemd isolation would be clear benefit.

**Comment by mpareja** [comment]
Oh, that's great. Short of i3 becoming aware when it's running in a systemd session, I think this is as good as it gets.

I'll start wrapping any of my heavy app launch commands in the same way. Thanks for sharing the info!
