### ISSUE TITLE
Add release for ubuntu "jammy" on ppa

### ISSUE THREAD

**Issue by jcode-hub** [regolith-linux/regolith-desktop#638]
- [x ] I've [run a search on the existing enhancements](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ x] I've read [the Regolith documentation](https://regolith-linux.org/docs/https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

When I try to install regolith-desktop on a fresh ubuntu 22.04 (jammy) no release can be found. Steps to reproduce:

*  Be on the latest ubuntu version:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

*  Add ppa:
`sudo add-apt-repository ppa:regolith-linux/release`
Output: `: The repository 'https://ppa.launchpadcontent.net/regolith-linux/release/ubuntu jammy Release' does not have a Release file.`
*  Install:
`sudo apt install regolith-desktop-standard`
Output: `E: Unable to locate package regolith-desktop-standard`

**Comment by lee2sman** [comment]
I installed regolith 1.6 using the above steps onto 22.04, almost positive, but I'm now checking the link and don't see a jammy listing. Is it possible the devs yanked out? Otherwise, my workaround was that i installed it on 20.04 first and then upgraded to 22.04.

**Comment by kgilmer** [comment]
Regolith 2.0 (currently in beta) supports Ubuntu 22.04.  The package repository has moved away from launchpad.net.  The existing PPA for Regolith 1.6 will not be updated to support Ubuntu 22.04.  You can find more information about Regolith 2 here: https://regolith-desktop.com.
