### ISSUE TITLE
downgrade

### ISSUE THREAD

**Issue by peejxyy** [regolith-linux/regolith-desktop#646]
i dont like regolith 2.0, how do i go back to 1.6. i try searching everywhere but all your sights lead to the new version

**Comment by kgilmer** [comment]
Hi @peejxyy , sure you can downgrade back to 1.6 on Ubuntu Focal or Impish.  I setup a redirect from the old site to the new, which is interfering with your desire to get the older docs.  I may revert that change for something else but in the mean time the site is also available at the following address: https://regolith-linux.github.io/regolith-site-r16/

We'd love any feedback you have to share about what you prefer in 1.6 over 2.0.  :peace_symbol:
