### ISSUE TITLE
Problem installing from repositories on Ubuntu 22.04

### ISSUE THREAD

**Issue by andy47** [regolith-linux/regolith-desktop#650]
I figure that I'm doing something wrong so any help is appreciated. But I can't install `regolith-desktop` after following the installation instructions - https://regolith-desktop.com/#get-regolith-20

**Describe the bug**

I have a fresh install of Ubuntu 22.04.

I followed the instructions on https://regolith-desktop.com/#get-regolith-20 but `sudo apt install regolith-desktop` returns an error;

`E: Unable to locate package regolith-desktop`

**To Reproduce**

I have a file called `regolith-archive-keyring.gpg` in `/usr/share/keyrings`
I have a file called `regolith.list` in `/etc/apt/sources.list.d`

I have run `sudo apt update`

When I type:

    $ sudo apt install regolith-desktop

I get this output;

    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    E: Unable to locate package regolith-desktop

**Expected behavior**
I'm expecting the apt install to work.

**Screenshots**

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: [ISO/PPA] - Regolith package repository at https://regolith-desktop.io/
 - Regolith Version: [e.g. 1.4] - 2.0
 - PPA url: [default: ppa:regolith-linux/release] - https://regolith-desktop.io/
 - Host OS (for PPA): [e.g. Ubuntu 20.04] - Ubuntu 22.04

**Additional context**

**Comment by kgilmer** [comment]
Hmm, do you see any errors in the terminal after running `sudo apt update`?  What is the contents of `/etc/apt/sources.list.d/regolith.list`?  What does `cat /etc/lsb-release` say?

**Comment by andy47** [comment]
Thanks for the quick response. Everything looks good, but to answer your questions;

```
andy47@conina ~ [100]> cat /etc/apt/sources.list.d/regolith.list
deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy main
```
and
```
andy47@conina ~> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
```
I appear to be getting something from the Regolith apt sources because I can see at least one regolith package in my cache;

```
andy47@conina ~> apt-cache search regolith
regolith-control-center-dev - utilities to configure the Regolith desktop
```

**Comment by andy47** [comment]
Could this have anything to do with the 'arch'? We specify `amd64` in `/etc/apt/sources.list.d/regolith.list` but I'm running in a VM on Apple Silicon and the `arch` command returns `aarch64`.

**Comment by andy47** [comment]
that was it. I changed `/etc/apt/sources.list.d/regolith.list` to;

```
deb [signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.io/release-ubuntu-jammy-arm64 jammy main
```
After an `sudo apt update` I can now `sudo apt install regolith-desktop`
