### ISSUE TITLE
i3xrocks focused window name shows CSS for workspace name

### ISSUE THREAD

**Issue by smokeythemonkey** [regolith-linux/regolith-desktop#652]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
i3xrocks blocklet focused window name displays the css instead of the workspace name. Correct information for a focused window is shown.

**To Reproduce**
Click in an empty workspace

**Expected behavior**
Expect the workspace number/name to be shown without CSS 

**Screenshots**
![image](https://user-images.githubusercontent.com/45724383/174126916-71613980-92e9-4983-a774-31bd96061089.png)

![image](https://user-images.githubusercontent.com/45724383/174127323-1c07c6fe-3177-467a-acb1-6d303aa584ad.png)

**Configuration file(s)**
Standard config files, fresh upgrade from 21.10 and regolith 1.6 as per instructions.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 2.0
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Pop!_OS 22.04

**Additional context**

**Comment by kgilmer** [comment]
@ferdinandyb is this something you could look into?

**Comment by ferdinandyb** [comment]
Just to confirm, so this was not an issue in 1.6, but is one in 2.0?

 @kgilmer The xml escaping we added a few days back was only pushed to 2.0 I guess?

**Comment by smokeythemonkey** [comment]
Yup 2.0, upgraded yesterday and is the first time I've noticed on both my personal and work PCs

**Comment by ferdinandyb** [comment]
Just a note, that what the update does currently, is that it doesn't show anything for an empty workspace, instead of duplicating the workspace name.

**Comment by kgilmer** [comment]
Fantastic, excellent work @ferdinandyb !

**Comment by ferdinandyb** [comment]
@smokeythemonkey Has this issue gone away after an upgrade to the latest version of Regolith?

**Comment by smokeythemonkey** [comment]
Yeah, it's fixed. Much appreciated!

**Comment by ferdinandyb** [comment]
Great!
