### ISSUE TITLE
PrtSc does not function on Regolith 2 / Ubuntu Jammy

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#653]
[reported by user in slack]

**Comment by williamgrimes** [comment]
Is this a duplicate issue?

https://github.com/regolith-linux/regolith-desktop/issues/648

**Comment by kgilmer** [comment]
Yes seems so

**Comment by ferdinandyb** [comment]
In that case it shouldn't we close?

**Comment by ferdinandyb** [comment]
I'm closing it :)
