### ISSUE TITLE
Changing look, causes font issues

### ISSUE THREAD

**Issue by csgillespie** [regolith-linux/regolith-desktop#656]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

The slack link doesn't work. It just redirects.

**Describe the bug**

Fonts on google-chrome tabs are horrid

**To Reproduce**

```
# Tried other looks, refreshing and restarting
# Tried apt update / upgrade
regolith-look set nord
```

**Expected behavior**

A nicer font.

**Screenshots**

![2022-06-20_14-39](https://user-images.githubusercontent.com/1267747/174614669-c733fa20-9c31-4c94-a8e8-7426c7c69ae9.png)

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: apt-get
 - Regolith Version: 2.1
 - PPA URL: https://regolith-release-ubuntu-jammy-amd64.s3.amazonaws.com jammy InRelease
 - Host OS (for PPA): 22.04

**Additional context**

**Comment by kgilmer** [comment]
Hi @csgillespie , the default look is designed to require minimal dependencies.  So, we reduce font usage to achieve this.  You are free to override the default font with an Xresource override (`gtk.font_name`) or [try another look](https://regolith-desktop.com/docs/using-regolith/configuration/#looks) that may look better to you.  I've updated the old site to no longer redirect.

**Comment by st--** [comment]
I've got the same issue and this doesn't seem resolved to me. The default look has the standard Ubuntu font that looks fine. All the other regolith looks I've tried all change to this weird monospace font. Why not keep the default font?

What would I have to do to override the Xresources to use the default font ?
