### ISSUE TITLE
Some programs don't have active window border visible (Firefox, file browser)

### ISSUE THREAD

**Issue by TymekDev** [regolith-linux/regolith-desktop#657]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Firefox does not have active window borders visible. "Split direction border" (not sure how is it called) is also not visible. See the recording.

**To Reproduce**
Launch Firefox using Regolith Desktop 2.0. Compare with other windows, e.g. terminal.

**Expected behavior**
I expected behavior to be same across the windows, not differing based on what program runs in a given window.

**Recording**
![output](https://user-images.githubusercontent.com/38053499/174769674-34784dfe-b65c-448f-95da-28195be6ae29.gif)

**Installation Details**

 - Regolith Install Type: apt repo
 - Regolith Version: 2.0
 - apt repo url: `https://regolith-desktop.io/release-ubuntu-focal-amd64 focal main`
 - Host OS: Ubuntu 20.04.4

**Additional Context**
While filing this issue I have noticed that it is not exclusive to Firefox. File browser shares the same behavior.

**Comment by TymekDev** [comment]
@natejlong it is the same for me. Restarting Firefox after enabling title bar does the trick. Thanks!

**Comment by kgilmer** [comment]
Looks like this is resolved, closing.
