### ISSUE TITLE
Can't find the config files of Regolith-desktop in Ubuntu 22.04

### ISSUE THREAD

**Issue by Gauthamsudo** [regolith-linux/regolith-desktop#659]
I am currently using Ubuntu 22.04 and I got to know about Regolith-desktop. When I installed it, Some of it's config files are missing.  The `i3` folder, `picom` folder and other folders were missing. The only folder was `flags`.  I searched if Picom is in my PC, So I typed `which picom`, Which resulted a folder and The following folder is missing. I don't know it's problem and I am confused. I am thinking of It as a Bug or something of the new version of Regolith2. 

I was really interested in picom and things but Now I don't know where Picom is. If anybody have any solutions to it, Please mention.
Thank you.

**Comment by kgilmer** [comment]
Hi @Gauthamsudo , please see the intallation instructions for Regolith here: https://regolith-desktop.com/  If you have specific problems with the install please re-open the issue with any error messages or behavior you notice.  To ensure the picom compositor is installed, run: `sudo apt install regolith-compositor-picom-glx` and log back into your session.
