### ISSUE TITLE
Impossible to bind some Super+o?

### ISSUE THREAD

**Issue by cafeoh** [regolith-linux/regolith-desktop#66]
As title says, I can't seem to bind Super+o, My i3 config file contains this :

```
 71 # resize focused window
 72 bindsym $mod+y resize shrink width 10 px or 10 ppt
 73 bindsym $mod+u resize grow height 10 px or 10 ppt
 74 bindsym $mod+i resize shrink height 10 px or 10 ppt
 75 bindsym $mod+o resize grow width 10 px or 10 ppt
```

And every bind except $mod+o works. I'm on an AZERTY keyboard (not that it should matter in that instance), but there's no other bind to $mod+o in that file, and this has always worked fine in i3. I couldn't find a piece of software included in regolith that would capture that bind (not even sure capturing key presses is a thing in x11 :man_shrugging: )

Any idea on what could be causing it?

Thanks!

Cafe

**Comment by kgilmer** [comment]
Whoa @cafeoh yeah I see what you mean.  I spent some time trying to determine what could be capturing that key event, trying to bind via code instead of keysym but was unable to get Super+o to work for me either.  Given that neither keysym or keycode work, I'm guessing that something else is intercepting it before it gets to i3, but am unsure of what it could be at this point.  :question:

**Comment by kgilmer** [comment]
I tried [following this](https://unix.stackexchange.com/questions/261371/how-do-i-find-out-what-program-owns-a-hotkey) but was unable to find anything via `journalctrl` that was bound to Super+o.  It's a bit confusing though so I may have gotten it wrong.

**Comment by cafeoh** [comment]
Hmm, I tried doing the same thing mentioned in that thread just now, and suddenly my `Super+o` bind works. :thinking: 

I guess I won't close the issue myself as it seems to happens to you too, but if it happens again I'll try to do the manips again and report here if I find anything new!

**Comment by kgilmer** [comment]
So weird!  Does the "fix" survive reboot or logging out of the session?

**Comment by cafeoh** [comment]
Yup, problem seems to be gone even after a reboot. I can't tell what exactly changed, I don't think I did any related change to the i3 config file either. I'll ping you if I get an idea!

**Comment by kgilmer** [comment]
Assuming fixed.  Please reopen if you continue to have problems.
