### ISSUE TITLE
ARM64 repos not working?

### ISSUE THREAD

**Issue by dragon99919** [regolith-linux/regolith-desktop#660]
- [ + ] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ + ] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [  -  ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
ARM64 repo doesn't seem to be working.

**To Reproduce**
Put Raspberry Pi OS (Debian based) or Ubuntu 22.04 on microSD card, and install it onto raspberry. When trying to add Regolith repos (the "Register the Regolith public key to your local" thing), something strange happens (see screenshot) and all letters are bugged up, and this happens until you reboot. Doing later steps doesn't seem to do much either. Also, I know - it appears I'm launching some script that does it, but this script literally is copy-pasted step from the site, and copied do SD card (I initially though I'm maybe making some sort of typo).

**Expected behavior**
An install occurs.

**Screenshots**
![289773431_3206284736253975_1654292899002050672_n](https://user-images.githubusercontent.com/15349744/175839258-eeced980-f2bd-4bbf-be24-7e68e6a63352.jpg)

**Installation Details**
 - Regolith Install Type: from steps on site
 - Regolith Version: 2.0
 - PPA url: from steps on site
 - Host OS (for PPA): Ubuntu 22.04, Rasperry Pi OS Bullseye

**Comment by kgilmer** [comment]
Hi @dragon99919 , thanks for your detailed bug report!  I've updated the installation directions such that the binary data is not printed to the screen.  I've just tested that I'm able to install Regolith 2.1 beta 1 on a RP4 using the updated instructions.  Kindly reopen if you continue to have problems.
