### ISSUE TITLE
Ubuntu 22.04: Cannot isntall (No Valid OpenPGP / Unable to locate regolith-desktop)

### ISSUE THREAD

**Issue by antoinewaugh** [regolith-linux/regolith-desktop#667]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

I am finding that the Regolith download instructions to not work on Ubuntu 22.02

```
~$ chmod 755 install-release-ubuntu-22.04-amd64.txt 
~$ ./install-release-ubuntu-22.04-amd64.txt 

gpg: no valid OpenPGP data found.
deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy main
Hit:1 http://au.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease              
Hit:3 http://au.archive.ubuntu.com/ubuntu jammy-backports InRelease            
Ign:4 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease   
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease               
Hit:6 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Ign:4 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease   
Ign:7 https://ppa.launchpadcontent.net/regolith-linux/release/ubuntu jammy InRelease
Ign:4 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease
Err:8 https://ppa.launchpadcontent.net/regolith-linux/release/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.52 443]
Err:4 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 104.238.213.207 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/regolith-linux/release/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Regolith Desktop can be installed by executing: sudo apt install regolith-desktop

~$: sudo apt install regolith-desktop


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package regolith-desktop

```

**To Reproduce**

```
~$ ./install-release-ubuntu-22.04-amd64.txt 
sudo apt install regolith-desktop

```
or
```
wget -qO - https://regolith-desktop.io/regolith.key | \
gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null

echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy main" | \
sudo tee /etc/apt/sources.list.d/regolith.list

sudo apt update
sudo apt install regolith-desktop
```

**Expected behavior**

Regolith should install but instead we see:

```
E: Unable to locate package regolith-desktop

```

**Installation Details**
 - Regolith Install Type: [ISO/PPA]: PPA
 - Regolith Version: [e.g. 1.4]: 2.1
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 20.04]: 22.04

**Additional context**

**Comment by antoinewaugh** [comment]
I saw on a slack message that current workaround is changing the url to `.org` in `/etc/apt/sources.list.d/regolith.list`.

This allowed the install to proceed.

```
XPS-15-9520:~$ cat /etc/apt/sources.list.d/regolith.list 
deb [trusted=yes arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main
```

**Comment by kgilmer** [comment]
The service provided that issued the cert has not responded to the ticket, breaching SLA.  I have opted to switch the instructions on the website to use the ".org" version, of which I control the cert because I issued it myself.  Going forward we'll continue with regolith-desktop.org for the debian repo and at some point when the .io domain is under control we'll do something else with that.  Sorry for the confusion.

Please re-open this ticket if there are further problems with updating/installing.

**Comment by antoinewaugh** [comment]
Great- thanks Ken




Antoine Waugh, Director

***@***.******@***.***>

+61 404 157 246



[X]



________________________________
