### ISSUE TITLE
i3 config error on logout not reproducible on i3 reload

### ISSUE THREAD

**Issue by p3k** [regolith-linux/regolith-desktop#669]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

On login I get an i3 alert about errors in the config – nevertheless, the settings seem to be applied correctly.

![image](https://user-images.githubusercontent.com/16631/180497049-b36494a6-3b93-4cce-832d-e5941adf2439.png)

Furthermore, any later `i3-msg reload` or `i3-msg restart` does not produce the error alert.

I assume the problem is because of quotation marks:

![image](https://user-images.githubusercontent.com/16631/180494657-1e043115-7f55-4780-9b30-c7d5816bd928.png)

**Steps to reproduce the behavior**

Use something like the following in `Xresources` and the i3 config, resp.

```h
! ~/.config/regolith2/Xresources
#define q(x) #x
#define quote(x) q(x)
#define text_font quote(UbuntuCondensed 10)
#define glyph_font quote(BitstreamVeraSansMono Nerd Font 12)
#define workspace_name(index, color) index:<span> </span><span font_desc="UbuntuCondensed 10">index</span> <span font_desc="BitstreamVeraSansMono Nerd Font 12" foreground=color></span><span> </span>
#define color_yellow #f99b11

i3-wm.workspace.01.name: workspace_name(1, quote(color_yellow))
```

```sh
# ~/.config/regolith2/i3/99_custom
workspace "$ws1" output $primary
```

**Expected behavior**

There either should not be an error displayed after login, or it should be displayed all the time, i.e. when reloading / restarting i3, too.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 2 / 4.2.0-1regolith (prerelease)
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 22.04

**Additional context**

As I mentioned before I assume there is an issue about the quotation marks – would be glad if somebody could help me solve this.

**Comment by p3k** [comment]
i was wrong regarding the settings being correctly applied, must have been by chance or randomly that the workspaces appear on the desired monitor output. 

also, the issue is indeed reproducible: i have to reload the `Xresources` file before restarting i3, though:

```sh
xrdb -remove
xrdb -merge ~/.config/regolith2/Xresource
i3-msg restart
```

anyway, the root cause obviously are quotation marks, i.e. an undesired premature ending of a quoted string:

```sh
"1:<span> </span><span font_desc='UbuntuCondensed 10'>9</span> <span font_desc='BitstreamVeraSansMono Nerd Font 12' foreground="#878787"></span><span> </span>" output DP-3
                                                                                                                               ↑       ↑
                                                                                                      these quotation marks should be escaped or replaced by single ones
```

does anyone have the missing clue for me how to achieve either escaping the quotation marks or replacing them by single ones, e.g. like this:

```sh
"1:<span> </span><span font_desc='UbuntuCondensed 10'>9</span> <span font_desc='BitstreamVeraSansMono Nerd Font 12' foreground='#878787'></span><span> </span>" output DP-3
```

here are the corresponding lines of my config again (slightly modified, i already replaced some double with single quotation marks):

```h
! ~/.config/regolith2/Xresources
#define workspace_name(index, color) index:<span> </span><span font_desc='UbuntuCondensed 10'>index</span> <span font_desc='BitstreamVeraSansMono Nerd Font 12' foreground=color></span><span> </span>
#define color_yellow #f99b11
i3-wm.workspace.01.name: workspace_name(1, quote(color_yellow))
```

```sh
# ~/.config/regolith2/i3/99_custom
workspace "$ws1" output $primary
```

it basically boils down to the question: how can i output the `color` variable in the macro with escaped or single quotation marks?

**Comment by p3k** [comment]
i gave up too early, with the help from [so thread about the c preprocessor](https://stackoverflow.com/a/14731887) i was able to solve this puzzle:

```h
! ~/.config/regolith2/Xresources
#define apos '
#define q2(a, x, b) a##x##b
#define q1(a, x, b) q2(a, x, b)
#define quote(x) q1(apos, x, apos)
#define workspace_name(index, color) index:<span> </span><span font_desc='UbuntuCondensed 10'>index</span> <span font_desc='BitstreamVeraSansMono Nerd Font 12' foreground=color></span><span> </span>
#define color_yellow #f99b11

i3-wm.workspace.01.name: workspace_name(1, quote(color_yellow))
```

**Comment by kgilmer** [comment]
You're a preprocessor power user @p3k !  Glad you got the issue resolved, closing.
