### ISSUE TITLE
Wallpaper no longer displaying correctly.

### ISSUE THREAD

**Issue by MoreThanLuck** [regolith-linux/regolith-desktop#67]
Hey there! Sorry I've been away for a bit, got busy with work. Hope to contribute more now. 

I'd patched in a custom wallpaper by revising the filepath in the config file and the wallpaper refresh shell script. However, even though the filepath is the same and those files are unedited, my wallpaper no longer displays, instead showing black.

**Comment by kgilmer** [comment]
Hi @MoreThanLuck , well the wallpaper configuration has changed.  We no longer use `feh` executed from the i3 config but rather use gnome so that users can more easily configure it.  You may need to ensure that your Regolith packages are up to date as well.

**Comment by MoreThanLuck** [comment]
Gotcha, I figured I was just out of the loop. I set it in gnome which seems to have resolved the issue. 

As far as updating, running off of the PPA that's no different than just apt-get update and upgrade, right?

**Comment by kgilmer** [comment]
That's correct.  PPAs are Ubuntu's way of letting third-parties such as Regolith to add themselves as package providers.  Once you add the PPA, the package updates are done as if they were stock Ubuntu packages.

**Comment by MoreThanLuck** [comment]
Got it, thanks! I should be up to date in that case, running on the stable branch.
