### ISSUE TITLE
Apt issue with untrusted certificates after adding 2.1 regolith repo

### ISSUE THREAD

**Issue by gigatexal** [regolith-linux/regolith-desktop#677]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

```
sudo apt update
Hit:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease                            
Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease                          
Get:4 https://download.docker.com/linux/ubuntu jammy InRelease [48,9 kB]                     
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease                             
Ign:6 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease  
Ign:6 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease
Ign:6 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease
Err:6 https://regolith-desktop.io/release-ubuntu-jammy-amd64 jammy InRelease                 
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 104.238.213.207 443]
Fetched 48,9 kB in 9s (5.671 B/s)                                                            
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://regolith-desktop.io/release-ubuntu-jammy-amd64/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 104.238.213.207 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```
I added the 2.1 repo copying and pasting from here: https://regolith-desktop.com/#get-regolith-21

**To Reproduce**

Follow steps https://regolith-desktop.com/#get-regolith-21 to add repos, run `apt update` get failure message about certificate not being trusted

**Expected behavior**

Be able to get updated packages without certificate issue.

**Screenshots**

See code block above.

**Configuration file(s)**

This is not related to i3 config.

**Installation Details**
 - Regolith Install Type: 2.1 ppa
 - Regolith Version: 2.1
 - PPA url: https://regolith-desktop.io/release-ubuntu-jammy-amd64/dists/jammy/InRelease
 - Host OS (for PPA): [e.g. Ubuntu 22.04]

**Comment by jjsearle** [comment]
Change regolith-desktop.io to regolith-desktop.org.

The instructions have been updated on the website.

**Comment by gigatexal** [comment]
this solves the issue, thanks!!!
