### ISSUE TITLE
Can't figure out keybindings since upgrade to 2.1

### ISSUE THREAD

**Issue by Whyglobaleyes** [regolith-linux/regolith-desktop#679]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I can't figure out how to customise keybindings in the config files since upgrading to 2.1. The previous ones from 1.6 just don't seem to run at all. I suspect I'm getting something very basic all wrong but scratching my head to baldness.  
 
**To Reproduce**
1. Fresh install of Debian (dual boot with the <Xubuntu 20/ Regolith 1.6> daily driver I want to retire) :: Install regolith 
3. Made a few changes to keybindings using the visual settings dialogue - but I can't figure out how to do anything other than launch a programme 
4. Tried to copy my previous `[unmounted]$HOME/.config/regolith/i3/config` file over to `$HOME/.config/regolith2/i3/config` (attached as config_1) ==> very disrupted system: had to boot back into the daily driver to rename the `regolith2/i3/config` file.
5. On a whim: created a `~/.config/regolith/i3/config` file alongside `~/.config/regolith2` directory  ==> no effect 
6. Edited the regolith2/i3/config file down to just 4 lines (attached as SHORT_conf) ==> no longer disrupted system but seemed to have no effect
7. Referred to: https://regolith-desktop.com/docs/using-regolith/configuration/#keybindings and https://github.com/regolith-linux/regolith-desktop/discussions/678 ==> reached the conclusion that I need to edit `$HOME/.config/regolith2/Xresources`, tried searching for i3 info however I can't figure out what syntax to use instead of `i3-wm.mod: Mod1`
Thanks in advance for any guidance.

**Expected behavior**
Use config files to set keybings

**Screenshots**

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: ppa
 - Regolith Version: 2.1
 - PPA url:  https://regolith-desktop.org/release-debian-bullseye-amd64
 - Host OS (for PPA): uname -rv: `5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23)` = Debian XFCE

**Additional context**
[SHORT_conf.txt](https://github.com/regolith-linux/regolith-desktop/files/9221457/SHORT_conf.txt)
[config_1.txt](https://github.com/regolith-linux/regolith-desktop/files/9221484/config_1.txt)

**Comment by ferdinandyb** [comment]
See the relevant part of the documentation: https://regolith-desktop.com/docs/using-regolith/configuration/#i3-features

In short, Regolith 2 implements partials and user configs should be placed in `~/.config/regolith2/i3/config.d/`

**Comment by Whyglobaleyes** [comment]
@ferdinandyb Thank you - that did it. 

Can't tell you how silly I feel for not reading the manual. Actually I did read that page and the one about staging configs but a lot of it confused me, I still don't really grok it but it's working. There's a few keybindings that I can't get right (some have become new default bindings) and I'm sure that I'll make more mistakes but - I'm ready to ditch the Ubuntu installation ! 

best wishes

**Comment by ferdinandyb** [comment]
No worries. I recommend you join the slack, you'll get faster feedback there (and now we have github discussions as well).
