### ISSUE TITLE
Window shadows display from other monitors 

### ISSUE THREAD

**Issue by JohnGebbie** [regolith-linux/regolith-desktop#68]
Just a nitpick.

I have two monitors (they are different sizes). The drop shadows from the left monitor display at the left edge of the right monitor. The bar at the bottom (with the time and window numbers) does the same.
![Screenshot from 2019-07-12 17-30-14](https://user-images.githubusercontent.com/43242915/61144291-0838db80-a4c4-11e9-831b-56c2cbc0ede9.png)
![Screenshot from 2019-07-12 17-45-35](https://user-images.githubusercontent.com/43242915/61144481-82696000-a4c4-11e9-8093-5bcdaff38361.png)

**Comment by kgilmer** [comment]
Yeah I have noticed this a well.  I'm guessing that this is related to Compton, but could be wrong.  This issue may be relevant: https://github.com/chjj/compton/issues/137

**Comment by leosunmo** [comment]
Not sure how to fix the window from casting shadows across screen borders, but we should be able to at least disable shadows entirely for the i3 bar. We'd never want a shadow cast by that anyway, correct?

Looking at the Compton config we should be able to exclude it using the `shadow-exclude` option. Regolith already has a few windows in that list but I'm guessing that `"class_g = 'i3-frame'"` doesn't include the bottom bar?

**Comment by kgilmer** [comment]
#79 might fix the shadow thing.  

Regarding shadowing the bottom bar, yes in fact that's intentional.  I find it gives a subtle hint between the bar and terminal when a terminal is full screen.  Without out it, visually there is nothing to separate the bar from the terminal window and IMHO it's better with the shadow.

**Comment by leosunmo** [comment]
Ah I see what you mean with the bottom bar.

I just hooked up an external display and was able to solve John's problem by using `xinerama-shadow-crop = true;`. Doesn't seem to be any drawback in enabling that by default!

**Comment by leosunmo** [comment]
@kgilmer https://github.com/regolith-linux/regolith-compton-config/pull/1

**Comment by leosunmo** [comment]
This change is now in `regolith-unstable`.

**Comment by leosunmo** [comment]
Both me and Ken have been running this fix for a little while and there's been no problems so far. Looks like a fairly low-impact change so will push this to stable soon.

**Comment by kgilmer** [comment]
Package has been promoted to `regolith-stable`.  Please re-open if a problem is found.  Thanks @leosunmo !
