### ISSUE TITLE
Screenshot shortcuts are not working

### ISSUE THREAD

**Issue by JohannesPertl** [regolith-linux/regolith-desktop#681]
Using `Print` key or any combination set in keyboard shortcuts does nothing. Executing `gnome-screenshot` via terminal or using the Screenshot GUI tool works though.

**To Reproduce**
Steps to reproduce the behavior: Press `Print`.

**Expected behavior**
A screenshot should be taken in the `Pictures` folder.

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 2.1

**Comment by ferdinandyb** [comment]
Closing because of duplicate issue, please see #648 for a few workarounds until we have a proper fix.
