### ISSUE TITLE
Can not use custom keyboard layout for login screen

### ISSUE THREAD

**Issue by floratmin** [regolith-linux/regolith-desktop#682]
I have an individual keyboard. The keyboard is set in /etc/default/keyboard. I also set the configuration  in the gnome settings window under keyboard input sources and added a user defined custom layout. In the gnome settings display it gets also displayed in the right way. But I can not use this layout for logging in.
I also tried to run "sudo dpkg-reconfigure keyboard-configuration", "sudo setupcon -v" and "sudo update-initramfs -u" but none made any difference. Before upgrading Ubuntu to 22.04 and Regolith to 2.0 the keyboard layout was working on the login screen.

**To Reproduce**
Create own keyboard definition files and dpkg-reconfigure keyboard-configuration.

**Expected behavior**
Can login using layout of custom keyboard.

**Configuration file(s)**
Added in config these two lines:

focus_follows_mouse yes
exec sh setxkbmap -layout us,us -variant ansi-qgmfwy,ansi-qgmfwy-testing -option shift:both_caps_lock_cancel,grp:ctrls_toggle

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 2.1
 - PPA url: Followed instructions from homepage
 - Host OS (for PPA): Ubuntu 22.04

**Comment by kgilmer** [comment]
Hi @floratmin , unless you've changed it, since you installed via repository, the login screen is not part of Regolith.  If you're running the ISO version then we use LightDM with the Slick greeter.  Otherwise the login screen is managed by the distro.  I would check Ubuntu 22.04 docs if there has been some change to how this is achieved.  Please LMK if you find a solution to your problem. :)

**Comment by floratmin** [comment]
Hello @kgilmer, thank you for hinting into the right direction. I added to the file `/etc/lightdm/lightdm.conf.d/10_regolith.conf` the line `display-setup-script=setxkbmap -layout us,us -variant ansi-qgmfwy,ansi-qgmfwy-testing -option shift:both_caps_lock_cancel,grp:ctrls_toggle` which resolved my problem.
