### ISSUE TITLE
keyboard layout indicator

### ISSUE THREAD

**Issue by vzaliva** [regolith-linux/regolith-desktop#69]
I am using two languages and switch between 2 keyboard layouts.
It works but I am missing the current layout indicator in the toolbar (like in standard Ubuntu).

**Comment by kgilmer** [comment]
Hi @vzaliva !  You can try this i3blocks extension to show your current keyboard layout in the bar: https://github.com/vivien/i3blocks-contrib/tree/master/key_layout.

After checking this out and putting the script somewhere, add the code mentioned in the readme into `\etc\i3blocks.conf`.

**Comment by PickingUpPieces** [comment]
@kgilmer First of all, many thanks for your efforts. I love regolith :heart:  

One question to i3blocks: Since you want the setup as simple as possible for users, is it intended to add more possible blocks to i3blocks from regolith side? That users can activate certain blocks which are customized for regolith or do you want to keep it there as clean as possible and users configure the i3bar themselves? :)

**Comment by kgilmer** [comment]
Hi @PickingUpPieces , thanks glad you're liking Regolith!  Ideally everything in Regolith would be easy and consistent to configure from the control panel.  Unfortunately gnome-control-center is not open to extension, and the effort to create and maintain a fork is not sometime I can take on at this point.  I am currently searching for other ways in which configuration UIs can be created that are both consistent w/ the UI as a whole and as bullet-proof as gnome-control-center is.  I don't have any answers yet.  In any case, it is pretty straightforward to add blocklets to the bar by updating the `/etc/i3blocks.conf` file.  Please keep in mind this file is about to change however with the introduction of Xresource-based styling as described in #24.

**Comment by vzaliva** [comment]
it does not work. After configuring the extension it shows in toolbar list of configured layouts but it does not change when I switch keyboard languages via hotkey. The list shown in my case is: `is,ru,us (,mac,)`

**Comment by mochja** [comment]
@kgilmer could I help here somehow? I really miss layout indicator.

**Comment by leosunmo** [comment]
I had a similar problem, solved it with https://github.com/leosunmo/dotfiles/blob/master/i3blocks/i3blocks/key_layout2

Not at my computer so not sure if I modified it (not sure my dotfiles repo is up to date) but give it a try. 

I set it to interval=2 in the i3blocks config.

**Comment by leosunmo** [comment]
Just confirmed with the latest update (i3xrocks, XResources etc.) that the `key_layout2` script works fine.

**Comment by mochja** [comment]
@leosunmo, thanks!

I've updated your the script to monitor changes

``` bash
#!/usr/bin/env bash

gsettings get org.gnome.desktop.input-sources mru-sources | sed -r "s/\S*\s'([^']+).*/\1/"
gsettings monitor org.gnome.desktop.input-sources mru-sources | sed -u -r "s/\S*\s\S*\s'([^']+).*/\1/"
```

with this script set `interval=persist` in i3blocks config.

**Comment by leosunmo** [comment]
Ah excellent. That was in my list to fix. Didn't know about the monitor command.

**Comment by kgilmer** [comment]
@vzaliva did the suggestions provided by @mochja  and @leosunmo resolve your issue?

**Comment by vzaliva** [comment]
@kgilmer I am little lost. There are several suggestions. I will appreciate if somebody can provide me with step-by-step instructions. Thanks!

**Comment by kgilmer** [comment]
Hi @vzaliva , well I don't have multiple keyboard layouts so cannot be sure this is right but I was able to get something working from the steps above.  Here it is:
1. create a file `~/.config/i3xrocks/key_layout2` in your favorite text editor.  Set it to the contents from @mochja 's changes:
```
#!/usr/bin/env bash

gsettings get org.gnome.desktop.input-sources mru-sources | sed -r "s/\S*\s'([^']+).*/\1/"
gsettings monitor org.gnome.desktop.input-sources mru-sources | sed -u -r "s/\S*\s\S*\s'([^']+).*/\1/"
```
2. Save the file, and set it to have executable permissions: `chmod a+x ~/.config/i3xrocks/key_layout2`
3. Update your i3xrocks config to reference the new "blocklet" by adding this in, depending on in what order you want your info to render on the bar.  I put it at line 31:
```
# Keyboard layout
# See https://github.com/regolith-linux/regolith-desktop/issues/69
[key_layout2]
label=K
interval=persist
```
4. Reload i3 or log back into your session and you should see some new info on your bar.  For me, it was just "K@a(ss) []" which doesn't make any sense to me, but hopefully it will to you.  @mochja or @leosunmo , if this is not the expected output, any ideas on what could be wrong?

**Comment by mochja** [comment]
@kgilmer What output you get from

```
gsettings get org.gnome.desktop.input-sources mru-sources
```

**Comment by kgilmer** [comment]
Thanks for the quick response @mochja.  Here's what I see:
```
$ gsettings get org.gnome.desktop.input-sources mru-sources
@a(ss) []
```

**Comment by leosunmo** [comment]
For me it returns what I expect (us and swedish layouts, active is always first in the list).
```
$ gsettings get org.gnome.desktop.input-sources mru-sources
[('xkb', 'us'), ('xkb', 'se')]
```

**Comment by vzaliva** [comment]
Thanks! This works. I recommend this to be integrated into distribution. This solution works for me.
