### ISSUE TITLE
pgAdmin looking for system tray plug in

### ISSUE THREAD

**Issue by chaseydog** [regolith-linux/regolith-desktop#70]
I'm just learning about i3 WM and Regolith looks like a great place to start. I have hit my fist snag though. I installed pgAdmin 4 but when I launch it I get a popup window that states "Note: Installing a system tray plugin will prevent this window from being shown" To make matters worse there doesn't seem to be a way to dismiss the popup. Is there a system tray plugin for Regolith?
![pgAdmin](https://user-images.githubusercontent.com/30329469/61172916-b04cb400-a559-11e9-8bf2-020dc7239eb1.png)

**Comment by kgilmer** [comment]
Hi @chaseydog , glad you're liking Regolith!  A few people have asked about enabling the tray so I've created a short howto that should cover it: https://regolith-linux.org/howto.html#i3-tray

If that works for you please close the ticket, or let me know if you get stuck.

**Comment by chaseydog** [comment]
Thanks. The howto was very helpful and solved my issue.

**Comment by JandroMejia97** [comment]
@kgilmer the link no longer available.

**Comment by kgilmer** [comment]
Sorry for the confusion @JandroMejia97 , it has moved here: https://github.com/regolith-linux/regolith-desktop/wiki/HowTo:-Enable-an-Icon-Tray-in-the-Bar
