### ISSUE TITLE
Using greenclip with regolith / rofi

### ISSUE THREAD

**Issue by fjellvannet** [regolith-linux/regolith-desktop#703]
I have used regolith as my primary working desktop for the past two years, and got used to https://github.com/erebe/greenclip in regolith, which I installed as described here:

https://dev.to/funkyidol/regolith-linux-my-descent-into-mouse-less-navigation-17dc

After several clean installs I didn't manage to make it work in regolith 2.1. I guess the reason is that the old rofi-command doesn't work anymore. When I type rofi in my terminal in ubuntu 22.04 / regolith 2.1 the command is not found, whereas it is found in regolith 1.6 based on ubuntu 21.04.

Could you tell me what happened to the rofi command or what other command can be used now instead to run greenclip? Thx in advance :D

**Comment by fjellvannet** [comment]
You can just install rofi yourself (apt install rofi), and then greenclip works like before

**Comment by ferdinandyb** [comment]
Regolith moved to `ilia` instead of `rofi`, very likely you could get it to also work with greenclip.

**Comment by fjellvannet** [comment]
I made it work in ilia, awesome (i'll post how soon).

Just one question - in the ilia - p textlist mode, how can I make it not show any icons? @ferdinandyb

**Comment by fjellvannet** [comment]
The config that works for me using greenclip with ilia is:

```
# Greenclip set $greenclip /path/to/file/greenclip bindsym $mod+Shift+v exec $greenclip print | ilia -p textlist -l "Clipboard history" | xargs -r -d'\n' -I '{}' $greenclip print '{}'
exec --no-startup-id $greenclip daemon
```

**Comment by ferdinandyb** [comment]
Thanks for sharing! As for your question, @kgilmer is more likely to know the answer.

**Comment by kgilmer** [comment]
@fjellvannet please file a feature request to disable icons for textlist here: https://github.com/regolith-linux/ilia/issues

There is a way to disable *all* icons but not a way to disable them only in the textlist page.

**Comment by kgilmer** [comment]
I have been looking for better clipboard management @fjellvannet , I'll try out your new integration!

**Comment by fjellvannet** [comment]
https://github.com/regolith-linux/ilia/issues/42

Feature-request submitted :) For me this integration with greenclip works perfectly fine. A clipboard manager is such a central part of my workflow that I just can't stand being without it. greenclip is simple and does exactly what I need. Unfortunately (as far as I know), it doesn't support e.g. direct copy-pasting of images. But what you want in 95 % of the cases is just reuse of text-clipboards, which works fine.

**Comment by ferdinandyb** [comment]
On Sun Aug 21, 2022 at 11:17 PM CEST, fjellvannet wrote:
> Feature-request submitted :) For me this integration with greenclip works perfectly fine. A clipboard manager is such a central part of my workflow that I just can't stand being without it. greenclip is simple and does exactly what I need. Unfortunately (as far as I know), it doesn't support e.g. direct copy-pasting of images. But what you want in 95 % of the cases is just reuse of text-clipboards, which works fine.

It actually does, but has a size limit. In my experience screenshots are
well within the limit always.

**Comment by fjellvannet** [comment]
I made it work in ilia, awesome (i'll post how soon).

Just one question - in the ilia - p textlist mode, how can I make it not
show any icons?

lør. 20. aug. 2022, 15:04 skrev Bence Ferdinandy ***@***.***>:
