### ISSUE TITLE
App Launcher not launching?

### ISSUE THREAD

**Issue by MoreThanLuck** [regolith-linux/regolith-desktop#71]
Hey Ken! I ran into a weird issue lately, where pressing `cmd` + `space` seems to launch the app launcher, but the program never fully deploys. It just opens up a translucent solarized-blue rectangle in the middle of the screen, but no search bar, no recent apps, etc. Any idea? Pretty sure I'm running on the latest version.

**Comment by kgilmer** [comment]
Hi @MoreThanLuck :smile: 

Are you using the `regolith-stable` or `regolith-unstable` PPA?  Nothing has been pushed to stable in a few weeks so I'm not sure of a specific change that could have caused this, although I have been making Rofi theme changes in unstable.  To ensure you're on the latest configuration, remove or move these files and re-login to have them freshly copied from baseline:
```
~/.config/i3-regolith/config
~/.Xresources-regolith
~/.Xresources.d
```

Let me know if that fixes Rofi for you...

**Comment by kgilmer** [comment]
This was a regression based on partially implemented Xresource configuration.  I've tested and it should be fixed now.  Kindly re-open if you still experience the issue after getting latest packages, and logging out of your session.

**Comment by MoreThanLuck** [comment]
Got it, thanks! Sorry, been swamped lately. Updating everything and then rebooting resolved the issue.
