### ISSUE TITLE
Two different cursors depending on window

### ISSUE THREAD

**Issue by p3k** [regolith-linux/regolith-desktop#715]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I see two different styles of cursors (pointer) depending on which window the mouse is hovering.

**To Reproduce**

1. `gsettings set org.gnome.desktop.interface cursor-theme Yaru-dark`
2. Hover over Firefox window → Yaru-dark cursor
3. Hover over Nautilus window → other cursor

**Expected behavior**
I should see the same cursor from the Yaru-dark theme, no matter which window is hovered.

**Screenshots**
![image](https://user-images.githubusercontent.com/16631/187483724-d0e2eef1-cbc3-4a5f-ad23-5dd5233ea4c0.png)

![image](https://user-images.githubusercontent.com/16631/187484054-552d9805-73ec-4b37-a5bc-522c5afc28ac.png)

**Configuration file(s)**
In `~/.config/regolith2/Xresources`:

```xres
Xcursor.theme: Yaru-dark
```

**Installation Details**
 - Regolith Install Type: ISO (?)
 - Regolith Version: 4.2.0-1regolith
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Ubuntu 22.04

**Comment by kgilmer** [comment]
I am unable to reproduce this on my pc.  I do not have Yaru icons available (debian testing) but tried Faba and Papirus-Dark and did not detect any cursor difference between firefox and nautilus.  My firefox is installed via deb, I wonder if you have a snap version installed?  As I recall users have to do something for snap apps to integrate with local gtk settings..

**Comment by tomasfrtala** [comment]
Try adding to your `~/.config/regolith2/Xresources` this line:
```
Xcursor.theme: Yaru
```
It helped me with a consistent cursor theme across applications. Ubuntu 22.04, Regolith 2.2

**Comment by p3k** [comment]
thanks @tomasfrtala, this works for me, too :)
