### ISSUE TITLE
Bar config not applying / remaining after reboot

### ISSUE THREAD

**Issue by shadowrylander** [regolith-linux/regolith-desktop#72]
Hello!
Quick question: to fix the status bar being so small on a 4K resolution display, I edited my bar font size from 13 to 15; however, it is not applying on login / restart. I symlinked the modified regolith i3 config to `~/.config/i3/config` and `~/.i3/config`, but it's still seemingly loading the default, though it states:
```
Binary i3 version:  4.16.1-non-git © 2009 Michael Stapelberg and contributors          
Running i3 version: 4.16.1-non-git (pid 1382)c to abort…)                              
Loaded i3 config: /home/shadowrylander/.config/i3-regolith/config (Last modified: Wed 17
 Jul 2019 10:40:13 PM EDT, 7401 seconds ago)                                           

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```
with the associated regolith file using:
```
# Configure the bar
bar {
  font pango:Source Code Pro Medium 15
  separator_symbol " "
  status_command i3blocks
  tray_output none

  colors {
      background $base03
      statusline $base1
      separator  $blue
#                        BORDER  BACKGROUND TEXT
      focused_workspace  $base02  $base02  $base2
      active_workspace   $base02  $base02  $base01
      inactive_workspace $base03  $base03  $base01
      urgent_workspace   $red     $red     $base3
  }
}
```
and it reloads every time I reload i3 using `mod - shift - r`.
How might I go about fixing this?

**Comment by kgilmer** [comment]
Hi @shadowrylander :smile:  Hmm, that's odd.  If I understand it your i3 config file changed work if reloading i3 from within a session but as soon as you logout and return a default version is loading?  Or your changes to `~/.config/i3-regolith/config` are being overwritten?

Here is the code that writes the config file on login: https://github.com/regolith-linux/regolith-gnome-flashback/blob/master/i3-gnome-flashback#L64-L69

It tests that `~/.config/i3-regolith/config` is a file.  I'm guessing that since you're using a symlink the test is failing and your symlink is being overwritten.  You could verify this by writing your actual file to `~/.config/i3-regolith/config` and see if the problem continues or not.  If you can confirm this is your issue I can make a fix to the login script to also check for symlinks.

**Comment by shadowrylander** [comment]
Yes; upon logging out or rebooting, a default file is loading. I don't even need to change the config file again; I just reload `i3` when coming back and it fixes itself! I will try to copy over my file and see if that works instead; thank you!

**Comment by shadowrylander** [comment]
Wait, sorry; didn't fully understand that statement. I changed `~/.config/i3-regolith/config` in the first place, but it doesn't seem to apply. I'm on a `Surface Book 2 15"`, if that's any help!

**Comment by shadowrylander** [comment]
Also, quick note: Apparently `.Xresources.d/rofi` does not exist; shall I create a new issue for this?

**Comment by kgilmer** [comment]
Tell me what you see after `ls -l ~/.config/i3-regolith/`.  Thanks for the note about the rofi Xresources.  No need to file a bug, this is something I'm working through now.

**Comment by shadowrylander** [comment]
Due to my new wallpaper being applied upon reboot, I believe:
1. The bar size was being overridden by `~/.Xresources-regolith`
2. Which couldn't activate due to `.Xresources.d/rofi` not existing

Therefore, the config actually was applying, but I didn't realize it due to the bar font size being the only thing I had changed at the time.

However, I believe the gnome settings and i3 config are still interfering with each other; this is shown in this youtube review as well:
https://youtu.be/B1Suas9OtqU?t=623
```
total 12
-rw-r--r-- 1 shadowrylander shadowrylander 8231 Jul 25 19:39 config
-rw-rw-r-- 1 shadowrylander shadowrylander    0 Jul 17 22:08 config-flag-1.22-1ubuntu1
-rw-rw-r-- 1 shadowrylander shadowrylander    0 Jul 25 18:36 config-flag-1.28-1ubuntu1ppa1
-rw-rw-r-- 1 shadowrylander shadowrylander    0 Jul 17 15:38 ftue-flag-4.16-1ubuntu15
```

**Comment by kgilmer** [comment]
Yes, the wallpaper configuration has moved from i3's config (via feh) to gnome.  I suggest you compare the i3 config file in `/etc/i3/config` with your version.  You'll want to remove anything in there that's doing wallpaper stuff and instead use gnome-control-center.

Regarding the rofi thing, sorry about that.  I'll have a fix pushed to the stable PPA very soon now.

**Comment by shadowrylander** [comment]
No worries! And fair enough! I'll run a diff. Thank you kindly for the help!
