### ISSUE TITLE
Incorrect workspace name on automatic assignment

### ISSUE THREAD

**Issue by rosencreuz** [regolith-linux/regolith-desktop#721]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I have a custom name for a workspace in `~/.config/regolith2/Xresources` file:
```
i3-wm.workspace.08.name: 8:<span> </span><span font_desc='RobotoMono Nerd Font 12'>8 Keepass</span> <span foreground='#5daa1e'></span><span> </span>
```

With this configuration, when I switch to workspace number 8, I can see the custom workspace name as expected.

I also have a custom workspace assignment in `~/.config/regolith2/i3/config.d/20_workspaces` file: 
```
assign [class="^KeePassXC$"] → number 8
```

With this configuration, when I start KeePassXC application, it's automatically assigned to workspace number 8. If I start the application from another workspace, workspace 8 is created and application starts there as expected. However, in this case, the name of the workspace is simply `8` instead of the custom name specified in the configuration. 

If I move the application to another workspace and back to workspace 8 again, this time the the name of the workspace is correct. The name is only incorrect when the workspace is created due to automatic assignment on application creation.

**To Reproduce**

**Expected behavior**
When an application is created on a new workspace other than the currently focused workspace, the name of the workspace should respect the custom name for that workspace.

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/11143375/188317143-24d30505-f7ee-4931-a7b4-dad13a6e9b7d.png)

Expected:
![image](https://user-images.githubusercontent.com/11143375/188317163-1858026a-0413-4634-991a-536a1157c06b.png)

**Configuration file(s)**

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 2 (`4.2.0-1regolith` on Ubuntu)
 - PPA url: https://regolith-desktop.org/release-ubuntu-jammy-amd64
 - Host OS (for PPA): Ubuntu 22.04.1 LTS

**Additional context**

**Comment by ferdinandyb** [comment]
You need to use the `Xresources` variable to have a consistent experience, e.g. 
```
assign [instance="outlook.office.com"] workspace $ws7
```
