### ISSUE TITLE
PPA reporsitory for Ubuntu 22.04 Jammy not available

### ISSUE THREAD

**Issue by RafKarr** [regolith-linux/regolith-desktop#725]
Hey. 
I'm not sure if this is the place to put this issue, but as the title says, your Ubuntu main PPA repository is not available for Ubuntu 22.04 LTS. I was wondering if you're planning to do that soon. 
Thank you in advance

**Comment by kgilmer** [comment]
Hi @RafKarr , jammy is supported.  See regolith-desktop.com.  if you still have trouble reopen with the line you're adding to apt.

**Comment by RafKarr** [comment]
I'm sorry ! I was adding it through Launchpad, where it does not work. My bad
