### ISSUE TITLE
Application Launcher Bugs

### ISSUE THREAD

**Issue by Gurp1272** [regolith-linux/regolith-desktop#726]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
3 bugs

1. Settings application disappeared from app launcher automatically, then reappeared a few minutes later
2. Sometimes the keybindings menu isn't populated at all
3. 'Alt -' does decrease size of menu, but 'Alt +' does not increase the size of menu

**To Reproduce**
I'm on a clean install

**Expected behavior**

1. I expect the settings application to always be in the application launcher.
2. I expect to be able to increase the size of the menu.
3. I expect the keybindings menu to always be populated

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 2.1

**Comment by kgilmer** [comment]
Thanks for the report @Gurp1272 .  

1. Hmm, unsure of what would cause that.  Ilia scans the file system at launch and reads the desktop files.  I have not seen this myself
2. I noticed this in early versions but thought I've fixed that one.  Is there anything you can tell me about how to consistently reproduce it?
3. Hmm, depending on your keyboard you have to press `shift` to get the `+`.  Did you try that?

**Comment by Gurp1272** [comment]
2. Not sure how to reproduce. But for me it happens consistently. On a clean install, no manual config. I can even do it 10 times in a row, and 4/10 will be blank. 
3. `alt -` works to decrease size. To increase size I need to press `alt`+`shift` + `+`

**Comment by kgilmer** [comment]
Regarding 2, is there anything particular about your hardware setup?  Is it old/slow or new/fast?  Anything else that may help reproduce?
Regarding 3, yes this is by design.  The `+` character is by `shift`.  If you would like the ability to reassign keys for these functions kindly file a feature request against https://github.com/regolith-linux/ilia

**Comment by Gurp1272** [comment]
Hardware is top of the line 2 years ago. However, not able to reproduce it right now. I'm not sure what changed. Thanks for your responses.
