### ISSUE TITLE
Live boot from USB with UEFI machines

### ISSUE THREAD

**Issue by jalfonsi** [regolith-linux/regolith-desktop#73]
When booting live from USB on UEFI computer the boot option from USB key is not present although the image iso is built with EFI support. However there's an additional EFI.img which probably should not be there...this does not occur with Voyager Linux which boots perfectly and is also Ubuntu based as Regolith.

**Comment by kgilmer** [comment]
Hi @jalfonsi , yes this is a known issue.  See https://github.com/regolith-linux/regolith-desktop/issues/23.  Now that Xresources is out, I will be able to roll a new release.  The Cubic developers have responded to my bug report so I'll get some help.  Most likely I configured something incorrectly when generating the ISO.
