### ISSUE TITLE
Fatal error in the regolith-control center

### ISSUE THREAD

**Issue by evwltrs** [regolith-linux/regolith-desktop#738]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Upon opening the regolith-control-center, it crashes with a fatal error.
```
** (regolith-control-center:9182): ERROR **: 08:58:50.202: Fatal error in cc_shell_model_set_panel_visibility, unknown panel id: info-overview
```

**To Reproduce**
Run the command `regolith-control-center` or click on the i3xrocks battery

**Expected behavior**
The settings page to open

**Screenshots**
![image](https://user-images.githubusercontent.com/20270765/194504817-23005980-92db-461f-bbe9-444c8c36557c.png)

**Configuration file(s)**
None except for setting a theme

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 2.1
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): 22.04

**Additional context**
Spontaneously started a few days ago, did not change any settings.

**Comment by kgilmer** [comment]
Thanks for the report @evwltrs .  Until the bug is fixed, you can use `gnome-control-center` for the configuration tasks that you'd do with `regolith-control-center`.  To temporarily fix the issue, unset the offending dconf key from a terminal:

```
gsettings set org.gnome.Settings last-panel ""
```

After that `regolith-control-center` should not crash while loading.

**Comment by kgilmer** [comment]
This will be fixed for newer releases only: kinetic and bookworm.

**Comment by mbtuckersimm** [comment]
> This will be fixed for newer releases only: kinetic and bookworm.

Will there be any way to fix it in 22.04? I'm running Linux Mint 21, which is based on 22.04.

**Comment by mbtuckersimm** [comment]
> > This will be fixed for newer releases only: kinetic and bookworm.
> 
> Will there be any way to fix it in 22.04? I'm running Linux Mint 21, which is based on 22.04.

I should say that [kgilmer's fix](https://github.com/regolith-linux/regolith-desktop/issues/738#issuecomment-1274044129) does work for me, so it's not a crisis or anything. Just wondering if there will be a way to get the underlying fix working in 22.04.

**Comment by JakobRieckhGraf** [comment]
> Thanks for the report @evwltrs . Until the bug is fixed, you can use `gnome-control-center` for the configuration tasks that you'd do with `regolith-control-center`. To temporarily fix the issue, unset the offending dconf key from a terminal:
> 
> ```
> gsettings set org.gnome.Settings last-panel ""
> ```
> 
> After that `regolith-control-center` should not crash while loading.

Thanks. I've tried this temporary fix, but keep getting the following error message:

```
No such schema “org.gnome.Settings”
```

Any idea why this is?

**Comment by kgilmer** [comment]
@evwltrs if you are still experiencing this problem in Regolith 2.2 kindly reopen this issue.
