### ISSUE TITLE
Display config lost after reboot

### ISSUE THREAD

**Issue by marco-fp** [regolith-linux/regolith-desktop#75]
I've got dual monitors, after setting up one of them to rotate left within the Display settings, when I reboot this configuration is lost.

Any hint on how to persist this config?

Not sure if this is by design or a bug. 

Thanks in advance

**Comment by PickingUpPieces** [comment]
Hi @marco-fp,
As far as i know, that is an error in the gnome-control-center, which exists for ages https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1292398 
You could fix this with a small script every reboot which sets the display with xrandr, but that's not a fancy solution, I admit.

**Comment by marco-fp** [comment]
Thanks for your answer @PickingUpPieces :+1:

**Comment by kgilmer** [comment]
Hey!  @marco-fp I use two monitors at home and three at work and don't have any issues with the configuration being lost.  Did you install from PPA or LiveCD?  Do you logout of your session before rebooting?

**Comment by marco-fp** [comment]
I updated recently and the issue seems to be solved :D
