### ISSUE TITLE
i3xrocks-battery percentage is unreadable with ayu-dark theme

### ISSUE THREAD

**Issue by yodaldevoid** [regolith-linux/regolith-desktop#780]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
With default settings, the i3xrocks-battery percentage indicator is unreadable with the ayu-dark theme due to the font being black.

**To Reproduce**
1. Install regolith-desktop
2. Install regolith-look-ayu-dark
3. Install i3xrocks-battery
4. Switch to the ayu-dark theme using the look manager

**Expected behavior**
The battery percentage should be a light grey like most other text in the system bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/1204409/203810871-34dffba3-46a9-4714-b0d8-a859b00cddac.png)

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: ISO install of 20.04 and then upgrade following instructions on website to Ubuntu 22.04 and Regolith 2.1
 - Regolith Version: 2.1
 - PPA url:  https://regolith-desktop.org/release-ubuntu-jammy-amd64
 - Host OS (for PPA): Ubuntu 22.04

**Additional context**
None right now.

**Comment by kgilmer** [comment]
Thanks for the report @yodaldevoid .  I am not seeing the same thing though:

![image](https://user-images.githubusercontent.com/49683/204048857-086a2d8e-4647-48c8-a2eb-77294720154a.png)

To verify version, what does this say?

```
cat /etc/regolith/version
```

**Comment by yodaldevoid** [comment]
> Thanks for the report @yodaldevoid . I am not seeing the same thing though:
> 
> ![image](https://user-images.githubusercontent.com/49683/204048857-086a2d8e-4647-48c8-a2eb-77294720154a.png)
> 
> To verify version, what does this say?
> 
> ```
> cat /etc/regolith/version
> ```

Ah, that's what I was looking for.
```
> cat /etc/regolith/version
REGOLITH_VERSION=2.1
```

> Also do you see this as well?
> 
> ```
> $ xrdb -query | grep nominal
> i3xrocks.nominal:	#0B0E14
> ```

Yup, same result.
```
> xrdb -query | grep nominal
i3xrocks.nominal:	#0B0E14
```

**Comment by yodaldevoid** [comment]
This seems to have been resolved sometime between when this issue was submitted and 3.0.

**Comment by behretv** [comment]
I have exactly the same issue, but on Ubuntu 23.10 and Regolith 3.1. For `i3xrocks.nominal` I have the same color as you have mentioned.
