### ISSUE TITLE
Shipping Regolith with new updated fork of Compton

### ISSUE THREAD

**Issue by tiritto** [regolith-linux/regolith-desktop#79]
I've recently encountered some very minor issues with compton and on my quest for answers and warning-free terminal I ended up with sad realization that my compton, provided by default from Ubuntu repos, is just simply very oudated (0.1~beta2+20150922).

After some digging I found out that current newest compton provided by ubuntu was uploaded all the way back in 2016 and was uploaded to Debian Sid. When I tried to find compton github page I ran into [github.com/chjj/compton](https://github.com/chjj/compton) project page that was not updated since 2017. After reseraching some more, I found out that development has now moved to the fork that is activly updated (at the time of writing this message, last commit was 20 hours ago) and can be found on [github.com/yshui/compton](https://github.com/yshui/compton) page. 

Obviously, it's not that much of an issue to compile those newer versions of compton and use them (however, it might be for some people even less advanced than I am), but since compton is one of regolith dependencies I wonder if there is any chance that we could get newer versions of compton shipped with regolith-desktop in the future?

**Comment by kgilmer** [comment]
@tiritto again, thanks for the research.  It's very helpful.  Yes, I agree it would be nice to update Compton.  I think it's probably more appropriate as a [speed ricer](https://github.com/regolith-linux/speed-ricer) package however, so then anyone with Ubuntu can benefit.

**Comment by kgilmer** [comment]
I have built v7 release and installed it locally.  It partially fixes the wallpaper garbage on screen change bug, and _feels_ faster.  Hard to say for sure but so far I have found no problems.

**Comment by kgilmer** [comment]
Thanks to a Lubuntu developer, this package is available for testing in speed-ricer PPA: https://launchpad.net/~kgilmer/+archive/ubuntu/speed-ricer/

**Comment by kgilmer** [comment]
Compton package and Regolith Compton config are available in `regolith-experimental` for testing.

**Comment by kgilmer** [comment]
It would be nice to take any fix found from this issue if ever resolved: https://github.com/chjj/compton/issues/314
