### ISSUE TITLE
Setting Key Repeat Speed Slider To Max crashes and bricks X session

### ISSUE THREAD

**Issue by Salad360** [regolith-linux/regolith-desktop#796]
- [X ] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Adjusting Repeat Key Speed under Accessibility Settings Crashes Desktop, screen displays full-screen error message which says "Oh no, something has gone wrong and the system can't recover". Subsequent attempts to login to affected user account immediate displays the same error message.

Performing dist-upgrade, apt-get clean, and dpkg --configure a in recovery mode did not resolve the issue. Creating a new user in recovery mode allows me to login normally as that user.

To recover from this issue, I had to login as my normal user account in a tty session and rename the file ~/.config/dconf/user. After this I was able to login to a desktop session as my normal user and the system generated a new dconf/user file

**To Reproduce**
Open "Settings" app, go to 'Accessibility' > Repeat Keys, Adjust Speed slider to max

**Expected behavior**
Repeat key speed adjusts to max, desktop session doesn't crash

**Screenshots**
![maxresdefault](https://user-images.githubusercontent.com/4982672/208560434-83c42a57-f6b7-47e2-bdb0-1d11173c61b3.jpg)

**Configuration file(s)**
The only things that come to mind that I have customized with my installation are: switched default shell to zsh, switched to kitty as default terminal emulator and installed themes for both. Nothing I'd expect to relate to this issue 

**Installation Details**
 - Regolith Install Type: ISO
 - Regolith Version: 2.x (idk how to check exact version but system is up to date as of this writing)
 - PPA url: N/A
 - Host OS (for PPA): N/A

**Additional context**

**Comment by Pixel-Jack** [comment]
I experienced the exact same issue and had to reset the values using [this](https://askubuntu.com/a/1031070)

**Comment by kgilmer** [comment]
using gsettings to fix the issue seems like a good work around.  I believe this issue would be upstream in the gnome project, maybe with `gnome-flashback` or the `settings` components.
