### ISSUE TITLE
Experimental: Use i3bar to view notifications instead of gnome-flashback

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#8]
This may require a combination of the following:

* Some change to gnome-flashback to disable the notification frontend
* Some change in DBus configuration that can route notification messages to i3bar
* Allow i3bar to receive and render notifications

As the bar is much smaller in surface area than the standard notification pop-up, some thought will be needed to determine how it can best be viewed by the user.

**Comment by leosunmo** [comment]
I would be quite interested in this feature. While I do like the pop-up notification, my own theme makes it hard to see and it doesn't take me to the workspace when clicked on (that's another feature request). 

Having it flash or light up red in the bottom bar using i3blocks or similar would be nice as it would show on all screens as well. Right now it will show up top right on my right-most display. If I'm working on the left display, at the bottom of the terminal, I won't notice the notification.

**Comment by PickingUpPieces** [comment]
Found this: https://github.com/sboli/twmn
Clickable notifications would be dope though 👌🏻
But not sure how you can get a click event on it. Maybe a i3block would be a solution, since there you can get the event.

**Comment by kgilmer** [comment]
That's awesome, nice find @PickingUpPieces !   Once the Xresources stuff is done I'll certainly look into twnm.

Forgive me if I've already asked but if you're interested in a few Regolith stickers send me a mailing address to kgilmer at gmail.com and I'll mail you a few.

**Comment by kgilmer** [comment]
This is done in Regolith 1.3.
