### ISSUE TITLE
Reloaded i3, i3xrocks broke

### ISSUE THREAD

**Issue by yapishu** [regolith-linux/regolith-desktop#813]
- [ x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues) (**slack heroku link was broken** when I tried)

**Describe the bug**

I reloaded my i3 session (mod+r) and my i3rocks broke. I now see markup in the status bar rather than theming; additionally other parts of my theme seem to have broken, like my window settings (hidden title bars etc), and I can no longer use some (but not all) key combinations using my mod key (eg launching drun). It is a confusing set of things to suddenly break and I'm not sure how to safely un-break it.

I do not know what changed, besides suspecting an update that went bad. My configuration files are all still in place. reinstalling regolith-desktop and regolith-i3xrocks-config does not change anything.

**To Reproduce**

Unclear

**Expected behavior**

Upon reloading, i3 continues showing my i3xrocks configuration; rofi launcher continues working

**Screenshots**

![](https://i.imgur.com/G8tP1e0.png)

**Configuration file(s)**

i3 config: 

https://pastebin.com/XEdcmXeR

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: Current (unsure how to tell)
 - PPA url: https://regolith-desktop.org/release-ubuntu-jammy-amd64
 - Host OS (for PPA): e.g. Ubuntu 22.04

**Comment by codigo47** [comment]
Workaround: add "pango" before the font name in `/usr/share/regolith-look/default/i3-wm`
```
bar {
  position $i3-wm.bar.position
  mode $i3-wm.bar.mode
  #font $i3-wm.bar.font
  font pango:DejaVu Sans Mono 10
  ...
```

**Comment by yapishu** [comment]
@codigo47 Hm, I think my issues might stem from differences between 1.6 and 2, because I don't have a `regolith2` dir. Is there a simple way to uhh, just reinstall?

**Comment by kgilmer** [comment]
Hi @yapishu , hmm, not sure about the root cause given the info.  To know what version of Regolith is installed: `cat /etc/regolith/version`.  I'm guessing you have some user configuration that might be part of the issue.  You can disable any local state with `mv ~/.config/regolith2 ~/.config/regolith2-disabled` or something like that.  Log back in and the Regolith config should be back to default.

**Comment by ForwardFeed** [comment]
I got the same issue (i3-rocks total dysfunction) but it appears to me out of thin air. I was playing a game, got logged out from my desktop session. I then proceeded to re-login, only to see in total confusion the total loss of my task bar and to the application launcher dialog window.
I tried anything i read here and just ended up reinstalling.

**Comment by yapishu** [comment]
I never fixed this but eventually i edited the scripts in `/usr/share/i3xrocks/scripts` to remove the HTML formatting from the output and now it's fine
