### ISSUE TITLE
Provide support for Base16 color scheme

### ISSUE THREAD

**Issue by seblw** [regolith-linux/regolith-desktop#82]
Just a suggestion that Base16 scheme would be nice addition. This repository contains configurations for most of the software that is used in regolith: https://github.com/chriskempson/base16

**Comment by kgilmer** [comment]
This is a really interesting project, thanks for the link @seblw .  I was looking for something that would provide a semantic mapping between abstract color labels and specific UI treatments.  At the time I didn't find anything, so just used the Solarized naming convention, however Base16 does in a way do this: https://github.com/chriskempson/base16/blob/master/styling.md

The abstract mapping looks to be particular to programming languages and not UIs however.  There are many color themes and many "builders", including st and even [Xresources](https://github.com/binaryplease/base16-xresources/tree/master/xresources).

I'll have to look at how difficult it will be to migrate my own mapping to the Base16 mapping.

**Comment by kgilmer** [comment]
We're moving in a different direction, essentially using the packaging system as a way of making it easy to install themes.  This doesn't preclude users from using base16 to create their own themes, but is not the standard approach we will use for themeing in R1.3.  Removing from the release.

**Comment by kgilmer** [comment]
Closing, unlikely to implement this due to the fuzzy subtle mismatches of color data between Regolith and base16.  If anyone would like to work on this feel free to reopen.
