### ISSUE TITLE
Expired Certificate: regolith-desktop.org

### ISSUE THREAD

**Issue by sambodhi-b** [regolith-linux/regolith-desktop#829]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
The regolith-desktop.org certificate seems to have expired.

**To Reproduce**
```
$ sudo apt update
...
Ign:3 https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy InRelease
Err:3 https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy InRelease                                                                                                                  
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 104.238.213.207 443]
...
W: Failed to fetch https://regolith-desktop.org/release-ubuntu-jammy-amd64/dists/jammy/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 104.238.213.207 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Expected behavior**
Successful apt update

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 2.2
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Pop!OS 22.04 (Ubuntu 22.04)

**Additional context**
Saw similar issue #809, however, that one was closed so opening new issue

**Comment by jumus-jumbuck** [comment]
I am having the same issue can you turn it off and on again please

**Comment by kgilmer** [comment]
Should be GTG, LMK if issue persists.

**Comment by jumus-jumbuck** [comment]
404 on the ip now (104.238.213.207)
