### ISSUE TITLE
switching desktop while in a video conference causes system to hang

### ISSUE THREAD

**Issue by clarkevans** [regolith-linux/regolith-desktop#837]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ]  I notice the [Slack](https://regolith-linux.org/interact/) link no longer works.

**Describe the bug**
Switching desktops (meta-tab, meta-n, etc.) causes my system to hang when video conferencing software is being used (MS Teams, Zoom). 

**To Reproduce**
- Enter a video conference using Zoom or MSTeams (on Firefox or Chrome)
- Switch to another desktop, and it usually hangs within seconds
- The screen remains on, but totally frozen.  Audio for the video conference works. System is otherwise unresponsive, a hardware reset seems required.

**Other Notes**
Surprisingly, moving the video conference to another frame, or switching frame layouts, or resizing a frame that affects the video conference doesn't seem to have an issue. It seems to have something to do with the video conferencing window going to a background desktop. Of course, normal desktop switching otherwise works fine.

This is probably a lower-level issue, but I thought I'd start here.  What sort of log files or system configuration would be useful for further diagnosis?  

**Configuration file(s)**
There is minimal configuration changes from default, just keybindings.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 2.2
 - PPA url: https://
regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main
 - Host OS (for PPA): Ubuntu 22.04.2 LTS

**Comment by kgilmer** [comment]
Hi @clarkevans , I've used zoom in the past and did not notice any crashes.  I wonder if it may be related to a graphics driver.  Are you using a discrete graphics card?

**Comment by clarkevans** [comment]
Ken, Thank you so much.  Yes, I have a discrete graphics card. I just changed over to using nvidia's proprietary driver, and things seem to be working. - Clark
