### ISSUE TITLE
Regolith 3: ~/.config/regolith2/Xresources used

### ISSUE THREAD

**Issue by theova** [regolith-linux/regolith-desktop#862]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)

- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Hello, I just updated to Regolith 3, thanks for the new version!

I realized, that I could not change the look, `regolith-look set` had no effect.

I think the underlying reason is that Regolith 3 does not use the correct Xresource folder:

```
$ regolith-diagnostic    
--- Regolith Diagnostic - Fri Jun 16 09:35:55 AM CEST 2023
--- /etc/regolith/version:
REGOLITH_VERSION=3.0

--- System Info 
Linux user-machine 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
--- /etc/lsb-release:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar
DISTRIB_DESCRIPTION="Ubuntu 23.04"
--- Xresources
--- [/home/user/.Xresources does not exist]
--- /home/user/.config/regolith2/Xresources:
```

**To Reproduce**
Opt in for the testing, run `regolith-diagnosis` or `regolith-look set`

**Expected behavior**
The look changes.

**Configuration file(s)**
I did not customize any files

**Installation Details**
 - Regolith Install Type: PPA
 -  - Regolith Version: 3.0
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA):  Ubuntu 23.04

**Comment by SoumyaRanjanPatnaik** [comment]
Can you try updating your system packages? The new configs are supposed to exist at `~/. config/regolith3`. This seems like an older version of regolith diagnostic.
