### ISSUE TITLE
Regolith 3 Beta 1: Keybindings don't migrate

### ISSUE THREAD

**Issue by alexschneider** [regolith-linux/regolith-desktop#866]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
I had several custom settings/keybindings in `~/.config/regolith2/i3/config.d/keybindings` for use in Regolith 2, but when I migrated to Regolith 3 the keybindings don't seem to be sticking.  I've tried moving it to `~/.config/regolith3/i3/config.d`, `~/.config/regolith3/sway/config.d`,`~/.config/regolith3/common/config.d`, and none of them seem to work. 

**To Reproduce**

Here's a selection of configuration I've made:

```
bindsym $mod+x move workspace to output next
bindsym Print exec --no-startup-id flameshot gui
bindsym $mod+Shift+s sticky toggle
bindsym $mod+Shift+f floating toggle; [floating] resize set 1200 900 ; move position center
for_window [title="^Live Caption"] floating enable sticky enable border pixel 0
for_window [class="slack"] sticky enable
for_window [title="^zoom$"] floating enable
```

**Expected behavior**
The configuration takes effect

**Installation Details**
 - Regolith Install Type: [Ubuntu Repository]
 - Regolith Version: 3 Beta 1
 - PPA url: `deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/testing-ubuntu-jammy-amd64 jammy main`
 - Host OS (for PPA): Ubuntu 22.04

**Comment by SoumyaRanjanPatnaik** [comment]
Definitely a bug. The directory should be `regolith3/i3/config.d`.

**Comment by ferdinandyb** [comment]
> Definitely a bug. The directory should be `regolith3/i3/config.d`.

Yeah, the `regolith3/wm/config.d` was the correct folder before the recent update, but now it is `i3` again. Why is this not the same folder for i3 and sway?

**Comment by SoumyaRanjanPatnaik** [comment]
> > Definitely a bug. The directory should be `regolith3/i3/config.d`.
> 
> Yeah, the `regolith3/wm/config.d` was the correct folder before the recent update, but now it is `i3` again. Why is this not the same folder for i3 and sway?

Sway configurations are typically a superset of i3 configs. And in some cases, the same configs may cause. So it makes sense to have them separate. The latest update did however add a `common-wm` directory for common configs.

**Comment by ferdinandyb** [comment]
On Thu Jul 06, 2023 at 22:37, Soumya Ranjan Patnaik wrote:
> > > Definitely a bug. The directory should be `regolith3/i3/config.d`.
> > 
> > Yeah, the `regolith3/wm/config.d` was the correct folder before the recent update, but now it is `i3` again. Why is this not the same folder for i3 and sway?
>
> Sway configurations are typically a superset of i3 configs. And in some cases, the same configs may cause. So it makes sense to have them separate. The latest update did however add a `common-wm` directory for common configs.

nice, thanks for the info!

**Comment by kgilmer** [comment]
I believe this issue is addressed, kindly re-open if I missed something
