### ISSUE TITLE
Jammy Repos are returning 403

### ISSUE THREAD

**Issue by owen7900** [regolith-linux/regolith-desktop#871]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Regolith fails to install on Jammy. 

`E: Failed to fetch http://regolith-desktop.org/release-ubuntu-jammy-amd64/dists/jammy/InRelease  403  Forbidden [IP: 104.238.213.207 80]
`
**To Reproduce**
Follow the install instructions for Jammy.

**Expected behavior**
Regolith installs as expected.

**Installation Details**
 - Regolith Install Type: [ISO/PPA]
 - Regolith Version: [e.g. 2.2]
 - Host OS (for PPA): [e.g. Ubuntu 22.04]

**Comment by kgilmer** [comment]
Thanks for the report @owen7900 .  I'm not seeing the issue from my point in space and time, can you kindly try again?

```
/tmp$ wget http://regolith-desktop.org/release-ubuntu-jammy-amd64/dists/jammy/InRelease 
--2023-07-04 07:36:08--  http://regolith-desktop.org/release-ubuntu-jammy-amd64/dists/jammy/InRelease
Resolving regolith-desktop.org (regolith-desktop.org)... 104.238.213.207
Connecting to regolith-desktop.org (regolith-desktop.org)|104.238.213.207|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2406 (2.3K) [application/octet-stream]
Saving to: ‘InRelease’

InRelease                                                       100%[======================================================================================================================================================>]   2.35K  --.-KB/s    in 0s      

2023-07-04 07:36:08 (110 MB/s) - ‘InRelease’ saved [2406/2406]
 
/tmp$ head InRelease 
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
```

**Comment by kgilmer** [comment]
assuming resolved, kindly reopen if still seeing a problem

**Comment by owen7900** [comment]
Sorry for not getting back to you. It was still happening on and off, but I got regolith installed. I think it may have been IT at work fiddling with the firewall, since it worked fine for me at home.
