### ISSUE TITLE
A problem with Xresources commands and 'regolith-look refresh' command

### ISSUE THREAD

**Issue by NextStep-IM** [regolith-linux/regolith-desktop#881]
**Bug Details:**
 After setting the Xresources commands in ~/.config/regolith2/Xresources, I use the command 'regolith-look refresh' which doesn't have any visual effect. Then I log out and in and try the command, and then again I log out and in, which does the trick. But the effects are not permanent and reset after start another session.

**Steps to reproduce the behavior:**
1- Set up a command in Xresources file.
2- Use 'regolith-look refresh' command to check the effects.

**Expected Behavior:**
 I had set up transparency effect to unfocused and focused-inactive windows. By using the refresh command I expected the effects to take on immediately. If not then after logging out and in again.

**Configuration files:**
**Xresources:**
```
regolith.wallpaper.file: ~/Pictures/Wallpapers from Haven/New-York.png
regolith.lockscreen.wallpaper.file: ~/Pictures/Wallpapers from Haven/Forest.jpg

i3-wm.mod: Mod4
i3-wm.alt: Mod1

i3-wm.workspace.01.name: "1:Terminal"
i3-wm.workspace.02.name: "2:Firefox"
i3-wm.workspace.03.name: "3:VSCode"
i3-wm.workspace.04.name: "4:Okular"


i3-wm.client.focused_inactive.color.background: #07364266
i3-wm.client.unfocused.color.background: #07364280
```

**Installation Details**
 - Regolith Install Type: [PPA]
 - Regolith Version: [2.2]
 - PPA url: [https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main]
 - Host OS (for PPA): [Ubuntu 22.04]

**Additional context**
  The transparency effects don't go away, when they are activated, when I comment out the commands in Xresources and use the refresh command. Also, the refresh and 'mod+shift+r' mess with my workspace labels e.g, Terminal changes to '1: Terminal'.
One more thing, the commands for wallpapers and workspace names work all right.

**Comment by kgilmer** [comment]
Transparency would come from the compositor on X11.   Which compositor do you have installed?  `apt list --installed | grep regolith-compositor-`

**Comment by NextStep-IM** [comment]
@kgilmer Sorry. I do not use Regolith any longer. I did not know how to delete this issue so here it is. My sincerest apologies.
