### ISSUE TITLE
Make the cheatsheet an overlay

### ISSUE THREAD

**Issue by geajack** [regolith-linux/regolith-desktop#89]
The existence of the keyboard shortcut cheatsheet is a big improvement over vanilla i3 (unless it had that feature already and I didn't know about it) but I think an overlay would be a much better fit than the little background widget. It avoids having to open a new workspace to be able to see the cheatsheet - in fact, opening a new workspace requires using a keyboard shortcut, so you could end up stuck.

I would suggest that when you hold the keyboard shortcut, a cheatsheet appears over the top of whatever else you're doing, and then disappears when you let go of the keyboard shortcut. It would be transparent with a nice big font size, basically the same as how Rofi looks on Regolith.

PS: Is the Mod + ? shortcut remappable? I'd like to map it to Mod + F1.   ?⃣   requires me to hold Shift on my AZERTY keyboard.

**Comment by kgilmer** [comment]
I agree with you @geajack !  I haven't had time to work on the first time user experience part of Regolith at all in the past few months, but there are several enhancements I'd like to make including this.  

Regarding the mapping, I believe that should be do-able by changing the key binding in your i3 config file.  To find that:
```
$ ps aux | grep i3-regolith | grep config
```

Take the file after the `-c`, this is your i3 config file (I know this is complicated, it's going to become simpler soon).  In my case it's `/home/kgilmer/.config/i3-regolith/config-4.16-1ubuntu18ppa11`.

In there you'll find this line:
```
bindsym $mod+Shift+question exec --no-startup-id /usr/bin/conky-toggle.sh
```

Now you just have to change the key binding.  The i3 user guide can give you details on how to do that.  Once changed, reload i3 or log back in and your keybinding should be updated.

**Comment by ahoneybun** [comment]
I've seen some oddness where the overlay is broken and split between two displays. I'm going to switch my GPU to see if it follows the NVIDIA card to the AMD card.
