### ISSUE TITLE
The Debian bullseye repository appears to not be properly signed

### ISSUE THREAD

**Issue by adamroyjones** [regolith-linux/regolith-desktop#891]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

After adding the Debian bullseye repository following the instructions at regolith-desktop.com, `apt update` produces errors related to GPG signatures.

**To reproduce**

Following [regolith-desktop.com](https://regolith-desktop.com),

```sh
wget -qO - https://regolith-desktop.org/regolith.key \
| gpg --dearmor \
| sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null

echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-debian-bullseye-amd64 bullseye main" \
| sudo tee /etc/apt/sources.list.d/regolith.list

sudo apt update
```

leads to

```
Get:8 https://regolith-desktop.org/release-debian-bullseye-amd64 bullseye InRelease [2,418 B]
Err:8 https://regolith-desktop.org/release-debian-bullseye-amd64 bullseye InRelease
  The following signatures were invalid: EXPKEYSIG BFE717649A5C3D08 Regolith Linux <regolith.linux@gmail.com>
Reading package lists... Done
W: GPG error: https://regolith-desktop.org/release-debian-bullseye-amd64 bullseye InRelease: The following signatures were invalid: EXPKEYSIG BFE717649A5C3D08 Regolith Linux <regolith.linux@gmail.com>
E: The repository 'https://regolith-desktop.org/release-debian-bullseye-amd64 bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I can reproduce this in a debian:bookworm container.

**Expected behavior**

For there to be no errors.

**Screenshots**

N/A.

**Configuration file(s)**

N/A.

**Installation Details**

See above.

**Additional context**

I was previously using the PPA:

```
https://regolith-desktop.org/testing-debian-testing-amd64 testing InRelease
```

**Comment by kgilmer** [comment]
Hi @adamroyjones , thanks for reporting this.  More details and remediation options are mentioned here: https://github.com/orgs/regolith-linux/discussions/888

**Comment by adamroyjones** [comment]
Thanks! I completely neglected to look at the discussions—I'm sorry about that.

I'll close the issue so that everything's concentrated there. I'll add the link to the top of the issue description, as well.

**Comment by adamroyjones** [comment]
Just to add: this appears to be resolved. Thanks for the quick fix!
