### ISSUE TITLE
https://regolith-desktop.org/release-ubuntu-jammy-amd64 stopped working

### ISSUE THREAD

**Issue by newptcai** [regolith-linux/regolith-desktop#897]
When I tried `sudo apt update` today, I got the following warning.

Err:14 https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7107DED133505B88
Fetched 14.4 kB in 5s (2,916 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
18 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7107DED133505B88
W: Failed to fetch https://regolith-desktop.org/release-ubuntu-jammy-amd64/dists/jammy/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7107DED133505B88
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by kgilmer** [comment]
Hi @newptcai , sorry for the confusion.  The previous key used to sign Regolith packages expired.  A new key was created.  You simply need to get the new key to resolve the error.  See https://github.com/orgs/regolith-linux/discussions/888 for more details.
