### ISSUE TITLE
Launching terminal applications with Super + Space

### ISSUE THREAD

**Issue by manolomartinez** [regolith-linux/regolith-desktop#9]
If I try to use Super + Space to open a terminal application (such as ranger), the gnome terminal is used instead of regolith-st. Is there an easy way to change this behavior?

**Comment by kgilmer** [comment]
Hi @manolomartinez yep, you can set st as the default terminal via `update-alternatives`.  To do this, at a terminal launch `sudo update-alternatives --config x-terminal-emulator` and select which ever number st is defined as.  For me it was `3`.  After doing that, terminal apps should launch in st.

Please LMK if this doesn't resolve your issue.

**Comment by manolomartinez** [comment]
That's perfect, thanks a lot! Closing.

**Comment by peturh** [comment]
I just installed the very silly [`cool-retro-term`](https://github.com/Swordfish90/cool-retro-term) but that doesn't show up. I get this:

```
There is only one alternative in link group x-terminal-emulator (providing /usr/bin/x-terminal-emulator): /usr/bin/gnome-terminal.wrapper
Nothing to configure.
```

I tried to read the contents of `x-terminal-emulator` but I didn't get much wiser. I'm guessing `cool-retro-term` isn't considered an `x-terminal-emulator`?

**Comment by ferdinandyb** [comment]
I'm not sure what is needed to be listed in alternatives, but it is not handled by regolith. Another solution could be to just change the i3 binding in the regolith config to open a specific terminal instead of using the x-terminal-emulator.

**Comment by ferdinandyb** [comment]
https://stackoverflow.com/questions/55513672/how-to-add-a-path-to-update-alternatives-config-php see here for installing something as a viable alternative.
