### ISSUE TITLE
Follow windows when moving them to a new workspace

### ISSUE THREAD

**Issue by geajack** [regolith-linux/regolith-desktop#90]
I find that most of the time when I move a window to a new workspace, I want to keep using that window. My preferred behavior would be that when I move something to a new workspace, Regolith immediately switches to that workspace. This should definitely be an option, sort of like Firefox's "immediately switch when you open a link in a new tab" option.

**Comment by kgilmer** [comment]
Yes, I know what you mean @geajack .   I would also like that ability!  I think it can be achieved with a compound command mapped to a keybinding in i3's config file.

**Comment by Josh-Letts** [comment]
As @kgilmer says, this can currently be achieved with a compound command like so:
`bindsym $mod+Shift+Ctrl+1 move container to workspace $ws1; workspace $ws1`

Would be neat if there was a built in function to do it though! Perhaps something like `follow container to workspace` could work?
