### ISSUE TITLE
bug: `wm.program.N` does not work for auto-starting applications

### ISSUE THREAD

**Issue by georglauterbach** [regolith-linux/regolith-desktop#907]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

See https://github.com/orgs/regolith-linux/discussions/876#discussioncomment-6596071.

**To Reproduce**

Use `wm.program.N: /path/to/some/application` to start `application` automatically.

**Expected behavior**

I expected `application` to start.

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 3.0 `regolith-desktop` (`4.4.2-1regolith-jammy`) with `regolith-session-flashback` (`0.9.6-1regolith-jammy`)
 - PPA url: `https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64 jammy main`
 - Host OS (for PPA): Ubuntu 22.04 (6.2.0-31-generic)

**Additional context**

**Comment by ploum** [comment]
Indeed. This is due to a modification in i3.

The solution is to put what you want to start in the following file:

~/.config/regolith3/i3/config.d/autostart

**Comment by georglauterbach** [comment]
Okay, so we need to update the docs.

And how do I write it into `~/.config/regolith3/i3/config.d/autostart`?

**Comment by kgilmer** [comment]
I notice seem to have `vm` instead of `wm` in your key name: `vm.program.N: /path/to/some/application`

Also, do you have this package installed? `regolith-wm-user-programs`, it provides the partial that loads the user programs from Xresources.

**Comment by georglauterbach** [comment]
> I notice seem to have `vm` instead of `wm` in your key name: `vm.program.N: /path/to/some/application`

I tend to make this mistake, good observation. I double-checked my config files and there everything is correct (i.e. `wm`).

> Also, do you have this package installed? `regolith-wm-user-programs`, it provides the partial that loads the user programs from Xresources.

I didn't. I have installed it and will report back.

**Comment by georglauterbach** [comment]
So what should we do about this issue?

**Comment by kgilmer** [comment]
@georglauterbach if you'd like to update the docs, this might be a good place to do it: https://github.com/regolith-linux/regolith-desktop-website/blob/main/content/docs/reference/Releases/regolith-3.0-release-notes.md?plain=1#L20

Then I think the issue could be closed.

**Comment by georglauterbach** [comment]
I will try to provide a PR :)
