### ISSUE TITLE
Regolith 3 Wayland - touchpad settings not saved

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#908]
### Discussed in https://github.com/orgs/regolith-linux/discussions/905

<div type='discussions-op-text'>

<sup>Originally posted by **eljejer** September 10, 2023</sup>
When I modify touchpad settings in Modify Settings (Super+c), these are not saved after a reboot. Log out and log back in, they are saved.</div>

**Comment by postsolar** [comment]
For me this applies to the "Natural scrolling" and "Tap to Click" settings, but not to the "Touchpad Speed" and "Two-finger scrolling" settings, these two persist. I'm running Ubuntu 23.04 with regolith-session-sway. Meanwhile, is there a workaround for this?
