### ISSUE TITLE
Cannot login to a regolith on wayland session

### ISSUE THREAD

**Issue by meatballs** [regolith-linux/regolith-desktop#913]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
When I attempt to login to a regolith on wayland session, I'm taken straight back to the login screen.

regolith on x11 works fine as does an ordinary ubuntu desktop on wayland

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 3.0
 - PPA url: https://regolith-desktop.org/release-3_0-ubuntu-jammy-amd64
 - Host OS (for PPA): Ubuntu 22.04

**Additional context**
NVIDIA GeForce RTX 2070 SUPER
nvidia-driver-535

**Comment by SoumyaRanjanPatnaik** [comment]
Are you using proprietary nvidia drivers?

**Comment by meatballs** [comment]
Yes, as I put in the additional context - version 535

**Comment by SoumyaRanjanPatnaik** [comment]
Ohh sorry. I missed it.

**Comment by meatballs** [comment]
No problem! It made me double check again, so no bad thing!

**Comment by SoumyaRanjanPatnaik** [comment]
Ohh sorry. I missed it. In that case you should check [this](https://regolith-desktop.com/docs/howtos/install-sway/#hardware-support) out. Sway doesn't officially support proprietary drivers nor does Regolith. You need to enable it explicitly.

**Comment by meatballs** [comment]
Ahhhh..... Once I saw the driver was good enough for ubuntu to offer me the normal desktop on wayland, I thought  I was good to go. I'll read a little more....

Thank you

**Comment by meatballs** [comment]
Yep, that fixed it. Either switching to nouveau or adding that line makes everything work fine. Sorry I missed that in the docs and thanks for the help.
