### ISSUE TITLE
Regolith3: Regolith-Settings->Displays does not show all screens

### ISSUE THREAD

**Issue by gogsbread** [regolith-linux/regolith-desktop#928]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
Regolith Settings does not show all the displays after choosing a monitor with "Single Display" option.

**To Reproduce**
- Have multiple monitors connected
- Goto "Regolith Settings" (mod+c) and choose "Display". You should see all the connected monitors
- Choose "Single Display" for an external monitor and hit apply
- After a refresh, the other display will disappear.
- To bring back the lost display, you'd have to enable both monitors using something like `sway-regolith output eDP-1 enable && <other enable>` and then all the monitors will be shown.

**Expected behavior**
- Both displays should be shown so that the user can switch to a different display as desired.
- This is the behavior in mutter

**Screenshots**
working
![working](https://github.com/regolith-linux/regolith-desktop/assets/1146580/a1298556-58c4-4f3a-83e8-c1c26f549cb6)
not-working
![not-working](https://github.com/regolith-linux/regolith-desktop/assets/1146580/f3b90fff-2ef4-4dff-acdb-6b4ce8cda2f3)

**Configuration file(s)**
Monitoring the d-bus, `dbus-monitor --session "sender='org.gnome.Mutter.DisplayConfig'" `, it shows that in a mutter session, the dbus response has the "built-in Display" whereas the one in Regolith session does not.
[regolith-dbus.txt](https://github.com/regolith-linux/regolith-desktop/files/13062495/regolith-dbus.txt)
[mutter-dbus.txt](https://github.com/regolith-linux/regolith-desktop/files/13062496/mutter-dbus.txt)

**Additional context**
I have a feeling something is trying to apply a different profile and hence it is missing this information. It is weird because no matter what "Single Display" I choose, laptop built-in or external monitor, it always seems to pivot to the external monitor.

**Comment by gogsbread** [comment]
Ok monitoring `journalctl -f` I see a log line
`Oct 21 23:26:08 antonyd regolith-wayland.desktop[44603]: no profile matched`. So, somebody is trying to load some profile and they are failing. I'll try to debug this more when I have time later

**Comment by kgilmer** [comment]
CC @SoumyaRanjanPatnaik .. From the poster's notes, this is a sway session.  is this from the kanshi dependency?

**Comment by SoumyaRanjanPatnaik** [comment]
I think this is happening because `regolith-displayd` only returns the list of active mobitors via the dbus interface. I'll try to come up with a fix for this. I'll probably have to figure out how mutter reports monitors that are connected but disable

**Comment by SoumyaRanjanPatnaik** [comment]
https://github.com/regolith-linux/regolith-displayd/commit/c4ebc881bd58a2ed4cbe2717e29d9430f117db4b and https://github.com/regolith-linux/regolith-displayd/commit/aa3d572a3cf96f42a08bb68ac37574f4de748ba9 should fix this. The changes should ideally be available in the next beta of Regolith 3.1
