### ISSUE TITLE
Look at making the build process more open

### ISSUE THREAD

**Issue by leosunmo** [regolith-linux/regolith-desktop#93]
There's a lot of magic right now as to how packages get built and where they live.

Ideally we'd be able to have all of our build configuration as well as build steps in Git.

With all the modern `.deb` and `.rpm` build tools out there we should be able to build something transparent and easy to understand, and ideally easily reproducible.

There's also a lot of free options for opensource CI/CD, like https://travis-ci.org/ and https://circleci.com, both of which has free tiers for public projects.

The last question is where the packages should be hosted going forward. The current PPA can be a bit tricky to collaborate with, but more investigation has to be done.

**Comment by leosunmo** [comment]
Some notes for myself.

All-in-one `.deb` and `.fpm` builder that might be worth looking in to: https://github.com/goreleaser/nfpm
Official Debian tool: https://github.com/Debian/dh-make-golang

For building the LiveCD, take a look at https://github.com/go-debos/debos

**Comment by leosunmo** [comment]
https://github.com/aptly-dev/aptly/blob/master/README.rst

Combined with S3 hosting looks like an interesting alternative. https://www.aptly.info/doc/feature/s3/

I'd be keen to try mirroring our repos to S3.

**Comment by leosunmo** [comment]
Here's the Deb in docker project I was looking for: https://github.com/dawidd6/deber
Should give it a try as well.

**Comment by kgilmer** [comment]
Looking into https://manpages.debian.org/testing/git-buildpackage/gbp-buildpackage.1.en.html and http://www.joshknows.com/blog/68/CreatingDebianPackagesForUbuntu
