### ISSUE TITLE
Regolith desktop package not available on 18.10

### ISSUE THREAD

**Issue by SolidHal** [regolith-linux/regolith-desktop#94]
Tried to install the regolith-desktop package from the stable ppa on my 18.10 machine, apt states that it is unable to locate the package. Added the unstable ppa as well, and ran in to the same issue. Removed both ppas and readded them but got the same effect. 
I'm able to install other ubuntu packages.

**Comment by kgilmer** [comment]
Cosmic has been deprecated by Canonical.  I cannot publish new packages to the PPA.  So I removed the existing ones.  I guess this is how they get people to update to the latest LTS release.  Sorry, it's out of my hands.  :crying_cat_face:

**Comment by SolidHal** [comment]
Oh, I hadn't even realized 18.10 was dead. Thanks for the help!

**Comment by mikkokotila** [comment]
It's also not available in 18.04

**Comment by kgilmer** [comment]
Hi @mikkokotila , 18.04 is LTS so it has not been deprecated and Regolith supports this version (I'm running it now.)  What error are you getting when you try to install?
