### ISSUE TITLE
PATH overwritten in sway

### ISSUE THREAD

**Issue by busaster** [regolith-linux/regolith-desktop#958]
- [x ] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [ x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

Ubuntu 22.04.3 LTS 
Regolith with wayland and sway with bash as shell
When I open a terminal and echo my PATH variabile it is not as I set in my .profile.
Other variables declared in .profile instead are ok and set.
Executing systemctl --user show-environment | grep PATH shows me the right PATH I expect.
Which can be the cause of this behaviour ?
Thanks

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 4.1.6
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): [e.g. Ubuntu 22.04]

**Comment by SoumyaRanjanPatnaik** [comment]
The sway session uses environment.d to set environment variables. Setting them in .profile doesn't work. Try adding your path in .config/environment.d/environment.conf

**Comment by vitorarins** [comment]
Hey I am bumping into this issue and tried setting the PATH in the `~/.config/environment.d/environment.conf` but it doesn't work

I was also having a different issue where you suggested something similar for XDG_CURRENT_DESKTOP and it has no effect at all.

I am running Regolith version 3.1 with sway in Ubuntu 22.04 LTS
