### ISSUE TITLE
What is in workspace 12 and how can I access it?

### ISSUE THREAD

**Issue by ldesousa** [regolith-linux/regolith-desktop#961]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

I am not sure this is a bug. Since yesterday the status bar is reporting a twelfth workspace, highlighted in red. What is it? How can I access it? 

P.S.: the URL to the Slack web-site is currently returning an error.

**To Reproduce**
The twelfth workspace appeared out of its own volition.

**Screenshots**
![Selection_117](https://github.com/regolith-linux/regolith-desktop/assets/1137878/e264ee20-45fd-49f0-b7e2-ccb9a416c049)

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 4.3
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 22.04

**Comment by w18g** [comment]
you can probably [super]+TAB to that workspace.

My guess is you pressed [super] + ` to create a new workspace.

**Comment by ldesousa** [comment]
The extra workspace, sometimes 11, sometimes 12, is created when the system returns from sleep mode. Regolith automatically modifies display settings from mirrored displays to side-by-side, thus adding an extra, I believe empty workspace. When this happens I use ArandR to re-set the display and the extra workspace goes away.

I will give a try to <kbd>Super</kbd>+<kbd>TAB</kbd> next time.

**Comment by kgilmer** [comment]
> is created when the system returns from sleep mode.

I have noticed this behavior in the past and believe it's related to the graphics driver and sleep mode.   I am not aware of a fix.

> P.S.: the URL to the Slack web-site is currently returning an error.

Where do you see that old link?  See https://regolith-desktop.com/ , at the bottom of the page is details to our current chat system: matrix.

**Comment by ldesousa** [comment]
I have now tested this same sequence, into and out off sleep mode, with i3 and GNome. Only regolith yields this behaviour, creating a seemingly random additional workspace. Makes me doubt this being a graphics card issue.
