### ISSUE TITLE
Bluetooth issues in connecting and disconnecting

### ISSUE THREAD

**Issue by shadowrylander** [regolith-linux/regolith-desktop#97]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I seem to be having bluetooth connectivity issues which may or may not be due to `regolith`, though I have my suspicions that it's just from `Ubuntu 19.04 Disco Dingo`. My devices (my speakers, in particular), upon paring and connecting them, immediately disconnect after a few seconds, before connecting and disconnecting a second time, remaining disconnected from then on. Just to make sure this isn't a `regolith` issue, as I haven't used ubuntu in quite time, are there any tips and / or tricks I could do to find out? <br>
Thank you kindly for the help!

**Comment by kgilmer** [comment]
If you installed Regolith via PPA, you can just login to the normal Ubuntu session with the 'gear' icon on the login screen.  If you installed Regolith from the LiveCD (usb drive), then you can install the default ubuntu session with `sudo apt install ubuntu-session`.  Then you can log back in with the default Ubuntu session.

If your bluetooth issues persist then it's something upstream.  Either way let me know!

**Comment by shadowrylander** [comment]
Ah; seems to be something upstream. Also, how do I get back to i3, again?

**Comment by shadowrylander** [comment]
Never mind; had to reboot. I'll close this issue now, then! Thank you for the help, again!
