### ISSUE TITLE
regolith-session-common and regolith-styles both try to install /usr/bin/regolith-look

### ISSUE THREAD

**Issue by jjnesbitt** [regolith-linux/regolith-desktop#974]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [x] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**

I'm trying to upgrade to regolith 3.0 from regolith 1.6, and to begin, I purged everything regolith from my system that I could find. After that, I re-installed regolith based on the [instructions](https://regolith-desktop.com/docs/using-regolith/install/), and doing so without including extra looks works fine. However, if I try to install any of the look packages, I get the following error:

```
> sudo apt install regolith-look-ayu-mirage
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  arc-icon-theme faba-icon-theme fonts-font-awesome fonts-source-code-pro-ttf moka-icon-theme regolith-styles
The following NEW packages will be installed:
  arc-icon-theme faba-icon-theme fonts-font-awesome fonts-source-code-pro-ttf moka-icon-theme regolith-look-ayu-mirage regolith-styles
0 upgraded, 7 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B/58.8 MB of archives.
After this operation, 118 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package faba-icon-theme.
(Reading database ... 288209 files and directories currently installed.)
Preparing to unpack .../0-faba-icon-theme_4.3-1_all.deb ...
Unpacking faba-icon-theme (4.3-1) ...
Selecting previously unselected package moka-icon-theme.
Preparing to unpack .../1-moka-icon-theme_5.4.523-201905300105~daily~ubuntu19.04.1_all.deb ...
Unpacking moka-icon-theme (5.4.523-201905300105~daily~ubuntu19.04.1) ...
Selecting previously unselected package arc-icon-theme.
Preparing to unpack .../2-arc-icon-theme_20161122-1-1regolith-focal_amd64.deb ...
Unpacking arc-icon-theme (20161122-1-1regolith-focal) ...
Selecting previously unselected package fonts-font-awesome.
Preparing to unpack .../3-fonts-font-awesome_5.0.10+really4.7.0~dfsg-1_all.deb ...
Unpacking fonts-font-awesome (5.0.10+really4.7.0~dfsg-1) ...
Selecting previously unselected package fonts-source-code-pro-ttf.
Preparing to unpack .../4-fonts-source-code-pro-ttf_1.010-0ubuntu1~ppa2-1regolith-focal_all.deb ...
Unpacking fonts-source-code-pro-ttf (1.010-0ubuntu1~ppa2-1regolith-focal) ...
Preparing to unpack .../5-regolith-styles_2.9.7-1_amd64.deb ...
Unpacking regolith-styles (2.9.7-1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-ud4Weg/5-regolith-styles_2.9.7-1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/regolith-look', which is also in package regolith-session-common 0.9.6-1regolith-focal
Selecting previously unselected package regolith-look-ayu-mirage.
Preparing to unpack .../6-regolith-look-ayu-mirage_2.9.7-1_amd64.deb ...
Unpacking regolith-look-ayu-mirage (2.9.7-1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-ud4Weg/5-regolith-styles_2.9.7-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The notable section is the following:

```
dpkg: error processing archive /tmp/apt-dpkg-install-ud4Weg/5-regolith-styles_2.9.7-1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/regolith-look', which is also in package regolith-session-common 0.9.6-1regolith-focal
```

From what I can tell, the file from [regolith-styles](https://github.com/regolith-linux/regolith-styles/blob/master/regolith-look) is 3 years old, and the file from [regolith-session](https://github.com/regolith-linux/regolith-session/blob/main/usr/bin/regolith-look) (the file I currently have on my system) was last modified in August.

Anyone have any idea what's going on / how to fix this?

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 3.0
 - PPA url: https://regolith-desktop.org/release-3_0-ubuntu-focal-amd64
 - Host OS (for PPA): Ubuntu 20.04

**Additional context**
* I'm using `regolith-session-flashback`.
* To try to work around the issue, I force installed `regolith-styles`, which overwrote the `regolith-look` binary. I've tried using both the old and new binary for that, both of which produce a bugged (although somewhat usable) experience.

**Comment by kgilmer** [comment]
Hi, regolith-styles was depreciated on the 3.0 release.  It was replaced by regolith-look-default.  I suggest removing the depreciated package and installing whichever look you prefer.

**Comment by jjnesbitt** [comment]
> Hi, regolith-styles was depreciated on the 3.0 release. It was replaced by regolith-look-default. I suggest removing the depreciated package and installing whichever look you prefer.

How do I go about installing the look I prefer? The [documentation](https://regolith-desktop.com/docs/using-regolith/install/) just says to install whatever `regolith-look-*` package you want. Is there some other way to do it?

By the way, really appreciate the quick response! :smile:

**Comment by kgilmer** [comment]
> The [documentation](https://regolith-desktop.com/docs/using-regolith/install/) just says to install whatever regolith-look-* package you want. Is there some other way to do it?

It's not obvious, but you can just query the package manager:

```console
apt list | grep regolith-look-
```

**Comment by jjnesbitt** [comment]
I believe the issue is that `regolith-styles` is a dependency of any of those look packages. So simply installing any of those look packages attempts to install `regolith-styles`, which is what includes the conflicting binary.

**Comment by kgilmer** [comment]
Hmm, perhaps you are pulling from multiple regolith apt repositories?  Check for multiple things in /etc/apt/sources.list.d with 'regolith' in them.  You should only be installing regolith from a single repository

**Comment by jjnesbitt** [comment]
Indeed that seemed to be the issue! The installation of Regolith 3 left the old source in place (`regolith-linux-ubuntu-release-focal.list` vs `regolith.list`). Sorry for all the noise and I really appreciate your help!
