### ISSUE TITLE
xrescat doesn't work with regolith with sway

### ISSUE THREAD

**Issue by rmasad** [regolith-linux/regolith-desktop#986]
**Describe the bug**
xrescat doesn't work with regolith with sway. It returns: Can't obtain RESOURCE_MANAGER

**To Reproduce**
```
~ ❯ xrescat wm.workspace.02.name
Can't obtain RESOURCE_MANAGER

```

**Installation Details**
 - Regolith Version: 3.1
 - Host OS (for PPA): Ubuntu 23.10

**Comment by kgilmer** [comment]
Hi @rmasad , `xrescat` is coupled to X11.  There is an equivalent written by @SoumyaRanjanPatnaik that provides the same functionality on Wayland, called `trawl`.  Have a look at [this readme](https://github.com/regolith-linux/trawl), in particlar the `trawlcat` section to learn more

**Comment by rmasad** [comment]
Thanks @kgilmer and @SoumyaRanjanPatnaik. Works perfect
