### ISSUE TITLE
'login-required' 'access denied' when trying to install an app from the App Center on Regolith 3.1, X11

### ISSUE THREAD

**Issue by amongoos1** [regolith-linux/regolith-desktop#988]
**Describe the bug**
I'm running Regolith 3.1 as a PPA in Ubuntu 23.10.1 as a fresh install. Whenever I open Regolith Wayland and then the App Center and try to install an app, I am prompted with a small authentication window which asks me to input a password and everything works fine. However on X11, whenever I click the install button, a window pops up telling me 'login-required' and below that, 'access denied' along with a Close button. 
**To Reproduce**
1. Run Regolith 3.1 X11 on Ubuntu 23.10
2. Open the App Center/Snap Store
3. Choose any app (for instance Chromium)
4. Click Install
5. Be prompted with 'login-required' 'access-denied'.
**Expected behavior**

1. Run Regolith 3.1 X11 on Ubuntu 23.10
2. Open the App Center/Snap Store
3. Choose any app (for instance Chromium)
4. Click Install
5. Be prompted with an authentication screen
6. Enter password
7. Installation begins
**Screenshots**
![Screenshot from 2024-03-02 14-07-05](https://github.com/regolith-linux/regolith-desktop/assets/158026863/0586c593-891e-4975-b84a-f6eab5e191cb)

**Configuration file(s)**
It's a completely fresh install. 0 Configuration.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 3.1
 - Host OS (for PPA): Ubuntu 23.10.1

**Comment by Npepperlinux** [comment]
I am having the same problem with Regolith 3.1 and have encountered the problem in other situations that ask for a login password, but the conditions seem to be a little different.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 3.1
 - Host OS (for PPA): **Ubuntu 22.04.4 LTS**

I encountered this problem in **Wayland**, but could **not** reproduce it in X11. Is this the same issue?

**Comment by SoumyaRanjanPatnaik** [comment]
Should be fixed by this: https://github.com/regolith-linux/regolith-wm-config/pull/21

**Comment by SoumyaRanjanPatnaik** [comment]
The fixes should be available on `unstable`. It should be generally available with the 3.2 release.

**Comment by stbneb** [comment]
Hi @SoumyaRanjanPatnaik, thanks for the fix. Is there a way to apply the it without having to wait for the 3.2 release?
