### ISSUE TITLE
Error could not parse json 

### ISSUE THREAD

**Issue by Vangreen** [regolith-linux/regolith-desktop#99]
After yesterday update, after login to i3 desktop i have error `Error could not parse json (lexical error: invalid char in json text) ` on navbar. Nothing works, regolith terminal, roofi. I try to reinstall package (also with purge option), also i try to switch to unstable version. Nothing helps

**Comment by kgilmer** [comment]
Hi @Vangreen, please see troubleshooting steps here to resolve your issue: https://regolith-linux.org/troubleshooting.html#outdated-xresources

**Comment by Vangreen** [comment]
@kgilmer Thanks, this fix my problem. Thanks for quick answer

**Comment by zampierilucas** [comment]
Hi guys, 
I'm currently facing the same issue, and since the site is 404ing, could you give me more information in how you fixed it?

**Comment by kgilmer** [comment]
Hi @zampierilucas :smile: , sorry that paged moved here: https://github.com/regolith-linux/regolith-desktop/wiki/Troubleshooting#outdated-xresources

If your problem persists, please open a new issue and we'll figure out what's wrong.  :smile:

**Comment by setanta** [comment]
I've just had this problem today and solved the problem by replacing the `~` in the `#include` clauses on `.Xresources-regolith` by my full home path (`$HOME` too would not work).
