### ISSUE TITLE
Volume popup when changing volume gets its slider stuck when going below 30%

### ISSUE THREAD

**Issue by TheKamboy** [regolith-linux/regolith-desktop#994]
- [x] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [x] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)

**Describe the bug**
When turning down the volume below 30%, the slider on the volume popup doesn't go lower than where its position is for 30% volume. The interesting thing is that when it reaches 0%, it shows the slider is empty, with the speaker with a line through it.

**To Reproduce**
To be honest, I'm not sure.

**Expected behavior**
The slider keeps going to the left past 30%.

**Configuration file(s)**
Please attach or mention any customization you've done to configuration files which might have an impact on the bug you are describing. It'll help us determine the root cause of your issue.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 3.1
 - PPA url: https://regolith-desktop.org/release-current-ubuntu-jammy-amd64
 - Host OS (for PPA): Zorin OS 17.1 (basically Ubuntu 22.04)

**Additional context**

**Comment by TheKamboy** [comment]
This is what I'm talking about:
![image](https://github.com/regolith-linux/regolith-desktop/assets/89111294/d7f0428e-26e5-473e-8473-2e02fffc2060)

**Comment by TheKamboy** [comment]
From searching a bit more it seems it might have to do with `avizo`.

**Comment by TheKamboy** [comment]
Nevermind, it's not even installed.

**Comment by TheKamboy** [comment]
Closed for 2 reasons:

1. I guess I would get more responses in the discussions tab
2. It got fixed when I made a custom theme for regolith

**Comment by kgilmer** [comment]
Hi @TheKamboy , glad you were able to fix your issue.  If you make it back here, it would be interesting for me to know if you experienced this using `i3` or `sway`.

**Comment by TheKamboy** [comment]
It was an issue with i3, and the issue was with the lascaille theme.
